import type { TopicData } from '../types'

export const CITIES: TopicData = {
  topic: 'Cities & Urbanisation',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'cty_v1', type: 'vocabulary', term: 'urban', pronunciation: '/ˈɜːbən/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Relating to a town or city rather than the countryside.', vietnameseMeaning: 'Thuộc về đô thị, thành thị.', example: 'Urban residents enjoy better access to healthcare but pay far more for housing.', writingTip: 'The opposite is "rural". Both are essential in this topic — "urban areas" and "rural areas".', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['urban areas', 'urban population', 'urban development', 'urban planning'], antonym: 'rural', wordFamily: ['urbanise (v)', 'urbanisation (n)'], priority: 'must_learn' },
    { id: 'cty_v2', type: 'vocabulary', term: 'population', pronunciation: '/ˌpɒpjuˈleɪʃn/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'The total number of people living in a place.', vietnameseMeaning: 'Dân số.', example: 'The population of the capital has trebled since 1990, far outpacing the growth of its housing stock.', writingTip: 'Countable: "a growing population", "populations of major cities". Do not confuse with "people".', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['population growth', 'growing population', 'urban population', 'population density'], wordFamily: ['populate (v)', 'populated (adj)', 'populous (adj)'], priority: 'must_learn' },
    { id: 'cty_v3', type: 'vocabulary', term: 'overcrowded', pronunciation: '/ˌəʊvəˈkraʊdɪd/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Containing too many people or things for the available space.', vietnameseMeaning: 'Quá tải, chật chội, đông đúc quá mức.', example: 'Overcrowded classrooms in fast-growing suburbs make individual attention almost impossible.', writingTip: 'Use for places, not for the country as a whole — for that, use "overpopulated".', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['overcrowded housing', 'overcrowded schools', 'become overcrowded', 'overcrowded conditions'], wordFamily: ['overcrowding (n)'], priority: 'must_learn' },
    { id: 'cty_v4', type: 'vocabulary', term: 'suburb', pronunciation: '/ˈsʌbɜːb/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'A residential district on the outer edge of a city.', vietnameseMeaning: 'Vùng ngoại ô, khu dân cư ven thành phố.', example: 'Families increasingly move to the suburbs in search of larger homes and quieter streets.', writingTip: 'Usually plural with "the": "move to the suburbs". The adjective is "suburban".', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['move to the suburbs', 'leafy suburbs', 'outer suburbs', 'suburban housing'], wordFamily: ['suburban (adj)', 'suburbia (n)'], priority: 'high_value' },
    { id: 'cty_v5', type: 'vocabulary', term: 'housing', pronunciation: '/ˈhaʊzɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Buildings where people live, considered collectively.', vietnameseMeaning: 'Nhà ở, vấn đề nhà ở.', example: 'A shortage of affordable housing forces young workers to live far from the city where they are employed.', writingTip: 'Uncountable — "housing is expensive", never "housings". "House" is the countable building.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['affordable housing', 'social housing', 'housing shortage', 'housing crisis'], priority: 'must_learn' },
    { id: 'cty_v6', type: 'vocabulary', term: 'facilities', pronunciation: '/fəˈsɪlətiz/', partOfSpeech: 'noun (plural)', cefrLevel: 'B1', definition: 'Buildings, services and equipment provided for a particular purpose.', vietnameseMeaning: 'Tiện ích, cơ sở vật chất công cộng.', example: 'Newly built districts often lack basic facilities such as clinics, libraries and playgrounds.', writingTip: 'Almost always plural in this sense. "Amenities" is a good higher-band synonym.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['public facilities', 'recreational facilities', 'medical facilities', 'lack of facilities'], alternatives: ['amenities'], priority: 'must_learn' },
    { id: 'cty_v7', type: 'vocabulary', term: 'migrate', pronunciation: '/maɪˈɡreɪt/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To move from one place to another in order to live or work there.', vietnameseMeaning: 'Di cư, chuyển đến nơi khác sinh sống.', example: 'Each year hundreds of thousands migrate from farming villages to industrial cities in search of work.', writingTip: '"Migrate to" a destination, "migrate from" an origin. The people are "migrants".', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['migrate to cities', 'rural-urban migration', 'internal migration'], wordFamily: ['migration (n)', 'migrant (n)'], priority: 'must_learn' },
    { id: 'cty_v8', type: 'vocabulary', term: 'crowded', pronunciation: '/ˈkraʊdɪd/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Full of people.', vietnameseMeaning: 'Đông đúc, chật kín người.', example: 'Crowded pavements and narrow streets make the old quarter difficult to navigate at peak times.', writingTip: 'A safe Band 5-6 word. "Densely populated" is the higher-band equivalent for whole areas.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', collocations: ['crowded streets', 'crowded city centre', 'increasingly crowded'], alternatives: ['packed', 'congested'], priority: 'high_value' },
    { id: 'cty_v9', type: 'vocabulary', term: 'resident', pronunciation: '/ˈrezɪdənt/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'A person who lives in a particular place.', vietnameseMeaning: 'Cư dân, người dân sinh sống tại khu vực.', example: 'Long-standing residents are often the first to be priced out when a neighbourhood becomes fashionable.', writingTip: 'More precise than "people" when you mean those living in a specific area.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['local residents', 'city residents', 'long-term residents'], wordFamily: ['reside (v)', 'residential (adj)', 'residence (n)'], priority: 'high_value' },
    { id: 'cty_v10', type: 'vocabulary', term: 'expand', pronunciation: '/ɪkˈspænd/', partOfSpeech: 'verb', cefrLevel: 'B1', definition: 'To become larger in size, number or area.', vietnameseMeaning: 'Mở rộng, phát triển về quy mô.', example: 'As the city expanded outwards, farmland within twenty kilometres of the centre disappeared entirely.', writingTip: 'Useful for both Task 1 (data growth) and Task 2 (city growth). The noun is "expansion".', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['expand rapidly', 'expand outwards', 'urban expansion'], antonym: 'contract', wordFamily: ['expansion (n)', 'expanding (adj)'], priority: 'high_value' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'cty_v11', type: 'vocabulary', term: 'urbanisation', pronunciation: '/ˌɜːbənaɪˈzeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The process by which an increasing share of a population comes to live in cities.', vietnameseMeaning: 'Quá trình đô thị hoá.', example: 'Rapid urbanisation across Southeast Asia has outpaced the ability of governments to provide clean water and sanitation.', writingTip: 'The defining word of this topic. "Rapid" and "unplanned" are its most natural adjectives.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['rapid urbanisation', 'unplanned urbanisation', 'the pace of urbanisation'], wordFamily: ['urbanise (v)', 'urbanised (adj)'], priority: 'must_learn' },
    { id: 'cty_v12', type: 'vocabulary', term: 'infrastructure', pronunciation: '/ˈɪnfrəstrʌktʃə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The basic systems a city needs to work, including roads, water, power and drainage.', vietnameseMeaning: 'Cơ sở hạ tầng đô thị.', example: 'Cities that grow faster than their infrastructure end up with flooded streets and unreliable electricity.', writingTip: 'Uncountable. Pair with "invest in", "upgrade", "ageing" and "strain on".', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['urban infrastructure', 'invest in infrastructure', 'upgrade infrastructure', 'strain on infrastructure'], priority: 'must_learn' },
    { id: 'cty_v13', type: 'vocabulary', term: 'sanitation', pronunciation: '/ˌsænɪˈteɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Systems for keeping places clean, especially the removal of sewage and waste.', vietnameseMeaning: 'Điều kiện vệ sinh, hệ thống thoát nước thải.', example: 'Poor sanitation in informal settlements remains one of the leading causes of childhood illness.', writingTip: 'Uncountable and quite specific — it concerns sewage and hygiene, not general cleanliness.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['poor sanitation', 'adequate sanitation', 'sanitation facilities', 'water and sanitation'], wordFamily: ['sanitary (adj)', 'unsanitary (adj)'], priority: 'must_learn' },
    { id: 'cty_v14', type: 'vocabulary', term: 'metropolitan', pronunciation: '/ˌmetrəˈpɒlɪtən/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Relating to a large city together with the surrounding towns that depend on it.', vietnameseMeaning: 'Thuộc vùng đô thị lớn, thuộc thành phố trung tâm và vùng phụ cận.', example: 'The metropolitan area now contains more people than the six next-largest cities combined.', writingTip: 'Almost always used before a noun: metropolitan area, metropolitan authority, metropolitan region.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['metropolitan area', 'metropolitan region', 'metropolitan authority'], wordFamily: ['metropolis (n)'], priority: 'high_value' },
    { id: 'cty_v15', type: 'vocabulary', term: 'municipality', pronunciation: '/mjuːˌnɪsɪˈpæləti/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'A town or district with its own local government.', vietnameseMeaning: 'Chính quyền địa phương, đơn vị hành chính thành phố.', example: 'Individual municipalities, rather than national governments, decide how land within their boundaries may be used.', writingTip: 'The adjective "municipal" is more common in essays: municipal services, municipal budget.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['local municipality', 'municipal government', 'municipal services'], alternatives: ['local authority', 'council'], wordFamily: ['municipal (adj)'], priority: 'optional' },
    { id: 'cty_v16', type: 'vocabulary', term: 'slum', pronunciation: '/slʌm/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A very poor, densely built area of a city with substandard housing.', vietnameseMeaning: 'Khu ổ chuột, khu nhà ở tồi tàn.', example: 'Roughly a quarter of the urban population in developing countries lives in slums without secure land rights.', writingTip: '"Informal settlement" is the neutral term preferred in policy writing and reads as more sophisticated.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['live in slums', 'slum housing', 'slum upgrading'], alternatives: ['informal settlement', 'shantytown'], priority: 'high_value' },
    { id: 'cty_v17', type: 'vocabulary', term: 'liveable', pronunciation: '/ˈlɪvəbl/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Pleasant and comfortable enough to live in.', vietnameseMeaning: 'Đáng sống, thuận lợi cho cuộc sống.', example: 'A liveable city is judged not by the height of its towers but by the quality of its streets and parks.', writingTip: 'American spelling is "livable". "Liveability" is a key term in urban planning writing.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a liveable city', 'the most liveable cities', 'liveability ranking'], antonym: 'unliveable', wordFamily: ['liveability (n)'], priority: 'high_value' },
    { id: 'cty_v18', type: 'vocabulary', term: 'zoning', pronunciation: '/ˈzəʊnɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The legal division of land into areas designated for particular uses.', vietnameseMeaning: 'Quy hoạch phân khu chức năng đất đai.', example: 'Restrictive zoning that permits only detached houses is a major cause of housing shortages in wealthy cities.', writingTip: 'A precise planning term. Use it when arguing about why housing is scarce or why suburbs sprawl.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['zoning laws', 'zoning regulations', 'relax zoning rules', 'restrictive zoning'], wordFamily: ['zone (n, v)'], priority: 'high_value' },
    { id: 'cty_v19', type: 'vocabulary', term: 'overpopulation', pronunciation: '/ˌəʊvəpɒpjuˈleɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'A situation in which there are too many people for the available space and resources.', vietnameseMeaning: 'Tình trạng quá tải dân số.', example: 'Overpopulation in coastal megacities has left millions exposed to flooding on land that should never have been built on.', writingTip: 'Refers to whole areas or countries. For a single building or bus, use "overcrowding".', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['urban overpopulation', 'the problem of overpopulation', 'lead to overpopulation'], wordFamily: ['overpopulated (adj)'], priority: 'must_learn' },
    { id: 'cty_v20', type: 'vocabulary', term: 'amenity', pronunciation: '/əˈmiːnəti/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A useful or pleasant feature or service in a place.', vietnameseMeaning: 'Tiện ích công cộng, dịch vụ tiện nghi.', example: 'Parks, libraries and public squares are the amenities that make dense living tolerable.', writingTip: 'Usually plural: "local amenities". Slightly more formal and more precise than "facilities".', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['local amenities', 'public amenities', 'basic amenities', 'access to amenities'], priority: 'high_value' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'cty_v21', type: 'vocabulary', term: 'urban sprawl', pronunciation: '/ˌɜːbən ˈsprɔːl/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The uncontrolled spread of low-density housing outwards from a city.', vietnameseMeaning: 'Sự phát triển đô thị lan toả thiếu kiểm soát.', example: 'Urban sprawl consumes farmland, lengthens journeys and makes public transport prohibitively expensive to run.', writingTip: 'A precise term that names the phenomenon. Far stronger than "the city is getting bigger".', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['curb urban sprawl', 'unchecked urban sprawl', 'contribute to urban sprawl'], wordFamily: ['sprawling (adj)', 'sprawl (v)'], priority: 'must_learn' },
    { id: 'cty_v22', type: 'vocabulary', term: 'gentrification', pronunciation: '/ˌdʒentrɪfɪˈkeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The process by which a poor area becomes more expensive as wealthier people move in.', vietnameseMeaning: 'Quá trình cao cấp hoá khu dân cư, đẩy người thu nhập thấp ra ngoài.', example: 'Gentrification improves the appearance of a neighbourhood while gradually displacing the community that shaped it.', writingTip: 'A genuinely nuanced word — it lets you acknowledge benefits and harms in a single sentence.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['rapid gentrification', 'the effects of gentrification', 'resist gentrification'], wordFamily: ['gentrify (v)', 'gentrified (adj)'], priority: 'high_value' },
    { id: 'cty_v23', type: 'vocabulary', term: 'densification', pronunciation: '/ˌdensɪfɪˈkeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The process of increasing the number of homes or people within an existing built-up area.', vietnameseMeaning: 'Tăng mật độ xây dựng và dân cư trong khu vực hiện hữu.', example: 'Densification along existing metro lines is far cheaper than extending services into new suburbs.', writingTip: 'The natural counter-argument to sprawl. Use "build upwards rather than outwards" to explain it.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['urban densification', 'encourage densification'], antonym: 'urban sprawl', wordFamily: ['dense (adj)', 'density (n)', 'densify (v)'], priority: 'optional' },
    { id: 'cty_v24', type: 'vocabulary', term: 'population density', pronunciation: '/ˌpɒpjuˈleɪʃn ˈdensəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The number of people living in each unit of area.', vietnameseMeaning: 'Mật độ dân số.', example: 'High population density is not inherently a problem; it becomes one only when services fail to keep pace.', writingTip: 'Essential for Task 1 maps and tables, and a sophisticated way to discuss crowding in Task 2.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['high population density', 'low density housing', 'densely populated'], priority: 'must_learn' },
    { id: 'cty_v25', type: 'vocabulary', term: 'affordable housing', pronunciation: '/əˈfɔːdəbl ˈhaʊzɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Homes priced within reach of households on ordinary incomes.', vietnameseMeaning: 'Nhà ở giá phù hợp với thu nhập trung bình.', example: 'Requiring developers to include affordable housing in every new project is one of the few measures that works quickly.', writingTip: 'A fixed policy phrase — do not break it up. Uncountable, like "housing" itself.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a shortage of affordable housing', 'provide affordable housing', 'affordable housing scheme'], priority: 'must_learn' },
    { id: 'cty_v26', type: 'vocabulary', term: 'displace', pronunciation: '/dɪsˈpleɪs/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To force people to leave the place where they normally live.', vietnameseMeaning: 'Đẩy đi, buộc phải rời khỏi nơi ở.', example: 'Large infrastructure projects frequently displace the poorest residents with minimal compensation.', writingTip: 'Often passive: "residents were displaced". The noun "displacement" is equally useful.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['displace residents', 'be displaced by', 'displaced communities'], wordFamily: ['displacement (n)', 'displaced (adj)'], priority: 'high_value' },
    { id: 'cty_v27', type: 'vocabulary', term: 'smart city', pronunciation: '/smɑːt ˈsɪti/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'A city that uses digital technology and data to manage its services more efficiently.', vietnameseMeaning: 'Thành phố thông minh (ứng dụng công nghệ trong quản lý đô thị).', example: 'Smart city technology can optimise traffic signals in real time, though it raises obvious concerns about surveillance.', writingTip: 'A modern, credible example. Balance it with a privacy caveat to show critical thinking.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['smart city technology', 'smart city initiative'], priority: 'optional' },
    { id: 'cty_v28', type: 'vocabulary', term: 'regeneration', pronunciation: '/rɪˌdʒenəˈreɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The process of improving a run-down area through investment and rebuilding.', vietnameseMeaning: 'Tái thiết, chỉnh trang khu vực xuống cấp.', example: 'The regeneration of the docklands created thousands of jobs, but almost none went to former dock workers.', writingTip: '"Urban regeneration" is the standard phrase. It is the deliberate, planned version of gentrification.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['urban regeneration', 'regeneration scheme', 'regeneration project'], alternatives: ['renewal', 'revitalisation'], wordFamily: ['regenerate (v)'], priority: 'high_value' },
    { id: 'cty_v29', type: 'vocabulary', term: 'exodus', pronunciation: '/ˈeksədəs/', partOfSpeech: 'noun (singular)', cefrLevel: 'C1', definition: 'The departure of a large number of people from a place at the same time.', vietnameseMeaning: 'Làn sóng rời bỏ, cuộc di cư ồ ạt.', example: 'The exodus of young people from rural provinces has left many villages with only the elderly.', writingTip: 'Usually "an exodus of" or "a mass exodus from". Reserve it for genuinely large movements.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['a mass exodus', 'an exodus of young people', 'rural exodus'], priority: 'optional' },
    { id: 'cty_v30', type: 'vocabulary', term: 'outstrip', pronunciation: '/ˌaʊtˈstrɪp/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To grow faster or become greater than something else.', vietnameseMeaning: 'Vượt xa, tăng nhanh hơn.', example: 'Demand for housing has consistently outstripped supply in every major city over the past two decades.', writingTip: '"Demand outstrips supply" is the classic pairing and an elegant way to explain a shortage.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['demand outstrips supply', 'outstrip growth', 'far outstrip'], alternatives: ['exceed', 'surpass', 'outpace'], priority: 'must_learn' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'cty_c1', type: 'collocation', term: 'population growth', collocationType: 'Noun + Noun', definition: 'An increase in the number of people living in an area.', vietnameseMeaning: 'Sự gia tăng dân số.', example: 'Rapid population growth in coastal cities has placed unprecedented pressure on water supplies.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'cty_c2', type: 'collocation', term: 'move to the city', collocationType: 'Verb + Noun', definition: 'To relocate from a rural area to an urban one.', vietnameseMeaning: 'Chuyển đến thành phố sinh sống.', example: 'Young graduates move to the city because that is where professional work is concentrated.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'cty_c3', type: 'collocation', term: 'the cost of living', collocationType: 'Noun phrase', definition: 'The amount of money needed to cover basic expenses in a place.', vietnameseMeaning: 'Chi phí sinh hoạt.', example: 'The cost of living in the capital is now roughly double that of provincial towns.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'cty_c4', type: 'collocation', term: 'green space', collocationType: 'Adj + Noun', definition: 'Parks and other areas of grass and trees within a city.', vietnameseMeaning: 'Không gian xanh trong đô thị.', example: 'Access to green space has a measurable effect on residents’ mental health.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'cty_c5', type: 'collocation', term: 'job opportunities', collocationType: 'Noun + Noun', definition: 'Chances to find paid employment.', vietnameseMeaning: 'Cơ hội việc làm.', example: 'Cities continue to attract migrants because job opportunities are simply more plentiful there.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'cty_c6', type: 'collocation', term: 'standard of living', collocationType: 'Noun phrase', definition: 'The level of comfort and material wealth people enjoy.', vietnameseMeaning: 'Mức sống.', example: 'Urban migration usually raises a family’s standard of living within a single generation.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', priority: 'must_learn', writingTip: 'Distinguish from "quality of life", which includes non-material factors such as air, safety and time.' },
    { id: 'cty_c7', type: 'collocation', term: 'city centre', collocationType: 'Noun + Noun', definition: 'The central business and commercial district of a city.', vietnameseMeaning: 'Trung tâm thành phố.', example: 'Rents in the city centre have risen so steeply that most shop workers commute in from the outskirts.', alternative: 'downtown', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', priority: 'high_value' },
    { id: 'cty_c8', type: 'collocation', term: 'lack of facilities', collocationType: 'Noun + Prep + Noun', definition: 'An absence of the services and buildings a community needs.', vietnameseMeaning: 'Sự thiếu hụt cơ sở vật chất, tiện ích.', example: 'A lack of facilities in newly built districts leaves residents driving long distances for everyday needs.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'task2', priority: 'high_value' },

    // Advanced (Band 6-7)
    { id: 'cty_c9', type: 'collocation', term: 'rural-urban migration', collocationType: 'Adj + Noun', definition: 'The movement of people from the countryside into cities.', vietnameseMeaning: 'Di cư từ nông thôn ra thành thị.', example: 'Rural-urban migration accelerates whenever agricultural incomes stagnate while urban wages rise.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cty_c10', type: 'collocation', term: 'put a strain on public services', collocationType: 'Verb + Noun', definition: 'To create pressure that public services struggle to cope with.', vietnameseMeaning: 'Gây áp lực lên các dịch vụ công.', example: 'An influx of newcomers puts a strain on public services that were planned for a much smaller population.', alternative: 'place pressure on public services', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cty_c11', type: 'collocation', term: 'a housing shortage', collocationType: 'Noun + Noun', definition: 'A situation in which there are too few homes for the people who need them.', vietnameseMeaning: 'Tình trạng thiếu nhà ở.', example: 'The housing shortage is a consequence of planning restrictions as much as of population growth.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cty_c12', type: 'collocation', term: 'urban planning', collocationType: 'Adj + Noun', definition: 'The design and regulation of how land in cities is used.', vietnameseMeaning: 'Quy hoạch đô thị.', example: 'Sound urban planning anticipates growth rather than reacting to it a decade too late.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cty_c13', type: 'collocation', term: 'quality of life', collocationType: 'Noun phrase', definition: 'How comfortable, healthy and satisfying daily life is.', vietnameseMeaning: 'Chất lượng cuộc sống.', example: 'Higher wages do not automatically translate into a better quality of life when commuting consumes three hours a day.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cty_c14', type: 'collocation', term: 'mixed-use development', collocationType: 'Adj + Noun', definition: 'Building projects that combine homes, shops and workplaces in one area.', vietnameseMeaning: 'Khu phát triển đa chức năng (kết hợp nhà ở, thương mại, văn phòng).', example: 'Mixed-use development allows people to walk to work, which no amount of road building can achieve.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'cty_c15', type: 'collocation', term: 'be priced out of', collocationType: 'Verb phrase', definition: 'To be unable to afford to live in an area because prices have risen.', vietnameseMeaning: 'Bị đẩy ra khỏi khu vực vì giá cả quá cao.', example: 'Teachers and nurses are increasingly priced out of the districts they serve.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'cty_c16', type: 'collocation', term: 'curb urban sprawl', collocationType: 'Verb + Noun', definition: 'To place limits on the outward spread of a city.', vietnameseMeaning: 'Kiềm chế sự lan toả đô thị.', example: 'Green belts were introduced specifically to curb urban sprawl, with mixed results.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'cty_c17', type: 'collocation', term: 'demand consistently outstrips supply', collocationType: 'Noun + Verb + Noun', definition: 'People want far more of something than is available, over a sustained period.', vietnameseMeaning: 'Nhu cầu liên tục vượt quá nguồn cung.', example: 'In every desirable city, demand consistently outstrips supply, and prices rise accordingly.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'cty_c18', type: 'collocation', term: 'unchecked population growth', collocationType: 'Adj + Noun', definition: 'Increases in population that are not controlled or planned for.', vietnameseMeaning: 'Sự gia tăng dân số không được kiểm soát.', example: 'Unchecked population growth in flood-prone districts has turned a natural hazard into a recurring disaster.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'cty_c19', type: 'collocation', term: 'revitalise deprived neighbourhoods', collocationType: 'Verb + Adj + Noun', definition: 'To bring new life and investment to poor urban areas.', vietnameseMeaning: 'Hồi sinh các khu dân cư nghèo khó.', example: 'Public libraries and transport links revitalise deprived neighbourhoods more reliably than luxury developments do.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'cty_c20', type: 'collocation', term: 'strike a balance between growth and liveability', collocationType: 'Verb + Noun', definition: 'To find a compromise between expanding a city and keeping it pleasant to live in.', vietnameseMeaning: 'Cân bằng giữa tăng trưởng và chất lượng sống đô thị.', example: 'The central challenge for planners is to strike a balance between growth and liveability.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'cty_p1', type: 'phrasal_verb', term: 'move out', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To leave a home or area in order to live somewhere else.', vietnameseMeaning: 'Chuyển đi, dọn khỏi nơi ở.', example: 'Families with young children tend to move out of the centre as soon as they can afford to.', formalAlternative: 'relocate', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['relocate', 'depart', 'leave'] },
    { id: 'cty_p2', type: 'phrasal_verb', term: 'settle down', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To start living somewhere permanently.', vietnameseMeaning: 'Định cư, ổn định cuộc sống lâu dài.', example: 'Many migrants intend to work in the city temporarily but eventually settle down there.', formalAlternative: 'settle permanently', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['establish residence', 'settle'] },
    { id: 'cty_p3', type: 'phrasal_verb', term: 'build up', partOfSpeech: 'phrasal verb (separable)', definition: 'To cover an area with buildings; to develop gradually.', vietnameseMeaning: 'Xây dựng dày đặc, phát triển thành khu đô thị.', example: 'Land that was farmland thirty years ago is now completely built up.', formalAlternative: 'develop', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', priority: 'high_value', collocations: ['a built-up area', 'built up over time'], academicAlternatives: ['develop', 'urbanise'] },
    { id: 'cty_p4', type: 'phrasal_verb', term: 'knock down', partOfSpeech: 'phrasal verb (separable)', definition: 'To destroy a building deliberately.', vietnameseMeaning: 'Phá dỡ, đập bỏ (công trình).', example: 'Historic townhouses are frequently knocked down to make way for office towers.', formalAlternative: 'demolish', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Conversational. "Demolish" is the correct register for an academic essay.', academicAlternatives: ['demolish', 'raze', 'clear'] },
    { id: 'cty_p5', type: 'phrasal_verb', term: 'grow up', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To spend one’s childhood in a particular place.', vietnameseMeaning: 'Lớn lên, trưởng thành ở một nơi.', example: 'Children who grow up in dense neighbourhoods with safe streets tend to be more independent.', formalAlternative: 'be raised', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['be raised', 'spend one’s childhood'] },

    // Advanced / less common
    { id: 'cty_p6', type: 'phrasal_verb', term: 'spring up', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To appear suddenly and in large numbers.', vietnameseMeaning: 'Mọc lên nhanh chóng, xuất hiện hàng loạt.', example: 'Informal settlements spring up on the edges of cities faster than authorities can register them.', formalAlternative: 'emerge rapidly', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['emerge', 'proliferate', 'appear'] },
    { id: 'cty_p7', type: 'phrasal_verb', term: 'crop up', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To appear or occur unexpectedly.', vietnameseMeaning: 'Nảy sinh, phát sinh bất ngờ.', example: 'New problems crop up whenever a city expands without a coherent drainage plan.', formalAlternative: 'arise', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'use_with_caution', priority: 'optional', usageWarning: 'Informal and slightly casual. "Arise" or "emerge" is safer in Task 2.', academicAlternatives: ['arise', 'emerge', 'occur'] },
    { id: 'cty_p8', type: 'phrasal_verb', term: 'push out', partOfSpeech: 'phrasal verb (separable)', definition: 'To force people to leave an area, usually through rising costs.', vietnameseMeaning: 'Đẩy ra khỏi khu vực (do chi phí tăng cao).', example: 'Rising rents have pushed out precisely the workers the city centre depends on.', formalAlternative: 'displace', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['displace', 'force out', 'exclude'] },
    { id: 'cty_p9', type: 'phrasal_verb', term: 'take over', partOfSpeech: 'phrasal verb (separable)', definition: 'To gain control of something, or to spread across an area.', vietnameseMeaning: 'Chiếm lĩnh, tiếp quản, lan rộng khắp.', example: 'Chain stores have taken over high streets that once housed independent traders.', formalAlternative: 'assume control of', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['dominate', 'supplant', 'assume control of'] },
    { id: 'cty_p10', type: 'phrasal_verb', term: 'cope with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To deal successfully with a difficult situation.', vietnameseMeaning: 'Ứng phó, xoay xở với khó khăn.', example: 'Few municipal governments are equipped to cope with an additional half a million residents in a decade.', formalAlternative: 'manage', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['cope with demand', 'cope with growth', 'struggle to cope with'], academicAlternatives: ['manage', 'accommodate', 'contend with'] },
  ],

  writingPhrases: [
    { id: 'cty_w1', type: 'writing_phrase', term: 'The central dilemma facing fast-growing cities is that...', function: 'Introducing an argument', vietnameseMeaning: 'Thế khó cốt lõi mà các thành phố tăng trưởng nhanh phải đối mặt là...', example: 'The central dilemma facing fast-growing cities is that the housing people need most is the housing that is hardest to build.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'cty_w2', type: 'writing_phrase', term: 'People are drawn to cities primarily because...', function: 'Giving a reason', vietnameseMeaning: 'Người dân bị thu hút đến thành phố chủ yếu vì...', example: 'People are drawn to cities primarily because opportunity is concentrated there in a way it never is in the countryside.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cty_w3', type: 'writing_phrase', term: 'This influx of new residents stems from...', function: 'Explaining a cause', vietnameseMeaning: 'Làn sóng cư dân mới này bắt nguồn từ...', example: 'This influx of new residents stems from the mechanisation of farming, which has removed the need for rural labour.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cty_w4', type: 'writing_phrase', term: 'The inevitable consequence of building outwards is that...', function: 'Explaining an effect', vietnameseMeaning: 'Hệ quả tất yếu của việc mở rộng ra ngoài là...', example: 'The inevitable consequence of building outwards is that journeys lengthen and public transport becomes uneconomic to operate.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'cty_w5', type: 'writing_phrase', term: 'Seoul illustrates this pattern clearly:', function: 'Giving an example', vietnameseMeaning: 'Seoul minh hoạ rõ ràng cho mô hình này:', example: 'Seoul illustrates this pattern clearly: dense development along metro lines has allowed the city to grow without endless sprawl.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'cty_w6', type: 'writing_phrase', term: 'The greatest benefit of urban density is that...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi ích lớn nhất của mật độ đô thị cao là...', example: 'The greatest benefit of urban density is that it makes hospitals, universities and transport networks affordable to run.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cty_w7', type: 'writing_phrase', term: 'The price of this rapid expansion is paid mainly by...', function: 'Discussing disadvantages', vietnameseMeaning: 'Cái giá của sự mở rộng nhanh chóng này chủ yếu do... gánh chịu.', example: 'The price of this rapid expansion is paid mainly by low-income families, who are pushed into districts without schools or clinics.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'cty_w8', type: 'writing_phrase', term: 'Rather than restricting migration, authorities should...', function: 'Suggesting a solution', vietnameseMeaning: 'Thay vì hạn chế di cư, chính quyền nên...', example: 'Rather than restricting migration, authorities should invest in the secondary cities that could absorb it.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cty_w9', type: 'writing_phrase', term: 'To my mind, a successful city is one that...', function: 'Expressing an opinion', vietnameseMeaning: 'Theo tôi, một thành phố thành công là nơi...', example: 'To my mind, a successful city is one that a low-paid worker can afford to live in without a two-hour commute.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cty_w10', type: 'writing_phrase', term: 'Whereas rural communities offer space and quiet, urban ones provide...', function: 'Comparing ideas', vietnameseMeaning: 'Trong khi nông thôn mang lại không gian và sự yên tĩnh, đô thị lại cung cấp...', example: 'Whereas rural communities offer space and quiet, urban ones provide the density of opportunity that allows careers to develop.', topic: 'Cities & Urbanisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'cty_m1', type: 'common_mistake', incorrect: 'The population of Hanoi is very crowded.', correct: 'Hanoi is very crowded. / Hanoi has a very high population density.', explanation: 'A population is large or small, not crowded; a place is crowded. This mismatch between subject and adjective is extremely common.', topic: 'Cities & Urbanisation', priority: 'must_learn' },
    { id: 'cty_m2', type: 'common_mistake', incorrect: 'More and more people move to city to find a job.', correct: 'An increasing number of people are moving to cities to find work.', explanation: 'Three fixes: "city" is countable and needs "a"/"the" or the plural; "more and more" is spoken register; and the present continuous better expresses an ongoing trend.', topic: 'Cities & Urbanisation', priority: 'must_learn' },
    { id: 'cty_m3', type: 'common_mistake', incorrect: 'The government should build more infrastructures.', correct: 'The government should invest in more infrastructure.', explanation: '"Infrastructure" is uncountable and takes no plural -s. It is also normally something you "invest in", "upgrade" or "expand" rather than simply "build".', topic: 'Cities & Urbanisation', priority: 'must_learn' },
    { id: 'cty_m4', type: 'common_mistake', incorrect: 'In the countryside, the life is more peaceful than city.', correct: 'Life in the countryside is more peaceful than life in the city.', explanation: 'Two errors: "life" in the general sense takes no article, and a comparison must compare like with like — "than in the city", not "than city".', topic: 'Cities & Urbanisation', priority: 'high_value' },
    { id: 'cty_m5', type: 'common_mistake', incorrect: 'Urbanization causes many bad effects for the environment.', correct: 'Urbanisation has a number of adverse effects on the environment.', explanation: 'The correct preposition is "effect on", not "effect for". "Bad" is also too informal — use "adverse", "detrimental" or "negative".', topic: 'Cities & Urbanisation', priority: 'must_learn' },
  ],

  learnFirst: {
    vocabulary: ['cty_v11', 'cty_v12', 'cty_v5', 'cty_v13', 'cty_v19', 'cty_v21', 'cty_v24', 'cty_v25', 'cty_v30', 'cty_v7'],
    collocations: ['cty_c9', 'cty_c10', 'cty_c11', 'cty_c12', 'cty_c20'],
    phrasalVerbs: ['cty_p10', 'cty_p8', 'cty_p6'],
    writingPhrases: ['cty_w1', 'cty_w2', 'cty_w8'],
  },
}
