import type { TopicData } from '../types'

export const CRIME: TopicData = {
  topic: 'Crime & Law',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'crm_v1', type: 'vocabulary', term: 'crime', pronunciation: '/kraɪm/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'An illegal act punishable by law.', vietnameseMeaning: 'Tội phạm, hành vi phạm tội.', example: 'Crime has fallen steadily in most wealthy countries, though few voters believe it.', writingTip: 'Countable for individual acts ("a serious crime"), uncountable for the phenomenon ("crime is falling").', topic: 'Crime & Law', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['commit a crime', 'the crime rate', 'violent crime', 'petty crime'], wordFamily: ['criminal (n/adj)', 'criminalise (v)'], priority: 'must_learn' },
    { id: 'crm_v2', type: 'vocabulary', term: 'punishment', pronunciation: '/ˈpʌnɪʃmənt/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A penalty imposed for breaking a rule or law.', vietnameseMeaning: 'Hình phạt.', example: 'Punishment satisfies a public desire for justice without necessarily reducing future offending.', writingTip: 'Common adjectives: harsh, severe, lenient, capital, proportionate.', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['harsh punishment', 'capital punishment', 'impose a punishment'], wordFamily: ['punish (v)', 'punitive (adj)'], priority: 'must_learn' },
    { id: 'crm_v3', type: 'vocabulary', term: 'offender', pronunciation: '/əˈfendə/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A person who has committed a crime.', vietnameseMeaning: 'Người phạm tội.', example: 'First-time offenders sent to prison are more likely to reoffend than those given community sentences.', writingTip: 'More neutral and formal than "criminal". Useful phrases: young offenders, repeat offenders.', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['young offenders', 'repeat offenders', 'first-time offenders'], alternatives: ['criminal', 'perpetrator'], wordFamily: ['offend (v)', 'offence (n)'], priority: 'must_learn' },
    { id: 'crm_v4', type: 'vocabulary', term: 'prison', pronunciation: '/ˈprɪzn/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A building where people convicted of crimes are held.', vietnameseMeaning: 'Nhà tù, trại giam.', example: 'Building more prisons has never reduced crime anywhere it has been tried.', writingTip: 'No article when talking about the institution: "sent to prison", "in prison". Use "the prison" only for a specific building.', topic: 'Crime & Law', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['send someone to prison', 'the prison population', 'prison sentence'], alternatives: ['jail', 'penitentiary'], wordFamily: ['imprison (v)', 'imprisonment (n)'], priority: 'must_learn' },
    { id: 'crm_v5', type: 'vocabulary', term: 'victim', pronunciation: '/ˈvɪktɪm/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A person harmed by a crime or an event.', vietnameseMeaning: 'Nạn nhân.', example: 'Systems designed around the offender frequently forget the victim entirely.', writingTip: 'Pattern: "a victim of" + crime. Also "fall victim to".', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a victim of crime', 'fall victim to', 'support victims'], priority: 'high_value' },
    { id: 'crm_v6', type: 'vocabulary', term: 'illegal', pronunciation: '/ɪˈliːɡl/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Not allowed by law.', vietnameseMeaning: 'Bất hợp pháp, trái luật.', example: 'Making a practice illegal often drives it underground rather than ending it.', writingTip: '"Illegal" means against the law; "unlawful" is broader; "illicit" suggests secrecy and social disapproval.', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['illegal activity', 'illegal immigration', 'make something illegal'], alternatives: ['unlawful', 'illicit'], antonym: 'legal', wordFamily: ['illegally (adv)', 'legality (n)'], priority: 'must_learn' },
    { id: 'crm_v7', type: 'vocabulary', term: 'arrest', pronunciation: '/əˈrest/', partOfSpeech: 'verb / noun', cefrLevel: 'B1', definition: 'To take someone into police custody on suspicion of a crime.', vietnameseMeaning: 'Bắt giữ, tạm giam.', example: 'Arrest rates say more about policing priorities than about the amount of crime committed.', writingTip: 'Pattern: "arrest somebody for something". Note "be under arrest".', topic: 'Crime & Law', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['arrest someone for', 'be under arrest', 'make an arrest'], priority: 'high_value' },
    { id: 'crm_v8', type: 'vocabulary', term: 'fine', pronunciation: '/faɪn/', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'A sum of money paid as a penalty.', vietnameseMeaning: 'Tiền phạt; phạt tiền.', example: 'A fixed fine punishes the poor far more severely than the wealthy for the same offence.', writingTip: 'Verbs: impose, issue, pay. Also a verb: "fine somebody for doing something".', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['impose a fine', 'a heavy fine', 'pay a fine'], priority: 'high_value' },
    { id: 'crm_v9', type: 'vocabulary', term: 'security', pronunciation: '/sɪˈkjʊərəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Protection from danger or crime.', vietnameseMeaning: 'An ninh, sự an toàn.', example: 'Improved street lighting delivers more security per pound spent than additional cameras.', topic: 'Crime & Law', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['tighten security', 'security measures', 'public security', 'a sense of security'], wordFamily: ['secure (adj/v)'], priority: 'high_value' },
    { id: 'crm_v10', type: 'vocabulary', term: 'court', pronunciation: '/kɔːt/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A place where legal cases are heard and judged.', vietnameseMeaning: 'Toà án.', example: 'Cases that reach court represent a small fraction of the offences actually reported.', writingTip: 'No article in "go to court", "appear in court" — like "prison" and "hospital".', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['go to court', 'appear in court', 'a court ruling', 'take someone to court'], priority: 'high_value' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'crm_v11', type: 'vocabulary', term: 'deterrent', pronunciation: '/dɪˈterənt/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'Something that discourages people from acting in a certain way.', vietnameseMeaning: 'Yếu tố răn đe, biện pháp ngăn chặn.', example: 'The certainty of being caught is a far stronger deterrent than the severity of the sentence.', writingTip: 'Central to almost every crime essay. Fixed phrase: "act as a deterrent".', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['act as a deterrent', 'an effective deterrent', 'a powerful deterrent'], antonym: 'incentive', wordFamily: ['deter (v)', 'deterrence (n)'], priority: 'must_learn' },
    { id: 'crm_v12', type: 'vocabulary', term: 'rehabilitation', pronunciation: '/ˌriːəˌbɪlɪˈteɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The process of helping an offender return to normal life.', vietnameseMeaning: 'Sự cải tạo, phục hồi để tái hoà nhập.', example: 'Rehabilitation is cheaper than repeated imprisonment, though it is politically harder to defend.', writingTip: 'The classic Task 2 contrast is "punishment versus rehabilitation" — learn both sides.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['rehabilitation programmes', 'focus on rehabilitation', 'successful rehabilitation'], wordFamily: ['rehabilitate (v)'], priority: 'must_learn' },
    { id: 'crm_v13', type: 'vocabulary', term: 'sentence', pronunciation: '/ˈsentəns/', partOfSpeech: 'noun / verb', cefrLevel: 'B2', definition: 'The punishment given by a court; to give such a punishment.', vietnameseMeaning: 'Bản án; tuyên án.', example: 'Long sentences remove offenders from society without addressing why they offended.', writingTip: 'Patterns: "serve a sentence", "sentence somebody to five years".', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a prison sentence', 'serve a sentence', 'a lengthy sentence', 'a suspended sentence'], wordFamily: ['sentencing (n)'], priority: 'must_learn' },
    { id: 'crm_v14', type: 'vocabulary', term: 'juvenile', pronunciation: '/ˈdʒuːvənaɪl/', partOfSpeech: 'adjective / noun', cefrLevel: 'C1', definition: 'Relating to young people below the age of legal adulthood.', vietnameseMeaning: 'Thuộc về vị thành niên.', example: 'Juvenile offenders tried as adults reoffend at consistently higher rates.', writingTip: '"Juvenile delinquency" is the standard term for youth crime in academic writing.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['juvenile crime', 'juvenile delinquency', 'juvenile offenders'], priority: 'high_value' },
    { id: 'crm_v15', type: 'vocabulary', term: 'custody', pronunciation: '/ˈkʌstədi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The state of being held by the police or in prison.', vietnameseMeaning: 'Sự giam giữ, tạm giữ.', example: 'Holding suspects in custody before trial punishes people who have not been convicted.', writingTip: 'Also used in family law to mean legal responsibility for a child.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['in custody', 'take into custody', 'police custody'], wordFamily: ['custodial (adj)'], priority: 'high_value' },
    { id: 'crm_v16', type: 'vocabulary', term: 'reoffend', pronunciation: '/ˌriːəˈfend/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To commit another crime after being punished for a previous one.', vietnameseMeaning: 'Tái phạm.', example: 'Roughly half of those released from short sentences reoffend within a year.', writingTip: 'The noun "reoffending" is very useful: "reduce reoffending rates".', topic: 'Crime & Law', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['reoffending rates', 'likely to reoffend', 'reduce reoffending'], alternatives: ['relapse into crime'], priority: 'must_learn' },
    { id: 'crm_v17', type: 'vocabulary', term: 'legitimate', pronunciation: '/lɪˈdʒɪtɪmət/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Allowed by law; reasonable and justifiable.', vietnameseMeaning: 'Hợp pháp; chính đáng.', example: 'Where legitimate work is unavailable, illegal work becomes the only realistic option.', writingTip: 'Two useful senses: lawful, and reasonable ("a legitimate concern").', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['legitimate business', 'a legitimate concern', 'perfectly legitimate'], antonym: 'illegitimate', wordFamily: ['legitimacy (n)', 'legitimise (v)'], priority: 'high_value' },
    { id: 'crm_v18', type: 'vocabulary', term: 'prosecute', pronunciation: '/ˈprɒsɪkjuːt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To formally accuse someone of a crime in court.', vietnameseMeaning: 'Truy tố, khởi tố ra toà.', example: 'Companies are rarely prosecuted for offences that individuals would be jailed for.', writingTip: 'Do not confuse with "persecute" (to treat cruelly because of beliefs).', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['prosecute an offender', 'be prosecuted for', 'the prosecution'], wordFamily: ['prosecution (n)', 'prosecutor (n)'], priority: 'high_value' },
    { id: 'crm_v19', type: 'vocabulary', term: 'lenient', pronunciation: '/ˈliːniənt/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Not strict enough in punishing.', vietnameseMeaning: 'Khoan dung, nhẹ tay (trong xử phạt).', example: 'Sentences regarded as lenient by the public are often the ones that reduce reoffending most.', writingTip: 'The natural opposite of "harsh" or "severe" — perfect for a balanced crime essay.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a lenient sentence', 'overly lenient', 'lenient treatment'], antonym: 'harsh', wordFamily: ['leniency (n)'], priority: 'must_learn' },
    { id: 'crm_v20', type: 'vocabulary', term: 'vandalism', pronunciation: '/ˈvændəlɪzəm/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The deliberate destruction of public or private property.', vietnameseMeaning: 'Hành vi phá hoại tài sản công.', example: 'Vandalism is often a symptom of boredom rather than of criminality.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['acts of vandalism', 'petty vandalism', 'prevent vandalism'], wordFamily: ['vandalise (v)', 'vandal (n)'], priority: 'optional' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'crm_v21', type: 'vocabulary', term: 'deter', pronunciation: '/dɪˈtɜː/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To discourage someone from doing something by making them fear the consequences.', vietnameseMeaning: 'Răn đe, khiến ai đó chùn bước.', example: 'Visible policing deters opportunistic theft far more effectively than longer sentences.', writingTip: 'Pattern: "deter somebody from doing something". Do not confuse with "detain" or "defer".', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['deter offenders', 'deter people from', 'effectively deter'], alternatives: ['discourage', 'dissuade'], antonym: 'encourage', wordFamily: ['deterrent (n)', 'deterrence (n)'], priority: 'must_learn' },
    { id: 'crm_v22', type: 'vocabulary', term: 'recidivism', pronunciation: '/rɪˈsɪdɪvɪzəm/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'The tendency of convicted criminals to reoffend.', vietnameseMeaning: 'Tình trạng tái phạm tội.', example: 'Countries that invest in education inside prisons report markedly lower recidivism.', writingTip: 'The technical term for reoffending. One well-placed use signals a strong lexical range.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['high recidivism rates', 'reduce recidivism'], wordFamily: ['recidivist (n)'], priority: 'high_value' },
    { id: 'crm_v23', type: 'vocabulary', term: 'incarceration', pronunciation: '/ɪnˌkɑːsəˈreɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'The act of imprisoning someone.', vietnameseMeaning: 'Việc giam giữ, cầm tù.', example: 'Mass incarceration has proved enormously expensive and only modestly effective.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['mass incarceration', 'the cost of incarceration', 'rates of incarceration'], alternatives: ['imprisonment'], wordFamily: ['incarcerate (v)'], priority: 'high_value' },
    { id: 'crm_v24', type: 'vocabulary', term: 'miscarriage of justice', pronunciation: '/ˌmɪskærɪdʒ əv ˈdʒʌstɪs/', partOfSpeech: 'noun', cefrLevel: 'C2', definition: 'A failure of a court leading to an innocent person being punished.', vietnameseMeaning: 'Án oan, sai lầm tư pháp.', example: 'A single miscarriage of justice damages public confidence more than a hundred correct verdicts restore it.', writingTip: 'The decisive argument against irreversible punishments such as the death penalty.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a serious miscarriage of justice', 'prevent miscarriages of justice'], priority: 'must_learn' },
    { id: 'crm_v25', type: 'vocabulary', term: 'proportionate', pronunciation: '/prəˈpɔːʃənət/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Appropriate in size or severity to the situation.', vietnameseMeaning: 'Tương xứng, cân xứng với mức độ vi phạm.', example: 'A punishment must be proportionate to the offence if the law is to retain public respect.', writingTip: 'Always "proportionate to". A key concept in any essay on sentencing.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['proportionate to the offence', 'a proportionate response'], antonym: 'disproportionate', wordFamily: ['proportion (n)', 'proportionality (n)'], priority: 'must_learn' },
    { id: 'crm_v26', type: 'vocabulary', term: 'impunity', pronunciation: '/ɪmˈpjuːnəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'Freedom from punishment for wrongdoing.', vietnameseMeaning: 'Sự không bị trừng phạt, thoát tội.', example: 'When powerful individuals act with impunity, ordinary citizens lose faith in the law entirely.', writingTip: 'The fixed phrase is "with impunity". Very effective in arguments about corruption and inequality before the law.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['act with impunity', 'a culture of impunity'], priority: 'high_value' },
    { id: 'crm_v27', type: 'vocabulary', term: 'mitigating', pronunciation: '/ˈmɪtɪɡeɪtɪŋ/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Making an offence seem less serious and deserving of a lighter penalty.', vietnameseMeaning: 'Giảm nhẹ (tình tiết giảm nhẹ tội).', example: 'Courts routinely consider mitigating circumstances such as age, coercion and previous good character.', writingTip: 'Almost always in the phrase "mitigating circumstances" or "mitigating factors".', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['mitigating circumstances', 'mitigating factors'], antonym: 'aggravating', wordFamily: ['mitigate (v)', 'mitigation (n)'], priority: 'high_value' },
    { id: 'crm_v28', type: 'vocabulary', term: 'perpetrator', pronunciation: '/ˈpɜːpətreɪtə/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'A person who carries out a crime or harmful act.', vietnameseMeaning: 'Thủ phạm, kẻ gây ra hành vi phạm tội.', example: 'Focusing exclusively on the perpetrator obscures the conditions that produced the offence.', writingTip: 'More formal than "criminal" and useful for variety alongside "offender".', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the perpetrator of a crime', 'identify the perpetrator'], wordFamily: ['perpetrate (v)'], priority: 'high_value' },
    { id: 'crm_v29', type: 'vocabulary', term: 'custodial', pronunciation: '/kʌˈstəʊdiəl/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Involving imprisonment.', vietnameseMeaning: 'Thuộc về hình phạt tù giam.', example: 'A custodial sentence for a non-violent offence often costs society more than the crime did.', writingTip: 'The standard legal term. "A custodial sentence" is far more precise than "going to prison".', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['a custodial sentence', 'non-custodial alternatives'], priority: 'optional' },
    { id: 'crm_v30', type: 'vocabulary', term: 'restorative', pronunciation: '/rɪˈstɒrətɪv/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Aiming to repair the harm done rather than simply to punish.', vietnameseMeaning: 'Mang tính phục hồi, hàn gắn thay vì trừng phạt.', example: 'Restorative justice requires the offender to face the victim, which many find harder than prison.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['restorative justice', 'a restorative approach'], wordFamily: ['restore (v)', 'restoration (n)'], priority: 'high_value' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'crm_c1', type: 'collocation', term: 'commit a crime', collocationType: 'Verb + Noun', definition: 'To carry out an illegal act.', vietnameseMeaning: 'Phạm tội, thực hiện hành vi phạm pháp.', example: 'Most people who commit a crime once never do so again.', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'The verb is always "commit" — never "do" or "make" a crime.' },
    { id: 'crm_c2', type: 'collocation', term: 'the crime rate', collocationType: 'Noun + Noun', definition: 'The number of crimes recorded in a population.', vietnameseMeaning: 'Tỷ lệ tội phạm.', example: 'The crime rate has fallen while public fear of crime has risen.', topic: 'Crime & Law', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'crm_c3', type: 'collocation', term: 'break the law', collocationType: 'Verb + Noun', definition: 'To do something illegal.', vietnameseMeaning: 'Vi phạm pháp luật.', example: 'Laws that most citizens routinely break are unlikely to be enforced fairly.', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'crm_c4', type: 'collocation', term: 'serve a sentence', collocationType: 'Verb + Noun', definition: 'To spend the period of punishment ordered by a court.', vietnameseMeaning: 'Thi hành bản án, chấp hành hình phạt.', example: 'Prisoners who serve a sentence far from home lose the family ties that prevent reoffending.', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'crm_c5', type: 'collocation', term: 'petty crime', collocationType: 'Adj + Noun', definition: 'Minor offences such as small-scale theft.', vietnameseMeaning: 'Tội vặt, phạm tội nhỏ.', example: 'Petty crime responds far better to social intervention than to imprisonment.', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'crm_c6', type: 'collocation', term: 'law enforcement', collocationType: 'Noun + Noun', definition: 'The activity of ensuring laws are obeyed, and the agencies that do so.', vietnameseMeaning: 'Việc thực thi pháp luật; lực lượng chấp pháp.', example: 'Law enforcement is only as effective as public willingness to cooperate with it.', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'crm_c7', type: 'collocation', term: 'send someone to prison', collocationType: 'Verb + Noun', definition: 'To imprison a person as punishment.', vietnameseMeaning: 'Tống giam ai đó vào tù.', example: 'Sending someone to prison for an unpaid fine creates more problems than it resolves.', alternative: 'imprison', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', priority: 'high_value', writingTip: 'No article before "prison" in this phrase.' },
    { id: 'crm_c8', type: 'collocation', term: 'impose a fine', collocationType: 'Verb + Noun', definition: 'To officially require payment as a penalty.', vietnameseMeaning: 'Áp dụng hình phạt tiền.', example: 'Courts in Finland impose a fine calculated as a share of the offender’s income.', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', priority: 'high_value' },

    // Advanced (Band 6-7)
    { id: 'crm_c9', type: 'collocation', term: 'act as a deterrent', collocationType: 'Verb + Noun', definition: 'To discourage people from offending.', vietnameseMeaning: 'Có tác dụng răn đe.', example: 'Longer sentences act as a deterrent only if potential offenders expect to be caught.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'crm_c10', type: 'collocation', term: 'juvenile delinquency', collocationType: 'Adj + Noun', definition: 'Criminal behaviour by young people.', vietnameseMeaning: 'Tình trạng phạm pháp ở tuổi vị thành niên.', example: 'Juvenile delinquency correlates more closely with school exclusion than with poverty alone.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'crm_c11', type: 'collocation', term: 'reduce reoffending', collocationType: 'Verb + Noun', definition: 'To lower the number of released offenders who commit further crimes.', vietnameseMeaning: 'Giảm tỷ lệ tái phạm.', example: 'Guaranteed housing on release does more to reduce reoffending than any supervision scheme.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'crm_c12', type: 'collocation', term: 'the root causes of crime', collocationType: 'Noun + Prep + Noun', definition: 'The underlying social conditions that produce criminal behaviour.', vietnameseMeaning: 'Nguyên nhân gốc rễ của tội phạm.', example: 'Any durable strategy must address the root causes of crime rather than its symptoms.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'crm_c13', type: 'collocation', term: 'a custodial sentence', collocationType: 'Adj + Noun', definition: 'A punishment involving imprisonment.', vietnameseMeaning: 'Bản án tù giam.', example: 'A custodial sentence should be reserved for offenders who present a genuine danger.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'crm_c14', type: 'collocation', term: 'community service', collocationType: 'Noun + Noun', definition: 'Unpaid work performed as an alternative to prison.', vietnameseMeaning: 'Lao động công ích thay cho án tù.', example: 'Community service allows offenders to repay society without losing their employment.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'crm_c15', type: 'collocation', term: 'organised crime', collocationType: 'Adj + Noun', definition: 'Criminal activity run by structured groups on a large scale.', vietnameseMeaning: 'Tội phạm có tổ chức.', example: 'Organised crime flourishes wherever there is high demand and prohibition.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'crm_c16', type: 'collocation', term: 'rehabilitate offenders', collocationType: 'Verb + Noun', definition: 'To help criminals change so they can rejoin society.', vietnameseMeaning: 'Cải tạo người phạm tội để tái hoà nhập.', example: 'Prisons that genuinely rehabilitate offenders need staff, not just walls.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'crm_c17', type: 'collocation', term: 'a proportionate punishment', collocationType: 'Adj + Noun', definition: 'A penalty matching the seriousness of the offence.', vietnameseMeaning: 'Hình phạt tương xứng với mức độ phạm tội.', example: 'A proportionate punishment satisfies justice without creating a lasting grievance.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'crm_c18', type: 'collocation', term: 'restorative justice', collocationType: 'Adj + Noun', definition: 'An approach focused on repairing harm and involving victims.', vietnameseMeaning: 'Tư pháp phục hồi, hướng tới hàn gắn tổn hại.', example: 'Restorative justice produces higher victim satisfaction than conventional sentencing.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'crm_c19', type: 'collocation', term: 'act with impunity', collocationType: 'Verb + Prep + Noun', definition: 'To behave badly without facing any punishment.', vietnameseMeaning: 'Hành xử ngang nhiên mà không bị trừng phạt.', example: 'Companies that act with impunity abroad rely on the weakness of local enforcement.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'crm_c20', type: 'collocation', term: 'mitigating circumstances', collocationType: 'Adj + Noun', definition: 'Facts that make an offence less serious in the eyes of a court.', vietnameseMeaning: 'Các tình tiết giảm nhẹ.', example: 'Sentencing guidelines that ignore mitigating circumstances produce results the public finds unjust.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'crm_p1', type: 'phrasal_verb', term: 'get away with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To avoid punishment for something wrong.', vietnameseMeaning: 'Thoát tội, không bị trừng phạt.', example: 'Offenders who get away with minor crimes are emboldened to attempt larger ones.', formalAlternative: 'escape punishment for', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Fairly informal. "Escape punishment" or "act with impunity" is stronger in Task 2.', academicAlternatives: ['escape punishment for', 'evade justice'] },
    { id: 'crm_p2', type: 'phrasal_verb', term: 'break into', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To enter a building illegally and by force.', vietnameseMeaning: 'Đột nhập, phá cửa vào.', example: 'Burglars break into houses that appear unoccupied rather than those that appear wealthy.', formalAlternative: 'burgle', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['burgle', 'enter unlawfully'] },
    { id: 'crm_p3', type: 'phrasal_verb', term: 'look into', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To investigate a matter.', vietnameseMeaning: 'Điều tra, xem xét kỹ vụ việc.', example: 'Police rarely have the resources to look into every reported theft.', formalAlternative: 'investigate', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Conversational. "Investigate" or "examine" is the academic choice.', academicAlternatives: ['investigate', 'examine', 'inquire into'] },
    { id: 'crm_p4', type: 'phrasal_verb', term: 'lock up', partOfSpeech: 'phrasal verb (separable)', definition: 'To imprison someone.', vietnameseMeaning: 'Nhốt, tống giam.', example: 'Locking up addicts rather than treating them guarantees they will return.', formalAlternative: 'incarcerate', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Informal and slightly emotive. Use "imprison" or "incarcerate" in a formal essay.', academicAlternatives: ['imprison', 'incarcerate', 'detain'] },
    { id: 'crm_p5', type: 'phrasal_verb', term: 'let off', partOfSpeech: 'phrasal verb (separable)', definition: 'To give someone no punishment or a very light one.', vietnameseMeaning: 'Tha bổng, xử nhẹ.', example: 'Offenders let off with a warning are less likely to reoffend than those given short sentences.', formalAlternative: 'excuse', topic: 'Crime & Law', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'optional', usageWarning: 'Informal. Prefer "acquit", "discharge" or "treat leniently".', academicAlternatives: ['acquit', 'discharge', 'treat leniently'] },

    // Advanced / less common
    { id: 'crm_p6', type: 'phrasal_verb', term: 'stamp out', partOfSpeech: 'phrasal verb (separable)', definition: 'To eliminate something harmful completely.', vietnameseMeaning: 'Dẹp bỏ, xoá sổ hoàn toàn.', example: 'No government has ever stamped out corruption by legislation alone.', formalAlternative: 'eradicate', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['eradicate', 'eliminate', 'suppress'] },
    { id: 'crm_p7', type: 'phrasal_verb', term: 'track down', partOfSpeech: 'phrasal verb (separable)', definition: 'To find someone after a long search.', vietnameseMeaning: 'Truy tìm, lần ra dấu vết.', example: 'Digital records make it far easier to track down offenders than it was a generation ago.', formalAlternative: 'locate', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['locate', 'apprehend', 'trace'] },
    { id: 'crm_p8', type: 'phrasal_verb', term: 'turn to', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To start doing something, often as a last resort.', vietnameseMeaning: 'Xoay sang, sa vào (con đường nào đó).', example: 'Young people turn to crime where legitimate opportunities are genuinely absent.', formalAlternative: 'resort to', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['turn to crime', 'turn to violence'], academicAlternatives: ['resort to', 'have recourse to'] },
    { id: 'crm_p9', type: 'phrasal_verb', term: 'own up to', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To admit that you did something wrong.', vietnameseMeaning: 'Thú nhận, nhận lỗi.', example: 'Offenders who own up to their actions are treated more leniently in almost every system.', formalAlternative: 'confess to', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'use_with_caution', priority: 'optional', usageWarning: 'Informal. Use "admit", "confess to" or "acknowledge" in academic writing.', academicAlternatives: ['confess to', 'admit', 'acknowledge'] },
    { id: 'crm_p10', type: 'phrasal_verb', term: 'tip off', partOfSpeech: 'phrasal verb (separable)', definition: 'To secretly give someone information, usually about a crime.', vietnameseMeaning: 'Mật báo, cung cấp tin cho cơ quan chức năng.', example: 'Most large seizures follow a member of the public tipping off the authorities.', formalAlternative: 'inform', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['inform', 'alert', 'notify'] },
  ],

  writingPhrases: [
    { id: 'crm_w1', type: 'writing_phrase', term: 'The central question in sentencing is whether the aim is to punish or to...', function: 'Introducing an argument', vietnameseMeaning: 'Câu hỏi trung tâm trong việc tuyên án là mục đích để trừng phạt hay để...', example: 'The central question in sentencing is whether the aim is to punish or to prevent the next offence.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'crm_w2', type: 'writing_phrase', term: 'People turn to crime largely because...', function: 'Giving a reason', vietnameseMeaning: 'Người ta sa vào con đường phạm tội chủ yếu vì...', example: 'People turn to crime largely because the legal alternatives available to them pay too little to live on.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'crm_w3', type: 'writing_phrase', term: 'Much of this offending originates in...', function: 'Explaining a cause', vietnameseMeaning: 'Phần lớn hành vi phạm tội này bắt nguồn từ...', example: 'Much of this offending originates in childhood exclusion from school rather than in adult choices.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'crm_w4', type: 'writing_phrase', term: 'The result is a cycle in which offenders...', function: 'Explaining an effect', vietnameseMeaning: 'Kết quả là một vòng luẩn quẩn trong đó người phạm tội...', example: 'The result is a cycle in which offenders leave prison unemployable and return within a year.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'crm_w5', type: 'writing_phrase', term: 'Norway’s prison system is frequently cited here:', function: 'Giving an example', vietnameseMeaning: 'Hệ thống nhà tù của Na Uy thường được nhắc tới ở đây:', example: 'Norway’s prison system is frequently cited here: it emphasises rehabilitation and records among the lowest reoffending rates in Europe.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'crm_w6', type: 'writing_phrase', term: 'The advantage of non-custodial sentences is that they...', function: 'Discussing advantages', vietnameseMeaning: 'Ưu điểm của các hình phạt không giam giữ là chúng...', example: 'The advantage of non-custodial sentences is that they allow offenders to keep the job and family that keep them out of trouble.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'crm_w7', type: 'writing_phrase', term: 'The obvious objection to harsher penalties is that...', function: 'Discussing disadvantages', vietnameseMeaning: 'Phản đối rõ ràng đối với hình phạt nặng hơn là...', example: 'The obvious objection to harsher penalties is that they fill prisons without reducing the crime rate.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'crm_w8', type: 'writing_phrase', term: 'A more effective response would be to invest in...', function: 'Suggesting a solution', vietnameseMeaning: 'Một giải pháp hiệu quả hơn sẽ là đầu tư vào...', example: 'A more effective response would be to invest in youth services in the districts where offending is concentrated.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'crm_w9', type: 'writing_phrase', term: 'I remain convinced that prevention is preferable to...', function: 'Expressing an opinion', vietnameseMeaning: 'Tôi vẫn tin rằng phòng ngừa tốt hơn là...', example: 'I remain convinced that prevention is preferable to punishment, both morally and financially.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'crm_w10', type: 'writing_phrase', term: 'Imprisonment removes the offender; rehabilitation, by contrast, attempts to...', function: 'Comparing ideas', vietnameseMeaning: 'Giam giữ loại bỏ người phạm tội; ngược lại, cải tạo cố gắng...', example: 'Imprisonment removes the offender; rehabilitation, by contrast, attempts to return a changed person to society.', topic: 'Crime & Law', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'crm_m1', type: 'common_mistake', incorrect: 'Crime rate in big cities is rising.', correct: 'The crime rate in big cities is rising.', explanation: 'Specific rates, figures and percentages take "the": the crime rate, the unemployment rate, the number of offenders.', topic: 'Crime & Law', priority: 'must_learn' },
    { id: 'crm_m2', type: 'common_mistake', incorrect: 'Courts should punish offenders more strict.', correct: 'Courts should punish offenders more strictly.', explanation: 'You need an adverb to modify a verb. "Strict" describes a noun; "strictly" describes how the punishing is done.', topic: 'Crime & Law', priority: 'must_learn' },
    { id: 'crm_m3', type: 'common_mistake', incorrect: 'Some teenagers do crimes because of peer pressure.', correct: 'Some teenagers commit crimes because of peer pressure.', explanation: 'The verb that goes with "crime", "offence" and "fraud" is "commit". "Do a crime" is a direct translation and always wrong.', topic: 'Crime & Law', priority: 'must_learn' },
    { id: 'crm_m4', type: 'common_mistake', incorrect: 'He was sentenced to three years in the prison.', correct: 'He was sentenced to three years in prison.', explanation: 'Institutions used for their intended purpose take no article: in prison, at school, in hospital, at university.', topic: 'Crime & Law', priority: 'must_learn' },
    { id: 'crm_m5', type: 'common_mistake', incorrect: 'Death penalty should be abolished in every country.', correct: 'The death penalty should be abolished in every country.', explanation: 'Unique institutions and systems take "the": the death penalty, the legal system, the police, the government.', topic: 'Crime & Law', priority: 'high_value' },
  ],

  learnFirst: {
    vocabulary: ['crm_v3', 'crm_v11', 'crm_v12', 'crm_v13', 'crm_v16', 'crm_v19', 'crm_v21', 'crm_v22', 'crm_v25', 'crm_v30'],
    collocations: ['crm_c1', 'crm_c9', 'crm_c11', 'crm_c12', 'crm_c18'],
    phrasalVerbs: ['crm_p8', 'crm_p2', 'crm_p6'],
    writingPhrases: ['crm_w1', 'crm_w4', 'crm_w9'],
  },
}
