import type { TopicData } from '../types'

export const CULTURE: TopicData = {
  topic: 'Culture',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'cul_v1', type: 'vocabulary', term: 'tradition', pronunciation: '/trəˈdɪʃn/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'A custom or belief passed down within a community over a long period.', vietnameseMeaning: 'Truyền thống, phong tục lâu đời.', example: 'Traditions survive not because they are old but because each generation finds a reason to keep them.', writingTip: 'Countable: "a long-standing tradition", "local traditions". The adjective is "traditional".', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a long-standing tradition', 'preserve traditions', 'break with tradition', 'local traditions'], wordFamily: ['traditional (adj)', 'traditionally (adv)'], priority: 'must_learn' },
    { id: 'cul_v2', type: 'vocabulary', term: 'custom', pronunciation: '/ˈkʌstəm/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'A way of behaving that is usual in a particular society.', vietnameseMeaning: 'Tập quán, thói quen của một cộng đồng.', example: 'Visitors who take the trouble to learn local customs are received very differently from those who do not.', writingTip: 'Slightly narrower than "tradition" — a custom is a normal practice rather than an inherited ritual.', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['local customs', 'social customs', 'observe a custom', 'customs and traditions'], wordFamily: ['customary (adj)'], priority: 'must_learn' },
    { id: 'cul_v3', type: 'vocabulary', term: 'heritage', pronunciation: '/ˈherɪtɪdʒ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The buildings, traditions and values inherited from previous generations.', vietnameseMeaning: 'Di sản văn hoá, di sản của cha ông để lại.', example: 'Cultural heritage is easy to destroy in a decade and impossible to rebuild in a century.', writingTip: 'Uncountable — never "heritages". "Cultural heritage" and "heritage site" are the key collocations.', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cultural heritage', 'heritage site', 'preserve our heritage', 'rich heritage'], priority: 'must_learn' },
    { id: 'cul_v4', type: 'vocabulary', term: 'diverse', pronunciation: '/daɪˈvɜːs/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Made up of many different kinds of people or things.', vietnameseMeaning: 'Đa dạng, phong phú về thành phần.', example: 'Diverse cities tend to be more inventive, precisely because different ways of thinking collide in them.', writingTip: 'The noun "diversity" is even more useful: "cultural diversity", "promote diversity".', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['culturally diverse', 'a diverse population', 'diverse backgrounds'], antonym: 'homogeneous', wordFamily: ['diversity (n)', 'diversify (v)'], priority: 'must_learn' },
    { id: 'cul_v5', type: 'vocabulary', term: 'identity', pronunciation: '/aɪˈdentəti/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'The qualities and beliefs that make a person or group who they are.', vietnameseMeaning: 'Bản sắc, căn tính.', example: 'Language is often the last element of identity a migrant community gives up.', writingTip: '"Cultural identity", "national identity" and "a sense of identity" are all high-frequency.', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cultural identity', 'national identity', 'a sense of identity', 'lose one’s identity'], wordFamily: ['identify (v)', 'identification (n)'], priority: 'must_learn' },
    { id: 'cul_v6', type: 'vocabulary', term: 'celebrate', pronunciation: '/ˈselɪbreɪt/', partOfSpeech: 'verb', cefrLevel: 'B1', definition: 'To mark an important event or day with special activities.', vietnameseMeaning: 'Kỷ niệm, tổ chức lễ mừng.', example: 'Communities that celebrate their festivals publicly pass them on far more reliably than those that do not.', writingTip: 'Also used figuratively: "celebrate diversity", meaning to value it openly.', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['celebrate a festival', 'celebrate diversity', 'widely celebrated'], wordFamily: ['celebration (n)', 'celebratory (adj)'], priority: 'high_value' },
    { id: 'cul_v7', type: 'vocabulary', term: 'ancestor', pronunciation: '/ˈænsestə/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A person from whom one is descended, especially a distant one.', vietnameseMeaning: 'Tổ tiên, ông bà tổ phụ.', example: 'Rituals honouring ancestors remain central to family life across much of East Asia.', writingTip: 'Useful for essays on tradition and family. "Ancestral" is the adjective.', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', collocations: ['honour one’s ancestors', 'ancestral home', 'distant ancestors'], antonym: 'descendant', wordFamily: ['ancestral (adj)', 'ancestry (n)'], priority: 'high_value' },
    { id: 'cul_v8', type: 'vocabulary', term: 'adapt', pronunciation: '/əˈdæpt/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To change in order to fit new conditions.', vietnameseMeaning: 'Thích nghi, điều chỉnh cho phù hợp.', example: 'Cultures that adapt survive; those that refuse to change tend to be preserved only in museums.', writingTip: '"Adapt to" a situation. Do not confuse with "adopt" (to take up a practice).', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['adapt to change', 'adapt to a new culture', 'quickly adapt'], wordFamily: ['adaptation (n)', 'adaptable (adj)'], priority: 'must_learn' },
    { id: 'cul_v9', type: 'vocabulary', term: 'values', pronunciation: '/ˈvæljuːz/', partOfSpeech: 'noun (plural)', cefrLevel: 'B2', definition: 'The principles a person or society considers important.', vietnameseMeaning: 'Các giá trị, chuẩn mực đạo đức của một cộng đồng.', example: 'Traditional values around family obligation persist even where the economic conditions that created them have gone.', writingTip: 'Plural in this sense. "Shared values", "traditional values", "instil values" are all natural.', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['traditional values', 'shared values', 'moral values', 'instil values'], priority: 'must_learn' },
    { id: 'cul_v10', type: 'vocabulary', term: 'generation', pronunciation: '/ˌdʒenəˈreɪʃn/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'All the people born at roughly the same time.', vietnameseMeaning: 'Thế hệ.', example: 'Each generation reinterprets its inheritance rather than simply receiving it unchanged.', writingTip: '"The younger generation", "pass down through the generations", "generation gap" are all standard.', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the younger generation', 'future generations', 'generation gap', 'from generation to generation'], wordFamily: ['generational (adj)'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'cul_v11', type: 'vocabulary', term: 'multicultural', pronunciation: '/ˌmʌltiˈkʌltʃərəl/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Consisting of several distinct cultural groups living together.', vietnameseMeaning: 'Đa văn hoá.', example: 'Multicultural societies function best when institutions treat every group as equally legitimate.', writingTip: 'The noun "multiculturalism" refers to the policy of encouraging this; know both forms.', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a multicultural society', 'multicultural city', 'multicultural education'], wordFamily: ['multiculturalism (n)'], priority: 'must_learn' },
    { id: 'cul_v12', type: 'vocabulary', term: 'indigenous', pronunciation: '/ɪnˈdɪdʒənəs/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Originating in and naturally belonging to a particular place.', vietnameseMeaning: 'Bản địa, thuộc về dân tộc gốc của một vùng đất.', example: 'Indigenous communities hold ecological knowledge that formal science has only recently begun to take seriously.', writingTip: 'The correct and respectful term. Avoid "native" as a noun for people in academic writing.', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['indigenous people', 'indigenous languages', 'indigenous knowledge', 'indigenous communities'], priority: 'must_learn' },
    { id: 'cul_v13', type: 'vocabulary', term: 'assimilation', pronunciation: '/əˌsɪmɪˈleɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The process by which a minority group takes on the culture of the majority.', vietnameseMeaning: 'Sự đồng hoá vào văn hoá đa số.', example: 'Policies of forced assimilation caused lasting damage that integration policies have had to work hard to repair.', writingTip: 'Contrast it with "integration", which allows a group to retain its own identity. This distinction earns marks.', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cultural assimilation', 'forced assimilation', 'resist assimilation'], alternatives: ['integration'], wordFamily: ['assimilate (v)'], priority: 'high_value' },
    { id: 'cul_v14', type: 'vocabulary', term: 'stereotype', pronunciation: '/ˈsteriətaɪp/', partOfSpeech: 'noun / verb', cefrLevel: 'B2', definition: 'A fixed, oversimplified idea about what a group of people is like.', vietnameseMeaning: 'Định kiến rập khuôn về một nhóm người.', example: 'Films exported worldwide often reinforce stereotypes that the societies they depict have long outgrown.', writingTip: '"Reinforce", "challenge" and "perpetuate" stereotypes are the standard verb pairings.', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['reinforce stereotypes', 'challenge stereotypes', 'cultural stereotypes', 'negative stereotype'], wordFamily: ['stereotypical (adj)'], priority: 'must_learn' },
    { id: 'cul_v15', type: 'vocabulary', term: 'preserve', pronunciation: '/prɪˈzɜːv/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To keep something in its original state so that it survives.', vietnameseMeaning: 'Bảo tồn, gìn giữ nguyên vẹn.', example: 'Recording elderly speakers is often the only way to preserve a language with no written form.', writingTip: 'The essential verb of this topic. "Preservation" is the noun; "conserve" is a close synonym.', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['preserve traditions', 'preserve heritage', 'cultural preservation', 'preserve a language'], alternatives: ['conserve', 'safeguard', 'maintain'], wordFamily: ['preservation (n)'], priority: 'must_learn' },
    { id: 'cul_v16', type: 'vocabulary', term: 'ritual', pronunciation: '/ˈrɪtʃuəl/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A set of actions performed in a fixed order as part of a ceremony.', vietnameseMeaning: 'Nghi lễ, nghi thức.', example: 'Wedding rituals vary enormously, yet almost every society marks the occasion publicly in some way.', writingTip: 'More specific than "custom" — a ritual is ceremonial and formalised.', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['religious ritual', 'perform a ritual', 'traditional rituals'], wordFamily: ['ritualistic (adj)'], priority: 'high_value' },
    { id: 'cul_v17', type: 'vocabulary', term: 'westernisation', pronunciation: '/ˌwestənaɪˈzeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The adoption of Western customs, values and consumer habits.', vietnameseMeaning: 'Quá trình Tây hoá.', example: 'What is described as westernisation is frequently just urbanisation arriving with a foreign label attached.', writingTip: 'A useful term, but avoid treating it as automatically negative — examiners reward balanced treatment.', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['the westernisation of', 'increasing westernisation'], wordFamily: ['westernise (v)', 'westernised (adj)'], priority: 'high_value' },
    { id: 'cul_v18', type: 'vocabulary', term: 'norm', pronunciation: '/nɔːm/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A standard of behaviour that is expected within a group.', vietnameseMeaning: 'Chuẩn mực, quy tắc ứng xử được mặc định.', example: 'Social norms about punctuality differ so much between countries that misunderstandings are almost inevitable.', writingTip: 'Usually plural: "social norms", "cultural norms". "Norms and values" is a natural pairing.', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['social norms', 'cultural norms', 'challenge the norm', 'conform to norms'], wordFamily: ['normal (adj)', 'normative (adj)'], priority: 'must_learn' },
    { id: 'cul_v19', type: 'vocabulary', term: 'authentic', pronunciation: '/ɔːˈθentɪk/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Genuine and true to its original form.', vietnameseMeaning: 'Nguyên bản, đích thực, không bị pha tạp.', example: 'Tourists demand authentic experiences, and in supplying them communities inevitably alter what they were.', writingTip: 'A nuanced word — perfect for the tension between tourism and cultural preservation.', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['authentic culture', 'authentic experience', 'genuinely authentic'], antonym: 'artificial', wordFamily: ['authenticity (n)'], priority: 'high_value' },
    { id: 'cul_v20', type: 'vocabulary', term: 'cultural exchange', pronunciation: '/ˈkʌltʃərəl ɪksˈtʃeɪndʒ/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'The sharing of ideas, art and customs between different societies.', vietnameseMeaning: 'Giao lưu văn hoá.', example: 'Student exchange programmes achieve more genuine cultural exchange than any amount of official diplomacy.', writingTip: 'A ready-made phrase for the positive side of globalisation in a culture essay.', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['promote cultural exchange', 'mutual cultural exchange'], priority: 'must_learn' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'cul_v21', type: 'vocabulary', term: 'homogenisation', pronunciation: '/həˌmɒdʒənaɪˈzeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'The process by which distinct cultures become increasingly similar.', vietnameseMeaning: 'Sự đồng nhất hoá văn hoá.', example: 'The homogenisation of global youth culture is most visible in music, clothing and food.', writingTip: 'The precise term for what people loosely call "everywhere becoming the same".', topic: 'Culture', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cultural homogenisation', 'lead to homogenisation'], antonym: 'diversification', wordFamily: ['homogenise (v)', 'homogeneous (adj)'], priority: 'must_learn' },
    { id: 'cul_v22', type: 'vocabulary', term: 'intangible heritage', pronunciation: '/ɪnˈtændʒəbl ˈherɪtɪdʒ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Cultural inheritance that has no physical form, such as songs, crafts and oral traditions.', vietnameseMeaning: 'Di sản văn hoá phi vật thể.', example: 'Intangible heritage is the hardest to protect, since it disappears the moment nobody performs it.', writingTip: 'A precise term from UNESCO usage. It contrasts neatly with monuments and buildings.', topic: 'Culture', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['intangible cultural heritage', 'safeguard intangible heritage'], antonym: 'tangible heritage', priority: 'high_value' },
    { id: 'cul_v23', type: 'vocabulary', term: 'acculturation', pronunciation: '/əˌkʌltʃəˈreɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'The process of adopting elements of another culture while retaining one’s own.', vietnameseMeaning: 'Quá trình tiếp biến văn hoá.', example: 'Acculturation is a two-way process: host societies are changed by newcomers as surely as newcomers are changed by them.', writingTip: 'Distinguish from assimilation, which implies giving up the original culture entirely.', topic: 'Culture', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['the process of acculturation', 'rapid acculturation', 'acculturation stress'], wordFamily: ['acculturate (v)'], priority: 'optional' },
    { id: 'cul_v24', type: 'vocabulary', term: 'erode', pronunciation: '/ɪˈrəʊd/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To gradually weaken or destroy something.', vietnameseMeaning: 'Bào mòn, làm mai một dần.', example: 'Mass tourism erodes precisely the character that attracted visitors in the first place.', writingTip: 'Implies gradual, cumulative loss — ideal for describing what happens to traditions.', topic: 'Culture', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['erode traditions', 'gradually erode', 'erode cultural identity'], alternatives: ['undermine', 'dilute', 'weaken'], wordFamily: ['erosion (n)'], priority: 'must_learn' },
    { id: 'cul_v25', type: 'vocabulary', term: 'revive', pronunciation: '/rɪˈvaɪv/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To bring something back into use or popularity after a decline.', vietnameseMeaning: 'Phục hồi, làm sống lại (nghề, ngôn ngữ, phong tục).', example: 'Welsh has been revived to the point where the number of young speakers is now rising.', writingTip: 'A hopeful counterweight to "erode" — useful for balanced conclusions. The noun is "revival".', topic: 'Culture', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['revive a tradition', 'revive a language', 'a cultural revival'], wordFamily: ['revival (n)'], priority: 'high_value' },
    { id: 'cul_v26', type: 'vocabulary', term: 'ethnicity', pronunciation: '/eθˈnɪsəti/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'Belonging to a group with a shared cultural, linguistic or ancestral background.', vietnameseMeaning: 'Sắc tộc, dân tộc.', example: 'Census categories based on ethnicity capture something real, but they flatten enormous internal variation.', writingTip: 'Use "ethnicity" or "ethnic group" rather than "race" in careful academic writing.', topic: 'Culture', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['ethnic minority', 'ethnic group', 'regardless of ethnicity'], wordFamily: ['ethnic (adj)'], priority: 'high_value' },
    { id: 'cul_v27', type: 'vocabulary', term: 'cosmopolitan', pronunciation: '/ˌkɒzməˈpɒlɪtən/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Containing or familiar with people and ideas from many countries.', vietnameseMeaning: 'Mang tính quốc tế, hội tụ nhiều nền văn hoá.', example: 'Cosmopolitan cities produce citizens who move easily between cultures but sometimes belong fully to none.', writingTip: 'Positive in tone. A precise upgrade on "international" when describing places or outlooks.', topic: 'Culture', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['a cosmopolitan city', 'cosmopolitan outlook'], antonym: 'parochial', priority: 'optional' },
    { id: 'cul_v28', type: 'vocabulary', term: 'perpetuate', pronunciation: '/pəˈpetʃueɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To cause something, often undesirable, to continue indefinitely.', vietnameseMeaning: 'Duy trì, khiến điều gì đó tiếp diễn mãi (thường mang nghĩa tiêu cực).', example: 'Textbooks that describe only one community’s history perpetuate the exclusion of everyone else.', writingTip: 'Almost always used of negative things: perpetuate stereotypes, inequality, myths.', topic: 'Culture', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['perpetuate stereotypes', 'perpetuate inequality', 'perpetuate a myth'], wordFamily: ['perpetuation (n)', 'perpetual (adj)'], priority: 'must_learn' },
    { id: 'cul_v29', type: 'vocabulary', term: 'inclusive', pronunciation: '/ɪnˈkluːsɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Deliberately including people who might otherwise be excluded.', vietnameseMeaning: 'Bao trùm, không loại trừ ai, hoà nhập.', example: 'An inclusive national story has room for the histories of minorities without diminishing anyone else’s.', writingTip: 'A key word in solution paragraphs about diversity. The noun is "inclusion".', topic: 'Culture', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['an inclusive society', 'inclusive policies', 'socially inclusive'], antonym: 'exclusive', wordFamily: ['inclusion (n)', 'include (v)'], priority: 'high_value' },
    { id: 'cul_v30', type: 'vocabulary', term: 'coexist', pronunciation: '/ˌkəʊɪɡˈzɪst/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To exist together in the same place, usually peacefully.', vietnameseMeaning: 'Cùng tồn tại, chung sống hoà bình.', example: 'Several languages have coexisted in the region for centuries without any of them displacing the others.', writingTip: '"Coexist with" or "coexist peacefully". The noun "coexistence" is equally useful.', topic: 'Culture', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['coexist peacefully', 'coexist alongside', 'peaceful coexistence'], wordFamily: ['coexistence (n)'], priority: 'must_learn' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'cul_c1', type: 'collocation', term: 'cultural identity', collocationType: 'Adj + Noun', definition: 'The sense of belonging to a particular culture.', vietnameseMeaning: 'Bản sắc văn hoá.', example: 'Young migrants frequently develop a cultural identity that belongs entirely to neither country.', topic: 'Culture', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c2', type: 'collocation', term: 'preserve traditions', collocationType: 'Verb + Noun', definition: 'To keep customs alive so that they are not lost.', vietnameseMeaning: 'Gìn giữ, bảo tồn truyền thống.', example: 'Schools that teach traditional crafts preserve traditions far more effectively than museums do.', alternative: 'maintain traditions', topic: 'Culture', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c3', type: 'collocation', term: 'cultural diversity', collocationType: 'Adj + Noun', definition: 'The presence of many different cultures within one society.', vietnameseMeaning: 'Sự đa dạng văn hoá.', example: 'Cultural diversity enriches a country’s cuisine, music and language in ways that are impossible to quantify.', topic: 'Culture', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c4', type: 'collocation', term: 'traditional values', collocationType: 'Adj + Noun', definition: 'Long-established beliefs about how people should behave.', vietnameseMeaning: 'Các giá trị truyền thống.', example: 'Traditional values around respect for the elderly have proved remarkably resilient in urban Vietnam.', topic: 'Culture', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c5', type: 'collocation', term: 'pass down from generation to generation', collocationType: 'Verb phrase', definition: 'To transmit something from older people to younger ones over time.', vietnameseMeaning: 'Truyền lại từ đời này sang đời khác.', example: 'Recipes and songs are passed down from generation to generation with no written record at all.', topic: 'Culture', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c6', type: 'collocation', term: 'a cultural festival', collocationType: 'Adj + Noun', definition: 'A public event celebrating the traditions of a community.', vietnameseMeaning: 'Lễ hội văn hoá.', example: 'Cultural festivals give young people a reason to learn skills they would otherwise never encounter.', topic: 'Culture', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'cul_c7', type: 'collocation', term: 'respect other cultures', collocationType: 'Verb + Noun', definition: 'To treat the customs of other societies with consideration.', vietnameseMeaning: 'Tôn trọng các nền văn hoá khác.', example: 'Travelling teaches people to respect other cultures in a way no classroom can replicate.', topic: 'Culture', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'cul_c8', type: 'collocation', term: 'the younger generation', collocationType: 'Adj + Noun', definition: 'Young people considered as a group.', vietnameseMeaning: 'Thế hệ trẻ.', example: 'The younger generation is often blamed for abandoning tradition when in fact it is reshaping it.', topic: 'Culture', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'Takes "the" and a singular verb. Avoid the plural "the younger generations" unless you mean several.' },

    // Advanced (Band 6-7)
    { id: 'cul_c9', type: 'collocation', term: 'safeguard cultural heritage', collocationType: 'Verb + Noun', definition: 'To protect inherited traditions and sites from loss or damage.', vietnameseMeaning: 'Bảo vệ di sản văn hoá.', example: 'Legal protection alone cannot safeguard cultural heritage if the community that sustains it disperses.', alternative: 'protect cultural heritage', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c10', type: 'collocation', term: 'reinforce stereotypes', collocationType: 'Verb + Noun', definition: 'To strengthen oversimplified ideas about a group.', vietnameseMeaning: 'Củng cố những định kiến rập khuôn.', example: 'Casting the same communities in the same roles reinforces stereotypes with every film released.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c11', type: 'collocation', term: 'embrace cultural differences', collocationType: 'Verb + Noun', definition: 'To welcome and value the ways in which cultures differ.', vietnameseMeaning: 'Đón nhận sự khác biệt văn hoá.', example: 'Workplaces that genuinely embrace cultural differences report measurably higher levels of innovation.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c12', type: 'collocation', term: 'a sense of belonging', collocationType: 'Noun phrase', definition: 'The feeling of being an accepted part of a group.', vietnameseMeaning: 'Cảm giác thuộc về, gắn bó với cộng đồng.', example: 'Community festivals give newcomers a sense of belonging that language classes alone cannot provide.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c13', type: 'collocation', term: 'adapt to a new culture', collocationType: 'Verb + Noun', definition: 'To adjust one’s behaviour to fit an unfamiliar society.', vietnameseMeaning: 'Thích nghi với một nền văn hoá mới.', example: 'Children adapt to a new culture within months, while their parents may take a decade.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'cul_c14', type: 'collocation', term: 'cultural sensitivity', collocationType: 'Adj + Noun', definition: 'Awareness of and respect for cultural differences.', vietnameseMeaning: 'Sự nhạy cảm, tinh tế về văn hoá.', example: 'Training in cultural sensitivity has become standard for anyone working across borders.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'cul_c15', type: 'collocation', term: 'lose touch with one’s roots', collocationType: 'Verb phrase', definition: 'To become disconnected from one’s original culture or origins.', vietnameseMeaning: 'Đánh mất kết nối với cội nguồn.', example: 'Second-generation migrants often fear losing touch with their roots without ever quite belonging elsewhere.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'cul_c16', type: 'collocation', term: 'erode cultural identity', collocationType: 'Verb + Noun', definition: 'To gradually weaken a group’s distinctive character.', vietnameseMeaning: 'Làm xói mòn bản sắc văn hoá.', example: 'Whether global commerce genuinely erodes cultural identity or merely adds to it is far from settled.', topic: 'Culture', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c17', type: 'collocation', term: 'strike a balance between tradition and modernity', collocationType: 'Verb + Noun', definition: 'To find a workable compromise between old customs and modern life.', vietnameseMeaning: 'Cân bằng giữa truyền thống và hiện đại.', example: 'Successful societies strike a balance between tradition and modernity rather than choosing one over the other.', topic: 'Culture', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'cul_c18', type: 'collocation', term: 'foster mutual understanding', collocationType: 'Verb + Noun', definition: 'To encourage groups to understand each other better.', vietnameseMeaning: 'Thúc đẩy sự thấu hiểu lẫn nhau.', example: 'Exchange programmes foster mutual understanding more reliably than any government campaign.', topic: 'Culture', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'cul_c19', type: 'collocation', term: 'a rich cultural tapestry', collocationType: 'Adj + Noun', definition: 'A society made up of many interwoven cultural traditions.', vietnameseMeaning: 'Bức tranh văn hoá đa sắc, phong phú.', example: 'Centuries of migration have produced a rich cultural tapestry visible in the city’s architecture and food.', topic: 'Culture', bandLevel: '7+', task: 'task2', priority: 'optional', writingTip: 'A vivid metaphor, but use it once at most — repeated, it reads as memorised.' },
    { id: 'cul_c20', type: 'collocation', term: 'assert one’s cultural identity', collocationType: 'Verb + Noun', definition: 'To express and defend one’s cultural belonging openly.', vietnameseMeaning: 'Khẳng định bản sắc văn hoá của mình.', example: 'Minority communities increasingly assert their cultural identity through language rather than dress.', topic: 'Culture', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'cul_p1', type: 'phrasal_verb', term: 'pass on', partOfSpeech: 'phrasal verb (separable)', definition: 'To give knowledge or customs to a younger generation.', vietnameseMeaning: 'Truyền lại (kiến thức, phong tục) cho thế hệ sau.', example: 'Grandparents pass on dialects and songs that formal schooling never records.', formalAlternative: 'transmit', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['pass on traditions', 'pass on knowledge'], academicAlternatives: ['transmit', 'hand down', 'convey'] },
    { id: 'cul_p2', type: 'phrasal_verb', term: 'die out', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To gradually disappear until nothing remains.', vietnameseMeaning: 'Mai một, biến mất dần.', example: 'A language dies out roughly every fortnight, and with it a distinct way of describing the world.', formalAlternative: 'become extinct', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['become extinct', 'disappear', 'vanish'] },
    { id: 'cul_p3', type: 'phrasal_verb', term: 'fit in', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To feel accepted as part of a group.', vietnameseMeaning: 'Hoà nhập, cảm thấy thuộc về nhóm.', example: 'Children of immigrants often work hard to fit in at the cost of the language spoken at home.', formalAlternative: 'integrate', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['integrate', 'assimilate', 'adapt'] },
    { id: 'cul_p4', type: 'phrasal_verb', term: 'grow up', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To spend one’s childhood in a particular environment.', vietnameseMeaning: 'Lớn lên, trưởng thành trong môi trường nào đó.', example: 'People who grow up between two cultures develop a flexibility that monolingual peers rarely acquire.', formalAlternative: 'be raised', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['be raised', 'be brought up'] },
    { id: 'cul_p5', type: 'phrasal_verb', term: 'take part in', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To join in an activity with others.', vietnameseMeaning: 'Tham gia vào (hoạt động, lễ hội).', example: 'Encouraging young people to take part in local festivals is the cheapest form of cultural preservation there is.', formalAlternative: 'participate in', topic: 'Culture', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['participate in', 'engage in'] },

    // Advanced / less common
    { id: 'cul_p6', type: 'phrasal_verb', term: 'hand down', partOfSpeech: 'phrasal verb (separable)', definition: 'To pass something to a younger generation, especially over a long period.', vietnameseMeaning: 'Truyền lại qua nhiều thế hệ.', example: 'Weaving patterns handed down for three centuries are now recorded digitally in case the last practitioners stop.', formalAlternative: 'bequeath', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['handed down through generations', 'hand down a tradition'], academicAlternatives: ['bequeath', 'transmit', 'pass on'] },
    { id: 'cul_p7', type: 'phrasal_verb', term: 'cling to', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To hold on to a belief or custom, often stubbornly.', vietnameseMeaning: 'Bám víu vào, khư khư giữ lấy.', example: 'Communities under pressure sometimes cling to customs precisely because they feel them slipping away.', formalAlternative: 'adhere to', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', usageWarning: 'Slightly critical in tone — it implies resistance to necessary change.', academicAlternatives: ['adhere to', 'retain', 'hold on to'] },
    { id: 'cul_p8', type: 'phrasal_verb', term: 'take root', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To become established and start to grow in a new place.', vietnameseMeaning: 'Bén rễ, bám rễ và phát triển.', example: 'Foreign cuisines take root far faster than foreign values do.', formalAlternative: 'become established', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'high_value', academicAlternatives: ['become established', 'take hold'] },
    { id: 'cul_p9', type: 'phrasal_verb', term: 'break with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To stop following an established custom or practice.', vietnameseMeaning: 'Từ bỏ, đoạn tuyệt với (tập tục cũ).', example: 'Each generation breaks with some traditions and, almost unnoticed, invents others.', formalAlternative: 'depart from', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'high_value', collocations: ['break with tradition', 'break with convention'], academicAlternatives: ['depart from', 'abandon', 'reject'] },
    { id: 'cul_p10', type: 'phrasal_verb', term: 'water down', partOfSpeech: 'phrasal verb (separable)', definition: 'To make something weaker or less distinctive.', vietnameseMeaning: 'Làm nhạt đi, làm mất tính đặc trưng.', example: 'Traditions repackaged for tourists are frequently watered down until little of the original meaning survives.', formalAlternative: 'dilute', topic: 'Culture', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['dilute', 'weaken', 'trivialise'] },
  ],

  writingPhrases: [
    { id: 'cul_w1', type: 'writing_phrase', term: 'The question of whether tradition can survive modernisation is best approached by...', function: 'Introducing an argument', vietnameseMeaning: 'Câu hỏi liệu truyền thống có tồn tại được qua quá trình hiện đại hoá nên được tiếp cận bằng cách...', example: 'The question of whether tradition can survive modernisation is best approached by asking what traditions are actually for.', topic: 'Culture', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'cul_w2', type: 'writing_phrase', term: 'Young people abandon traditional practices largely because...', function: 'Giving a reason', vietnameseMeaning: 'Giới trẻ từ bỏ các tập tục truyền thống chủ yếu vì...', example: 'Young people abandon traditional practices largely because those practices were built around a rural life they no longer lead.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cul_w3', type: 'writing_phrase', term: 'This gradual loss of local custom originates in...', function: 'Explaining a cause', vietnameseMeaning: 'Sự mai một dần của phong tục địa phương bắt nguồn từ...', example: 'This gradual loss of local custom originates in migration rather than in any deliberate rejection of the past.', topic: 'Culture', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'cul_w4', type: 'writing_phrase', term: 'The effect on the community is that...', function: 'Explaining an effect', vietnameseMeaning: 'Tác động lên cộng đồng là...', example: 'The effect on the community is that shared rituals which once brought people together simply stop happening.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cul_w5', type: 'writing_phrase', term: 'The revival of the Welsh language demonstrates this well:', function: 'Giving an example', vietnameseMeaning: 'Sự hồi sinh của tiếng Wales minh chứng rõ cho điều này:', example: 'The revival of the Welsh language demonstrates this well: sustained schooling turned a declining language into a growing one.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'cul_w6', type: 'writing_phrase', term: 'The clearest benefit of a multicultural society is that...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi ích rõ ràng nhất của một xã hội đa văn hoá là...', example: 'The clearest benefit of a multicultural society is that its members learn early that there is more than one reasonable way to live.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cul_w7', type: 'writing_phrase', term: 'The risk inherent in this openness is that...', function: 'Discussing disadvantages', vietnameseMeaning: 'Rủi ro tiềm ẩn trong sự cởi mở này là...', example: 'The risk inherent in this openness is that smaller traditions are absorbed by larger ones without anyone deciding it should happen.', topic: 'Culture', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'cul_w8', type: 'writing_phrase', term: 'A more constructive approach would be to make traditions relevant by...', function: 'Suggesting a solution', vietnameseMeaning: 'Một cách tiếp cận mang tính xây dựng hơn là làm cho truyền thống trở nên phù hợp bằng cách...', example: 'A more constructive approach would be to make traditions relevant by allowing young people to adapt them rather than merely observe them.', topic: 'Culture', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'cul_w9', type: 'writing_phrase', term: 'It seems to me that cultures are strengthened, not weakened, by...', function: 'Expressing an opinion', vietnameseMeaning: 'Với tôi, các nền văn hoá được củng cố chứ không suy yếu đi bởi...', example: 'It seems to me that cultures are strengthened, not weakened, by contact with others, provided the exchange runs both ways.', topic: 'Culture', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'cul_w10', type: 'writing_phrase', term: 'Museums preserve the objects of a culture, whereas living communities preserve...', function: 'Comparing ideas', vietnameseMeaning: 'Bảo tàng lưu giữ hiện vật của một nền văn hoá, trong khi cộng đồng sống lưu giữ...', example: 'Museums preserve the objects of a culture, whereas living communities preserve the practices that gave those objects meaning.', topic: 'Culture', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'cul_m1', type: 'common_mistake', incorrect: 'Vietnamese people have many traditional cultures.', correct: 'Vietnam has a rich cultural tradition. / Vietnamese people observe many traditions.', explanation: '"Culture" is normally uncountable when referring to a people’s way of life, so "many cultures" wrongly implies several separate societies. Use "traditions", "customs" or "cultural practices".', topic: 'Culture', priority: 'must_learn' },
    { id: 'cul_m2', type: 'common_mistake', incorrect: 'We should keep our tradition and not follow the Western.', correct: 'We should preserve our traditions rather than simply imitating Western practices.', explanation: 'Three fixes: use the plural "traditions"; "keep" is weak where "preserve" or "maintain" is expected; and "the Western" is incomplete — an adjective needs a noun after it.', topic: 'Culture', priority: 'must_learn' },
    { id: 'cul_m3', type: 'common_mistake', incorrect: 'Young people today are influenced by foreign culture and forget their root.', correct: 'Young people today are influenced by foreign cultures and risk losing touch with their roots.', explanation: '"Roots" in this sense is always plural, and "forget" is too absolute — "lose touch with" is both more accurate and more natural.', topic: 'Culture', priority: 'high_value' },
    { id: 'cul_m4', type: 'common_mistake', incorrect: 'When I go abroad, I must adapt with the new culture.', correct: 'When people go abroad, they have to adapt to a new culture.', explanation: 'The preposition after "adapt" is "to", not "with". In Task 2 it is also better to write about people generally than about yourself.', topic: 'Culture', priority: 'must_learn' },
    { id: 'cul_m5', type: 'common_mistake', incorrect: 'Globalisation makes all countries have the same culture.', correct: 'Globalisation may lead to a degree of cultural homogenisation.', explanation: '"Makes ... have" is clumsy, and the claim is far too absolute. Use a precise noun ("homogenisation") with a hedge ("may", "a degree of") to sound academic and defensible.', topic: 'Culture', priority: 'must_learn' },
  ],

  learnFirst: {
    vocabulary: ['cul_v3', 'cul_v5', 'cul_v11', 'cul_v12', 'cul_v14', 'cul_v15', 'cul_v18', 'cul_v21', 'cul_v24', 'cul_v28'],
    collocations: ['cul_c1', 'cul_c2', 'cul_c9', 'cul_c16', 'cul_c17'],
    phrasalVerbs: ['cul_p1', 'cul_p6', 'cul_p2'],
    writingPhrases: ['cul_w1', 'cul_w6', 'cul_w8'],
  },
}
