import type { TopicData } from '../types'

export const ECONOMY: TopicData = {
  topic: 'Economy',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'eco_v1', type: 'vocabulary', term: 'income', pronunciation: '/ˈɪnkʌm/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'Money received regularly from work or investments.', vietnameseMeaning: 'Thu nhập.', example: 'Households on a low income spend a far greater share of it on food and fuel.', writingTip: 'Note "a low/high income", "household income", "income inequality". Do not say "income money".', topic: 'Economy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['household income', 'a low income', 'income inequality', 'disposable income'], alternatives: ['earnings', 'revenue'], antonym: 'expenditure', priority: 'must_learn' },
    { id: 'eco_v2', type: 'vocabulary', term: 'profit', pronunciation: '/ˈprɒfɪt/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'Money gained after all costs have been paid.', vietnameseMeaning: 'Lợi nhuận.', example: 'Firms that pursue short-term profit rarely survive a long downturn.', writingTip: '"Make a profit" is the standard verb, not "get" or "earn a profit".', topic: 'Economy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['make a profit', 'record profits', 'profit margin', 'maximise profit'], antonym: 'loss', wordFamily: ['profitable (adj)', 'profitability (n)'], priority: 'must_learn' },
    { id: 'eco_v3', type: 'vocabulary', term: 'investment', pronunciation: '/ɪnˈvestmənt/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'Money put into something in the expectation of future gain.', vietnameseMeaning: 'Sự đầu tư, khoản đầu tư.', example: 'Sustained investment in infrastructure produces returns that take decades to appear.', writingTip: 'Remember the preposition: "investment in", never "investment for".', topic: 'Economy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['foreign investment', 'investment in infrastructure', 'attract investment', 'long-term investment'], wordFamily: ['invest (v)', 'investor (n)'], priority: 'must_learn' },
    { id: 'eco_v4', type: 'vocabulary', term: 'consumer', pronunciation: '/kənˈsjuːmə/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A person who buys goods or services.', vietnameseMeaning: 'Người tiêu dùng.', example: 'Consumers respond far more strongly to price than to environmental labelling.', topic: 'Economy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['consumer spending', 'consumer demand', 'consumer confidence', 'protect consumers'], wordFamily: ['consume (v)', 'consumption (n)', 'consumerism (n)'], priority: 'must_learn' },
    { id: 'eco_v5', type: 'vocabulary', term: 'inflation', pronunciation: '/ɪnˈfleɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'A general rise in prices, which reduces the value of money.', vietnameseMeaning: 'Lạm phát.', example: 'Inflation erodes savings most severely for those who have the least of them.', writingTip: 'Uncountable. Verbs: rise, fall, accelerate, curb. Adjectives: high, rampant, low.', topic: 'Economy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['rising inflation', 'curb inflation', 'the rate of inflation', 'high inflation'], wordFamily: ['inflationary (adj)', 'inflate (v)'], priority: 'must_learn' },
    { id: 'eco_v6', type: 'vocabulary', term: 'tax', pronunciation: '/tæks/', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'Money paid to the government from income, sales or property.', vietnameseMeaning: 'Thuế; đánh thuế.', example: 'Raising tax on tobacco reduces consumption more reliably than health warnings.', writingTip: 'The verb is "raise" or "cut" taxes — never "rise taxes". "Taxation" is the abstract noun.', topic: 'Economy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['raise taxes', 'cut taxes', 'income tax', 'tax revenue', 'a tax on'], wordFamily: ['taxation (n)', 'taxable (adj)'], priority: 'must_learn' },
    { id: 'eco_v7', type: 'vocabulary', term: 'poverty', pronunciation: '/ˈpɒvəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The state of being extremely poor.', vietnameseMeaning: 'Nghèo đói, sự bần cùng.', example: 'Poverty is best understood not as a lack of money but as a lack of options.', writingTip: 'Verbs: alleviate, reduce, tackle, eradicate. Note "live in poverty" and "the poverty line".', topic: 'Economy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['alleviate poverty', 'live in poverty', 'the poverty line', 'extreme poverty'], antonym: 'affluence', wordFamily: ['poor (adj)', 'impoverished (adj)'], priority: 'must_learn' },
    { id: 'eco_v8', type: 'vocabulary', term: 'growth', pronunciation: '/ɡrəʊθ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'An increase in size, value or economic output.', vietnameseMeaning: 'Sự tăng trưởng, phát triển.', example: 'Economic growth that leaves wages flat brings little benefit to ordinary households.', writingTip: 'Essential in Task 1 too: "steady growth", "a period of rapid growth".', topic: 'Economy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['economic growth', 'rapid growth', 'steady growth', 'stimulate growth'], antonym: 'decline', wordFamily: ['grow (v)', 'growing (adj)'], priority: 'must_learn' },
    { id: 'eco_v9', type: 'vocabulary', term: 'currency', pronunciation: '/ˈkʌrənsi/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'The system of money used in a particular country.', vietnameseMeaning: 'Tiền tệ, đồng tiền của một quốc gia.', example: 'A weak currency makes exports cheaper but imported food more expensive.', topic: 'Economy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a strong currency', 'a weak currency', 'foreign currency', 'currency fluctuations'], priority: 'high_value' },
    { id: 'eco_v10', type: 'vocabulary', term: 'afford', pronunciation: '/əˈfɔːd/', partOfSpeech: 'verb', cefrLevel: 'B1', definition: 'To have enough money or time for something.', vietnameseMeaning: 'Có đủ khả năng chi trả.', example: 'Families who cannot afford childcare are effectively excluded from full-time work.', writingTip: 'Almost always used with "can", "cannot" or "be able to". Followed by a noun or "to + verb".', topic: 'Economy', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cannot afford', 'afford to buy', 'affordable housing'], wordFamily: ['affordable (adj)', 'affordability (n)'], priority: 'high_value' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'eco_v11', type: 'vocabulary', term: 'fluctuate', pronunciation: '/ˈflʌktʃueɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To rise and fall irregularly.', vietnameseMeaning: 'Dao động lên xuống thất thường.', example: 'Oil prices fluctuated sharply between 2014 and 2020 before stabilising.', writingTip: 'A Task 1 essential. Only use it for irregular up-and-down movement — never for a steady trend.', topic: 'Economy', bandLevel: '6-7', task: 'task1', writingSuitability: 'highly_suitable', collocations: ['fluctuate wildly', 'fluctuate between', 'prices fluctuate'], alternatives: ['vary', 'oscillate'], wordFamily: ['fluctuation (n)'], priority: 'must_learn' },
    { id: 'eco_v12', type: 'vocabulary', term: 'recession', pronunciation: '/rɪˈseʃn/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A period during which an economy shrinks rather than grows.', vietnameseMeaning: 'Suy thoái kinh tế.', example: 'Young workers who enter the labour market during a recession earn less for decades afterwards.', writingTip: 'Fixed phrases: "go into recession", "emerge from recession", "a deep recession".', topic: 'Economy', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['go into recession', 'a deep recession', 'emerge from recession'], alternatives: ['downturn', 'slump'], antonym: 'boom', priority: 'must_learn' },
    { id: 'eco_v13', type: 'vocabulary', term: 'subsidy', pronunciation: '/ˈsʌbsədi/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'Money paid by a government to reduce the cost of a product or service.', vietnameseMeaning: 'Khoản trợ cấp của nhà nước.', example: 'Fuel subsidies are politically popular and economically indefensible.', writingTip: 'Plural is "subsidies". The verb is "subsidise".', topic: 'Economy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['government subsidies', 'remove subsidies', 'agricultural subsidies'], wordFamily: ['subsidise (v)', 'subsidised (adj)'], priority: 'high_value' },
    { id: 'eco_v14', type: 'vocabulary', term: 'stimulate', pronunciation: '/ˈstɪmjuleɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To encourage activity or growth.', vietnameseMeaning: 'Kích thích, thúc đẩy tăng trưởng.', example: 'Cutting interest rates is intended to stimulate borrowing and investment.', topic: 'Economy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['stimulate growth', 'stimulate demand', 'stimulate the economy', 'stimulate investment'], alternatives: ['boost', 'spur', 'invigorate'], antonym: 'dampen', wordFamily: ['stimulus (n)', 'stimulation (n)'], priority: 'must_learn' },
    { id: 'eco_v15', type: 'vocabulary', term: 'disposable income', pronunciation: '/dɪˌspəʊzəbl ˈɪnkʌm/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The money left after tax and essential costs have been paid.', vietnameseMeaning: 'Thu nhập khả dụng, tiền còn lại sau chi phí thiết yếu.', example: 'Rising rents have swallowed almost all the growth in disposable income over the last decade.', writingTip: 'A precise term that shows economic literacy — much better than "spare money".', topic: 'Economy', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['rising disposable income', 'limited disposable income'], priority: 'must_learn' },
    { id: 'eco_v16', type: 'vocabulary', term: 'revenue', pronunciation: '/ˈrevənjuː/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Income received by a company or government.', vietnameseMeaning: 'Doanh thu, nguồn thu (của nhà nước hoặc doanh nghiệp).', example: 'Tourism generates more revenue for the region than manufacturing and farming combined.', writingTip: 'Revenue is total income before costs; profit is what remains after them. Do not confuse the two.', topic: 'Economy', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['generate revenue', 'tax revenue', 'a source of revenue', 'revenue streams'], priority: 'high_value' },
    { id: 'eco_v17', type: 'vocabulary', term: 'expenditure', pronunciation: '/ɪkˈspendɪtʃə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The total amount of money spent.', vietnameseMeaning: 'Chi tiêu, khoản chi.', example: 'Public expenditure on healthcare has grown faster than the economy as a whole.', writingTip: 'A formal Task 1 favourite — far more academic than "spending".', topic: 'Economy', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['public expenditure', 'household expenditure', 'reduce expenditure', 'capital expenditure'], alternatives: ['spending', 'outlay'], antonym: 'income', wordFamily: ['expend (v)'], priority: 'must_learn' },
    { id: 'eco_v18', type: 'vocabulary', term: 'living standards', pronunciation: '/ˈlɪvɪŋ ˌstændədz/', partOfSpeech: 'noun (plural)', cefrLevel: 'B2', definition: 'The level of comfort and material wealth available to a population.', vietnameseMeaning: 'Mức sống của người dân.', example: 'Living standards have improved in absolute terms while inequality has widened.', writingTip: 'Usually plural. Also written "standard of living" (singular) with the same meaning.', topic: 'Economy', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['improve living standards', 'falling living standards', 'the standard of living'], priority: 'must_learn' },
    { id: 'eco_v19', type: 'vocabulary', term: 'deficit', pronunciation: '/ˈdefɪsɪt/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'The amount by which spending exceeds income.', vietnameseMeaning: 'Thâm hụt (ngân sách, thương mại).', example: 'Closing the budget deficit through spending cuts alone has rarely succeeded.', writingTip: 'The opposite is a "surplus". Common types: budget deficit, trade deficit.', topic: 'Economy', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a budget deficit', 'a trade deficit', 'reduce the deficit'], antonym: 'surplus', priority: 'high_value' },
    { id: 'eco_v20', type: 'vocabulary', term: 'monopoly', pronunciation: '/məˈnɒpəli/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'Complete control of a market by a single company.', vietnameseMeaning: 'Sự độc quyền thị trường.', example: 'When a single platform enjoys a near monopoly, consumers lose the ability to switch.', topic: 'Economy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['have a monopoly on', 'break up a monopoly', 'a near monopoly'], wordFamily: ['monopolise (v)', 'monopolistic (adj)'], priority: 'high_value' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'eco_v21', type: 'vocabulary', term: 'affluent', pronunciation: '/ˈæfluənt/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Having a great deal of money; wealthy.', vietnameseMeaning: 'Giàu có, sung túc.', example: 'Even in affluent societies, a significant minority cannot meet basic housing costs.', writingTip: 'A more formal alternative to "rich" and very natural before "society", "nations", "households".', topic: 'Economy', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['affluent societies', 'increasingly affluent', 'affluent households'], alternatives: ['prosperous', 'wealthy', 'well-off'], antonym: 'impoverished', wordFamily: ['affluence (n)'], priority: 'must_learn' },
    { id: 'eco_v22', type: 'vocabulary', term: 'austerity', pronunciation: '/ɔːˈsterəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'Government policy of severe spending cuts to reduce debt.', vietnameseMeaning: 'Chính sách thắt lưng buộc bụng của chính phủ.', example: 'A decade of austerity reduced public debt but left services unable to cope with any shock.', topic: 'Economy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['austerity measures', 'a period of austerity', 'impose austerity'], antonym: 'stimulus', wordFamily: ['austere (adj)'], priority: 'high_value' },
    { id: 'eco_v23', type: 'vocabulary', term: 'redistribute', pronunciation: '/ˌriːdɪˈstrɪbjuːt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To share out money or resources differently, usually more evenly.', vietnameseMeaning: 'Phân phối lại (của cải, nguồn lực).', example: 'Progressive taxation redistributes wealth without discouraging enterprise, if the rates are moderate.', topic: 'Economy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['redistribute wealth', 'redistribute income', 'redistributive policies'], wordFamily: ['redistribution (n)', 'redistributive (adj)'], priority: 'must_learn' },
    { id: 'eco_v24', type: 'vocabulary', term: 'volatile', pronunciation: '/ˈvɒlətaɪl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Likely to change suddenly and unpredictably.', vietnameseMeaning: 'Biến động mạnh, khó lường.', example: 'Economies dependent on a single commodity are inherently volatile.', writingTip: 'The perfect adjective for Task 1 data that jumps around, and for unstable markets in Task 2.', topic: 'Economy', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a volatile market', 'highly volatile', 'volatile prices'], alternatives: ['unstable', 'unpredictable', 'erratic'], antonym: 'stable', wordFamily: ['volatility (n)'], priority: 'must_learn' },
    { id: 'eco_v25', type: 'vocabulary', term: 'lucrative', pronunciation: '/ˈluːkrətɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Producing a great deal of money.', vietnameseMeaning: 'Sinh lợi cao, béo bở.', example: 'Data has proved a far more lucrative commodity than most of the services that collect it.', writingTip: 'Use before "market", "business", "contract", "career" — not before people.', topic: 'Economy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a lucrative market', 'highly lucrative', 'a lucrative career'], alternatives: ['profitable', 'remunerative'], priority: 'high_value' },
    { id: 'eco_v26', type: 'vocabulary', term: 'impoverished', pronunciation: '/ɪmˈpɒvərɪʃt/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Made very poor.', vietnameseMeaning: 'Bị bần cùng hoá, nghèo khổ.', example: 'Debt repayments consume revenue that impoverished nations need for schools and clinics.', writingTip: 'Implies poverty caused by circumstances — stronger and more formal than "poor".', topic: 'Economy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['impoverished communities', 'impoverished nations', 'become impoverished'], alternatives: ['destitute', 'deprived'], antonym: 'affluent', wordFamily: ['impoverish (v)', 'impoverishment (n)'], priority: 'high_value' },
    { id: 'eco_v27', type: 'vocabulary', term: 'surge', pronunciation: '/sɜːdʒ/', partOfSpeech: 'verb / noun', cefrLevel: 'C1', definition: 'To increase suddenly and strongly.', vietnameseMeaning: 'Tăng vọt, tăng đột biến.', example: 'Demand for second-hand goods surged as household budgets tightened.', writingTip: 'One of the strongest Task 1 verbs for a sharp rise. Noun form: "a surge in demand".', topic: 'Economy', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['surge in demand', 'prices surged', 'a sudden surge'], alternatives: ['soar', 'rocket', 'escalate'], antonym: 'plummet', priority: 'must_learn' },
    { id: 'eco_v28', type: 'vocabulary', term: 'sustained', pronunciation: '/səˈsteɪnd/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Continuing steadily over a long period.', vietnameseMeaning: 'Liên tục, kéo dài không gián đoạn.', example: 'Only sustained investment, not one-off grants, will revive these regions.', writingTip: 'Very useful before growth, investment, effort, decline — signals duration precisely.', topic: 'Economy', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['sustained growth', 'sustained investment', 'a sustained decline'], alternatives: ['prolonged', 'continuous'], wordFamily: ['sustain (v)'], priority: 'high_value' },
    { id: 'eco_v29', type: 'vocabulary', term: 'diversify', pronunciation: '/daɪˈvɜːsɪfaɪ/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To increase the variety of products, activities or investments.', vietnameseMeaning: 'Đa dạng hoá (ngành nghề, đầu tư).', example: 'Oil-producing states that failed to diversify their economies are now dangerously exposed.', topic: 'Economy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['diversify the economy', 'diversify into', 'a diversified portfolio'], wordFamily: ['diversification (n)', 'diverse (adj)'], priority: 'high_value' },
    { id: 'eco_v30', type: 'vocabulary', term: 'speculation', pronunciation: '/ˌspekjuˈleɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Buying assets hoping their price will rise, rather than for their use.', vietnameseMeaning: 'Đầu cơ (mua để chờ giá lên).', example: 'Speculation in urban property has pushed housing beyond the reach of local wage earners.', writingTip: 'Also means "guessing without evidence" — the financial sense needs a clear context.', topic: 'Economy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['property speculation', 'financial speculation', 'curb speculation'], wordFamily: ['speculate (v)', 'speculative (adj)', 'speculator (n)'], priority: 'optional' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'eco_c1', type: 'collocation', term: 'economic growth', collocationType: 'Adj + Noun', definition: 'An increase in the value of goods and services a country produces.', vietnameseMeaning: 'Tăng trưởng kinh tế.', example: 'Economic growth alone does not guarantee that living standards will improve.', topic: 'Economy', bandLevel: '5-6', task: 'both', priority: 'must_learn', writingTip: 'The adjective is "economic" (relating to the economy), not "economical" (money-saving).' },
    { id: 'eco_c2', type: 'collocation', term: 'the cost of living', collocationType: 'Noun + Prep + Noun', definition: 'The amount of money needed to pay for basic necessities.', vietnameseMeaning: 'Chi phí sinh hoạt.', example: 'The cost of living has risen faster than wages for most of the past fifteen years.', topic: 'Economy', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'eco_c3', type: 'collocation', term: 'create jobs', collocationType: 'Verb + Noun', definition: 'To bring new employment opportunities into existence.', vietnameseMeaning: 'Tạo ra việc làm.', example: 'Public works programmes create jobs quickly, though not always durable ones.', alternative: 'generate employment', topic: 'Economy', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'eco_c4', type: 'collocation', term: 'raise taxes', collocationType: 'Verb + Noun', definition: 'To increase the amount of tax people pay.', vietnameseMeaning: 'Tăng thuế.', example: 'Few governments raise taxes willingly, whatever the state of the public finances.', alternative: 'increase taxation', topic: 'Economy', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: '"Raise" takes an object; "rise" does not. Never write "rise taxes".' },
    { id: 'eco_c5', type: 'collocation', term: 'reduce poverty', collocationType: 'Verb + Noun', definition: 'To decrease the number of people living without adequate resources.', vietnameseMeaning: 'Giảm nghèo.', example: 'Cash transfers reduce poverty more efficiently than most in-kind assistance.', alternative: 'alleviate poverty', topic: 'Economy', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'eco_c6', type: 'collocation', term: 'foreign investment', collocationType: 'Adj + Noun', definition: 'Money invested in a country by businesses based abroad.', vietnameseMeaning: 'Đầu tư nước ngoài.', example: 'Foreign investment brings capital and expertise, but also exposes economies to sudden withdrawal.', topic: 'Economy', bandLevel: '5-6', task: 'both', priority: 'high_value' },
    { id: 'eco_c7', type: 'collocation', term: 'improve living standards', collocationType: 'Verb + Noun', definition: 'To raise the level of comfort and material wellbeing.', vietnameseMeaning: 'Nâng cao mức sống.', example: 'Access to clean water improves living standards more cheaply than almost any other measure.', topic: 'Economy', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'eco_c8', type: 'collocation', term: 'the labour market', collocationType: 'Noun + Noun', definition: 'The overall supply of and demand for workers.', vietnameseMeaning: 'Thị trường lao động.', example: 'Automation is reshaping the labour market faster than education systems can respond.', topic: 'Economy', bandLevel: '5-6', task: 'both', priority: 'high_value' },

    // Advanced (Band 6-7)
    { id: 'eco_c9', type: 'collocation', term: 'income inequality', collocationType: 'Noun + Noun', definition: 'The uneven distribution of earnings across a population.', vietnameseMeaning: 'Bất bình đẳng thu nhập.', example: 'Income inequality has widened even in countries that have grown steadily richer.', topic: 'Economy', bandLevel: '6-7', task: 'both', priority: 'must_learn' },
    { id: 'eco_c10', type: 'collocation', term: 'boost the economy', collocationType: 'Verb + Noun', definition: 'To increase economic activity.', vietnameseMeaning: 'Thúc đẩy nền kinh tế.', example: 'Cutting sales tax temporarily can boost the economy, but only at a cost to future revenue.', alternative: 'stimulate the economy', topic: 'Economy', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'eco_c11', type: 'collocation', term: 'government spending', collocationType: 'Noun + Noun', definition: 'Money the state pays out for services and investment.', vietnameseMeaning: 'Chi tiêu công của chính phủ.', example: 'Government spending on early education repays itself many times over.', alternative: 'public expenditure', topic: 'Economy', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'eco_c12', type: 'collocation', term: 'a trade deficit', collocationType: 'Noun + Noun', definition: 'A situation in which a country imports more than it exports.', vietnameseMeaning: 'Thâm hụt thương mại.', example: 'A persistent trade deficit is only a problem if it is financed by unsustainable borrowing.', topic: 'Economy', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'eco_c13', type: 'collocation', term: 'rising disposable income', collocationType: 'Adj + Noun', definition: 'An increase in the money households have left after essentials.', vietnameseMeaning: 'Thu nhập khả dụng tăng lên.', example: 'Rising disposable income in Asia has transformed global tourism patterns.', topic: 'Economy', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'eco_c14', type: 'collocation', term: 'an economic downturn', collocationType: 'Adj + Noun', definition: 'A period when economic activity declines.', vietnameseMeaning: 'Giai đoạn kinh tế đi xuống.', example: 'Small businesses rarely have the reserves to survive a prolonged economic downturn.', alternative: 'a recession', topic: 'Economy', bandLevel: '6-7', task: 'both', priority: 'must_learn' },
    { id: 'eco_c15', type: 'collocation', term: 'generate revenue', collocationType: 'Verb + Noun', definition: 'To produce income for a business or government.', vietnameseMeaning: 'Tạo ra nguồn thu.', example: 'Congestion charging generates revenue while simultaneously reducing traffic.', topic: 'Economy', bandLevel: '6-7', task: 'task2', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'eco_c16', type: 'collocation', term: 'redistribute wealth', collocationType: 'Verb + Noun', definition: 'To transfer resources from richer to poorer members of society.', vietnameseMeaning: 'Phân phối lại của cải trong xã hội.', example: 'Attempts to redistribute wealth are politically contentious even where inequality is extreme.', topic: 'Economy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'eco_c17', type: 'collocation', term: 'sustained economic growth', collocationType: 'Adj + Noun', definition: 'Continuous expansion of the economy over many years.', vietnameseMeaning: 'Tăng trưởng kinh tế bền vững, kéo dài.', example: 'Sustained economic growth requires stable institutions far more than abundant resources.', topic: 'Economy', bandLevel: '7+', task: 'both', priority: 'must_learn' },
    { id: 'eco_c18', type: 'collocation', term: 'a volatile market', collocationType: 'Adj + Noun', definition: 'A market whose prices change rapidly and unpredictably.', vietnameseMeaning: 'Thị trường biến động mạnh.', example: 'Farmers selling into a volatile market cannot plan their planting with any confidence.', topic: 'Economy', bandLevel: '7+', task: 'both', priority: 'high_value' },
    { id: 'eco_c19', type: 'collocation', term: 'narrow the wealth gap', collocationType: 'Verb + Noun', definition: 'To reduce the difference between the richest and poorest.', vietnameseMeaning: 'Thu hẹp khoảng cách giàu nghèo.', example: 'Inheritance taxes are among the few instruments that genuinely narrow the wealth gap.', topic: 'Economy', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'eco_c20', type: 'collocation', term: 'impose austerity measures', collocationType: 'Verb + Noun', definition: 'To introduce severe cuts in public spending.', vietnameseMeaning: 'Áp dụng các biện pháp thắt lưng buộc bụng.', example: 'Governments that impose austerity measures during a downturn often deepen it.', topic: 'Economy', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'eco_p1', type: 'phrasal_verb', term: 'pay off', partOfSpeech: 'phrasal verb (separable)', definition: 'To repay a debt completely; to produce a good result.', vietnameseMeaning: 'Trả hết nợ; mang lại kết quả tốt.', example: 'Graduates in many countries take two decades to pay off their student loans.', formalAlternative: 'repay in full', topic: 'Economy', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['pay off debt', 'pay off a loan', 'investment pays off'], academicAlternatives: ['repay', 'settle', 'yield returns'] },
    { id: 'eco_p2', type: 'phrasal_verb', term: 'put up', partOfSpeech: 'phrasal verb (separable)', definition: 'To increase a price, rate or charge.', vietnameseMeaning: 'Tăng (giá, lãi suất).', example: 'Retailers put up prices the moment their own costs rise, and lower them far more slowly.', formalAlternative: 'increase', topic: 'Economy', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Informal. In Task 1 and Task 2 use "raise" or "increase".', academicAlternatives: ['raise', 'increase', 'inflate'] },
    { id: 'eco_p3', type: 'phrasal_verb', term: 'take off', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To begin to grow or succeed rapidly.', vietnameseMeaning: 'Cất cánh, bùng nổ tăng trưởng.', example: 'The economy only really took off once foreign firms were permitted to invest directly.', formalAlternative: 'expand rapidly', topic: 'Economy', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['expand rapidly', 'accelerate', 'flourish'] },
    { id: 'eco_p4', type: 'phrasal_verb', term: 'bail out', partOfSpeech: 'phrasal verb (separable)', definition: 'To rescue a failing company or country with money.', vietnameseMeaning: 'Giải cứu tài chính, cứu trợ bằng tiền.', example: 'Governments that bail out failing banks create an expectation that they always will.', formalAlternative: 'provide a financial rescue for', topic: 'Economy', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['bail out a bank', 'a government bailout'], academicAlternatives: ['rescue financially', 'provide emergency funding to'] },
    { id: 'eco_p5', type: 'phrasal_verb', term: 'fall back on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To use something as a reserve when other options fail.', vietnameseMeaning: 'Dựa vào (khoản dự phòng) khi cần.', example: 'Households with no savings to fall back on are pushed into debt by a single unexpected bill.', formalAlternative: 'rely on as a reserve', topic: 'Economy', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['resort to', 'rely on'] },

    // Advanced / less common
    { id: 'eco_p6', type: 'phrasal_verb', term: 'level off', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To stop rising or falling and stay at the same level.', vietnameseMeaning: 'Chững lại, ổn định ở một mức.', example: 'After a decade of rapid increase, house prices levelled off in 2019.', formalAlternative: 'stabilise', topic: 'Economy', bandLevel: '6-7', task: 'task1', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['level off at', 'begin to level off'], academicAlternatives: ['stabilise', 'plateau', 'remain constant'] },
    { id: 'eco_p7', type: 'phrasal_verb', term: 'bottom out', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To reach the lowest point before starting to rise again.', vietnameseMeaning: 'Chạm đáy rồi bắt đầu hồi phục.', example: 'Unemployment bottomed out in 2007 before climbing steeply the following year.', formalAlternative: 'reach a low point', topic: 'Economy', bandLevel: '6-7', task: 'task1', writingSuitability: 'highly_suitable', priority: 'high_value', academicAlternatives: ['reach a trough', 'hit a low of'] },
    { id: 'eco_p8', type: 'phrasal_verb', term: 'eat into', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To gradually reduce an amount of money or time.', vietnameseMeaning: 'Bào mòn, ăn dần vào (tiền tiết kiệm, lợi nhuận).', example: 'Rising energy costs have eaten into the savings of even middle-income families.', formalAlternative: 'erode', topic: 'Economy', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['erode', 'deplete', 'diminish'] },
    { id: 'eco_p9', type: 'phrasal_verb', term: 'cash in on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To take advantage of a situation to make money, often unfairly.', vietnameseMeaning: 'Trục lợi, kiếm lời từ tình huống nào đó.', example: 'Landlords cashed in on the shortage by raising rents well above inflation.', formalAlternative: 'profit from', topic: 'Economy', bandLevel: '6-7', task: 'task2', writingSuitability: 'use_with_caution', priority: 'optional', usageWarning: 'Carries a disapproving tone and is fairly informal. "Profit from" or "exploit" is safer.', academicAlternatives: ['profit from', 'exploit', 'capitalise on'] },
    { id: 'eco_p10', type: 'phrasal_verb', term: 'scale back', partOfSpeech: 'phrasal verb (separable)', definition: 'To reduce the size or extent of something planned.', vietnameseMeaning: 'Thu hẹp quy mô, giảm bớt kế hoạch.', example: 'Several manufacturers scaled back production as demand weakened.', formalAlternative: 'reduce in scale', topic: 'Economy', bandLevel: '6-7', task: 'both', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['curtail', 'reduce', 'downsize'] },
  ],

  writingPhrases: [
    { id: 'eco_w1', type: 'writing_phrase', term: 'The economic case for this policy is straightforward:', function: 'Introducing an argument', vietnameseMeaning: 'Lập luận kinh tế cho chính sách này rất rõ ràng:', example: 'The economic case for this policy is straightforward: every pound spent returns more in tax than it costs.', topic: 'Economy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'eco_w2', type: 'writing_phrase', term: 'One reason living standards have stagnated is that...', function: 'Giving a reason', vietnameseMeaning: 'Một lý do khiến mức sống trì trệ là...', example: 'One reason living standards have stagnated is that productivity gains have gone to shareholders rather than wages.', topic: 'Economy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'eco_w3', type: 'writing_phrase', term: 'This downturn was triggered largely by...', function: 'Explaining a cause', vietnameseMeaning: 'Đợt suy thoái này chủ yếu bị châm ngòi bởi...', example: 'This downturn was triggered largely by a sudden collapse in export demand.', topic: 'Economy', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'eco_w4', type: 'writing_phrase', term: 'The knock-on effect on employment was severe:', function: 'Explaining an effect', vietnameseMeaning: 'Tác động dây chuyền lên việc làm là rất nghiêm trọng:', example: 'The knock-on effect on employment was severe: manufacturing shed a fifth of its workforce within two years.', topic: 'Economy', bandLevel: '7+', task: 'both', priority: 'high_value' },
    { id: 'eco_w5', type: 'writing_phrase', term: 'Singapore is a striking example of this:', function: 'Giving an example', vietnameseMeaning: 'Singapore là một ví dụ nổi bật cho điều này:', example: 'Singapore is a striking example of this: a country with almost no natural resources built one of the highest incomes in the world.', topic: 'Economy', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'eco_w6', type: 'writing_phrase', term: 'The clearest economic benefit would be...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi ích kinh tế rõ ràng nhất sẽ là...', example: 'The clearest economic benefit would be a broader tax base capable of funding public services.', topic: 'Economy', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'eco_w7', type: 'writing_phrase', term: 'The hidden cost of this approach falls on...', function: 'Discussing disadvantages', vietnameseMeaning: 'Cái giá ẩn của cách tiếp cận này rơi vào...', example: 'The hidden cost of this approach falls on future taxpayers, who inherit the borrowing.', topic: 'Economy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'eco_w8', type: 'writing_phrase', term: 'A more targeted measure would be to...', function: 'Suggesting a solution', vietnameseMeaning: 'Một biện pháp có trọng điểm hơn sẽ là...', example: 'A more targeted measure would be to raise the threshold at which income tax begins.', topic: 'Economy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'eco_w9', type: 'writing_phrase', term: 'In my judgement, growth is only worth pursuing if...', function: 'Expressing an opinion', vietnameseMeaning: 'Theo đánh giá của tôi, tăng trưởng chỉ đáng theo đuổi nếu...', example: 'In my judgement, growth is only worth pursuing if its benefits reach those on the lowest incomes.', topic: 'Economy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'eco_w10', type: 'writing_phrase', term: 'Tax cuts stimulate demand quickly; public investment, by contrast,...', function: 'Comparing ideas', vietnameseMeaning: 'Cắt giảm thuế kích cầu nhanh; ngược lại, đầu tư công thì...', example: 'Tax cuts stimulate demand quickly; public investment, by contrast, works slowly but leaves something behind.', topic: 'Economy', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'eco_m1', type: 'common_mistake', incorrect: 'The country has achieved rapid economical growth.', correct: 'The country has achieved rapid economic growth.', explanation: '"Economic" means relating to the economy; "economical" means cheap to run. "Economical growth" would mean growth that saves money.', topic: 'Economy', priority: 'must_learn' },
    { id: 'eco_m2', type: 'common_mistake', incorrect: 'Many people in the city earn many money.', correct: 'Many people in the city earn a great deal of money.', explanation: '"Money" is uncountable and cannot take "many". Use "much", "a great deal of" or "a large amount of".', topic: 'Economy', priority: 'must_learn' },
    { id: 'eco_m3', type: 'common_mistake', incorrect: 'The price of housing is very expensive.', correct: 'The price of housing is very high.', explanation: 'Prices are high or low; products are expensive or cheap. "An expensive price" is a literal translation that does not work in English.', topic: 'Economy', priority: 'must_learn' },
    { id: 'eco_m4', type: 'common_mistake', incorrect: 'Sales increased of 15% between 2010 and 2015.', correct: 'Sales increased by 15% between 2010 and 2015.', explanation: 'Use "increase by" for the size of the change and "increase to" for the final figure. This costs marks in Task 1 constantly.', topic: 'Economy', priority: 'must_learn' },
    { id: 'eco_m5', type: 'common_mistake', incorrect: 'The government should rise taxes on luxury goods.', correct: 'The government should raise taxes on luxury goods.', explanation: '"Raise" is transitive and needs an object; "rise" is intransitive and cannot take one. Prices rise; governments raise them.', topic: 'Economy', priority: 'must_learn' },
  ],

  learnFirst: {
    vocabulary: ['eco_v5', 'eco_v7', 'eco_v11', 'eco_v14', 'eco_v17', 'eco_v18', 'eco_v21', 'eco_v23', 'eco_v24', 'eco_v27'],
    collocations: ['eco_c1', 'eco_c2', 'eco_c9', 'eco_c14', 'eco_c17'],
    phrasalVerbs: ['eco_p6', 'eco_p7', 'eco_p1'],
    writingPhrases: ['eco_w1', 'eco_w7', 'eco_w9'],
  },
}
