import type { TopicData } from '../types'

export const EDUCATION: TopicData = {
  topic: 'Education',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'edu_v1', type: 'vocabulary', term: 'curriculum', pronunciation: '/kəˈrɪkjələm/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'The set of subjects and content taught in a school or university.', vietnameseMeaning: 'Chương trình giảng dạy, khung chương trình học.', example: 'Financial literacy should be added to the national curriculum in secondary schools.', writingTip: 'Plural is "curricula" (or "curriculums"). Use "the school/national curriculum".', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the national curriculum', 'a broad curriculum', 'reform the curriculum', 'curriculum design'], wordFamily: ['curricular (adj)', 'extracurricular (adj)'], priority: 'must_learn' },
    { id: 'edu_v2', type: 'vocabulary', term: 'compulsory', pronunciation: '/kəmˈpʌlsəri/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Required by law or by rules.', vietnameseMeaning: 'Bắt buộc, mang tính cưỡng chế.', example: 'Making a second language compulsory from primary level would improve national competitiveness.', writingTip: 'Contrast with "optional" or "elective" to build a balanced paragraph.', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['compulsory education', 'compulsory subject', 'make something compulsory'], alternatives: ['mandatory', 'obligatory'], antonym: 'optional', wordFamily: ['compel (v)', 'compulsion (n)'], priority: 'must_learn' },
    { id: 'edu_v3', type: 'vocabulary', term: 'tuition fees', pronunciation: '/tjuˈɪʃn fiːz/', partOfSpeech: 'noun (plural)', cefrLevel: 'B2', definition: 'The money charged for teaching at a school or university.', vietnameseMeaning: 'Học phí.', example: 'Rising tuition fees have deterred many capable students from applying to university.', writingTip: 'Normally plural. Say "pay tuition fees", not "pay tuition money".', topic: 'Education', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['rising tuition fees', 'pay tuition fees', 'abolish tuition fees', 'waive tuition fees'], priority: 'must_learn' },
    { id: 'edu_v4', type: 'vocabulary', term: 'literacy', pronunciation: '/ˈlɪtərəsi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The ability to read and write; competence in a particular field.', vietnameseMeaning: 'Khả năng đọc viết; sự thông thạo trong một lĩnh vực.', example: 'Adult literacy programmes have proved a cost-effective way of reducing long-term unemployment.', writingTip: 'Extends usefully beyond reading: digital literacy, financial literacy, media literacy.', topic: 'Education', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['literacy rate', 'adult literacy', 'digital literacy', 'improve literacy'], antonym: 'illiteracy', wordFamily: ['literate (adj)', 'illiterate (adj)'], priority: 'high_value' },
    { id: 'edu_v5', type: 'vocabulary', term: 'discipline', pronunciation: '/ˈdɪsəplɪn/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'Controlled and orderly behaviour, or the training that produces it.', vietnameseMeaning: 'Kỷ luật, nề nếp; cũng có nghĩa là ngành học.', example: 'Strict discipline may produce obedient pupils, but it rarely produces confident ones.', writingTip: 'Also means "an academic subject": "an interdisciplinary approach". Context makes the meaning clear.', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['strict discipline', 'self-discipline', 'maintain discipline', 'academic discipline'], wordFamily: ['disciplined (adj)', 'disciplinary (adj)'], priority: 'high_value' },
    { id: 'edu_v6', type: 'vocabulary', term: 'motivate', pronunciation: '/ˈməʊtɪveɪt/', partOfSpeech: 'verb', cefrLevel: 'B1', definition: 'To make someone want to do something and put effort into it.', vietnameseMeaning: 'Tạo động lực, khích lệ.', example: 'Teachers who relate lessons to real situations motivate pupils far more effectively than those who do not.', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['motivate students', 'highly motivated', 'intrinsic motivation'], alternatives: ['inspire', 'encourage', 'drive'], antonym: 'demotivate', wordFamily: ['motivation (n)', 'motivated (adj)', 'motivational (adj)'], priority: 'must_learn' },
    { id: 'edu_v7', type: 'vocabulary', term: 'vocational', pronunciation: '/vəʊˈkeɪʃənl/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Relating to training for a specific job or trade.', vietnameseMeaning: 'Thuộc về đào tạo nghề, hướng nghiệp.', example: 'Vocational courses deserve the same status as academic degrees, since both meet real economic needs.', writingTip: 'The natural opposite of "academic" in education essays — a ready-made contrast.', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['vocational training', 'vocational course', 'vocational qualification'], antonym: 'academic', wordFamily: ['vocation (n)'], priority: 'must_learn' },
    { id: 'edu_v8', type: 'vocabulary', term: 'graduate', pronunciation: '/ˈɡrædʒuət/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A person who has completed a university degree.', vietnameseMeaning: 'Người tốt nghiệp đại học, cử nhân.', example: 'Employers increasingly complain that graduates lack the practical skills their industries require.', writingTip: 'Noun /ˈɡrædʒuət/ and verb /ˈɡrædʒueɪt/ are pronounced differently. The verb needs "from": graduate from university.', topic: 'Education', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['university graduate', 'recent graduate', 'graduate employment', 'graduate from'], wordFamily: ['graduate (v)', 'graduation (n)', 'postgraduate (n/adj)'], priority: 'high_value' },
    { id: 'edu_v9', type: 'vocabulary', term: 'knowledge', pronunciation: '/ˈnɒlɪdʒ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Information and understanding gained through learning or experience.', vietnameseMeaning: 'Kiến thức, tri thức.', example: 'Theoretical knowledge is of limited value unless students learn how to apply it.', writingTip: 'Uncountable — never "knowledges". Use "a body of knowledge" or "a great deal of knowledge".', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['acquire knowledge', 'apply knowledge', 'theoretical knowledge', 'a body of knowledge'], wordFamily: ['knowledgeable (adj)'], priority: 'must_learn' },
    { id: 'edu_v10', type: 'vocabulary', term: 'equip', pronunciation: '/ɪˈkwɪp/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To give someone the skills or knowledge they need.', vietnameseMeaning: 'Trang bị (kỹ năng, kiến thức) cho ai đó.', example: 'Schools should equip young people with the ability to evaluate information critically.', writingTip: 'The pattern is "equip somebody with something" — the preposition is essential.', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['equip students with', 'better equipped', 'equip the workforce'], alternatives: ['prepare', 'arm', 'furnish'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'edu_v11', type: 'vocabulary', term: 'facilitate', pronunciation: '/fəˈsɪlɪteɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To make a process easier or more likely to happen.', vietnameseMeaning: 'Tạo điều kiện thuận lợi, hỗ trợ cho.', example: 'Small class sizes facilitate the kind of discussion that large lectures make impossible.', writingTip: 'Followed by a noun, not by a person doing something: "facilitate learning", not "facilitate students to learn".', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['facilitate learning', 'facilitate communication', 'facilitate access to'], alternatives: ['enable', 'promote', 'assist'], antonym: 'hinder', wordFamily: ['facilitation (n)', 'facilitator (n)'], priority: 'must_learn' },
    { id: 'edu_v12', type: 'vocabulary', term: 'cultivate', pronunciation: '/ˈkʌltɪveɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To develop a quality or skill through deliberate effort over time.', vietnameseMeaning: 'Vun đắp, trau dồi, rèn luyện dần dần.', example: 'Group projects cultivate the negotiation skills that employers value most.', writingTip: 'Suggests slow, deliberate growth — stronger than "develop" when discussing character or habits.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cultivate skills', 'cultivate curiosity', 'cultivate a habit', 'cultivate independence'], alternatives: ['foster', 'nurture', 'develop'], wordFamily: ['cultivation (n)'], priority: 'must_learn' },
    { id: 'edu_v13', type: 'vocabulary', term: 'rote learning', pronunciation: '/ˌrəʊt ˈlɜːnɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Learning by repeating information until it is memorised, without understanding it.', vietnameseMeaning: 'Học vẹt, học thuộc lòng máy móc.', example: 'Examination systems that reward rote learning discourage genuine intellectual engagement.', writingTip: 'Extremely useful in essays about Asian education systems. Contrast it with "critical thinking".', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['rely on rote learning', 'rote memorisation', 'move away from rote learning'], antonym: 'critical thinking', priority: 'must_learn' },
    { id: 'edu_v14', type: 'vocabulary', term: 'assessment', pronunciation: '/əˈsesmənt/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'The process of judging the quality or level of something, especially student work.', vietnameseMeaning: 'Việc đánh giá, kiểm tra năng lực.', example: 'Continuous assessment gives a fairer picture of ability than a single final examination.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['continuous assessment', 'formal assessment', 'assessment criteria', 'methods of assessment'], wordFamily: ['assess (v)', 'assessor (n)'], priority: 'high_value' },
    { id: 'edu_v15', type: 'vocabulary', term: 'tailor', pronunciation: '/ˈteɪlə/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To adapt something to suit a particular need or person.', vietnameseMeaning: 'Điều chỉnh, thiết kế riêng cho phù hợp.', example: 'Adaptive software allows teachers to tailor exercises to each pupil’s level.', writingTip: 'The pattern is "tailor something to somebody/something". A precise alternative to "change".', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['tailor teaching to', 'tailored to individual needs', 'a tailored approach'], alternatives: ['adapt', 'customise', 'adjust'], priority: 'high_value' },
    { id: 'edu_v16', type: 'vocabulary', term: 'autonomy', pronunciation: '/ɔːˈtɒnəmi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The freedom to make your own decisions.', vietnameseMeaning: 'Quyền tự chủ, sự độc lập trong quyết định.', example: 'Giving schools greater autonomy over their timetables has produced mixed results.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['learner autonomy', 'greater autonomy', 'grant autonomy', 'a degree of autonomy'], alternatives: ['independence', 'self-governance'], wordFamily: ['autonomous (adj)', 'autonomously (adv)'], priority: 'high_value' },
    { id: 'edu_v17', type: 'vocabulary', term: 'peer', pronunciation: '/pɪə/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A person of the same age or status as another.', vietnameseMeaning: 'Bạn đồng trang lứa, người cùng nhóm.', example: 'Adolescents are influenced far more by their peers than by their teachers.', writingTip: 'Very productive as a modifier: peer pressure, peer review, peer learning.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['peer pressure', 'peer group', 'peer review', 'learn from peers'], priority: 'high_value' },
    { id: 'edu_v18', type: 'vocabulary', term: 'subsidise', pronunciation: '/ˈsʌbsɪdaɪz/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To pay part of the cost of something so that it is cheaper for users.', vietnameseMeaning: 'Trợ cấp, bù giá cho một phần chi phí.', example: 'Governments that subsidise higher education tend to enjoy higher rates of social mobility.', writingTip: 'A sharper alternative to "the government pays for". Note the noun "subsidy" (plural: subsidies).', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['subsidise education', 'heavily subsidised', 'state-subsidised'], wordFamily: ['subsidy (n)', 'subsidised (adj)'], priority: 'high_value' },
    { id: 'edu_v19', type: 'vocabulary', term: 'holistic', pronunciation: '/həˈlɪstɪk/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Considering the whole of something rather than only its parts.', vietnameseMeaning: 'Toàn diện, xét trên tổng thể.', example: 'A holistic approach to education values emotional development as highly as examination results.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a holistic approach', 'holistic development', 'holistic education'], alternatives: ['comprehensive', 'all-round'], wordFamily: ['holistically (adv)'], priority: 'high_value' },
    { id: 'edu_v20', type: 'vocabulary', term: 'inclusive', pronunciation: '/ɪnˈkluːsɪv/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Designed so that everyone can take part, including those with disadvantages.', vietnameseMeaning: 'Hoà nhập, không loại trừ ai.', example: 'Truly inclusive schooling requires investment in specialist staff, not merely a change of policy.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['inclusive education', 'an inclusive classroom', 'socially inclusive'], antonym: 'exclusive', wordFamily: ['inclusion (n)', 'include (v)'], priority: 'high_value' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'edu_v21', type: 'vocabulary', term: 'pedagogy', pronunciation: '/ˈpedəɡɒdʒi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'The theory and practice of teaching.', vietnameseMeaning: 'Phương pháp sư phạm, khoa học giảng dạy.', example: 'Technology has changed the tools of the classroom without changing its underlying pedagogy.', writingTip: 'Use sparingly and only when genuinely discussing teaching method, not education in general.', topic: 'Education', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['modern pedagogy', 'teaching pedagogy', 'pedagogical approach'], wordFamily: ['pedagogical (adj)'], priority: 'optional' },
    { id: 'edu_v22', type: 'vocabulary', term: 'meritocracy', pronunciation: '/ˌmerɪˈtɒkrəsi/', partOfSpeech: 'noun', cefrLevel: 'C2', definition: 'A system in which people succeed according to ability and effort rather than background.', vietnameseMeaning: 'Chế độ trọng dụng người tài, xã hội dựa trên năng lực.', example: 'Education is often described as the foundation of a meritocracy, yet wealthy families continue to buy advantage.', topic: 'Education', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a genuine meritocracy', 'the ideal of meritocracy'], wordFamily: ['meritocratic (adj)'], priority: 'optional' },
    { id: 'edu_v23', type: 'vocabulary', term: 'instil', pronunciation: '/ɪnˈstɪl/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To gradually establish an idea or attitude in someone’s mind.', vietnameseMeaning: 'Gieo vào, truyền dần (giá trị, thói quen).', example: 'Reading aloud to young children instils a lasting enjoyment of books.', writingTip: 'Pattern: "instil something in somebody". Spelled "instill" in American English.', topic: 'Education', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['instil confidence', 'instil discipline', 'instil values', 'instil a sense of'], alternatives: ['inculcate', 'implant', 'foster'], priority: 'must_learn' },
    { id: 'edu_v24', type: 'vocabulary', term: 'aptitude', pronunciation: '/ˈæptɪtjuːd/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'A natural ability to learn or do something well.', vietnameseMeaning: 'Năng khiếu, khả năng bẩm sinh.', example: 'Selecting pupils by aptitude at the age of eleven condemns late developers to a narrower future.', writingTip: 'Followed by "for": "an aptitude for languages".', topic: 'Education', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['an aptitude for', 'natural aptitude', 'aptitude test'], alternatives: ['talent', 'flair', 'capacity'], priority: 'high_value' },
    { id: 'edu_v25', type: 'vocabulary', term: 'disparity', pronunciation: '/dɪˈspærəti/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'A large and unfair difference between groups.', vietnameseMeaning: 'Sự chênh lệch, khoảng cách bất bình đẳng.', example: 'The disparity in funding between urban and rural schools is difficult to justify.', writingTip: 'Followed by "in" (the area) and "between" (the groups). More precise than "difference".', topic: 'Education', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a growing disparity', 'disparity in funding', 'address the disparity', 'regional disparities'], alternatives: ['inequality', 'imbalance', 'gap'], antonym: 'parity', wordFamily: ['disparate (adj)'], priority: 'must_learn' },
    { id: 'edu_v26', type: 'vocabulary', term: 'extracurricular', pronunciation: '/ˌekstrəkəˈrɪkjələ/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Relating to activities done at school outside the normal syllabus.', vietnameseMeaning: 'Ngoại khoá, ngoài chương trình chính khoá.', example: 'Extracurricular activities develop leadership qualities that no examination can measure.', topic: 'Education', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['extracurricular activities', 'extracurricular programme'], priority: 'high_value' },
    { id: 'edu_v27', type: 'vocabulary', term: 'conducive', pronunciation: '/kənˈdjuːsɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Creating conditions in which something can happen or succeed.', vietnameseMeaning: 'Thuận lợi cho, tạo điều kiện cho.', example: 'Overcrowded classrooms are simply not conducive to concentrated study.', writingTip: 'Always "conducive to" + noun or -ing. Never "conducive for".', topic: 'Education', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['conducive to learning', 'conducive to concentration', 'an environment conducive to'], alternatives: ['favourable to', 'helpful for'], priority: 'must_learn' },
    { id: 'edu_v28', type: 'vocabulary', term: 'stifle', pronunciation: '/ˈstaɪfl/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To prevent something from developing or being expressed.', vietnameseMeaning: 'Kìm hãm, bóp nghẹt (sự sáng tạo, ý kiến).', example: 'Rigid, examination-driven teaching stifles the curiosity that motivates real learning.', writingTip: 'Perfect for criticising restrictive systems: stifle creativity / innovation / debate.', topic: 'Education', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['stifle creativity', 'stifle innovation', 'stifle debate', 'stifle initiative'], alternatives: ['suppress', 'inhibit', 'smother'], antonym: 'encourage', priority: 'must_learn' },
    { id: 'edu_v29', type: 'vocabulary', term: 'underpin', pronunciation: '/ˌʌndəˈpɪn/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To form the basis or foundation of something.', vietnameseMeaning: 'Làm nền tảng, làm cơ sở cho.', example: 'Literacy and numeracy underpin every other subject in the curriculum.', writingTip: 'Excellent for showing that one factor supports many others — a Band 8 kind of sentence.', topic: 'Education', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['underpin economic growth', 'underpin the argument', 'principles that underpin'], alternatives: ['form the basis of', 'support', 'buttress'], priority: 'high_value' },
    { id: 'edu_v30', type: 'vocabulary', term: 'lifelong', pronunciation: '/ˈlaɪflɒŋ/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Continuing for the whole of a person’s life.', vietnameseMeaning: 'Suốt đời, kéo dài cả cuộc đời.', example: 'In a labour market reshaped by automation, lifelong learning is no longer optional.', writingTip: '"Lifelong learning" is the standard phrase for continuing education after formal schooling.', topic: 'Education', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['lifelong learning', 'a lifelong habit', 'lifelong interest'], priority: 'high_value' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'edu_c1', type: 'collocation', term: 'higher education', collocationType: 'Adj + Noun', definition: 'Education at university or college level.', vietnameseMeaning: 'Giáo dục bậc cao, giáo dục đại học.', example: 'Access to higher education has widened dramatically over the past thirty years.', topic: 'Education', bandLevel: '5-6', task: 'both', priority: 'must_learn', writingTip: 'No article in the general sense: "higher education is...", not "the higher education".' },
    { id: 'edu_c2', type: 'collocation', term: 'sit an exam', collocationType: 'Verb + Noun', definition: 'To take a formal test.', vietnameseMeaning: 'Tham dự một kỳ thi.', example: 'Pupils in this country sit an exam that determines their entire educational future.', alternative: 'take an exam', topic: 'Education', bandLevel: '5-6', task: 'task2', priority: 'high_value', writingTip: 'British English says "sit an exam"; American English prefers "take an exam". Never "do an exam" in formal writing.' },
    { id: 'edu_c3', type: 'collocation', term: 'academic performance', collocationType: 'Adj + Noun', definition: 'How well a student does in their studies.', vietnameseMeaning: 'Thành tích học tập.', example: 'Sleep deprivation has a measurable effect on academic performance.', alternative: 'academic achievement', topic: 'Education', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'edu_c4', type: 'collocation', term: 'practical skills', collocationType: 'Adj + Noun', definition: 'Abilities that can be used directly in real work or life.', vietnameseMeaning: 'Kỹ năng thực hành, kỹ năng thực tế.', example: 'Degree courses should devote more time to the practical skills employers actually need.', topic: 'Education', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'edu_c5', type: 'collocation', term: 'acquire knowledge', collocationType: 'Verb + Noun', definition: 'To gain understanding through study or experience.', vietnameseMeaning: 'Tiếp thu kiến thức, thu nhận tri thức.', example: 'Students now acquire knowledge from sources their teachers cannot control.', alternative: 'gain knowledge', topic: 'Education', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'You acquire knowledge and skills — but you "gain experience".' },
    { id: 'edu_c6', type: 'collocation', term: 'compulsory education', collocationType: 'Adj + Noun', definition: 'The years of schooling that the law requires children to complete.', vietnameseMeaning: 'Giáo dục bắt buộc, phổ cập giáo dục.', example: 'Extending compulsory education to the age of eighteen would reduce youth unemployment.', topic: 'Education', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'edu_c7', type: 'collocation', term: 'equip students with skills', collocationType: 'Verb + Noun + Prep', definition: 'To give learners the abilities they will need.', vietnameseMeaning: 'Trang bị kỹ năng cho học sinh.', example: 'Universities must equip students with skills that remain useful as industries change.', topic: 'Education', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'edu_c8', type: 'collocation', term: 'the school curriculum', collocationType: 'Noun + Noun', definition: 'The official list of subjects and content taught in schools.', vietnameseMeaning: 'Chương trình học của nhà trường.', example: 'Adding personal finance to the school curriculum would benefit every pupil.', topic: 'Education', bandLevel: '5-6', task: 'task2', priority: 'high_value' },

    // Advanced (Band 6-7)
    { id: 'edu_c9', type: 'collocation', term: 'critical thinking skills', collocationType: 'Adj + Noun', definition: 'The ability to analyse information and judge it independently.', vietnameseMeaning: 'Kỹ năng tư duy phản biện.', example: 'An education that neglects critical thinking skills produces graduates who are easy to mislead.', topic: 'Education', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'edu_c10', type: 'collocation', term: 'narrow the attainment gap', collocationType: 'Verb + Noun', definition: 'To reduce the difference in results between advantaged and disadvantaged pupils.', vietnameseMeaning: 'Thu hẹp khoảng cách về thành tích học tập.', example: 'Free breakfast clubs have done more to narrow the attainment gap than any curriculum reform.', alternative: 'close the achievement gap', topic: 'Education', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'edu_c11', type: 'collocation', term: 'vocational training', collocationType: 'Adj + Noun', definition: 'Practical instruction that prepares people for a specific trade.', vietnameseMeaning: 'Đào tạo nghề.', example: 'Germany’s emphasis on vocational training explains its unusually low youth unemployment.', topic: 'Education', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'edu_c12', type: 'collocation', term: 'foster independent learning', collocationType: 'Verb + Noun', definition: 'To encourage students to study without constant supervision.', vietnameseMeaning: 'Khuyến khích khả năng tự học.', example: 'Project-based courses foster independent learning far more successfully than lectures do.', topic: 'Education', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'edu_c13', type: 'collocation', term: 'rising tuition fees', collocationType: 'Adj + Noun', definition: 'Steadily increasing charges for university study.', vietnameseMeaning: 'Học phí ngày càng tăng.', example: 'Rising tuition fees have shifted the cost of education from the state to the individual.', topic: 'Education', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'edu_c14', type: 'collocation', term: 'broaden your horizons', collocationType: 'Verb + Noun', definition: 'To widen your experience and understanding of the world.', vietnameseMeaning: 'Mở mang tầm nhìn, mở rộng hiểu biết.', example: 'Studying abroad broadens students’ horizons in ways no classroom can replicate.', topic: 'Education', bandLevel: '6-7', task: 'task2', priority: 'high_value', writingTip: 'Note the plural "horizons" — "broaden your horizon" is incorrect.' },
    { id: 'edu_c15', type: 'collocation', term: 'a well-rounded education', collocationType: 'Adj + Noun', definition: 'An education covering a wide range of academic and personal development.', vietnameseMeaning: 'Một nền giáo dục toàn diện.', example: 'A well-rounded education should include the arts as well as science and mathematics.', topic: 'Education', bandLevel: '6-7', task: 'task2', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'edu_c16', type: 'collocation', term: 'instil a love of learning', collocationType: 'Verb + Noun', definition: 'To create a lasting enjoyment of study in someone.', vietnameseMeaning: 'Gieo niềm say mê học tập.', example: 'The best teachers instil a love of learning that outlasts any syllabus.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'edu_c17', type: 'collocation', term: 'stifle creativity', collocationType: 'Verb + Noun', definition: 'To prevent original thinking from developing.', vietnameseMeaning: 'Kìm hãm, bóp nghẹt sự sáng tạo.', example: 'Standardised testing stifles creativity by rewarding only predictable answers.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'edu_c18', type: 'collocation', term: 'an environment conducive to learning', collocationType: 'Noun + Adj + Prep', definition: 'Surroundings that make effective study possible.', vietnameseMeaning: 'Môi trường thuận lợi cho việc học.', example: 'Reducing class sizes is the simplest way to create an environment conducive to learning.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'edu_c19', type: 'collocation', term: 'rote memorisation', collocationType: 'Noun + Noun', definition: 'Learning purely by repetition without understanding.', vietnameseMeaning: 'Việc học thuộc lòng máy móc.', example: 'Examinations built around rote memorisation reward patience rather than intelligence.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'edu_c20', type: 'collocation', term: 'widen educational disparities', collocationType: 'Verb + Noun', definition: 'To increase the unfair gap between different learners.', vietnameseMeaning: 'Làm gia tăng chênh lệch trong giáo dục.', example: 'Charging for online resources risks widening educational disparities still further.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'edu_p1', type: 'phrasal_verb', term: 'drop out (of)', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To leave a course of study before finishing it.', vietnameseMeaning: 'Bỏ học giữa chừng.', example: 'Students from low-income families are three times more likely to drop out of university.', formalAlternative: 'withdraw from', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', collocations: ['drop out of school', 'drop-out rate'], academicAlternatives: ['withdraw from', 'discontinue', 'abandon'] },
    { id: 'edu_p2', type: 'phrasal_verb', term: 'catch up (with)', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To reach the same level as others after being behind.', vietnameseMeaning: 'Theo kịp, bắt kịp các bạn khác.', example: 'Pupils who miss a term of schooling rarely catch up with their classmates.', formalAlternative: 'reach the level of', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['reach parity with', 'close the gap with'] },
    { id: 'edu_p3', type: 'phrasal_verb', term: 'hand in', partOfSpeech: 'phrasal verb (separable)', definition: 'To give completed work to a teacher.', vietnameseMeaning: 'Nộp bài, nộp bài tập.', example: 'Deadlines by which assignments must be handed in teach a discipline useful in any career.', formalAlternative: 'submit', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'optional', usageWarning: 'Slightly informal for essays. "Submit" is the standard academic verb.', academicAlternatives: ['submit', 'deliver'] },
    { id: 'edu_p4', type: 'phrasal_verb', term: 'look up', partOfSpeech: 'phrasal verb (separable)', definition: 'To search for information in a reference source.', vietnameseMeaning: 'Tra cứu, tìm thông tin.', example: 'When any fact can be looked up in seconds, memorising facts becomes less valuable.', formalAlternative: 'consult a source for', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'optional', usageWarning: 'Conversational. Prefer "consult" or "search for" in formal essays.', academicAlternatives: ['consult', 'research', 'search for'] },
    { id: 'edu_p5', type: 'phrasal_verb', term: 'fall behind', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To fail to keep up with others or with a schedule.', vietnameseMeaning: 'Tụt lại phía sau, không theo kịp.', example: 'Children without internet access at home quickly fall behind their better-connected peers.', formalAlternative: 'lag behind', topic: 'Education', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['lag behind', 'trail'] },

    // Advanced / less common
    { id: 'edu_p6', type: 'phrasal_verb', term: 'draw on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To use knowledge or experience as a resource.', vietnameseMeaning: 'Vận dụng, dựa vào (kiến thức, kinh nghiệm).', example: 'Effective teachers draw on a wide repertoire of methods rather than a single approach.', formalAlternative: 'utilise', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['draw on experience', 'draw on research', 'draw on expertise'], academicAlternatives: ['utilise', 'employ', 'make use of'] },
    { id: 'edu_p7', type: 'phrasal_verb', term: 'build on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To use something already achieved as a foundation for further progress.', vietnameseMeaning: 'Phát triển dựa trên nền tảng sẵn có.', example: 'A good syllabus builds on what learners already know rather than starting from nothing.', formalAlternative: 'develop from', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'high_value', academicAlternatives: ['expand upon', 'extend', 'develop from'] },
    { id: 'edu_p8', type: 'phrasal_verb', term: 'branch out (into)', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To begin doing something new and different.', vietnameseMeaning: 'Mở rộng sang lĩnh vực mới.', example: 'Universities have branched out into online provision to reach students who cannot relocate.', formalAlternative: 'diversify into', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['diversify', 'expand into'] },
    { id: 'edu_p9', type: 'phrasal_verb', term: 'take in', partOfSpeech: 'phrasal verb (separable)', definition: 'To understand and absorb information.', vietnameseMeaning: 'Tiếp thu, lĩnh hội thông tin.', example: 'There is a limit to how much new material a learner can take in during a single lesson.', formalAlternative: 'assimilate', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', usageWarning: 'Has several unrelated meanings (deceive, shelter). Context must make the sense clear.', academicAlternatives: ['absorb', 'assimilate', 'retain'] },
    { id: 'edu_p10', type: 'phrasal_verb', term: 'bring out', partOfSpeech: 'phrasal verb (separable)', definition: 'To make a hidden quality become noticeable.', vietnameseMeaning: 'Làm bộc lộ, khơi dậy (phẩm chất tiềm ẩn).', example: 'Small tutorial groups bring out the confidence of students who never speak in lectures.', formalAlternative: 'elicit', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['bring out the best in', 'bring out potential'], academicAlternatives: ['elicit', 'reveal', 'draw out'] },
  ],

  writingPhrases: [
    { id: 'edu_w1', type: 'writing_phrase', term: 'The strongest case for reforming the curriculum rests on...', function: 'Introducing an argument', vietnameseMeaning: 'Lập luận mạnh nhất cho việc cải cách chương trình học dựa trên...', example: 'The strongest case for reforming the curriculum rests on the gap between what schools teach and what workplaces require.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'edu_w2', type: 'writing_phrase', term: 'One reason why students disengage from school is that...', function: 'Giving a reason', vietnameseMeaning: 'Một lý do khiến học sinh mất hứng thú với trường học là...', example: 'One reason why students disengage from school is that they cannot see how the material relates to their lives.', topic: 'Education', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'edu_w3', type: 'writing_phrase', term: 'This underachievement can be traced back to...', function: 'Explaining a cause', vietnameseMeaning: 'Tình trạng học kém này có thể truy nguyên từ...', example: 'This underachievement can be traced back to inadequate support in the earliest years of schooling.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'edu_w4', type: 'writing_phrase', term: 'The knock-on effect on later employment is considerable:', function: 'Explaining an effect', vietnameseMeaning: 'Tác động dây chuyền lên việc làm sau này là rất lớn:', example: 'The knock-on effect on later employment is considerable: those who leave school without qualifications earn less throughout their lives.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'edu_w5', type: 'writing_phrase', term: 'Finland provides a useful case in point:', function: 'Giving an example', vietnameseMeaning: 'Phần Lan là một ví dụ điển hình:', example: 'Finland provides a useful case in point: pupils there begin formal schooling at seven yet consistently outperform their peers.', topic: 'Education', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'edu_w6', type: 'writing_phrase', term: 'The chief advantage of this approach for learners is...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi ích chính của cách tiếp cận này đối với người học là...', example: 'The chief advantage of this approach for learners is that it allows them to progress at their own pace.', topic: 'Education', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'edu_w7', type: 'writing_phrase', term: 'A serious objection to this policy is that it disadvantages...', function: 'Discussing disadvantages', vietnameseMeaning: 'Một phản đối nghiêm túc đối với chính sách này là nó gây bất lợi cho...', example: 'A serious objection to this policy is that it disadvantages pupils whose parents cannot afford private tutoring.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'edu_w8', type: 'writing_phrase', term: 'Schools could address this by...', function: 'Suggesting a solution', vietnameseMeaning: 'Nhà trường có thể giải quyết vấn đề này bằng cách...', example: 'Schools could address this by replacing a single final examination with continuous assessment.', topic: 'Education', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'edu_w9', type: 'writing_phrase', term: 'I would argue that the purpose of education is not merely to...', function: 'Expressing an opinion', vietnameseMeaning: 'Tôi cho rằng mục đích của giáo dục không chỉ đơn thuần là...', example: 'I would argue that the purpose of education is not merely to prepare workers, but to produce thoughtful citizens.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'edu_w10', type: 'writing_phrase', term: 'Whereas traditional teaching emphasises memorisation, modern methods prioritise...', function: 'Comparing ideas', vietnameseMeaning: 'Trong khi phương pháp truyền thống nhấn mạnh ghi nhớ, phương pháp hiện đại ưu tiên...', example: 'Whereas traditional teaching emphasises memorisation, modern methods prioritise the ability to find and evaluate information.', topic: 'Education', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'edu_m1', type: 'common_mistake', incorrect: 'Students can gain many knowledges at university.', correct: 'Students can gain a great deal of knowledge at university.', explanation: '"Knowledge" is uncountable. Never add -s and never use "many". Correct quantifiers: much, a great deal of, a body of.', topic: 'Education', priority: 'must_learn' },
    { id: 'edu_m2', type: 'common_mistake', incorrect: 'She graduated university two years ago.', correct: 'She graduated from university two years ago.', explanation: 'The verb "graduate" requires "from" before the institution. Also note "go to university" with no article when talking about study in general.', topic: 'Education', priority: 'must_learn' },
    { id: 'edu_m3', type: 'common_mistake', incorrect: 'Vietnamese pupils have to learn many subjects at school.', correct: 'Vietnamese pupils have to study many subjects at school.', explanation: 'Vietnamese uses one verb (học) for both. In English you "study" a subject over time but "learn" a fact or skill you have now mastered.', topic: 'Education', priority: 'must_learn' },
    { id: 'edu_m4', type: 'common_mistake', incorrect: 'Nowadays, education is more and more important.', correct: 'Education is becoming increasingly important.', explanation: '"More and more" is spoken English, and "nowadays" is overused in IELTS essays. "Increasingly" is one word and sounds far more academic.', topic: 'Education', priority: 'high_value' },
    { id: 'edu_m5', type: 'common_mistake', incorrect: 'A degree helps people to have a good job.', correct: 'A degree helps people to secure a well-paid job.', explanation: 'English collocates "get", "secure" or "obtain" with "job", not "have". "Have a job" only describes a state you are already in.', topic: 'Education', priority: 'high_value' },
  ],

  learnFirst: {
    vocabulary: ['edu_v1', 'edu_v10', 'edu_v11', 'edu_v12', 'edu_v13', 'edu_v23', 'edu_v25', 'edu_v27', 'edu_v28', 'edu_v7'],
    collocations: ['edu_c1', 'edu_c5', 'edu_c9', 'edu_c11', 'edu_c17'],
    phrasalVerbs: ['edu_p1', 'edu_p5', 'edu_p6'],
    writingPhrases: ['edu_w1', 'edu_w5', 'edu_w9'],
  },
}
