import type { TopicData } from '../types'

export const ENERGY: TopicData = {
  topic: 'Energy',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'egy_v1', type: 'vocabulary', term: 'renewable', pronunciation: '/rɪˈnjuːəbl/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Naturally replaced and therefore never exhausted.', vietnameseMeaning: 'Tái tạo được, không cạn kiệt.', example: 'Renewable sources now generate more electricity worldwide than coal did a decade ago.', writingTip: 'Also used as a plural noun: "investment in renewables". The opposite is "non-renewable".', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['renewable energy', 'renewable sources', 'renewable electricity', 'invest in renewables'], antonym: 'non-renewable', wordFamily: ['renew (v)', 'renewables (n)'], priority: 'must_learn' },
    { id: 'egy_v2', type: 'vocabulary', term: 'fossil fuel', pronunciation: '/ˈfɒsl fjuːəl/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'A fuel such as coal, oil or gas formed from ancient organic remains.', vietnameseMeaning: 'Nhiên liệu hoá thạch.', example: 'Fossil fuels still supply roughly four-fifths of the world’s primary energy.', writingTip: 'Usually plural in essays. "Dependence on fossil fuels" is the central phrase of this topic.', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['burn fossil fuels', 'dependence on fossil fuels', 'fossil fuel reserves'], priority: 'must_learn' },
    { id: 'egy_v3', type: 'vocabulary', term: 'coal', pronunciation: '/kəʊl/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'A black rock burned as fuel, the most carbon-intensive of the fossil fuels.', vietnameseMeaning: 'Than đá.', example: 'Coal remains attractive to poorer economies precisely because the plants are cheap to build.', writingTip: 'Uncountable. "Coal-fired power station" is the standard technical phrase.', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['coal-fired power station', 'burn coal', 'phase out coal'], priority: 'must_learn' },
    { id: 'egy_v4', type: 'vocabulary', term: 'solar power', pronunciation: '/ˈsəʊlə ˈpaʊə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Electricity generated from sunlight.', vietnameseMeaning: 'Năng lượng mặt trời.', example: 'The cost of solar power has fallen faster than almost any forecast predicted.', writingTip: 'Uncountable. "Solar panel" is the countable piece of equipment.', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['solar panels', 'solar energy', 'harness solar power'], priority: 'must_learn' },
    { id: 'egy_v5', type: 'vocabulary', term: 'wind turbine', pronunciation: '/wɪnd ˈtɜːbaɪn/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A tall machine that converts wind into electricity.', vietnameseMeaning: 'Tuabin gió.', example: 'Offshore wind turbines generate more consistently than those on land, though they cost far more to install.', writingTip: 'Countable. Note "wind farm" for a group of them, and "offshore" versus "onshore".', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['offshore wind turbines', 'a wind farm', 'install turbines'], priority: 'high_value' },
    { id: 'egy_v6', type: 'vocabulary', term: 'electricity', pronunciation: '/ɪˌlekˈtrɪsəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Energy supplied through wires for lighting, heating and machines.', vietnameseMeaning: 'Điện, điện năng.', example: 'Electricity generation accounts for a larger share of emissions than transport in most countries.', writingTip: 'Uncountable. Very common in Task 1: "electricity generation", "electricity consumption".', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['generate electricity', 'electricity consumption', 'electricity supply'], wordFamily: ['electric (adj)', 'electrical (adj)', 'electrify (v)'], priority: 'must_learn' },
    { id: 'egy_v7', type: 'vocabulary', term: 'pollution', pronunciation: '/pəˈluːʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Harmful substances released into the air, water or soil.', vietnameseMeaning: 'Ô nhiễm.', example: 'Air pollution from coal plants kills far more people each year than nuclear accidents ever have.', writingTip: 'Uncountable — never "pollutions". Specify the type: air pollution, water pollution.', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['air pollution', 'reduce pollution', 'cause pollution'], wordFamily: ['pollute (v)', 'pollutant (n)'], priority: 'must_learn' },
    { id: 'egy_v8', type: 'vocabulary', term: 'supply', pronunciation: '/səˈplaɪ/', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'The amount of something available; to provide it.', vietnameseMeaning: 'Nguồn cung, cung cấp.', example: 'A reliable electricity supply is a precondition for almost every form of industrial development.', writingTip: '"Supply and demand" is the core economic pairing. "Energy supply" is very high frequency.', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['energy supply', 'reliable supply', 'supply and demand', 'supply electricity'], antonym: 'demand', wordFamily: ['supplier (n)'], priority: 'must_learn' },
    { id: 'egy_v9', type: 'vocabulary', term: 'waste', pronunciation: '/weɪst/', partOfSpeech: 'verb / noun', cefrLevel: 'B1', definition: 'To use something carelessly; material that is discarded.', vietnameseMeaning: 'Lãng phí; chất thải.', example: 'Poorly insulated buildings waste a substantial proportion of the energy used to heat them.', writingTip: 'As a noun it is uncountable: "nuclear waste", "a great deal of waste".', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['waste energy', 'nuclear waste', 'reduce waste'], wordFamily: ['wasteful (adj)', 'wastage (n)'], priority: 'must_learn' },
    { id: 'egy_v10', type: 'vocabulary', term: 'efficient', pronunciation: '/ɪˈfɪʃnt/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Achieving a result with little wasted effort or resource.', vietnameseMeaning: 'Hiệu quả, ít lãng phí.', example: 'The cheapest unit of energy is the one that an efficient building never needs to use.', writingTip: '"Energy-efficient" is hyphenated before a noun. The noun "efficiency" is equally useful.', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['energy-efficient', 'highly efficient', 'improve efficiency'], antonym: 'inefficient', wordFamily: ['efficiency (n)', 'efficiently (adv)'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'egy_v11', type: 'vocabulary', term: 'emissions', pronunciation: '/ɪˈmɪʃnz/', partOfSpeech: 'noun (plural)', cefrLevel: 'B2', definition: 'Gases released into the atmosphere, especially by burning fuel.', vietnameseMeaning: 'Khí thải, lượng phát thải.', example: 'Emissions from electricity generation have begun to fall even as total demand continues to rise.', writingTip: 'Plural in this sense. "Cut", "reduce" and "curb" emissions are the natural verbs.', topic: 'Energy', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['carbon emissions', 'cut emissions', 'greenhouse gas emissions', 'net-zero emissions'], wordFamily: ['emit (v)'], priority: 'must_learn' },
    { id: 'egy_v12', type: 'vocabulary', term: 'carbon footprint', pronunciation: '/ˈkɑːbən ˈfʊtprɪnt/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'The total greenhouse gas emissions caused by a person, product or organisation.', vietnameseMeaning: 'Dấu chân carbon, tổng lượng phát thải gây ra.', example: 'A household’s carbon footprint is determined far more by heating and travel than by recycling habits.', writingTip: 'A fixed phrase — "reduce / lower your carbon footprint". Do not vary the wording.', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['reduce your carbon footprint', 'a large carbon footprint'], priority: 'must_learn' },
    { id: 'egy_v13', type: 'vocabulary', term: 'consumption', pronunciation: '/kənˈsʌmpʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The amount of a resource used.', vietnameseMeaning: 'Mức tiêu thụ.', example: 'Energy consumption per person in wealthy countries remains several times the global average.', writingTip: 'Uncountable and essential for Task 1: "consumption rose sharply", "per capita consumption".', topic: 'Energy', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['energy consumption', 'reduce consumption', 'per capita consumption'], wordFamily: ['consume (v)', 'consumer (n)'], priority: 'must_learn' },
    { id: 'egy_v14', type: 'vocabulary', term: 'nuclear energy', pronunciation: '/ˈnjuːkliə ˈenədʒi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Power generated by splitting atoms in a reactor.', vietnameseMeaning: 'Năng lượng hạt nhân.', example: 'Nuclear energy produces almost no carbon dioxide but leaves waste that remains hazardous for millennia.', writingTip: 'Mind the pronunciation: NEW-clee-uh, not "nuc-you-lar". A useful topic for balanced arguments.', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['nuclear power station', 'nuclear waste', 'nuclear reactor'], priority: 'must_learn' },
    { id: 'egy_v15', type: 'vocabulary', term: 'grid', pronunciation: '/ɡrɪd/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'The network of cables that distributes electricity across a region.', vietnameseMeaning: 'Lưới điện.', example: 'A grid built for a handful of large power stations copes badly with millions of small solar installations.', writingTip: 'Usually "the national grid" or "the electricity grid". A precise, technical-sounding noun.', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the national grid', 'connect to the grid', 'upgrade the grid'], priority: 'high_value' },
    { id: 'egy_v16', type: 'vocabulary', term: 'sustainability', pronunciation: '/səˌsteɪnəˈbɪləti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The capacity to continue indefinitely without depleting resources.', vietnameseMeaning: 'Tính bền vững.', example: 'Sustainability requires thinking in decades, which is precisely what electoral cycles discourage.', writingTip: 'Uncountable. The adjective "sustainable" is more frequent in essays.', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['environmental sustainability', 'long-term sustainability'], wordFamily: ['sustain (v)', 'sustainable (adj)'], priority: 'must_learn' },
    { id: 'egy_v17', type: 'vocabulary', term: 'hydropower', pronunciation: '/ˈhaɪdrəʊpaʊə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Electricity generated from flowing or falling water.', vietnameseMeaning: 'Thuỷ điện.', example: 'Hydropower provides a large share of Vietnam’s electricity but leaves it exposed to drought.', writingTip: 'Uncountable. Also written "hydroelectric power". A concrete regional example for Vietnamese students.', topic: 'Energy', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['hydropower plant', 'hydroelectric dam'], priority: 'high_value' },
    { id: 'egy_v18', type: 'vocabulary', term: 'insulation', pronunciation: '/ˌɪnsjuˈleɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Material used to stop heat escaping from a building.', vietnameseMeaning: 'Vật liệu cách nhiệt.', example: 'Improving insulation in older homes cuts both emissions and household bills at the same time.', writingTip: 'Uncountable. A specific, practical solution that lifts a vague "we should save energy" argument.', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['improve insulation', 'poor insulation', 'insulate homes'], wordFamily: ['insulate (v)', 'insulated (adj)'], priority: 'high_value' },
    { id: 'egy_v19', type: 'vocabulary', term: 'subsidy', pronunciation: '/ˈsʌbsədi/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'Money paid by a government to keep the price of something low.', vietnameseMeaning: 'Khoản trợ cấp, trợ giá.', example: 'Fossil fuel subsidies still exceed global spending on renewable energy in several regions.', writingTip: 'Countable: "subsidies for". The verb is "subsidise".', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['fuel subsidies', 'remove subsidies', 'government subsidies'], wordFamily: ['subsidise (v)', 'subsidised (adj)'], priority: 'must_learn' },
    { id: 'egy_v20', type: 'vocabulary', term: 'finite', pronunciation: '/ˈfaɪnaɪt/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Limited in quantity and therefore capable of running out.', vietnameseMeaning: 'Hữu hạn, có giới hạn.', example: 'Oil is a finite resource, though it will become uneconomic long before it becomes unavailable.', writingTip: '"A finite resource" is the standard collocation and a clean opposite to "renewable".', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a finite resource', 'finite supplies', 'finite reserves'], antonym: 'infinite', priority: 'must_learn' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'egy_v21', type: 'vocabulary', term: 'decarbonisation', pronunciation: '/diːˌkɑːbənaɪˈzeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The process of removing carbon emissions from an economy or sector.', vietnameseMeaning: 'Quá trình khử carbon trong nền kinh tế.', example: 'Decarbonisation of electricity is well under way; decarbonising heat and heavy industry has barely begun.', writingTip: 'A precise, current policy term. Using it correctly signals genuine command of the topic.', topic: 'Energy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['rapid decarbonisation', 'the decarbonisation of industry'], wordFamily: ['decarbonise (v)'], priority: 'must_learn' },
    { id: 'egy_v22', type: 'vocabulary', term: 'energy transition', pronunciation: '/ˈenədʒi trænˈzɪʃn/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'The shift from one dominant energy source to another.', vietnameseMeaning: 'Quá trình chuyển dịch năng lượng.', example: 'Every previous energy transition took roughly fifty years; this one is expected to take half that.', writingTip: 'A ready-made phrase for framing the whole topic. "A just transition" adds a social dimension.', topic: 'Energy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the energy transition', 'accelerate the transition', 'a just transition'], priority: 'must_learn' },
    { id: 'egy_v23', type: 'vocabulary', term: 'energy security', pronunciation: '/ˈenədʒi sɪˈkjʊərəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'A reliable and affordable supply of energy that is not vulnerable to disruption.', vietnameseMeaning: 'An ninh năng lượng.', example: 'Energy security has become an argument for renewables rather than against them, since domestic sun and wind cannot be embargoed.', writingTip: 'An excellent way to argue for clean energy on grounds other than climate.', topic: 'Energy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['threaten energy security', 'ensure energy security'], priority: 'must_learn' },
    { id: 'egy_v24', type: 'vocabulary', term: 'photovoltaic', pronunciation: '/ˌfəʊtəʊvɒlˈteɪɪk/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Converting light directly into electricity.', vietnameseMeaning: 'Quang điện (chuyển ánh sáng thành điện năng).', example: 'Photovoltaic cells have become so cheap that the panels are now a minor part of installation costs.', writingTip: 'Technical. Use once for precision, then revert to "solar panel" for readability.', topic: 'Energy', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['photovoltaic cells', 'photovoltaic panels'], priority: 'optional' },
    { id: 'egy_v25', type: 'vocabulary', term: 'intermittent', pronunciation: '/ˌɪntəˈmɪtənt/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Stopping and starting at irregular intervals rather than being continuous.', vietnameseMeaning: 'Không liên tục, gián đoạn theo chu kỳ.', example: 'The intermittent nature of wind and solar generation is the genuine engineering obstacle, not their cost.', writingTip: 'Naming this problem accurately is exactly what separates an informed essay from a slogan.', topic: 'Energy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['intermittent supply', 'intermittent generation'], antonym: 'continuous', wordFamily: ['intermittency (n)'], priority: 'high_value' },
    { id: 'egy_v26', type: 'vocabulary', term: 'viable', pronunciation: '/ˈvaɪəbl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Capable of working successfully in practice.', vietnameseMeaning: 'Khả thi, có thể thực hiện được.', example: 'Solar became commercially viable without any technological breakthrough, purely through manufacturing scale.', writingTip: '"Commercially viable", "economically viable", "a viable alternative" — all Band 7+ staples.', topic: 'Energy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['commercially viable', 'economically viable', 'a viable alternative'], antonym: 'unviable', wordFamily: ['viability (n)'], priority: 'must_learn' },
    { id: 'egy_v27', type: 'vocabulary', term: 'deplete', pronunciation: '/dɪˈpliːt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To use up a resource until little remains.', vietnameseMeaning: 'Làm cạn kiệt.', example: 'Extracting fuel faster than any conceivable replacement depletes reserves that took millions of years to form.', writingTip: 'Implies serious, often irreversible reduction. Pairs with resources, reserves and stocks.', topic: 'Energy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['deplete reserves', 'deplete natural resources', 'rapidly depleted'], alternatives: ['exhaust', 'use up'], wordFamily: ['depletion (n)'], priority: 'must_learn' },
    { id: 'egy_v28', type: 'vocabulary', term: 'incentivise', pronunciation: '/ɪnˈsentɪvaɪz/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To motivate action by offering a financial or practical reward.', vietnameseMeaning: 'Tạo động lực bằng lợi ích, khuyến khích.', example: 'Governments can incentivise home insulation far more cheaply than they can build additional generating capacity.', writingTip: 'Stronger than "encourage" because it implies a concrete reward. Ideal in solution paragraphs.', topic: 'Energy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['incentivise investment', 'financially incentivise'], wordFamily: ['incentive (n)'], priority: 'must_learn' },
    { id: 'egy_v29', type: 'vocabulary', term: 'diversify', pronunciation: '/daɪˈvɜːsɪfaɪ/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To increase the variety of something in order to reduce risk.', vietnameseMeaning: 'Đa dạng hoá (nguồn cung, danh mục).', example: 'Countries that diversify their energy mix are far less exposed to a single supplier or a single drought.', writingTip: '"Diversify the energy mix" is the natural phrase. The noun is "diversification".', topic: 'Energy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['diversify the energy mix', 'diversify supply', 'diversify sources'], wordFamily: ['diversification (n)', 'diverse (adj)'], priority: 'high_value' },
    { id: 'egy_v30', type: 'vocabulary', term: 'prohibitive', pronunciation: '/prəˈhɪbətɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'So expensive as to prevent something from being done.', vietnameseMeaning: 'Quá đắt đỏ đến mức không thể thực hiện.', example: 'Storage costs were prohibitive a decade ago; today they are merely high.', writingTip: '"Prohibitively expensive" is the standard adverbial form and reads as genuinely advanced.', topic: 'Energy', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['prohibitively expensive', 'prohibitive costs'], wordFamily: ['prohibit (v)', 'prohibitively (adv)'], priority: 'optional' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'egy_c1', type: 'collocation', term: 'renewable energy', collocationType: 'Adj + Noun', definition: 'Power generated from sources that naturally replenish.', vietnameseMeaning: 'Năng lượng tái tạo.', example: 'Renewable energy has moved from being the expensive option to being the cheapest in most markets.', topic: 'Energy', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'egy_c2', type: 'collocation', term: 'burn fossil fuels', collocationType: 'Verb + Noun', definition: 'To combust coal, oil or gas in order to release energy.', vietnameseMeaning: 'Đốt nhiên liệu hoá thạch.', example: 'Every unit of electricity generated without burning fossil fuels displaces one that would have emitted carbon.', topic: 'Energy', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'egy_c3', type: 'collocation', term: 'save energy', collocationType: 'Verb + Noun', definition: 'To use less energy than would otherwise be needed.', vietnameseMeaning: 'Tiết kiệm năng lượng.', example: 'Simple measures such as better insulation save energy at a fraction of the cost of new generation.', alternative: 'conserve energy', topic: 'Energy', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'egy_c4', type: 'collocation', term: 'generate electricity', collocationType: 'Verb + Noun', definition: 'To produce electrical power.', vietnameseMeaning: 'Phát điện, sản xuất điện năng.', example: 'The country generates electricity from a mix of hydropower, coal and, increasingly, solar.', topic: 'Energy', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'egy_c5', type: 'collocation', term: 'energy consumption', collocationType: 'Noun + Noun', definition: 'The total amount of energy used.', vietnameseMeaning: 'Mức tiêu thụ năng lượng.', example: 'Household energy consumption rose steadily between 2000 and 2015 before levelling off.', topic: 'Energy', bandLevel: '5-6', task: 'task1', priority: 'must_learn', writingTip: 'A core Task 1 phrase for line graphs and bar charts on energy use.' },
    { id: 'egy_c6', type: 'collocation', term: 'natural resources', collocationType: 'Adj + Noun', definition: 'Materials such as water, minerals and fuel occurring in nature.', vietnameseMeaning: 'Tài nguyên thiên nhiên.', example: 'Countries rich in natural resources do not automatically become prosperous ones.', topic: 'Energy', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'egy_c7', type: 'collocation', term: 'run out of', collocationType: 'Verb phrase', definition: 'To exhaust the available supply of something.', vietnameseMeaning: 'Cạn kiệt nguồn cung.', example: 'The world will not run out of oil so much as stop finding it worth extracting.', topic: 'Energy', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'egy_c8', type: 'collocation', term: 'energy-efficient appliances', collocationType: 'Adj + Noun', definition: 'Devices designed to perform their function using less power.', vietnameseMeaning: 'Thiết bị tiết kiệm điện năng.', example: 'Mandatory efficiency labels persuaded manufacturers to produce energy-efficient appliances long before consumers demanded them.', topic: 'Energy', bandLevel: '5-6', task: 'task2', priority: 'high_value' },

    // Advanced (Band 6-7)
    { id: 'egy_c9', type: 'collocation', term: 'reduce carbon emissions', collocationType: 'Verb + Noun', definition: 'To lower the amount of carbon dioxide released.', vietnameseMeaning: 'Giảm lượng khí thải carbon.', example: 'Replacing coal with gas reduces carbon emissions substantially, though it does not eliminate them.', alternative: 'cut carbon emissions', topic: 'Energy', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'egy_c10', type: 'collocation', term: 'dependence on fossil fuels', collocationType: 'Noun + Prep + Noun', definition: 'Reliance on coal, oil and gas for energy.', vietnameseMeaning: 'Sự phụ thuộc vào nhiên liệu hoá thạch.', example: 'Reducing dependence on fossil fuels is now an economic argument as much as an environmental one.', alternative: 'reliance on fossil fuels', topic: 'Energy', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'egy_c11', type: 'collocation', term: 'invest in renewable technology', collocationType: 'Verb + Noun', definition: 'To commit money to developing clean energy systems.', vietnameseMeaning: 'Đầu tư vào công nghệ năng lượng tái tạo.', example: 'Countries that invested in renewable technology early now export the equipment everyone else needs.', topic: 'Energy', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'egy_c12', type: 'collocation', term: 'meet growing demand', collocationType: 'Verb + Noun', definition: 'To supply enough to satisfy an increasing requirement.', vietnameseMeaning: 'Đáp ứng nhu cầu ngày càng tăng.', example: 'Meeting growing demand without increasing emissions is the defining challenge for every energy ministry.', topic: 'Energy', bandLevel: '6-7', task: 'both', priority: 'must_learn' },
    { id: 'egy_c13', type: 'collocation', term: 'the national grid', collocationType: 'Adj + Noun', definition: 'The country-wide network distributing electricity.', vietnameseMeaning: 'Lưới điện quốc gia.', example: 'Connecting remote wind farms to the national grid frequently costs more than the turbines themselves.', topic: 'Energy', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'egy_c14', type: 'collocation', term: 'harness solar power', collocationType: 'Verb + Noun', definition: 'To capture and make use of energy from the sun.', vietnameseMeaning: 'Khai thác năng lượng mặt trời.', example: 'Countries near the equator are best placed to harness solar power, yet many have barely begun.', topic: 'Energy', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'egy_c15', type: 'collocation', term: 'phase out coal', collocationType: 'Verb + Noun', definition: 'To gradually stop using coal for power generation.', vietnameseMeaning: 'Loại bỏ dần điện than.', example: 'Britain phased out coal within a decade, largely by making it more expensive than the alternatives.', topic: 'Energy', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },

    // High-impact (Band 7+)
    { id: 'egy_c16', type: 'collocation', term: 'accelerate the energy transition', collocationType: 'Verb + Noun', definition: 'To speed up the shift from fossil fuels to cleaner sources.', vietnameseMeaning: 'Đẩy nhanh quá trình chuyển dịch năng lượng.', example: 'Predictable, long-term policy accelerates the energy transition more effectively than any single subsidy.', topic: 'Energy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'egy_c17', type: 'collocation', term: 'diversify the energy mix', collocationType: 'Verb + Noun', definition: 'To draw on a wider range of energy sources.', vietnameseMeaning: 'Đa dạng hoá cơ cấu nguồn năng lượng.', example: 'Diversifying the energy mix protects a country from both price shocks and supply interruptions.', topic: 'Energy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'egy_c18', type: 'collocation', term: 'achieve net-zero emissions', collocationType: 'Verb + Noun', definition: 'To balance emissions produced against emissions removed.', vietnameseMeaning: 'Đạt mức phát thải ròng bằng không.', example: 'Achieving net-zero emissions by mid-century requires decisions taken now, not intentions announced now.', topic: 'Energy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'egy_c19', type: 'collocation', term: 'prohibitively expensive', collocationType: 'Adv + Adj', definition: 'So costly that the option is effectively impossible.', vietnameseMeaning: 'Đắt đỏ đến mức không khả thi.', example: 'Grid-scale storage was prohibitively expensive until battery costs fell by roughly ninety per cent.', topic: 'Energy', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'egy_c20', type: 'collocation', term: 'a finite resource', collocationType: 'Adj + Noun', definition: 'Something available only in limited quantity.', vietnameseMeaning: 'Nguồn tài nguyên hữu hạn.', example: 'Treating a finite resource as though it were inexhaustible is precisely how previous civilisations ran into trouble.', topic: 'Energy', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'egy_p1', type: 'phrasal_verb', term: 'use up', partOfSpeech: 'phrasal verb (separable)', definition: 'To consume the entire supply of something.', vietnameseMeaning: 'Dùng hết, tiêu thụ cạn kiệt.', example: 'Current rates of extraction will use up accessible reserves within a few generations.', formalAlternative: 'exhaust', topic: 'Energy', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['exhaust', 'deplete', 'consume'] },
    { id: 'egy_p2', type: 'phrasal_verb', term: 'turn off', partOfSpeech: 'phrasal verb (separable)', definition: 'To stop a device from operating.', vietnameseMeaning: 'Tắt (thiết bị điện).', example: 'Campaigns urging people to turn off lights achieve far less than replacing the bulbs entirely.', formalAlternative: 'switch off', topic: 'Energy', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['switch off', 'deactivate', 'power down'] },
    { id: 'egy_p3', type: 'phrasal_verb', term: 'run out of', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To have none of a supply left.', vietnameseMeaning: 'Cạn kiệt, hết nguồn cung.', example: 'Regions dependent on a single reservoir can run out of generating capacity in a dry year.', formalAlternative: 'exhaust supplies of', topic: 'Energy', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['exhaust', 'be depleted of'] },
    { id: 'egy_p4', type: 'phrasal_verb', term: 'give off', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To release a gas, heat or light.', vietnameseMeaning: 'Thải ra, phát ra (khí, nhiệt).', example: 'Coal plants give off sulphur compounds as well as carbon dioxide.', formalAlternative: 'emit', topic: 'Energy', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['emit', 'release', 'discharge'] },
    { id: 'egy_p5', type: 'phrasal_verb', term: 'cut down on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To reduce the amount of something used.', vietnameseMeaning: 'Cắt giảm mức sử dụng.', example: 'Households can cut down on heating costs substantially simply by sealing draughts.', formalAlternative: 'reduce', topic: 'Energy', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Informal. "Reduce", "curtail" or "minimise" is preferable in a Task 2 essay.', academicAlternatives: ['reduce', 'curtail', 'minimise'] },

    // Advanced / less common
    { id: 'egy_p6', type: 'phrasal_verb', term: 'phase out', partOfSpeech: 'phrasal verb (separable)', definition: 'To discontinue something gradually over a planned period.', vietnameseMeaning: 'Loại bỏ dần theo lộ trình.', example: 'Coal is being phased out far faster than anyone anticipated, largely for economic reasons.', formalAlternative: 'discontinue gradually', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['phase out coal', 'phase out subsidies'], academicAlternatives: ['discontinue', 'withdraw', 'eliminate progressively'] },
    { id: 'egy_p7', type: 'phrasal_verb', term: 'switch to', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To change from using one thing to another.', vietnameseMeaning: 'Chuyển sang sử dụng.', example: 'Industries switch to cleaner fuels when doing so is cheaper, and rarely before.', formalAlternative: 'transition to', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['switch to renewables', 'switch to electric heating'], academicAlternatives: ['transition to', 'convert to', 'adopt'] },
    { id: 'egy_p8', type: 'phrasal_verb', term: 'scale up', partOfSpeech: 'phrasal verb (separable)', definition: 'To increase the size or output of something substantially.', vietnameseMeaning: 'Mở rộng quy mô.', example: 'Scaling up manufacturing, rather than any laboratory advance, is what made solar affordable.', formalAlternative: 'expand', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'high_value', collocations: ['scale up production', 'scale up investment'], academicAlternatives: ['expand', 'increase substantially', 'ramp up'] },
    { id: 'egy_p9', type: 'phrasal_verb', term: 'draw on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To use something as a source of supply.', vietnameseMeaning: 'Khai thác, sử dụng (nguồn lực).', example: 'Grids increasingly draw on a wide range of sources rather than a handful of large stations.', formalAlternative: 'utilise', topic: 'Energy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'high_value', academicAlternatives: ['utilise', 'rely on', 'exploit'] },
    { id: 'egy_p10', type: 'phrasal_verb', term: 'bring down', partOfSpeech: 'phrasal verb (separable)', definition: 'To reduce a level, especially of cost or emissions.', vietnameseMeaning: 'Làm giảm, kéo xuống (chi phí, mức phát thải).', example: 'Mass production has brought down the cost of batteries more effectively than any research grant.', formalAlternative: 'reduce', topic: 'Energy', bandLevel: '6-7', task: 'both', writingSuitability: 'suitable', priority: 'must_learn', collocations: ['bring down costs', 'bring down emissions'], academicAlternatives: ['reduce', 'lower', 'diminish'] },
  ],

  writingPhrases: [
    { id: 'egy_w1', type: 'writing_phrase', term: 'The central argument for shifting to renewable sources is that...', function: 'Introducing an argument', vietnameseMeaning: 'Lập luận trung tâm ủng hộ việc chuyển sang các nguồn tái tạo là...', example: 'The central argument for shifting to renewable sources is that they are now the cheapest form of new generation.', topic: 'Energy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'egy_w2', type: 'writing_phrase', term: 'Countries remain dependent on coal chiefly because...', function: 'Giving a reason', vietnameseMeaning: 'Các quốc gia vẫn phụ thuộc vào than chủ yếu vì...', example: 'Countries remain dependent on coal chiefly because existing plants have already been paid for and closing them destroys jobs.', topic: 'Energy', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'egy_w3', type: 'writing_phrase', term: 'This surge in demand is largely attributable to...', function: 'Explaining a cause', vietnameseMeaning: 'Sự gia tăng nhu cầu này chủ yếu là do...', example: 'This surge in demand is largely attributable to rising incomes and the spread of air conditioning.', topic: 'Energy', bandLevel: '7+', task: 'both', priority: 'must_learn' },
    { id: 'egy_w4', type: 'writing_phrase', term: 'The environmental repercussions of continued reliance on coal include...', function: 'Explaining an effect', vietnameseMeaning: 'Những hệ luỵ môi trường của việc tiếp tục phụ thuộc vào than bao gồm...', example: 'The environmental repercussions of continued reliance on coal include acidified rainfall and premature deaths from particulates.', topic: 'Energy', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'egy_w5', type: 'writing_phrase', term: 'Denmark offers a striking illustration:', function: 'Giving an example', vietnameseMeaning: 'Đan Mạch là một minh chứng nổi bật:', example: 'Denmark offers a striking illustration: wind now supplies roughly half its electricity, a share unimaginable thirty years ago.', topic: 'Energy', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'egy_w6', type: 'writing_phrase', term: 'The principal advantage of clean generation is that...', function: 'Discussing advantages', vietnameseMeaning: 'Ưu điểm chính của việc sản xuất điện sạch là...', example: 'The principal advantage of clean generation is that the fuel is free once the equipment has been built.', topic: 'Energy', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'egy_w7', type: 'writing_phrase', term: 'The obvious limitation of wind and solar is that...', function: 'Discussing disadvantages', vietnameseMeaning: 'Hạn chế rõ ràng của điện gió và điện mặt trời là...', example: 'The obvious limitation of wind and solar is that they generate when conditions allow rather than when demand peaks.', topic: 'Energy', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'egy_w8', type: 'writing_phrase', term: 'A pragmatic first step would be to redirect existing subsidies towards...', function: 'Suggesting a solution', vietnameseMeaning: 'Một bước đi thực tế đầu tiên là chuyển hướng các khoản trợ cấp hiện có sang...', example: 'A pragmatic first step would be to redirect existing subsidies towards storage and grid upgrades rather than fuel.', topic: 'Energy', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'egy_w9', type: 'writing_phrase', term: 'In my opinion, the decisive factor will not be technology but...', function: 'Expressing an opinion', vietnameseMeaning: 'Theo tôi, yếu tố quyết định sẽ không phải công nghệ mà là...', example: 'In my opinion, the decisive factor will not be technology but whether governments can sustain a policy beyond a single electoral term.', topic: 'Energy', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'egy_w10', type: 'writing_phrase', term: 'Nuclear power offers reliability at high cost, whereas renewables offer...', function: 'Comparing ideas', vietnameseMeaning: 'Điện hạt nhân mang lại độ ổn định với chi phí cao, trong khi năng lượng tái tạo mang lại...', example: 'Nuclear power offers reliability at high cost, whereas renewables offer low cost with the complication of intermittency.', topic: 'Energy', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'egy_m1', type: 'common_mistake', incorrect: 'We should use more renewable energies to protect environment.', correct: 'We should use more renewable energy to protect the environment.', explanation: 'Two errors: "energy" is uncountable in this sense, so no plural -s; and "the environment" always takes an article in this general sense.', topic: 'Energy', priority: 'must_learn' },
    { id: 'egy_m2', type: 'common_mistake', incorrect: 'Fossil fuel will be run out in the future.', correct: 'Fossil fuel reserves will eventually be exhausted.', explanation: '"Run out" is not passive — write "we will run out of fossil fuels" or use the passive verb "be exhausted". The formal version is also better suited to an essay.', topic: 'Energy', priority: 'must_learn' },
    { id: 'egy_m3', type: 'common_mistake', incorrect: 'Solar energy is more cheaper than coal nowadays.', correct: 'Solar energy is now considerably cheaper than coal.', explanation: 'Never combine "more" with an -er comparative. Intensify with "considerably", "far" or "significantly" instead. "Nowadays" is also overused — "now" or "today" is cleaner.', topic: 'Energy', priority: 'high_value' },
    { id: 'egy_m4', type: 'common_mistake', incorrect: 'The government should encourage people to using solar panels.', correct: 'The government should encourage people to use solar panels.', explanation: '"Encourage someone to do something" takes the bare infinitive, not "to + -ing". The same applies to "persuade", "allow" and "enable".', topic: 'Energy', priority: 'must_learn' },
    { id: 'egy_m5', type: 'common_mistake', incorrect: 'Nuclear power has many bad effects to human health.', correct: 'Nuclear power carries potential risks to human health.', explanation: 'The preposition after "effect" is "on", not "to"; "bad" is too informal; and "many effects" overstates a case that is genuinely contested. "Carries potential risks" is accurate and appropriately hedged.', topic: 'Energy', priority: 'must_learn' },
  ],

  learnFirst: {
    vocabulary: ['egy_v1', 'egy_v2', 'egy_v11', 'egy_v12', 'egy_v13', 'egy_v20', 'egy_v21', 'egy_v22', 'egy_v23', 'egy_v26'],
    collocations: ['egy_c1', 'egy_c9', 'egy_c10', 'egy_c16', 'egy_c18'],
    phrasalVerbs: ['egy_p6', 'egy_p7', 'egy_p1'],
    writingPhrases: ['egy_w1', 'egy_w7', 'egy_w8'],
  },
}
