import type { TopicData } from '../types'

export const ENVIRONMENT: TopicData = {
  topic: 'Environment',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'env_v1', type: 'vocabulary', term: 'pollution', pronunciation: '/pəˈluːʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'The presence of harmful substances in the air, water, or soil.', vietnameseMeaning: 'Ô nhiễm môi trường.', example: 'Air pollution in major cities has reached levels that seriously endanger public health.', writingTip: 'Uncountable — never write "pollutions". Specify the type: air/water/noise/soil pollution.', topic: 'Environment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['air pollution', 'water pollution', 'noise pollution', 'cause pollution', 'reduce pollution'], alternatives: ['contamination'], wordFamily: ['pollute (v)', 'pollutant (n)', 'polluted (adj)'], priority: 'must_learn' },
    { id: 'env_v2', type: 'vocabulary', term: 'renewable', pronunciation: '/rɪˈnjuːəbl/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Able to be replaced naturally and therefore never used up.', vietnameseMeaning: 'Có thể tái tạo, không cạn kiệt (năng lượng).', example: 'Shifting to renewable energy is the most effective long-term response to climate change.', writingTip: 'Pairs almost exclusively with energy words: renewable energy/sources/electricity.', topic: 'Environment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['renewable energy', 'renewable sources', 'renewable electricity'], antonym: 'non-renewable', wordFamily: ['renew (v)', 'renewal (n)'], priority: 'must_learn' },
    { id: 'env_v3', type: 'vocabulary', term: 'recycle', pronunciation: '/ˌriːˈsaɪkl/', partOfSpeech: 'verb', cefrLevel: 'B1', definition: 'To treat used materials so that they can be used again.', vietnameseMeaning: 'Tái chế, xử lý để dùng lại.', example: 'Households should be required by law to recycle glass, paper and plastic separately.', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['recycle waste', 'recycle plastic', 'recycling scheme', 'recycling rate'], alternatives: ['reprocess', 'reuse'], wordFamily: ['recycling (n)', 'recyclable (adj)'], priority: 'must_learn' },
    { id: 'env_v4', type: 'vocabulary', term: 'waste', pronunciation: '/weɪst/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Unwanted material that is thrown away after use.', vietnameseMeaning: 'Rác thải, chất thải.', example: 'Industrial waste is frequently discharged into rivers without adequate treatment.', writingTip: 'Uncountable as "rubbish": say "a large amount of waste", not "many wastes".', topic: 'Environment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['household waste', 'industrial waste', 'food waste', 'waste disposal', 'waste management'], alternatives: ['rubbish', 'refuse'], wordFamily: ['wasteful (adj)', 'wastage (n)'], priority: 'must_learn' },
    { id: 'env_v5', type: 'vocabulary', term: 'deforestation', pronunciation: '/ˌdiːˌfɒrɪˈsteɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The clearing or destruction of forests, usually for farming or building.', vietnameseMeaning: 'Nạn phá rừng, chặt phá rừng.', example: 'Large-scale deforestation in the Amazon has destroyed the habitats of countless species.', writingTip: 'Very high frequency in environment essays. Use "large-scale / widespread deforestation".', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['large-scale deforestation', 'widespread deforestation', 'combat deforestation', 'rate of deforestation'], antonym: 'reforestation', wordFamily: ['deforest (v)', 'deforested (adj)'], priority: 'must_learn' },
    { id: 'env_v6', type: 'vocabulary', term: 'conserve', pronunciation: '/kənˈsɜːv/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To protect something from harm or from being used up.', vietnameseMeaning: 'Bảo tồn, giữ gìn, sử dụng tiết kiệm.', example: 'Simple changes in daily habits can help households conserve both water and electricity.', writingTip: 'Use for resources and nature. For money or time, "save" is more natural.', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['conserve energy', 'conserve water', 'conserve resources', 'conserve wildlife'], alternatives: ['preserve', 'protect', 'safeguard'], antonym: 'waste', wordFamily: ['conservation (n)', 'conservationist (n)'], priority: 'must_learn' },
    { id: 'env_v7', type: 'vocabulary', term: 'emissions', pronunciation: '/ɪˈmɪʃnz/', partOfSpeech: 'noun (plural)', cefrLevel: 'B2', definition: 'Gases or substances released into the atmosphere.', vietnameseMeaning: 'Khí thải, lượng phát thải ra môi trường.', example: 'The country has pledged to halve its carbon emissions within the next fifteen years.', writingTip: 'Usually plural in this sense: "carbon emissions", "cut emissions". "Emission" singular is the act of emitting.', topic: 'Environment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['carbon emissions', 'greenhouse gas emissions', 'cut emissions', 'emission levels'], wordFamily: ['emit (v)'], priority: 'must_learn' },
    { id: 'env_v8', type: 'vocabulary', term: 'wildlife', pronunciation: '/ˈwaɪldlaɪf/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Animals and plants that live and grow in natural conditions.', vietnameseMeaning: 'Động thực vật hoang dã.', example: 'Urban expansion has driven wildlife out of areas it has occupied for centuries.', writingTip: 'Uncountable — "wildlife is threatened", not "wildlifes are".', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['protect wildlife', 'wildlife conservation', 'wildlife habitat', 'threaten wildlife'], priority: 'high_value' },
    { id: 'env_v9', type: 'vocabulary', term: 'global warming', pronunciation: '/ˌɡləʊbl ˈwɔːmɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'The gradual rise in the average temperature of the earth.', vietnameseMeaning: 'Sự nóng lên toàn cầu.', example: 'Global warming is widely regarded as the single greatest challenge facing humanity today.', writingTip: 'No article: "Global warming is...", never "The global warming". Vary with "climate change".', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['contribute to global warming', 'combat global warming', 'the effects of global warming'], alternatives: ['climate change', 'rising global temperatures'], priority: 'must_learn' },
    { id: 'env_v10', type: 'vocabulary', term: 'sustainable', pronunciation: '/səˈsteɪnəbl/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Able to continue over a long period without damaging the environment.', vietnameseMeaning: 'Bền vững, duy trì được lâu dài.', example: 'Governments must promote sustainable farming methods that do not exhaust the soil.', writingTip: 'One of the highest-frequency words in this topic. Learn "sustainable development" as a fixed phrase.', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['sustainable development', 'sustainable energy', 'sustainable growth', 'environmentally sustainable'], antonym: 'unsustainable', wordFamily: ['sustain (v)', 'sustainability (n)', 'sustainably (adv)'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'env_v11', type: 'vocabulary', term: 'deplete', pronunciation: '/dɪˈpliːt/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To reduce a supply of something to a dangerously low level.', vietnameseMeaning: 'Làm cạn kiệt, tiêu hao gần hết (tài nguyên).', example: 'Intensive fishing has depleted stocks in the North Atlantic to a fraction of their former size.', writingTip: 'Reserve it for resources and reserves — it implies a serious, often irreversible loss.', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['deplete natural resources', 'deplete fish stocks', 'deplete the ozone layer', 'rapidly depleted'], alternatives: ['exhaust', 'drain', 'use up'], antonym: 'replenish', wordFamily: ['depletion (n)', 'depleted (adj)'], priority: 'must_learn' },
    { id: 'env_v12', type: 'vocabulary', term: 'degradation', pronunciation: '/ˌdeɡrəˈdeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The process by which the quality of the natural world is damaged or reduced.', vietnameseMeaning: 'Sự suy thoái, xuống cấp (của môi trường, đất đai).', example: 'Environmental degradation is an inevitable consequence of unregulated industrial expansion.', writingTip: '"Environmental degradation" is a Band 7+ noun phrase that replaces the vague "environment problems".', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['environmental degradation', 'soil degradation', 'land degradation', 'accelerate degradation'], alternatives: ['deterioration', 'decline'], wordFamily: ['degrade (v)', 'degraded (adj)'], priority: 'must_learn' },
    { id: 'env_v13', type: 'vocabulary', term: 'biodiversity', pronunciation: '/ˌbaɪəʊdaɪˈvɜːsəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The variety of plant and animal life in a particular habitat.', vietnameseMeaning: 'Đa dạng sinh học.', example: 'Clearing tropical rainforests results in a permanent loss of biodiversity.', writingTip: 'Use "loss of biodiversity" rather than "biodiversity is lost" — the noun phrase reads more academically.', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['loss of biodiversity', 'rich biodiversity', 'preserve biodiversity', 'biodiversity hotspot'], wordFamily: ['biodiverse (adj)'], priority: 'high_value' },
    { id: 'env_v14', type: 'vocabulary', term: 'contaminate', pronunciation: '/kənˈtæmɪneɪt/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To make something impure or poisonous by adding a harmful substance.', vietnameseMeaning: 'Làm nhiễm bẩn, làm ô nhiễm (nguồn nước, thực phẩm).', example: 'Chemical run-off from farms has contaminated groundwater across the region.', writingTip: 'Stronger and more specific than "pollute" when the substance enters water, soil or food.', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['contaminate water supplies', 'contaminated soil', 'heavily contaminated'], alternatives: ['pollute', 'poison', 'taint'], wordFamily: ['contamination (n)', 'contaminant (n)'], priority: 'high_value' },
    { id: 'env_v15', type: 'vocabulary', term: 'ecosystem', pronunciation: '/ˈiːkəʊsɪstəm/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'All the living things in an area and the way they affect each other.', vietnameseMeaning: 'Hệ sinh thái.', example: 'Even a small rise in ocean temperature can disrupt entire marine ecosystems.', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['fragile ecosystem', 'marine ecosystem', 'disrupt an ecosystem', 'restore an ecosystem'], wordFamily: ['ecological (adj)', 'ecology (n)'], priority: 'high_value' },
    { id: 'env_v16', type: 'vocabulary', term: 'deteriorate', pronunciation: '/dɪˈtɪəriəreɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To become progressively worse.', vietnameseMeaning: 'Xuống cấp, suy giảm dần theo thời gian.', example: 'Air quality in the capital has continued to deteriorate despite a series of government interventions.', writingTip: 'Use for quality or condition, not for numbers. Figures "fall"; conditions "deteriorate".', topic: 'Environment', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['conditions deteriorate', 'deteriorate rapidly', 'continue to deteriorate', 'deteriorating air quality'], alternatives: ['worsen', 'decline', 'degrade'], antonym: 'improve', wordFamily: ['deterioration (n)', 'deteriorating (adj)'], priority: 'must_learn' },
    { id: 'env_v17', type: 'vocabulary', term: 'fossil fuels', pronunciation: '/ˈfɒsl ˌfjuːəlz/', partOfSpeech: 'noun (plural)', cefrLevel: 'B2', definition: 'Fuels such as coal, oil and gas formed from the remains of ancient organisms.', vietnameseMeaning: 'Nhiên liệu hoá thạch (than, dầu, khí đốt).', example: 'Reducing our reliance on fossil fuels will require sustained public investment in clean energy.', writingTip: 'Almost always plural. Key partner verbs: burn, rely on, move away from.', topic: 'Environment', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['burn fossil fuels', 'reliance on fossil fuels', 'fossil fuel consumption'], antonym: 'renewable energy', priority: 'must_learn' },
    { id: 'env_v18', type: 'vocabulary', term: 'landfill', pronunciation: '/ˈlændfɪl/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A site where rubbish is buried under layers of earth.', vietnameseMeaning: 'Bãi chôn lấp rác.', example: 'Almost half of all household rubbish still ends up in landfill rather than being recycled.', writingTip: '"In landfill" is often used without an article, like a mass noun.', topic: 'Environment', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['landfill site', 'end up in landfill', 'landfill waste', 'divert waste from landfill'], priority: 'high_value' },
    { id: 'env_v19', type: 'vocabulary', term: 'habitat', pronunciation: '/ˈhæbɪtæt/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'The natural home of an animal or plant.', vietnameseMeaning: 'Môi trường sống tự nhiên của sinh vật.', example: 'Draining wetlands to create farmland destroys the habitat of migratory birds.', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['natural habitat', 'habitat loss', 'destroy habitats', 'habitat destruction'], priority: 'high_value' },
    { id: 'env_v20', type: 'vocabulary', term: 'offset', pronunciation: '/ˌɒfˈset/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To balance out a negative effect with an equal positive one.', vietnameseMeaning: 'Bù đắp, cân bằng lại (tác động tiêu cực).', example: 'Airlines now allow passengers to offset the carbon produced by their flights.', writingTip: 'Note the stress shift: verb /ˌɒfˈset/, noun /ˈɒfset/. "Carbon offsetting" is the fixed phrase.', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['offset emissions', 'offset the cost', 'carbon offsetting', 'partially offset'], alternatives: ['compensate for', 'counterbalance'], wordFamily: ['offsetting (n)'], priority: 'optional' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'env_v21', type: 'vocabulary', term: 'mitigate', pronunciation: '/ˈmɪtɪɡeɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To make the harmful effects of something less severe.', vietnameseMeaning: 'Giảm thiểu, làm dịu bớt tác hại.', example: 'Planting urban forests is one of the cheapest ways to mitigate the effects of extreme heat.', writingTip: 'You mitigate effects, impacts, risks or damage — not the problem itself. "Mitigate pollution" sounds wrong; "mitigate the effects of pollution" is correct.', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['mitigate the impact', 'mitigate the effects', 'mitigate the risks', 'mitigate damage'], alternatives: ['alleviate', 'lessen', 'reduce'], antonym: 'aggravate', wordFamily: ['mitigation (n)', 'mitigating (adj)'], priority: 'must_learn' },
    { id: 'env_v22', type: 'vocabulary', term: 'exacerbate', pronunciation: '/ɪɡˈzæsəbeɪt/', partOfSpeech: 'verb', cefrLevel: 'C2', definition: 'To make an already bad situation worse.', vietnameseMeaning: 'Làm trầm trọng thêm, khiến tình hình xấu đi.', example: 'Rapid industrialisation has exacerbated water shortages in already arid regions.', writingTip: 'Only for things that are already negative. You cannot exacerbate something good.', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['exacerbate the problem', 'exacerbate shortages', 'further exacerbate', 'exacerbate inequality'], alternatives: ['aggravate', 'worsen', 'compound'], antonym: 'alleviate', wordFamily: ['exacerbation (n)'], priority: 'must_learn' },
    { id: 'env_v23', type: 'vocabulary', term: 'detrimental', pronunciation: '/ˌdetrɪˈmentl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Causing harm or damage.', vietnameseMeaning: 'Có hại, gây tổn hại.', example: 'Single-use plastics have a profoundly detrimental effect on marine life.', writingTip: 'Almost always followed by "to" or used before effect/impact/consequences. A precise upgrade from "bad for".', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['detrimental effect', 'detrimental impact', 'detrimental to health', 'highly detrimental'], alternatives: ['harmful', 'damaging', 'adverse'], antonym: 'beneficial', wordFamily: ['detriment (n)'], priority: 'must_learn' },
    { id: 'env_v24', type: 'vocabulary', term: 'irreversible', pronunciation: '/ˌɪrɪˈvɜːsəbl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Impossible to change back to a previous state.', vietnameseMeaning: 'Không thể đảo ngược, không thể khắc phục.', example: 'Scientists warn that the loss of polar ice may soon become irreversible.', writingTip: 'Very effective in conclusions when arguing that action must be taken now.', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['irreversible damage', 'irreversible harm', 'irreversible decline', 'potentially irreversible'], alternatives: ['permanent', 'irreparable'], antonym: 'reversible', wordFamily: ['irreversibly (adv)'], priority: 'high_value' },
    { id: 'env_v25', type: 'vocabulary', term: 'carbon footprint', pronunciation: '/ˈkɑːbən ˈfʊtprɪnt/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'The total amount of greenhouse gas produced by a person, product or organisation.', vietnameseMeaning: 'Dấu chân carbon, tổng lượng khí thải mà một cá nhân hay tổ chức gây ra.', example: 'Eating less meat is one of the simplest ways for individuals to shrink their carbon footprint.', writingTip: 'Partner verbs are reduce, shrink, lower and cut — not "decrease" or "destroy".', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['reduce a carbon footprint', 'a large carbon footprint', 'measure a carbon footprint'], priority: 'high_value' },
    { id: 'env_v26', type: 'vocabulary', term: 'finite', pronunciation: '/ˈfaɪnaɪt/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Limited in amount and therefore capable of running out.', vietnameseMeaning: 'Hữu hạn, có giới hạn.', example: 'Oil and gas are finite resources, and no economy can depend on them indefinitely.', writingTip: '"Finite resources" is the natural pairing and instantly signals an academic register.', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['finite resources', 'finite supply', 'strictly finite'], alternatives: ['limited', 'exhaustible'], antonym: 'infinite', priority: 'high_value' },
    { id: 'env_v27', type: 'vocabulary', term: 'curb', pronunciation: '/kɜːb/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To control or limit something harmful.', vietnameseMeaning: 'Kiềm chế, hạn chế (điều gì đó có hại).', example: 'A carbon tax remains the most effective mechanism for curbing industrial emissions.', writingTip: 'Short, forceful and academic. Excellent for solution paragraphs about limiting a harmful trend.', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['curb emissions', 'curb consumption', 'curb pollution', 'curb the growth of'], alternatives: ['restrict', 'limit', 'restrain', 'rein in'], wordFamily: ['curbing (n)'], priority: 'must_learn' },
    { id: 'env_v28', type: 'vocabulary', term: 'rampant', pronunciation: '/ˈræmpənt/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Spreading in an uncontrolled and harmful way.', vietnameseMeaning: 'Tràn lan, hoành hành không kiểm soát.', example: 'Rampant illegal logging has stripped the region of nearly a third of its forest cover.', writingTip: 'Strong and slightly emotive — use once per essay at most, before a negative noun.', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['rampant deforestation', 'rampant consumption', 'run rampant'], alternatives: ['unchecked', 'widespread', 'uncontrolled'], priority: 'optional' },
    { id: 'env_v29', type: 'vocabulary', term: 'jeopardise', pronunciation: '/ˈdʒepədaɪz/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To put something valuable at risk of being harmed or lost.', vietnameseMeaning: 'Gây nguy hiểm cho, đe doạ làm mất đi.', example: 'Continued reliance on coal jeopardises the emissions targets the country has already agreed to.', writingTip: 'Stronger than "threaten" and ideal when arguing that short-term gains endanger long-term goals.', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['jeopardise the future', 'jeopardise progress', 'seriously jeopardise'], alternatives: ['endanger', 'threaten', 'imperil'], wordFamily: ['jeopardy (n)'], priority: 'high_value' },
    { id: 'env_v30', type: 'vocabulary', term: 'unprecedented', pronunciation: '/ʌnˈpresɪdentɪd/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Never having happened before.', vietnameseMeaning: 'Chưa từng có tiền lệ, chưa từng xảy ra trước đây.', example: 'The planet is warming at an unprecedented rate, leaving species little time to adapt.', writingTip: 'Powerful but overused by candidates — reserve it for genuinely new phenomena.', topic: 'Environment', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['unprecedented rate', 'unprecedented scale', 'unprecedented levels', 'on an unprecedented scale'], alternatives: ['unparalleled', 'record-breaking'], priority: 'high_value' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'env_c1', type: 'collocation', term: 'protect the environment', collocationType: 'Verb + Noun', definition: 'To take action that prevents damage to the natural world.', vietnameseMeaning: 'Bảo vệ môi trường.', example: 'Individuals as well as governments have a duty to protect the environment.', alternative: 'safeguard the environment', topic: 'Environment', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'Always with "the" — "protect environment" is a very common error.' },
    { id: 'env_c2', type: 'collocation', term: 'reduce carbon emissions', collocationType: 'Verb + Noun', definition: 'To lower the amount of carbon dioxide released into the air.', vietnameseMeaning: 'Giảm lượng khí thải carbon.', example: 'Switching from coal to gas would reduce carbon emissions almost immediately.', alternative: 'cut carbon emissions', topic: 'Environment', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'env_c3', type: 'collocation', term: 'renewable energy sources', collocationType: 'Adj + Noun', definition: 'Forms of energy that are naturally replaced, such as wind and solar.', vietnameseMeaning: 'Các nguồn năng lượng tái tạo.', example: 'Investment in renewable energy sources has quadrupled over the past decade.', topic: 'Environment', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'env_c4', type: 'collocation', term: 'tackle air pollution', collocationType: 'Verb + Noun', definition: 'To take determined action against dirty air.', vietnameseMeaning: 'Đối phó, xử lý vấn đề ô nhiễm không khí.', example: 'Congestion charges have proved to be an effective way to tackle air pollution in city centres.', alternative: 'combat air pollution', topic: 'Environment', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: '"Tackle" suits problems that can be acted on but not fully solved.' },
    { id: 'env_c5', type: 'collocation', term: 'natural resources', collocationType: 'Adj + Noun', definition: 'Materials such as water, timber and minerals that occur in nature.', vietnameseMeaning: 'Tài nguyên thiên nhiên.', example: 'Countries rich in natural resources do not always enjoy stable economic growth.', topic: 'Environment', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'env_c6', type: 'collocation', term: 'climate change', collocationType: 'Noun + Noun', definition: 'Long-term shifts in global weather patterns caused largely by human activity.', vietnameseMeaning: 'Biến đổi khí hậu.', example: 'Climate change is no longer a distant threat but a present reality.', topic: 'Environment', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'No article: "Climate change is...", never "The climate change is...".' },
    { id: 'env_c7', type: 'collocation', term: 'raise environmental awareness', collocationType: 'Verb + Noun', definition: "To increase people's understanding of environmental issues.", vietnameseMeaning: 'Nâng cao nhận thức về môi trường.', example: 'Documentaries have done a great deal to raise environmental awareness among young viewers.', topic: 'Environment', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'env_c8', type: 'collocation', term: 'recycle household waste', collocationType: 'Verb + Noun', definition: 'To process rubbish produced by homes so it can be used again.', vietnameseMeaning: 'Tái chế rác thải sinh hoạt.', example: 'Making it easier to recycle household waste is more effective than fining those who do not.', topic: 'Environment', bandLevel: '5-6', task: 'task2', priority: 'high_value' },

    // Advanced (Band 6-7)
    { id: 'env_c9', type: 'collocation', term: 'pose a serious threat', collocationType: 'Verb + Adj + Noun', definition: 'To represent a significant danger to something.', vietnameseMeaning: 'Gây ra mối đe doạ nghiêm trọng.', example: 'Rising sea levels pose a serious threat to low-lying coastal cities.', alternative: 'represent a significant risk', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'must_learn', writingTip: 'Follow with "to" + the thing endangered.' },
    { id: 'env_c10', type: 'collocation', term: 'environmental degradation', collocationType: 'Adj + Noun', definition: 'The gradual damaging of the natural world.', vietnameseMeaning: 'Sự suy thoái môi trường.', example: 'Environmental degradation and economic growth have historically gone hand in hand.', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'env_c11', type: 'collocation', term: 'greenhouse gas emissions', collocationType: 'Noun + Noun', definition: 'Gases released into the atmosphere that trap heat.', vietnameseMeaning: 'Khí thải nhà kính.', example: 'Agriculture accounts for a surprisingly large share of greenhouse gas emissions.', topic: 'Environment', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'env_c12', type: 'collocation', term: 'deplete natural resources', collocationType: 'Verb + Noun', definition: 'To use up natural materials faster than they can be replaced.', vietnameseMeaning: 'Làm cạn kiệt tài nguyên thiên nhiên.', example: 'Mass consumption in wealthy nations depletes natural resources extracted from poorer ones.', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'env_c13', type: 'collocation', term: 'endangered species', collocationType: 'Adj + Noun', definition: 'Types of animal or plant at risk of dying out completely.', vietnameseMeaning: 'Các loài có nguy cơ tuyệt chủng.', example: 'Strict penalties for trading in endangered species have reduced poaching considerably.', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'env_c14', type: 'collocation', term: 'reduce your carbon footprint', collocationType: 'Verb + Noun', definition: 'To lower the total greenhouse gas you are responsible for.', vietnameseMeaning: 'Giảm dấu chân carbon của bản thân.', example: 'Commuting by bicycle is one of the easiest ways to reduce your carbon footprint.', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'env_c15', type: 'collocation', term: 'sustainable development', collocationType: 'Adj + Noun', definition: 'Economic growth that does not damage resources needed by future generations.', vietnameseMeaning: 'Phát triển bền vững.', example: 'Sustainable development requires balancing economic ambition against ecological limits.', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },

    // High-impact (Band 7+)
    { id: 'env_c16', type: 'collocation', term: 'mitigate the impact of climate change', collocationType: 'Verb + Noun', definition: 'To reduce how severely climate change affects people and nature.', vietnameseMeaning: 'Giảm thiểu tác động của biến đổi khí hậu.', example: 'Restoring mangrove forests can mitigate the impact of climate change on coastal populations.', topic: 'Environment', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'env_c17', type: 'collocation', term: 'cause irreversible damage', collocationType: 'Verb + Adj + Noun', definition: 'To create harm that cannot be undone.', vietnameseMeaning: 'Gây ra thiệt hại không thể khắc phục.', example: 'Deep-sea mining risks causing irreversible damage to habitats we barely understand.', topic: 'Environment', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'env_c18', type: 'collocation', term: 'curb greenhouse gas emissions', collocationType: 'Verb + Noun', definition: 'To place effective limits on heat-trapping gases.', vietnameseMeaning: 'Kiềm chế lượng khí thải nhà kính.', example: 'Only binding international agreements are likely to curb greenhouse gas emissions at the necessary speed.', topic: 'Environment', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'env_c19', type: 'collocation', term: 'stringent environmental regulations', collocationType: 'Adj + Noun', definition: 'Strict legal rules governing pollution and resource use.', vietnameseMeaning: 'Các quy định môi trường nghiêm ngặt.', example: 'Manufacturers frequently relocate to countries without stringent environmental regulations.', alternative: 'strict environmental legislation', topic: 'Environment', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'env_c20', type: 'collocation', term: 'disrupt the ecological balance', collocationType: 'Verb + Noun', definition: 'To upset the stable relationship between living things in an area.', vietnameseMeaning: 'Phá vỡ cân bằng sinh thái.', example: 'Introducing non-native fish has disrupted the ecological balance of the lake.', topic: 'Environment', bandLevel: '7+', task: 'task2', priority: 'optional' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'env_p1', type: 'phrasal_verb', term: 'cut down', partOfSpeech: 'phrasal verb (separable)', definition: 'To make a tree fall by cutting through its trunk.', vietnameseMeaning: 'Chặt hạ (cây cối).', example: 'Vast areas of rainforest are cut down every year to make way for cattle ranching.', formalAlternative: 'fell', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['cut down trees', 'cut down forests'], academicAlternatives: ['fell', 'clear', 'log'] },
    { id: 'env_p2', type: 'phrasal_verb', term: 'cut down on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To use or consume less of something.', vietnameseMeaning: 'Cắt giảm, giảm bớt việc sử dụng.', example: 'Consumers are being urged to cut down on single-use packaging.', formalAlternative: 'reduce', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Fairly informal. In a Task 2 essay prefer "reduce", "limit" or "minimise".', academicAlternatives: ['reduce', 'limit', 'minimise', 'curtail'] },
    { id: 'env_p3', type: 'phrasal_verb', term: 'use up', partOfSpeech: 'phrasal verb (separable)', definition: 'To consume the whole supply of something.', vietnameseMeaning: 'Dùng hết, tiêu thụ cạn kiệt.', example: 'Current rates of consumption will use up known oil reserves within a century.', formalAlternative: 'exhaust', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['exhaust', 'deplete', 'consume'] },
    { id: 'env_p4', type: 'phrasal_verb', term: 'throw away', partOfSpeech: 'phrasal verb (separable)', definition: 'To get rid of something you no longer want.', vietnameseMeaning: 'Vứt bỏ, thải bỏ.', example: 'Roughly a third of the food produced globally is thrown away before it is eaten.', formalAlternative: 'discard', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Conversational. "Discard" or "dispose of" is safer in formal writing.', academicAlternatives: ['discard', 'dispose of'] },
    { id: 'env_p5', type: 'phrasal_verb', term: 'die out', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To gradually disappear until none are left.', vietnameseMeaning: 'Tuyệt chủng, biến mất dần.', example: 'Dozens of amphibian species have died out since the middle of the last century.', formalAlternative: 'become extinct', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['become extinct', 'disappear', 'vanish'] },

    // Advanced / less common
    { id: 'env_p6', type: 'phrasal_verb', term: 'phase out', partOfSpeech: 'phrasal verb (separable)', definition: 'To stop using something gradually over a planned period.', vietnameseMeaning: 'Loại bỏ dần theo lộ trình.', example: 'Several governments have committed to phasing out petrol vehicles by 2035.', formalAlternative: 'discontinue gradually', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['phase out subsidies', 'phase out coal', 'be phased out'], academicAlternatives: ['discontinue', 'withdraw', 'eliminate progressively'] },
    { id: 'env_p7', type: 'phrasal_verb', term: 'give off', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To release a gas, smell or heat.', vietnameseMeaning: 'Thải ra, phát ra (khí, mùi, nhiệt).', example: 'Vehicles idling in traffic give off a disproportionate quantity of nitrogen dioxide.', formalAlternative: 'emit', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['emit', 'release', 'discharge'] },
    { id: 'env_p8', type: 'phrasal_verb', term: 'wipe out', partOfSpeech: 'phrasal verb (separable)', definition: 'To destroy something completely.', vietnameseMeaning: 'Xoá sổ, tiêu diệt hoàn toàn.', example: 'A single oil spill can wipe out an entire coastal fishery.', formalAlternative: 'eradicate', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', usageWarning: 'Slightly dramatic — appropriate for genuine total destruction only.', academicAlternatives: ['eradicate', 'destroy', 'annihilate'] },
    { id: 'env_p9', type: 'phrasal_verb', term: 'run out of', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To have no more of a supply left.', vietnameseMeaning: 'Cạn kiệt, hết sạch (nguồn cung).', example: 'Several major cities came close to running out of drinking water during the drought.', formalAlternative: 'exhaust supplies of', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['exhaust', 'be depleted of'] },
    { id: 'env_p10', type: 'phrasal_verb', term: 'clean up', partOfSpeech: 'phrasal verb (separable)', definition: 'To remove pollution or rubbish from a place.', vietnameseMeaning: 'Dọn dẹp, làm sạch (ô nhiễm).', example: 'Cleaning up contaminated rivers costs far more than preventing the pollution in the first place.', formalAlternative: 'remediate', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'optional', collocations: ['clean up pollution', 'clean-up operation'], academicAlternatives: ['decontaminate', 'remediate', 'restore'] },
  ],

  writingPhrases: [
    { id: 'env_w1', type: 'writing_phrase', term: 'The most compelling argument for stronger environmental regulation is that...', function: 'Introducing an argument', vietnameseMeaning: 'Lập luận thuyết phục nhất ủng hộ việc siết chặt quy định môi trường là...', example: 'The most compelling argument for stronger environmental regulation is that market forces alone have never priced pollution correctly.', topic: 'Environment', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'env_w2', type: 'writing_phrase', term: 'A major driver of environmental damage is...', function: 'Giving a reason', vietnameseMeaning: 'Một nguyên nhân chính gây tổn hại môi trường là...', example: 'A major driver of environmental damage is the assumption that natural resources are free.', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'env_w3', type: 'writing_phrase', term: 'This trend stems largely from...', function: 'Explaining a cause', vietnameseMeaning: 'Xu hướng này chủ yếu bắt nguồn từ...', example: 'This trend stems largely from decades of subsidised fossil fuel production.', topic: 'Environment', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'env_w4', type: 'writing_phrase', term: 'The consequences of this are felt most acutely by...', function: 'Explaining an effect', vietnameseMeaning: 'Hậu quả của điều này được cảm nhận rõ rệt nhất bởi...', example: 'The consequences of this are felt most acutely by communities living on flood plains.', topic: 'Environment', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'env_w5', type: 'writing_phrase', term: 'Denmark offers a clear illustration of this:', function: 'Giving an example', vietnameseMeaning: 'Đan Mạch là một minh chứng rõ ràng cho điều này:', example: 'Denmark offers a clear illustration of this: wind now supplies almost half of the national grid.', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'env_w6', type: 'writing_phrase', term: 'The clearest benefit of switching to clean energy is...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi ích rõ ràng nhất của việc chuyển sang năng lượng sạch là...', example: 'The clearest benefit of switching to clean energy is the immediate improvement in urban air quality.', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'env_w7', type: 'writing_phrase', term: 'The principal drawback of this approach is its cost to...', function: 'Discussing disadvantages', vietnameseMeaning: 'Nhược điểm chính của cách tiếp cận này là chi phí đối với...', example: 'The principal drawback of this approach is its cost to low-income households, who spend a larger share of their income on fuel.', topic: 'Environment', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'env_w8', type: 'writing_phrase', term: 'A practical first step would be to...', function: 'Suggesting a solution', vietnameseMeaning: 'Một bước đi thiết thực đầu tiên sẽ là...', example: 'A practical first step would be to remove the tax advantages currently enjoyed by heavy polluters.', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'env_w9', type: 'writing_phrase', term: 'In my view, the primary responsibility lies with...', function: 'Expressing an opinion', vietnameseMeaning: 'Theo quan điểm của tôi, trách nhiệm chính thuộc về...', example: 'In my view, the primary responsibility lies with the industries that profit from extraction, not with individual consumers.', topic: 'Environment', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'env_w10', type: 'writing_phrase', term: 'While individual effort is valuable, legislation is considerably more effective at...', function: 'Comparing ideas', vietnameseMeaning: 'Mặc dù nỗ lực cá nhân có giá trị, luật pháp hiệu quả hơn nhiều trong việc...', example: 'While individual effort is valuable, legislation is considerably more effective at changing the behaviour of large corporations.', topic: 'Environment', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'env_m1', type: 'common_mistake', incorrect: 'We must protect environment for future generations.', correct: 'We must protect the environment for future generations.', explanation: '"Environment" in this general sense always takes "the". Vietnamese has no articles, so this is one of the most frequent errors in environment essays.', topic: 'Environment', priority: 'must_learn' },
    { id: 'env_m2', type: 'common_mistake', incorrect: 'There are many pollutions in big cities.', correct: 'There is a great deal of pollution in big cities.', explanation: '"Pollution" is uncountable: no plural -s and no "many". Use "much", "a great deal of" or "high levels of".', topic: 'Environment', priority: 'must_learn' },
    { id: 'env_m3', type: 'common_mistake', incorrect: 'The earth is becoming hotter and hotter every year.', correct: 'Global temperatures are rising steadily year on year.', explanation: 'The "hotter and hotter" pattern is spoken English. Academic writing prefers a precise verb plus an adverb: "rise steadily / sharply / gradually".', topic: 'Environment', priority: 'high_value' },
    { id: 'env_m4', type: 'common_mistake', incorrect: 'The government should ban to use plastic bags.', correct: 'The government should ban the use of plastic bags.', explanation: '"Ban" is followed by a noun or "-ing", never by "to + verb". Also correct: "ban people from using plastic bags".', topic: 'Environment', priority: 'must_learn' },
    { id: 'env_m5', type: 'common_mistake', incorrect: 'Environment problems are getting more serious.', correct: 'Environmental problems are becoming more serious.', explanation: 'Use the adjective "environmental" before a noun, not the noun "environment". Compare: environmental damage, environmental policy, environmental impact.', topic: 'Environment', priority: 'must_learn' },
  ],

  learnFirst: {
    vocabulary: ['env_v10', 'env_v7', 'env_v5', 'env_v11', 'env_v12', 'env_v16', 'env_v21', 'env_v22', 'env_v23', 'env_v27'],
    collocations: ['env_c1', 'env_c2', 'env_c9', 'env_c10', 'env_c16'],
    phrasalVerbs: ['env_p6', 'env_p5', 'env_p9'],
    writingPhrases: ['env_w1', 'env_w4', 'env_w8'],
  },
}
