import type { TopicData } from '../types'

export const FAMILY: TopicData = {
  topic: 'Family',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'fam_v1', type: 'vocabulary', term: 'upbringing', pronunciation: '/ˈʌpbrɪŋɪŋ/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'The way a child is cared for and taught while growing up.', vietnameseMeaning: 'Sự nuôi dạy, cách giáo dục trong gia đình.', example: 'A strict upbringing produces obedience, but not necessarily good judgement.', writingTip: 'Usually singular with an adjective: "a strict/happy/religious upbringing".', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a strict upbringing', 'a happy upbringing', 'family upbringing'], wordFamily: ['bring up (v)'], priority: 'must_learn' },
    { id: 'fam_v2', type: 'vocabulary', term: 'relative', pronunciation: '/ˈrelətɪv/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A member of your family.', vietnameseMeaning: 'Người thân, họ hàng.', example: 'In many cultures, elderly relatives are cared for at home rather than in institutions.', writingTip: 'A useful synonym for "family member". "Kin" is more formal but rarely needed.', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['close relatives', 'distant relatives', 'elderly relatives'], alternatives: ['family member', 'kin'], priority: 'high_value' },
    { id: 'fam_v3', type: 'vocabulary', term: 'household', pronunciation: '/ˈhaʊshəʊld/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'All the people living together in one home.', vietnameseMeaning: 'Hộ gia đình.', example: 'Single-person households have doubled as a proportion of the total since 1980.', writingTip: 'Essential for Task 1 charts about living arrangements and spending.', topic: 'Family', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['household income', 'a single-person household', 'household chores'], priority: 'must_learn' },
    { id: 'fam_v4', type: 'vocabulary', term: 'childcare', pronunciation: '/ˈtʃaɪldkeə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The care of children, especially while parents work.', vietnameseMeaning: 'Việc trông giữ, chăm sóc trẻ nhỏ.', example: 'Affordable childcare does more to raise female employment than any equality legislation.', writingTip: 'One word in British English. Uncountable, so no plural.', topic: 'Family', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['affordable childcare', 'childcare costs', 'state-funded childcare'], priority: 'must_learn' },
    { id: 'fam_v5', type: 'vocabulary', term: 'parenting', pronunciation: '/ˈpeərəntɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The activity of raising a child.', vietnameseMeaning: 'Việc làm cha mẹ, cách nuôi dạy con.', example: 'Parenting styles vary enormously between cultures, yet children thrive in most of them.', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['parenting styles', 'good parenting', 'parenting skills'], wordFamily: ['parent (n/v)', 'parental (adj)'], priority: 'must_learn' },
    { id: 'fam_v6', type: 'vocabulary', term: 'sibling', pronunciation: '/ˈsɪblɪŋ/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A brother or sister.', vietnameseMeaning: 'Anh chị em ruột.', example: 'Children with siblings learn to negotiate long before they learn to argue politely.', writingTip: 'A neat single word that avoids the clumsy "brothers and sisters".', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['sibling rivalry', 'older siblings', 'have siblings'], priority: 'high_value' },
    { id: 'fam_v7', type: 'vocabulary', term: 'divorce', pronunciation: '/dɪˈvɔːs/', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'The legal ending of a marriage.', vietnameseMeaning: 'Ly hôn.', example: 'Divorce rates have levelled off in several countries where marriage itself has become less common.', writingTip: 'Note "get divorced" (state) and "divorce somebody" (action, no preposition).', topic: 'Family', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['the divorce rate', 'get divorced', 'file for divorce'], wordFamily: ['divorced (adj)'], priority: 'high_value' },
    { id: 'fam_v8', type: 'vocabulary', term: 'affection', pronunciation: '/əˈfekʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'A gentle feeling of fondness and care.', vietnameseMeaning: 'Tình cảm yêu thương, sự trìu mến.', example: 'Children need consistent affection far more than they need expensive possessions.', writingTip: 'Uncountable. Note "show affection" and "a display of affection".', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['show affection', 'a lack of affection', 'genuine affection'], wordFamily: ['affectionate (adj)'], priority: 'high_value' },
    { id: 'fam_v9', type: 'vocabulary', term: 'supportive', pronunciation: '/səˈpɔːtɪv/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Providing encouragement and practical help.', vietnameseMeaning: 'Hỗ trợ, luôn ủng hộ và động viên.', example: 'A supportive family compensates for a great deal that schools cannot provide.', writingTip: 'Followed by "of": "supportive of her decision".', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a supportive family', 'supportive environment', 'supportive of'], wordFamily: ['support (v/n)'], priority: 'high_value' },
    { id: 'fam_v10', type: 'vocabulary', term: 'role model', pronunciation: '/ˈrəʊl ˌmɒdl/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A person whose behaviour others copy.', vietnameseMeaning: 'Hình mẫu, tấm gương để noi theo.', example: 'Parents remain the most influential role models children ever encounter, whether they intend to be or not.', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a positive role model', 'serve as a role model', 'lack role models'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'fam_v11', type: 'vocabulary', term: 'nurture', pronunciation: '/ˈnɜːtʃə/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To care for and encourage the growth of someone or something.', vietnameseMeaning: 'Nuôi dưỡng, vun đắp cho phát triển.', example: 'Families nurture confidence in ways that are almost impossible to reproduce elsewhere.', writingTip: 'The "nature versus nurture" debate is a ready-made framing for family essays.', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['nurture talent', 'nurture children', 'nature versus nurture'], alternatives: ['foster', 'cultivate', 'raise'], antonym: 'neglect', wordFamily: ['nurturing (adj)'], priority: 'must_learn' },
    { id: 'fam_v12', type: 'vocabulary', term: 'extended family', pronunciation: '/ɪkˌstendɪd ˈfæməli/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A family group including grandparents, aunts, uncles and cousins.', vietnameseMeaning: 'Đại gia đình nhiều thế hệ.', example: 'The extended family remains the main welfare system in much of the world.', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['live with the extended family', 'the support of the extended family'], antonym: 'nuclear family', priority: 'must_learn' },
    { id: 'fam_v13', type: 'vocabulary', term: 'nuclear family', pronunciation: '/ˌnjuːkliə ˈfæməli/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A family unit of parents and their children only.', vietnameseMeaning: 'Gia đình hạt nhân (chỉ gồm bố mẹ và con cái).', example: 'The nuclear family is a recent and geographically limited arrangement, not a universal norm.', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the traditional nuclear family', 'the decline of the nuclear family'], antonym: 'extended family', priority: 'must_learn' },
    { id: 'fam_v14', type: 'vocabulary', term: 'bond', pronunciation: '/bɒnd/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A strong emotional connection between people.', vietnameseMeaning: 'Sự gắn bó, mối liên kết tình cảm.', example: 'Shared meals build a bond between family members that scheduled activities rarely match.', writingTip: 'Verbs: form, strengthen, weaken, break. Also a verb: "bond with a child".', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a strong bond', 'form a bond', 'family bonds', 'strengthen a bond'], alternatives: ['tie', 'attachment'], priority: 'high_value' },
    { id: 'fam_v15', type: 'vocabulary', term: 'authoritarian', pronunciation: '/ɔːˌθɒrɪˈteəriən/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Demanding strict obedience and allowing little freedom.', vietnameseMeaning: 'Độc đoán, áp đặt và đòi hỏi tuân phục.', example: 'Authoritarian parenting produces compliant children who struggle to make decisions alone.', writingTip: 'The standard contrast in parenting research is "authoritarian" versus "authoritative" — the latter is firm but responsive.', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['authoritarian parenting', 'an authoritarian approach'], antonym: 'permissive', priority: 'high_value' },
    { id: 'fam_v16', type: 'vocabulary', term: 'dependant', pronunciation: '/dɪˈpendənt/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'A person who relies on someone else for financial support.', vietnameseMeaning: 'Người phụ thuộc (về tài chính).', example: 'Workers supporting several dependants have almost no capacity to save.', writingTip: 'The noun is spelled "dependant" in British English; the adjective is "dependent".', topic: 'Family', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['support dependants', 'elderly dependants', 'the dependency ratio'], priority: 'high_value' },
    { id: 'fam_v17', type: 'vocabulary', term: 'cohabit', pronunciation: '/kəʊˈhæbɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To live together as a couple without being married.', vietnameseMeaning: 'Sống chung như vợ chồng mà không kết hôn.', example: 'Couples who cohabit before marrying are no more likely to divorce than those who do not.', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cohabiting couples', 'choose to cohabit'], wordFamily: ['cohabitation (n)'], priority: 'optional' },
    { id: 'fam_v18', type: 'vocabulary', term: 'adolescence', pronunciation: '/ˌædəˈlesns/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The period between childhood and adulthood.', vietnameseMeaning: 'Tuổi vị thành niên, giai đoạn dậy thì.', example: 'Adolescence now lasts longer than at any point in history, both biologically and economically.', writingTip: 'Uncountable and takes no article: "during adolescence", not "during the adolescence".', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['during adolescence', 'early adolescence', 'the challenges of adolescence'], wordFamily: ['adolescent (n/adj)'], priority: 'high_value' },
    { id: 'fam_v19', type: 'vocabulary', term: 'breadwinner', pronunciation: '/ˈbredwɪnə/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'The family member who earns the money that supports the household.', vietnameseMeaning: 'Trụ cột kinh tế trong gia đình.', example: 'The assumption of a single male breadwinner still shapes tax systems designed decades ago.', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the main breadwinner', 'the sole breadwinner'], priority: 'high_value' },
    { id: 'fam_v20', type: 'vocabulary', term: 'formative', pronunciation: '/ˈfɔːmətɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Having a strong influence on how someone develops.', vietnameseMeaning: 'Có tính định hình, quyết định sự hình thành nhân cách.', example: 'What happens in the formative years shapes health and earnings decades later.', writingTip: 'Almost always used with "years", "period", "experience" or "influence".', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['formative years', 'a formative experience', 'a formative influence'], wordFamily: ['form (v)', 'formation (n)'], priority: 'must_learn' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'fam_v21', type: 'vocabulary', term: 'resilience', pronunciation: '/rɪˈzɪliəns/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The ability to recover quickly from difficulty.', vietnameseMeaning: 'Khả năng phục hồi, sự kiên cường trước khó khăn.', example: 'Children develop resilience through manageable setbacks, not through their absence.', writingTip: 'Verbs: build, develop, foster. One of the most useful abstract nouns in family and education essays.', topic: 'Family', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['build resilience', 'emotional resilience', 'develop resilience'], alternatives: ['toughness', 'adaptability'], wordFamily: ['resilient (adj)'], priority: 'must_learn' },
    { id: 'fam_v22', type: 'vocabulary', term: 'intergenerational', pronunciation: '/ˌɪntədʒenəˈreɪʃənl/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Involving or affecting people of different generations.', vietnameseMeaning: 'Liên thế hệ, giữa các thế hệ với nhau.', example: 'Housing wealth has created an intergenerational divide that earnings alone cannot bridge.', topic: 'Family', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['intergenerational support', 'intergenerational inequality', 'intergenerational conflict'], priority: 'high_value' },
    { id: 'fam_v23', type: 'vocabulary', term: 'estranged', pronunciation: '/ɪˈstreɪndʒd/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'No longer in contact or on friendly terms with a family member.', vietnameseMeaning: 'Xa cách, đoạn tuyệt quan hệ (với người thân).', example: 'Adults estranged from their parents report worse health outcomes in later life.', writingTip: 'Followed by "from". A precise formal alternative to "not speaking to each other".', topic: 'Family', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['estranged from', 'an estranged parent', 'become estranged'], wordFamily: ['estrangement (n)'], priority: 'optional' },
    { id: 'fam_v24', type: 'vocabulary', term: 'patriarchal', pronunciation: '/ˌpeɪtriˈɑːkl/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Controlled by men, with authority passing through the male line.', vietnameseMeaning: 'Mang tính phụ hệ, do nam giới nắm quyền.', example: 'Patriarchal expectations persist in households where both partners now earn equally.', topic: 'Family', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['a patriarchal society', 'patriarchal structures'], antonym: 'matriarchal', wordFamily: ['patriarchy (n)'], priority: 'optional' },
    { id: 'fam_v25', type: 'vocabulary', term: 'overprotective', pronunciation: '/ˌəʊvəprəˈtektɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Protecting someone more than is necessary or helpful.', vietnameseMeaning: 'Bao bọc quá mức.', example: 'Overprotective parenting spares children discomfort at the cost of their independence.', writingTip: 'A useful counterweight when discussing safety, freedom and risk in childhood.', topic: 'Family', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['overprotective parents', 'excessively overprotective'], priority: 'high_value' },
    { id: 'fam_v26', type: 'vocabulary', term: 'kinship', pronunciation: '/ˈkɪnʃɪp/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'Family relationship, or a feeling of closeness based on it.', vietnameseMeaning: 'Quan hệ họ hàng, tình thân tộc.', example: 'Kinship obligations continue to shape migration decisions across much of Asia.', topic: 'Family', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['kinship ties', 'a sense of kinship', 'kinship networks'], priority: 'optional' },
    { id: 'fam_v27', type: 'vocabulary', term: 'surrogate', pronunciation: '/ˈsʌrəɡət/', partOfSpeech: 'adjective / noun', cefrLevel: 'C2', definition: 'Acting as a substitute for someone else, especially a parent.', vietnameseMeaning: 'Thay thế, đóng vai trò thay cho (cha mẹ).', example: 'Grandparents increasingly act as surrogate parents while both parents work full time.', topic: 'Family', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['a surrogate parent', 'a surrogate family'], alternatives: ['substitute', 'stand-in'], priority: 'optional' },
    { id: 'fam_v28', type: 'vocabulary', term: 'reconcile', pronunciation: '/ˈrekənsaɪl/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To restore friendly relations; to make two conflicting things compatible.', vietnameseMeaning: 'Hoà giải; dung hoà hai điều mâu thuẫn.', example: 'Working parents struggle to reconcile career ambitions with the demands of small children.', writingTip: 'Two patterns worth knowing: "reconcile with somebody" and "reconcile X with Y".', topic: 'Family', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['reconcile work and family', 'difficult to reconcile', 'reconcile differences'], wordFamily: ['reconciliation (n)'], priority: 'must_learn' },
    { id: 'fam_v29', type: 'vocabulary', term: 'dysfunctional', pronunciation: '/dɪsˈfʌŋkʃənl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Not working normally, especially of relationships within a family.', vietnameseMeaning: 'Rối loạn chức năng, không lành mạnh (về quan hệ gia đình).', example: 'Children from dysfunctional households do best when one stable adult remains constant.', topic: 'Family', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a dysfunctional family', 'deeply dysfunctional'], antonym: 'functional', wordFamily: ['dysfunction (n)'], priority: 'high_value' },
    { id: 'fam_v30', type: 'vocabulary', term: 'filial', pronunciation: '/ˈfɪliəl/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Relating to the duties of a son or daughter towards their parents.', vietnameseMeaning: 'Thuộc về bổn phận làm con, hiếu thảo.', example: 'Filial duty is codified in law in several Asian countries, not merely expected socially.', writingTip: '"Filial piety" (hiếu thảo) is the standard phrase and is extremely useful when writing about Vietnamese or East Asian family values.', topic: 'Family', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['filial piety', 'filial duty', 'filial responsibility'], priority: 'high_value' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'fam_c1', type: 'collocation', term: 'raise a family', collocationType: 'Verb + Noun', definition: 'To have children and bring them up.', vietnameseMeaning: 'Xây dựng và nuôi dạy một gia đình.', example: 'Couples now wait far longer before deciding to raise a family.', alternative: 'start a family', topic: 'Family', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'You "start" a family when the first child arrives and "raise" one over the following years.' },
    { id: 'fam_c2', type: 'collocation', term: 'a close-knit family', collocationType: 'Adj + Noun', definition: 'A family whose members are emotionally very close.', vietnameseMeaning: 'Gia đình gắn bó khăng khít.', example: 'A close-knit family can absorb shocks that would overwhelm an isolated individual.', topic: 'Family', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'fam_c3', type: 'collocation', term: 'family values', collocationType: 'Noun + Noun', definition: 'Beliefs about how family members should behave towards one another.', vietnameseMeaning: 'Các giá trị gia đình.', example: 'Politicians invoke family values far more often than they define them.', topic: 'Family', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'fam_c4', type: 'collocation', term: 'a single-parent family', collocationType: 'Adj + Noun', definition: 'A household in which one parent raises the children alone.', vietnameseMeaning: 'Gia đình đơn thân.', example: 'Single-parent families are far more likely to fall below the poverty line.', topic: 'Family', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'fam_c5', type: 'collocation', term: 'spend quality time', collocationType: 'Verb + Noun', definition: 'To spend focused, meaningful time with someone.', vietnameseMeaning: 'Dành thời gian chất lượng bên nhau.', example: 'Parents who spend quality time with their children matter more than parents who simply spend hours.', topic: 'Family', bandLevel: '5-6', task: 'task2', priority: 'high_value', writingTip: 'The preposition after "time" is "with": spend time with someone, not "for" someone.' },
    { id: 'fam_c6', type: 'collocation', term: 'get married', collocationType: 'Verb + Adj', definition: 'To enter into marriage.', vietnameseMeaning: 'Kết hôn, lập gia đình.', example: 'People get married later in almost every country where women have access to higher education.', topic: 'Family', bandLevel: '5-6', task: 'both', priority: 'must_learn', writingTip: 'The preposition is "to": "married to someone", never "married with someone".' },
    { id: 'fam_c7', type: 'collocation', term: 'family background', collocationType: 'Noun + Noun', definition: 'The social and economic circumstances a person was born into.', vietnameseMeaning: 'Hoàn cảnh, xuất thân gia đình.', example: 'Family background still predicts examination results more accurately than any measure of effort.', topic: 'Family', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'fam_c8', type: 'collocation', term: 'working parents', collocationType: 'Adj + Noun', definition: 'Parents who are also in paid employment.', vietnameseMeaning: 'Cha mẹ đi làm.', example: 'Working parents need predictable hours far more than they need occasional bonuses.', topic: 'Family', bandLevel: '5-6', task: 'task2', priority: 'high_value' },

    // Advanced (Band 6-7)
    { id: 'fam_c9', type: 'collocation', term: 'a strong family bond', collocationType: 'Adj + Noun', definition: 'A powerful emotional connection between family members.', vietnameseMeaning: 'Mối gắn kết gia đình bền chặt.', example: 'A strong family bond protects adolescents from many of the risks their peers face.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fam_c10', type: 'collocation', term: 'the extended family', collocationType: 'Adj + Noun', definition: 'Relatives beyond the immediate parents and children.', vietnameseMeaning: 'Đại gia đình gồm nhiều thế hệ.', example: 'Where the extended family lives nearby, childcare costs fall dramatically.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fam_c11', type: 'collocation', term: 'parental guidance', collocationType: 'Adj + Noun', definition: 'Advice and supervision provided by parents.', vietnameseMeaning: 'Sự hướng dẫn, chỉ bảo của cha mẹ.', example: 'Parental guidance matters most precisely when adolescents appear least willing to accept it.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'fam_c12', type: 'collocation', term: 'a rising divorce rate', collocationType: 'Adj + Noun', definition: 'An increasing proportion of marriages ending legally.', vietnameseMeaning: 'Tỷ lệ ly hôn ngày càng tăng.', example: 'A rising divorce rate may reflect greater freedom rather than deeper unhappiness.', topic: 'Family', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'fam_c13', type: 'collocation', term: 'the nuclear family', collocationType: 'Adj + Noun', definition: 'A household of two parents and their children.', vietnameseMeaning: 'Gia đình hạt nhân.', example: 'The nuclear family became the norm only when housing and employment made it possible.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fam_c14', type: 'collocation', term: 'the generation gap', collocationType: 'Noun + Noun', definition: 'Differences in attitudes between older and younger people.', vietnameseMeaning: 'Khoảng cách thế hệ.', example: 'The generation gap is now measured in technology as much as in values.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'fam_c15', type: 'collocation', term: 'share household chores', collocationType: 'Verb + Noun', definition: 'To divide domestic tasks between family members.', vietnameseMeaning: 'Chia sẻ việc nhà.', example: 'Couples who share household chores equally report higher satisfaction with their relationship.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'high_value', writingTip: '"Chores" is the natural noun for routine domestic work; "housework" is uncountable.' },

    // High-impact (Band 7+)
    { id: 'fam_c16', type: 'collocation', term: 'instil values in children', collocationType: 'Verb + Noun', definition: 'To gradually establish moral principles in young people.', vietnameseMeaning: 'Gieo dưỡng các giá trị đạo đức cho trẻ.', example: 'Parents instil values in children through behaviour rather than instruction.', topic: 'Family', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'fam_c17', type: 'collocation', term: 'intergenerational support', collocationType: 'Adj + Noun', definition: 'Help exchanged between older and younger family members.', vietnameseMeaning: 'Sự hỗ trợ qua lại giữa các thế hệ.', example: 'Intergenerational support flows in both directions, though only one direction is usually counted.', topic: 'Family', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'fam_c18', type: 'collocation', term: 'a dysfunctional household', collocationType: 'Adj + Noun', definition: 'A home in which relationships work badly.', vietnameseMeaning: 'Một gia đình rối loạn, thiếu lành mạnh.', example: 'Escaping a dysfunctional household is far harder where housing is scarce.', topic: 'Family', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'fam_c19', type: 'collocation', term: 'the formative years', collocationType: 'Adj + Noun', definition: 'The early period of life in which character develops.', vietnameseMeaning: 'Những năm tháng định hình nhân cách.', example: 'Investment during the formative years yields returns no later intervention can match.', topic: 'Family', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'fam_c20', type: 'collocation', term: 'filial responsibility', collocationType: 'Adj + Noun', definition: 'The duty of children to care for their parents.', vietnameseMeaning: 'Bổn phận hiếu thảo với cha mẹ.', example: 'Filial responsibility remains a legal obligation in several countries, not merely a moral one.', alternative: 'filial piety', topic: 'Family', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'fam_p1', type: 'phrasal_verb', term: 'bring up', partOfSpeech: 'phrasal verb (separable)', definition: 'To care for and educate a child until adulthood.', vietnameseMeaning: 'Nuôi dạy, nuôi nấng (con cái).', example: 'Children brought up in two languages show measurable cognitive advantages.', formalAlternative: 'raise', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['bring up children', 'be brought up in'], academicAlternatives: ['raise', 'rear', 'nurture'] },
    { id: 'fam_p2', type: 'phrasal_verb', term: 'move out', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To leave the family home to live somewhere else.', vietnameseMeaning: 'Dọn ra ở riêng.', example: 'Young adults move out several years later than their parents did, largely because of housing costs.', formalAlternative: 'leave the parental home', topic: 'Family', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['relocate', 'leave home', 'establish an independent household'] },
    { id: 'fam_p3', type: 'phrasal_verb', term: 'take after', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To resemble an older relative in appearance or character.', vietnameseMeaning: 'Giống (bố mẹ, người thân) về ngoại hình hoặc tính cách.', example: 'Children who take after a successful parent face expectations they never chose.', formalAlternative: 'resemble', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['resemble', 'be similar to'] },
    { id: 'fam_p4', type: 'phrasal_verb', term: 'get on with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To have a friendly relationship with someone.', vietnameseMeaning: 'Hoà thuận, quan hệ tốt với ai đó.', example: 'Siblings who get on with each other in childhood usually remain close as adults.', formalAlternative: 'have a good relationship with', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Conversational. In Task 2 prefer "have a good relationship with" or "coexist harmoniously".', academicAlternatives: ['have a good relationship with', 'coexist with'] },
    { id: 'fam_p5', type: 'phrasal_verb', term: 'settle down', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To begin a stable life, often with a partner and children.', vietnameseMeaning: 'Ổn định cuộc sống, yên bề gia thất.', example: 'The age at which people settle down has risen steadily across the developed world.', formalAlternative: 'establish a permanent home', topic: 'Family', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['establish a stable household', 'put down roots'] },

    // Advanced / less common
    { id: 'fam_p6', type: 'phrasal_verb', term: 'fall out with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To quarrel and stop being friendly with someone.', vietnameseMeaning: 'Cãi nhau, giận nhau với ai.', example: 'Relatives who fall out with one another over inheritance rarely reconcile fully.', formalAlternative: 'become estranged from', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'use_with_caution', priority: 'optional', usageWarning: 'Informal. "Become estranged from" is the formal equivalent.', academicAlternatives: ['become estranged from', 'quarrel with'] },
    { id: 'fam_p7', type: 'phrasal_verb', term: 'stand by', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To remain loyal and supportive during difficulty.', vietnameseMeaning: 'Sát cánh, ủng hộ trong lúc khó khăn.', example: 'Families that stand by their members through illness reduce the burden on the state considerably.', formalAlternative: 'support', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['support', 'remain loyal to'] },
    { id: 'fam_p8', type: 'phrasal_verb', term: 'look up to', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To admire and respect someone.', vietnameseMeaning: 'Kính trọng, ngưỡng mộ.', example: 'Children look up to adults who keep promises, not to those who make impressive ones.', formalAlternative: 'admire', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['admire', 'respect', 'revere'] },
    { id: 'fam_p9', type: 'phrasal_verb', term: 'provide for', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To supply someone with what they need to live.', vietnameseMeaning: 'Chu cấp, lo liệu cho ai đó.', example: 'Parents working abroad to provide for their children pay a heavy emotional price.', formalAlternative: 'support financially', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['provide for a family', 'provide for dependants'], academicAlternatives: ['support', 'maintain', 'sustain'] },
    { id: 'fam_p10', type: 'phrasal_verb', term: 'drift apart', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To gradually become less close to someone.', vietnameseMeaning: 'Xa cách dần, mất kết nối theo thời gian.', example: 'Families drift apart when work scatters their members across different cities.', formalAlternative: 'become estranged', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['grow distant', 'become estranged'] },
  ],

  writingPhrases: [
    { id: 'fam_w1', type: 'writing_phrase', term: 'The family remains the first and most influential institution because...', function: 'Introducing an argument', vietnameseMeaning: 'Gia đình vẫn là thiết chế đầu tiên và có ảnh hưởng nhất bởi vì...', example: 'The family remains the first and most influential institution because it shapes children before any other body reaches them.', topic: 'Family', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'fam_w2', type: 'writing_phrase', term: 'Parents spend less time with their children largely because...', function: 'Giving a reason', vietnameseMeaning: 'Cha mẹ dành ít thời gian cho con chủ yếu vì...', example: 'Parents spend less time with their children largely because both now need to work to afford housing.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fam_w3', type: 'writing_phrase', term: 'This shift in family structure can be traced to...', function: 'Explaining a cause', vietnameseMeaning: 'Sự thay đổi cấu trúc gia đình này có thể truy nguyên từ...', example: 'This shift in family structure can be traced to greater economic independence among women.', topic: 'Family', bandLevel: '7+', task: 'both', priority: 'high_value' },
    { id: 'fam_w4', type: 'writing_phrase', term: 'The impact on children is long-lasting:', function: 'Explaining an effect', vietnameseMeaning: 'Tác động lên trẻ em là lâu dài:', example: 'The impact on children is long-lasting: early instability predicts difficulties well into adult life.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'fam_w5', type: 'writing_phrase', term: 'Multigenerational households in Vietnam illustrate this clearly:', function: 'Giving an example', vietnameseMeaning: 'Các gia đình nhiều thế hệ ở Việt Nam minh hoạ rõ điều này:', example: 'Multigenerational households in Vietnam illustrate this clearly: grandparents provide childcare that would otherwise cost a second salary.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fam_w6', type: 'writing_phrase', term: 'Living with the extended family offers the clear advantage of...', function: 'Discussing advantages', vietnameseMeaning: 'Sống cùng đại gia đình mang lại lợi ích rõ rệt là...', example: 'Living with the extended family offers the clear advantage of shared care for both children and the elderly.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'fam_w7', type: 'writing_phrase', term: 'The drawback of such close involvement is that it can...', function: 'Discussing disadvantages', vietnameseMeaning: 'Nhược điểm của sự gắn bó chặt chẽ như vậy là nó có thể...', example: 'The drawback of such close involvement is that it can leave young adults with very little privacy or independence.', topic: 'Family', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'fam_w8', type: 'writing_phrase', term: 'Employers could help by...', function: 'Suggesting a solution', vietnameseMeaning: 'Người sử dụng lao động có thể giúp bằng cách...', example: 'Employers could help by offering genuinely flexible hours rather than the appearance of them.', topic: 'Family', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fam_w9', type: 'writing_phrase', term: 'In my view, no institution can fully replace...', function: 'Expressing an opinion', vietnameseMeaning: 'Theo tôi, không thiết chế nào có thể thay thế hoàn toàn...', example: 'In my view, no institution can fully replace the attention of an adult who knows the child well.', topic: 'Family', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'fam_w10', type: 'writing_phrase', term: 'Traditional households prized obedience; contemporary parents tend to encourage...', function: 'Comparing ideas', vietnameseMeaning: 'Gia đình truyền thống đề cao sự vâng lời; cha mẹ hiện đại có xu hướng khuyến khích...', example: 'Traditional households prized obedience; contemporary parents tend to encourage negotiation and self-expression.', topic: 'Family', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'fam_m1', type: 'common_mistake', incorrect: 'My family are five people.', correct: 'There are five people in my family.', explanation: 'A family is not equal to a number of people. Use "There are X people in my family" or "My family has five members".', topic: 'Family', priority: 'must_learn' },
    { id: 'fam_m2', type: 'common_mistake', incorrect: 'She got married with a colleague last year.', correct: 'She got married to a colleague last year.', explanation: 'The preposition after "married" is "to". "Married with" is only correct in "married with two children", meaning they have children.', topic: 'Family', priority: 'must_learn' },
    { id: 'fam_m3', type: 'common_mistake', incorrect: 'Parents should take care for their children.', correct: 'Parents should take care of their children.', explanation: 'The fixed phrase is "take care of". "Care for" is also correct on its own, but "take care for" mixes the two.', topic: 'Family', priority: 'must_learn' },
    { id: 'fam_m4', type: 'common_mistake', incorrect: 'Many childrens grow up without a father.', correct: 'Many children grow up without a father.', explanation: '"Children" is already the plural of "child". Other irregular plurals worth remembering: women, men, people.', topic: 'Family', priority: 'must_learn' },
    { id: 'fam_m5', type: 'common_mistake', incorrect: 'Parents should spend more time to their children.', correct: 'Parents should spend more time with their children.', explanation: 'You spend time WITH a person and time ON an activity. "Time to" is a direct translation that does not exist in English.', topic: 'Family', priority: 'must_learn' },
  ],

  learnFirst: {
    vocabulary: ['fam_v1', 'fam_v4', 'fam_v10', 'fam_v11', 'fam_v12', 'fam_v13', 'fam_v20', 'fam_v21', 'fam_v25', 'fam_v28'],
    collocations: ['fam_c1', 'fam_c3', 'fam_c9', 'fam_c13', 'fam_c19'],
    phrasalVerbs: ['fam_p1', 'fam_p9', 'fam_p8'],
    writingPhrases: ['fam_w1', 'fam_w7', 'fam_w9'],
  },
}
