import type { TopicData } from '../types'

export const FOOD: TopicData = {
  topic: 'Food',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'fod_v1', type: 'vocabulary', term: 'nutrition', pronunciation: '/njuˈtrɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'The process of taking in food and the substances the body needs from it.', vietnameseMeaning: 'Dinh dưỡng.', example: 'Poor nutrition in the first two years of life has effects that education can never fully undo.', writingTip: 'Uncountable. The adjective is "nutritious" (food) or "nutritional" (value, content).', topic: 'Food', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['poor nutrition', 'proper nutrition', 'nutritional value', 'nutrition education'], wordFamily: ['nutritious (adj)', 'nutrient (n)', 'nutritional (adj)'], priority: 'must_learn' },
    { id: 'fod_v2', type: 'vocabulary', term: 'diet', pronunciation: '/ˈdaɪət/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'The kinds of food a person or group habitually eats.', vietnameseMeaning: 'Chế độ ăn uống, khẩu phần ăn.', example: 'A diet built around fresh vegetables and whole grains costs less than most people assume.', writingTip: '"A balanced diet", "a healthy diet". "On a diet" means restricting food to lose weight — a different sense.', topic: 'Food', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a balanced diet', 'a healthy diet', 'a poor diet', 'dietary habits'], wordFamily: ['dietary (adj)', 'dietician (n)'], priority: 'must_learn' },
    { id: 'fod_v3', type: 'vocabulary', term: 'obesity', pronunciation: '/əʊˈbiːsəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The condition of being severely overweight in a way that damages health.', vietnameseMeaning: 'Bệnh béo phì.', example: 'Childhood obesity has risen fastest in exactly the countries where processed food is cheapest.', writingTip: 'Uncountable and medical in tone. Far more appropriate in essays than "being fat".', topic: 'Food', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['childhood obesity', 'rising obesity rates', 'tackle obesity', 'the obesity epidemic'], wordFamily: ['obese (adj)'], priority: 'must_learn' },
    { id: 'fod_v4', type: 'vocabulary', term: 'ingredient', pronunciation: '/ɪnˈɡriːdiənt/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'One of the foods used to make a particular dish.', vietnameseMeaning: 'Nguyên liệu, thành phần món ăn.', example: 'Ready meals contain ingredients that no domestic kitchen would ever stock.', writingTip: 'Countable. "Fresh ingredients" and "locally sourced ingredients" are natural collocations.', topic: 'Food', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['fresh ingredients', 'local ingredients', 'artificial ingredients'], priority: 'high_value' },
    { id: 'fod_v5', type: 'vocabulary', term: 'agriculture', pronunciation: '/ˈæɡrɪkʌltʃə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The practice of farming, including growing crops and raising animals.', vietnameseMeaning: 'Nông nghiệp.', example: 'Agriculture uses roughly seventy per cent of the world’s fresh water.', writingTip: 'Uncountable. The adjective "agricultural" is equally common: agricultural land, agricultural output.', topic: 'Food', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['modern agriculture', 'intensive agriculture', 'agricultural land', 'agricultural output'], wordFamily: ['agricultural (adj)'], priority: 'must_learn' },
    { id: 'fod_v6', type: 'vocabulary', term: 'harvest', pronunciation: '/ˈhɑːvɪst/', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'The gathering of crops; the crops gathered.', vietnameseMeaning: 'Vụ thu hoạch; thu hoạch mùa màng.', example: 'A single failed harvest can push millions of subsistence farmers into debt.', writingTip: '"A good/poor harvest", "harvest failure". Useful in essays on climate and food supply.', topic: 'Food', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a good harvest', 'harvest failure', 'harvest crops'], priority: 'high_value' },
    { id: 'fod_v7', type: 'vocabulary', term: 'hunger', pronunciation: '/ˈhʌŋɡə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'The state of not having enough food to eat.', vietnameseMeaning: 'Nạn đói, tình trạng thiếu ăn.', example: 'World hunger is not primarily a problem of production; enough food is grown to feed everyone.', writingTip: 'Uncountable. "Eradicate", "reduce" and "combat" hunger are the standard verbs.', topic: 'Food', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['world hunger', 'combat hunger', 'eradicate hunger', 'go hungry'], wordFamily: ['hungry (adj)'], priority: 'must_learn' },
    { id: 'fod_v8', type: 'vocabulary', term: 'organic', pronunciation: '/ɔːˈɡænɪk/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Grown without synthetic chemicals or artificial fertilisers.', vietnameseMeaning: 'Hữu cơ, canh tác tự nhiên không dùng hoá chất.', example: 'Organic produce is better for soil health, but yields per hectare are typically lower.', writingTip: 'A concrete example for sustainability arguments. Present the trade-off rather than only the benefit.', topic: 'Food', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['organic farming', 'organic produce', 'organic food'], priority: 'high_value' },
    { id: 'fod_v9', type: 'vocabulary', term: 'consume', pronunciation: '/kənˈsjuːm/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To eat or drink something; to use up a resource.', vietnameseMeaning: 'Tiêu thụ, sử dụng, ăn uống.', example: 'People in wealthy countries consume roughly twice as much meat as nutritionists recommend.', writingTip: 'More formal than "eat" and works for both food and resources. "Consumption" is the noun.', topic: 'Food', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['consume less meat', 'food consumption', 'consume resources'], wordFamily: ['consumption (n)', 'consumer (n)'], priority: 'must_learn' },
    { id: 'fod_v10', type: 'vocabulary', term: 'fast food', pronunciation: '/ˌfɑːst ˈfuːd/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Food prepared and served very quickly, typically high in fat and salt.', vietnameseMeaning: 'Thức ăn nhanh.', example: 'Fast food outlets cluster around schools precisely because that is where the customers are.', writingTip: 'Uncountable: "fast food is", never "fast foods". A staple of health and food essays.', topic: 'Food', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['fast food outlets', 'fast food chains', 'rely on fast food'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'fod_v11', type: 'vocabulary', term: 'malnutrition', pronunciation: '/ˌmælnjuˈtrɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Poor health caused by not eating enough, or by an unbalanced diet.', vietnameseMeaning: 'Suy dinh dưỡng.', example: 'Malnutrition and obesity increasingly coexist within the same households, since cheap food is often calorie-rich and nutrient-poor.', writingTip: 'Note that malnutrition includes overnutrition, not only hunger — that nuance is worth making.', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['chronic malnutrition', 'suffer from malnutrition', 'child malnutrition'], wordFamily: ['malnourished (adj)'], priority: 'must_learn' },
    { id: 'fod_v12', type: 'vocabulary', term: 'food security', pronunciation: '/fuːd sɪˈkjʊərəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Reliable access for all people to sufficient, safe and nutritious food.', vietnameseMeaning: 'An ninh lương thực.', example: 'Food security depends less on total production than on income, storage and functioning transport.', writingTip: 'The central policy term of this topic. Its opposite is "food insecurity", not "food danger".', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['improve food security', 'threaten food security', 'global food security'], antonym: 'food insecurity', priority: 'must_learn' },
    { id: 'fod_v13', type: 'vocabulary', term: 'processed food', pronunciation: '/ˈprəʊsest fuːd/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Food that has been industrially altered, often with added sugar, salt or fat.', vietnameseMeaning: 'Thực phẩm chế biến sẵn.', example: 'Ultra-processed food now accounts for more than half the calories consumed in several wealthy countries.', writingTip: '"Ultra-processed" is the precise technical upgrade and reads as genuinely informed.', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['heavily processed food', 'ultra-processed food', 'reduce processed food'], antonym: 'fresh produce', priority: 'must_learn' },
    { id: 'fod_v14', type: 'vocabulary', term: 'food waste', pronunciation: '/fuːd weɪst/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Edible food that is thrown away rather than eaten.', vietnameseMeaning: 'Lãng phí thực phẩm, thức ăn bị vứt bỏ.', example: 'Roughly a third of all food produced is lost or wasted before it reaches anyone’s plate.', writingTip: 'Uncountable. "Reduce" and "cut" food waste are the natural verbs.', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['reduce food waste', 'household food waste', 'tackle food waste'], priority: 'must_learn' },
    { id: 'fod_v15', type: 'vocabulary', term: 'sustainable agriculture', pronunciation: '/səˈsteɪnəbl ˈæɡrɪkʌltʃə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Farming that maintains soil, water and biodiversity for future use.', vietnameseMeaning: 'Nông nghiệp bền vững.', example: 'Sustainable agriculture usually means accepting slightly lower yields in exchange for soil that lasts.', writingTip: 'A ready-made phrase that lets you connect food to environment in a single move.', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['promote sustainable agriculture', 'sustainable farming practices'], priority: 'must_learn' },
    { id: 'fod_v16', type: 'vocabulary', term: 'GMO', pronunciation: '/ˌdʒiː em ˈəʊ/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'A genetically modified organism, whose DNA has been deliberately altered.', vietnameseMeaning: 'Sinh vật biến đổi gen.', example: 'GMOs remain banned in several markets despite decades of evidence about their safety.', writingTip: 'Write "genetically modified crops" in full at least once before using the abbreviation.', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['GMO crops', 'genetically modified food', 'ban GMOs'], priority: 'high_value' },
    { id: 'fod_v17', type: 'vocabulary', term: 'famine', pronunciation: '/ˈfæmɪn/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'An extreme shortage of food across a whole region.', vietnameseMeaning: 'Nạn đói trên diện rộng.', example: 'Modern famines are almost always caused by conflict or policy rather than by crop failure alone.', writingTip: 'Countable: "a famine in the region". Stronger and more specific than "hunger".', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['widespread famine', 'avert famine', 'famine relief'], priority: 'high_value' },
    { id: 'fod_v18', type: 'vocabulary', term: 'subsistence farming', pronunciation: '/səbˈsɪstəns ˈfɑːmɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Farming that produces just enough food for the farmer’s own family.', vietnameseMeaning: 'Nông nghiệp tự cung tự cấp.', example: 'Households dependent on subsistence farming have no buffer whatsoever against a single bad season.', writingTip: 'A precise term that lets you explain rural vulnerability without vague generalisation.', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['subsistence farmers', 'rely on subsistence farming'], antonym: 'commercial farming', priority: 'optional' },
    { id: 'fod_v19', type: 'vocabulary', term: 'additive', pronunciation: '/ˈædətɪv/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A substance added to food to preserve it or improve its taste or appearance.', vietnameseMeaning: 'Phụ gia thực phẩm.', example: 'Labelling rules require additives to be listed, though few shoppers can interpret the names.', writingTip: 'Countable. "Artificial additives" and "food additives" are the standard pairings.', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['food additives', 'artificial additives', 'chemical additives'], priority: 'high_value' },
    { id: 'fod_v20', type: 'vocabulary', term: 'staple', pronunciation: '/ˈsteɪpl/', partOfSpeech: 'noun (countable) / adjective', cefrLevel: 'B2', definition: 'A basic food that forms the main part of a population’s diet.', vietnameseMeaning: 'Lương thực chính, thực phẩm chủ yếu.', example: 'Rice, wheat and maize are the staples on which most of humanity depends.', writingTip: '"Staple food" or "staple crop". A precise, useful noun in global food essays.', topic: 'Food', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['staple food', 'staple crop', 'a dietary staple'], priority: 'high_value' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'fod_v21', type: 'vocabulary', term: 'food system', pronunciation: '/fuːd ˈsɪstəm/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'The whole network of growing, processing, distributing and consuming food.', vietnameseMeaning: 'Hệ thống lương thực (từ sản xuất đến tiêu dùng).', example: 'Reforming the food system means addressing farming, transport, retail and waste together rather than separately.', writingTip: 'Thinking in systems rather than isolated problems is exactly what a Band 8 answer does.', topic: 'Food', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the global food system', 'reform the food system', 'a resilient food system'], priority: 'must_learn' },
    { id: 'fod_v22', type: 'vocabulary', term: 'food miles', pronunciation: '/fuːd maɪlz/', partOfSpeech: 'noun (plural)', cefrLevel: 'C1', definition: 'The distance food travels from where it is produced to where it is eaten.', vietnameseMeaning: 'Quãng đường vận chuyển thực phẩm.', example: 'Reducing food miles helps, though how food is grown usually matters more than how far it travels.', writingTip: 'A concrete, current concept. The qualification in the example is exactly the nuance examiners reward.', topic: 'Food', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['reduce food miles', 'high food miles'], priority: 'high_value' },
    { id: 'fod_v23', type: 'vocabulary', term: 'food sovereignty', pronunciation: '/fuːd ˈsɒvrənti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'The right of communities to control their own food production and policy.', vietnameseMeaning: 'Chủ quyền lương thực của cộng đồng.', example: 'Advocates of food sovereignty argue that importing cheap grain destroys the local farming it undercuts.', writingTip: 'Distinguish from food security: sovereignty concerns who decides, security concerns whether people eat.', topic: 'Food', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['the food sovereignty movement', 'the principle of food sovereignty', 'advocate food sovereignty'], priority: 'optional' },
    { id: 'fod_v24', type: 'vocabulary', term: 'agroecology', pronunciation: '/ˌæɡrəʊɪˈkɒlədʒi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'Farming that works with natural ecosystems rather than overriding them.', vietnameseMeaning: 'Nông nghiệp sinh thái.', example: 'Agroecology has produced yields comparable to conventional farming on smallholdings in several trials.', writingTip: 'A specialist term — use it once with brief explanation rather than assuming familiarity.', topic: 'Food', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['agroecological practices', 'agroecological farming'], priority: 'optional' },
    { id: 'fod_v25', type: 'vocabulary', term: 'perishable', pronunciation: '/ˈperɪʃəbl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Likely to decay or spoil quickly.', vietnameseMeaning: 'Dễ hỏng, mau ôi thiu.', example: 'Without refrigerated transport, perishable produce simply cannot reach distant markets.', writingTip: 'Explains a genuine mechanism behind food loss in poorer countries. Precise and useful.', topic: 'Food', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['perishable goods', 'highly perishable', 'perishable produce'], wordFamily: ['perish (v)'], priority: 'high_value' },
    { id: 'fod_v26', type: 'vocabulary', term: 'dietary', pronunciation: '/ˈdaɪətəri/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Relating to what a person or population eats.', vietnameseMeaning: 'Thuộc về chế độ ăn uống.', example: 'Dietary guidelines have changed repeatedly, which has understandably eroded public confidence in them.', writingTip: '"Dietary habits", "dietary guidelines", "dietary requirements" — all high-value phrases.', topic: 'Food', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['dietary habits', 'dietary guidelines', 'dietary requirements', 'dietary change'], priority: 'must_learn' },
    { id: 'fod_v27', type: 'vocabulary', term: 'yield', pronunciation: '/jiːld/', partOfSpeech: 'noun (countable) / verb', cefrLevel: 'C1', definition: 'The quantity of crop produced from a given area of land.', vietnameseMeaning: 'Năng suất, sản lượng thu hoạch.', example: 'Crop yields have tripled since 1960, largely through fertiliser rather than through additional land.', writingTip: 'Essential for Task 1 charts on agriculture: "yields rose steadily", "average yield per hectare".', topic: 'Food', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['crop yields', 'increase yields', 'yield per hectare', 'declining yields'], priority: 'must_learn' },
    { id: 'fod_v28', type: 'vocabulary', term: 'exacerbate', pronunciation: '/ɪɡˈzæsəbeɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To make a bad situation considerably worse.', vietnameseMeaning: 'Làm trầm trọng thêm.', example: 'Export bans imposed during shortages exacerbate the very price rises they are meant to prevent.', writingTip: 'A powerful verb for cause-and-effect paragraphs. Pair with problems, not with people.', topic: 'Food', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['exacerbate shortages', 'exacerbate the crisis', 'further exacerbate'], alternatives: ['aggravate', 'worsen', 'compound'], priority: 'must_learn' },
    { id: 'fod_v29', type: 'vocabulary', term: 'subsidise', pronunciation: '/ˈsʌbsɪdaɪz/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To pay part of the cost of something so that it is cheaper.', vietnameseMeaning: 'Trợ giá, trợ cấp.', example: 'Governments that subsidise sugar and grain while taxing vegetables should not be surprised by the resulting diets.', writingTip: 'A sharp, evidence-based argument for food policy essays. The noun is "subsidy".', topic: 'Food', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['subsidise farmers', 'agricultural subsidies', 'heavily subsidised'], wordFamily: ['subsidy (n)'], priority: 'must_learn' },
    { id: 'fod_v30', type: 'vocabulary', term: 'affluent', pronunciation: '/ˈæfluənt/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Having a great deal of money; wealthy.', vietnameseMeaning: 'Giàu có, khá giả.', example: 'Diets in affluent societies have shifted towards meat at precisely the moment the climate can least afford it.', writingTip: 'A refined alternative to "rich" when describing countries, households or societies.', topic: 'Food', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['affluent societies', 'affluent households', 'increasingly affluent'], antonym: 'impoverished', wordFamily: ['affluence (n)'], priority: 'high_value' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'fod_c1', type: 'collocation', term: 'a balanced diet', collocationType: 'Adj + Noun', definition: 'A diet containing the right variety and quantity of foods.', vietnameseMeaning: 'Chế độ ăn cân bằng.', example: 'A balanced diet is far cheaper to achieve than the supplement industry would have consumers believe.', topic: 'Food', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'fod_c2', type: 'collocation', term: 'eating habits', collocationType: 'Noun + Noun', definition: 'The regular patterns of what and how a person eats.', vietnameseMeaning: 'Thói quen ăn uống.', example: 'Eating habits formed in childhood are remarkably difficult to change in adulthood.', alternative: 'dietary habits', topic: 'Food', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'fod_c3', type: 'collocation', term: 'junk food', collocationType: 'Noun + Noun', definition: 'Food with high calories and little nutritional value.', vietnameseMeaning: 'Đồ ăn vặt kém dinh dưỡng.', example: 'Restricting junk food advertising to children is one of the few measures with clear evidence behind it.', topic: 'Food', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'Uncountable and slightly informal, but standard in academic writing on public health.' },
    { id: 'fod_c4', type: 'collocation', term: 'fresh produce', collocationType: 'Adj + Noun', definition: 'Fruit and vegetables that have not been processed.', vietnameseMeaning: 'Nông sản tươi.', example: 'Neighbourhoods with no shop selling fresh produce are known as food deserts.', topic: 'Food', bandLevel: '5-6', task: 'both', priority: 'must_learn', writingTip: '"Produce" here is an uncountable noun stressed on the first syllable: /ˈprɒdjuːs/.' },
    { id: 'fod_c5', type: 'collocation', term: 'grow crops', collocationType: 'Verb + Noun', definition: 'To cultivate plants for food.', vietnameseMeaning: 'Trồng trọt, canh tác cây lương thực.', example: 'Farmers who grow crops for export are exposed to price swings entirely outside their control.', topic: 'Food', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'fod_c6', type: 'collocation', term: 'food shortage', collocationType: 'Noun + Noun', definition: 'A situation in which there is not enough food available.', vietnameseMeaning: 'Tình trạng thiếu lương thực.', example: 'Food shortages rarely result from a single cause; drought, conflict and poor storage usually combine.', topic: 'Food', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'fod_c7', type: 'collocation', term: 'put on weight', collocationType: 'Verb phrase', definition: 'To become heavier.', vietnameseMeaning: 'Tăng cân.', example: 'People put on weight gradually, which is precisely why the trend is so easy to ignore.', alternative: 'gain weight', topic: 'Food', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'fod_c8', type: 'collocation', term: 'food safety', collocationType: 'Noun + Noun', definition: 'The handling and preparation of food so that it does not cause illness.', vietnameseMeaning: 'An toàn thực phẩm.', example: 'Food safety inspections are among the cheapest public health measures available to any government.', topic: 'Food', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },

    // Advanced (Band 6-7)
    { id: 'fod_c9', type: 'collocation', term: 'tackle the obesity epidemic', collocationType: 'Verb + Noun', definition: 'To take action against widespread severe overweight.', vietnameseMeaning: 'Đối phó với đại dịch béo phì.', example: 'Tackling the obesity epidemic requires changing what is available and affordable, not merely what is advised.', topic: 'Food', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fod_c10', type: 'collocation', term: 'reduce food waste', collocationType: 'Verb + Noun', definition: 'To decrease the amount of edible food thrown away.', vietnameseMeaning: 'Giảm lãng phí thực phẩm.', example: 'Supermarkets can reduce food waste simply by abandoning cosmetic standards for fruit and vegetables.', topic: 'Food', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fod_c11', type: 'collocation', term: 'suffer from malnutrition', collocationType: 'Verb + Noun', definition: 'To experience ill health caused by an inadequate diet.', vietnameseMeaning: 'Bị suy dinh dưỡng.', example: 'Children who suffer from malnutrition before the age of two rarely make up the lost growth.', topic: 'Food', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fod_c12', type: 'collocation', term: 'intensive farming', collocationType: 'Adj + Noun', definition: 'Agriculture that maximises output from a given area using heavy inputs.', vietnameseMeaning: 'Canh tác thâm canh.', example: 'Intensive farming feeds far more people per hectare while steadily degrading the soil that makes it possible.', topic: 'Food', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'fod_c13', type: 'collocation', term: 'meet growing demand', collocationType: 'Verb + Noun', definition: 'To supply enough to satisfy increasing needs.', vietnameseMeaning: 'Đáp ứng nhu cầu ngày càng tăng.', example: 'Producing enough protein to meet growing demand without clearing more forest is the central agricultural challenge.', topic: 'Food', bandLevel: '6-7', task: 'both', priority: 'must_learn' },
    { id: 'fod_c14', type: 'collocation', term: 'impose a sugar tax', collocationType: 'Verb + Noun', definition: 'To place a levy on sugary products in order to reduce consumption.', vietnameseMeaning: 'Áp thuế đối với đồ uống có đường.', example: 'Countries that imposed a sugar tax saw manufacturers reformulate products rather than lose sales.', topic: 'Food', bandLevel: '6-7', task: 'task2', priority: 'high_value', writingTip: 'A specific, real policy example — far stronger than a vague call for government action.' },
    { id: 'fod_c15', type: 'collocation', term: 'locally sourced food', collocationType: 'Adv + Verb + Noun', definition: 'Food produced near where it is sold and eaten.', vietnameseMeaning: 'Thực phẩm có nguồn gốc địa phương.', example: 'Restaurants advertising locally sourced food have multiplied, though verification is rarely rigorous.', topic: 'Food', bandLevel: '6-7', task: 'task2', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'fod_c16', type: 'collocation', term: 'ensure global food security', collocationType: 'Verb + Noun', definition: 'To guarantee that everyone has reliable access to sufficient food.', vietnameseMeaning: 'Bảo đảm an ninh lương thực toàn cầu.', example: 'Ensuring global food security in a warming climate will depend on distribution as much as on yields.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'fod_c17', type: 'collocation', term: 'shift towards plant-based diets', collocationType: 'Noun + Prep + Noun', definition: 'A move away from meat towards food derived from plants.', vietnameseMeaning: 'Xu hướng chuyển sang chế độ ăn từ thực vật.', example: 'A modest shift towards plant-based diets in wealthy countries would free up enormous quantities of farmland.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'fod_c18', type: 'collocation', term: 'place a strain on agricultural resources', collocationType: 'Verb + Noun', definition: 'To put pressure on the land, water and inputs farming depends on.', vietnameseMeaning: 'Gây áp lực lên các nguồn lực nông nghiệp.', example: 'Rising meat consumption places a strain on agricultural resources far out of proportion to the calories it provides.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'fod_c19', type: 'collocation', term: 'nutritionally inadequate', collocationType: 'Adv + Adj', definition: 'Not providing the nutrients a person needs.', vietnameseMeaning: 'Không đủ dinh dưỡng.', example: 'A diet can be calorie-dense and nutritionally inadequate at the same time.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'fod_c20', type: 'collocation', term: 'address the root causes of hunger', collocationType: 'Verb + Noun', definition: 'To deal with the fundamental reasons people go without food.', vietnameseMeaning: 'Giải quyết nguyên nhân gốc rễ của nạn đói.', example: 'Food aid saves lives, but only functioning markets and stable governments address the root causes of hunger.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'fod_p1', type: 'phrasal_verb', term: 'cut down on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To consume less of something.', vietnameseMeaning: 'Cắt giảm, ăn uống ít đi.', example: 'Health campaigns urging people to cut down on salt have achieved less than quietly reformulating products.', formalAlternative: 'reduce', topic: 'Food', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'must_learn', usageWarning: 'Fairly informal. Prefer "reduce", "limit" or "moderate" in a Task 2 essay.', academicAlternatives: ['reduce', 'limit', 'moderate', 'curtail'] },
    { id: 'fod_p2', type: 'phrasal_verb', term: 'give up', partOfSpeech: 'phrasal verb (separable)', definition: 'To stop consuming something completely.', vietnameseMeaning: 'Từ bỏ hoàn toàn (một loại thực phẩm).', example: 'Asking people to give up meat entirely has proved far less effective than asking them to eat less of it.', formalAlternative: 'abstain from', topic: 'Food', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['abstain from', 'forgo', 'renounce'] },
    { id: 'fod_p3', type: 'phrasal_verb', term: 'eat out', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To have a meal in a restaurant rather than at home.', vietnameseMeaning: 'Ăn ngoài, ăn tại nhà hàng.', example: 'Households that eat out several times a week consume considerably more salt and sugar without realising it.', formalAlternative: 'dine out', topic: 'Food', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['dine out', 'eat in restaurants'] },
    { id: 'fod_p4', type: 'phrasal_verb', term: 'run out of', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To exhaust the supply of something.', vietnameseMeaning: 'Cạn kiệt, hết sạch (nguồn cung).', example: 'Regions that run out of stored grain before the next harvest face a predictable annual crisis.', formalAlternative: 'exhaust supplies of', topic: 'Food', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['exhaust', 'deplete', 'be depleted of'] },
    { id: 'fod_p5', type: 'phrasal_verb', term: 'throw away', partOfSpeech: 'phrasal verb (separable)', definition: 'To dispose of something as rubbish.', vietnameseMeaning: 'Vứt bỏ, bỏ đi.', example: 'Households throw away a substantial proportion of the food they buy, most of it still edible.', formalAlternative: 'discard', topic: 'Food', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'must_learn', usageWarning: 'Conversational. "Discard" or "dispose of" reads better in an academic essay.', academicAlternatives: ['discard', 'dispose of'] },

    // Advanced / less common
    { id: 'fod_p6', type: 'phrasal_verb', term: 'live off', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To survive by eating or depending on a particular thing.', vietnameseMeaning: 'Sống nhờ vào, chỉ ăn mỗi (loại thực phẩm nào đó).', example: 'Communities that live off a single staple crop are acutely vulnerable to any disease affecting it.', formalAlternative: 'subsist on', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['subsist on', 'depend on', 'be sustained by'] },
    { id: 'fod_p7', type: 'phrasal_verb', term: 'stem from', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To originate from a particular cause.', vietnameseMeaning: 'Bắt nguồn từ, xuất phát từ.', example: 'Much modern malnutrition stems from poverty rather than from any absolute shortage of food.', formalAlternative: 'originate from', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', academicAlternatives: ['originate from', 'arise from', 'result from'] },
    { id: 'fod_p8', type: 'phrasal_verb', term: 'phase out', partOfSpeech: 'phrasal verb (separable)', definition: 'To discontinue something gradually over a planned period.', vietnameseMeaning: 'Loại bỏ dần theo lộ trình.', example: 'Several countries have begun to phase out antibiotics used purely to accelerate livestock growth.', formalAlternative: 'discontinue gradually', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['phase out subsidies', 'be phased out'], academicAlternatives: ['discontinue', 'withdraw', 'eliminate progressively'] },
    { id: 'fod_p9', type: 'phrasal_verb', term: 'do without', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To manage despite not having something.', vietnameseMeaning: 'Xoay xở khi không có, đành thiếu.', example: 'Families on the lowest incomes routinely do without fresh vegetables in the final week of the month.', formalAlternative: 'manage without', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['manage without', 'forgo', 'be deprived of'] },
    { id: 'fod_p10', type: 'phrasal_verb', term: 'go off', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To become unfit to eat; to spoil.', vietnameseMeaning: 'Bị ôi thiu, hỏng (thực phẩm).', example: 'Produce that goes off during transport represents a substantial share of total food loss.', formalAlternative: 'spoil', topic: 'Food', bandLevel: '6-7', task: 'task2', writingSuitability: 'use_with_caution', priority: 'optional', usageWarning: 'British and conversational. Use "spoil", "perish" or "deteriorate" in a formal essay.', academicAlternatives: ['spoil', 'perish', 'deteriorate'] },
  ],

  writingPhrases: [
    { id: 'fod_w1', type: 'writing_phrase', term: 'The paradox at the centre of the global food debate is that...', function: 'Introducing an argument', vietnameseMeaning: 'Nghịch lý trung tâm của cuộc tranh luận về lương thực toàn cầu là...', example: 'The paradox at the centre of the global food debate is that hunger and obesity are rising simultaneously.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'fod_w2', type: 'writing_phrase', term: 'People choose processed food largely because...', function: 'Giving a reason', vietnameseMeaning: 'Người ta chọn thực phẩm chế biến sẵn chủ yếu vì...', example: 'People choose processed food largely because it is cheap, filling and requires no time to prepare.', topic: 'Food', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fod_w3', type: 'writing_phrase', term: 'This deterioration in diet can be traced to...', function: 'Explaining a cause', vietnameseMeaning: 'Sự suy giảm chất lượng bữa ăn này có thể truy nguyên từ...', example: 'This deterioration in diet can be traced to longer working hours as much as to any failure of willpower.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'fod_w4', type: 'writing_phrase', term: 'The public health consequences of this are severe, since...', function: 'Explaining an effect', vietnameseMeaning: 'Hậu quả đối với sức khoẻ cộng đồng là nghiêm trọng, bởi vì...', example: 'The public health consequences of this are severe, since diet-related illness now consumes a growing share of every health budget.', topic: 'Food', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fod_w5', type: 'writing_phrase', term: 'Mexico’s experience is revealing here:', function: 'Giving an example', vietnameseMeaning: 'Kinh nghiệm của Mexico rất đáng chú ý ở đây:', example: 'Mexico’s experience is revealing here: a tax on sugary drinks reduced purchases measurably within two years.', topic: 'Food', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'fod_w6', type: 'writing_phrase', term: 'The clearest advantage of shorter supply chains is that...', function: 'Discussing advantages', vietnameseMeaning: 'Ưu điểm rõ nhất của chuỗi cung ứng ngắn là...', example: 'The clearest advantage of shorter supply chains is that far less produce spoils before it reaches a kitchen.', topic: 'Food', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'fod_w7', type: 'writing_phrase', term: 'The difficulty with relying on individual choice is that...', function: 'Discussing disadvantages', vietnameseMeaning: 'Khó khăn của việc trông cậy vào lựa chọn cá nhân là...', example: 'The difficulty with relying on individual choice is that people cannot choose foods their neighbourhood does not sell.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'fod_w8', type: 'writing_phrase', term: 'A more effective intervention would be to change what is affordable rather than to...', function: 'Suggesting a solution', vietnameseMeaning: 'Một biện pháp hiệu quả hơn là thay đổi những gì người dân có thể mua được thay vì...', example: 'A more effective intervention would be to change what is affordable rather than to lecture households about willpower.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'fod_w9', type: 'writing_phrase', term: 'I would contend that responsibility for diet lies less with consumers than with...', function: 'Expressing an opinion', vietnameseMeaning: 'Tôi cho rằng trách nhiệm về chế độ ăn thuộc về người tiêu dùng ít hơn là về...', example: 'I would contend that responsibility for diet lies less with consumers than with the companies and policies that shape what is available.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'fod_w10', type: 'writing_phrase', term: 'Educating individuals changes behaviour slowly, whereas regulating the food industry...', function: 'Comparing ideas', vietnameseMeaning: 'Giáo dục cá nhân thay đổi hành vi chậm chạp, trong khi quản lý ngành thực phẩm...', example: 'Educating individuals changes behaviour slowly, whereas regulating the food industry alters millions of diets at once.', topic: 'Food', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'fod_m1', type: 'common_mistake', incorrect: 'Fast foods are very popular among young people.', correct: 'Fast food is very popular among young people.', explanation: '"Food" is uncountable in this general sense, so "fast food" takes a singular verb and no plural -s. The same applies to "junk food" and "street food".', topic: 'Food', priority: 'must_learn' },
    { id: 'fod_m2', type: 'common_mistake', incorrect: 'Eating too much sugar makes people become obesity.', correct: 'Excessive sugar consumption contributes to obesity.', explanation: '"Obesity" is a noun, so it cannot follow "become" as if it were an adjective — either "become obese" or "contribute to obesity". "Contribute to" is also more accurate than the absolute "makes".', topic: 'Food', priority: 'must_learn' },
    { id: 'fod_m3', type: 'common_mistake', incorrect: 'The government should raise people’s awareness about healthy food.', correct: 'The government should raise public awareness of healthy eating.', explanation: 'The standard collocation is "raise awareness of". "Public awareness" is also more natural than "people’s awareness" in academic writing.', topic: 'Food', priority: 'high_value' },
    { id: 'fod_m4', type: 'common_mistake', incorrect: 'Vietnamese food is more delicious than the other countries.', correct: 'Vietnamese food is more flavourful than that of many other countries.', explanation: 'A comparison must be between comparable things — food with food, so use "that of". "Delicious" is also rather subjective for an academic essay.', topic: 'Food', priority: 'must_learn' },
    { id: 'fod_m5', type: 'common_mistake', incorrect: 'Many people in poor countries have not enough foods to eat.', correct: 'Many people in low-income countries do not have enough food.', explanation: 'Three fixes: "food" is uncountable; negation of "have" requires the auxiliary "do not"; and "low-income countries" is the accepted term in academic writing.', topic: 'Food', priority: 'must_learn' },
  ],

  learnFirst: {
    vocabulary: ['fod_v1', 'fod_v3', 'fod_v11', 'fod_v12', 'fod_v13', 'fod_v14', 'fod_v15', 'fod_v21', 'fod_v26', 'fod_v29'],
    collocations: ['fod_c1', 'fod_c9', 'fod_c10', 'fod_c16', 'fod_c20'],
    phrasalVerbs: ['fod_p7', 'fod_p8', 'fod_p4'],
    writingPhrases: ['fod_w1', 'fod_w7', 'fod_w8'],
  },
}
