import type { TopicData } from '../types'

export const GLOBALISATION: TopicData = {
  topic: 'Globalisation',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'glb_v1', type: 'vocabulary', term: 'globalisation', pronunciation: '/ˌɡləʊbəlaɪˈzeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The process by which countries become more closely connected through trade, travel and communication.', vietnameseMeaning: 'Toàn cầu hoá.', example: 'Globalisation has lifted hundreds of millions out of poverty while leaving certain regions permanently behind.', writingTip: 'Uncountable and takes no article in general statements: "Globalisation has changed...", not "The globalisation".', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the process of globalisation', 'economic globalisation', 'the effects of globalisation'], wordFamily: ['global (adj)', 'globalise (v)', 'globally (adv)'], priority: 'must_learn' },
    { id: 'glb_v2', type: 'vocabulary', term: 'trade', pronunciation: '/treɪd/', partOfSpeech: 'noun (uncountable) / verb', cefrLevel: 'B1', definition: 'The buying and selling of goods and services, especially between countries.', vietnameseMeaning: 'Thương mại, giao thương, mua bán.', example: 'International trade allows small countries to specialise in what they produce best.', writingTip: 'Uncountable in this sense. "Trade with" a country, "trade in" a product.', topic: 'Globalisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['international trade', 'free trade', 'trade barriers', 'trade agreement'], wordFamily: ['trader (n)', 'trading (n)'], priority: 'must_learn' },
    { id: 'glb_v3', type: 'vocabulary', term: 'export', pronunciation: '/ˈekspɔːt/ (n), /ɪkˈspɔːt/ (v)', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'To sell goods to another country; goods sold abroad.', vietnameseMeaning: 'Xuất khẩu; hàng xuất khẩu.', example: 'Vietnam’s exports of electronics have grown faster than those of any neighbouring economy.', writingTip: 'The stress moves: EXport (noun), exPORT (verb). Very common in Task 1 trade charts.', topic: 'Globalisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['export goods', 'export markets', 'exports rose', 'export earnings'], antonym: 'import', wordFamily: ['exporter (n)', 'exportation (n)'], priority: 'must_learn' },
    { id: 'glb_v4', type: 'vocabulary', term: 'foreign', pronunciation: '/ˈfɒrən/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Belonging to or coming from a country other than your own.', vietnameseMeaning: 'Thuộc về nước ngoài, ngoại quốc.', example: 'Foreign investment brought both capital and management expertise to the region.', writingTip: '"Foreign investment", "foreign companies", "foreign markets" are all high-frequency in this topic.', topic: 'Globalisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['foreign investment', 'foreign markets', 'foreign competition', 'foreign firms'], antonym: 'domestic', wordFamily: ['foreigner (n)'], priority: 'must_learn' },
    { id: 'glb_v5', type: 'vocabulary', term: 'compete', pronunciation: '/kəmˈpiːt/', partOfSpeech: 'verb', cefrLevel: 'B1', definition: 'To try to be more successful than others in the same market.', vietnameseMeaning: 'Cạnh tranh.', example: 'Small local manufacturers simply cannot compete with imported goods produced at enormous scale.', writingTip: '"Compete with" a rival, "compete for" a prize or market share. The noun is "competition".', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['compete with', 'compete for market share', 'compete effectively', 'unable to compete'], wordFamily: ['competition (n)', 'competitive (adj)', 'competitor (n)'], priority: 'must_learn' },
    { id: 'glb_v6', type: 'vocabulary', term: 'worldwide', pronunciation: '/ˌwɜːldˈwaɪd/', partOfSpeech: 'adjective / adverb', cefrLevel: 'B1', definition: 'Existing or happening in all parts of the world.', vietnameseMeaning: 'Trên toàn thế giới, khắp toàn cầu.', example: 'The brand is now recognised worldwide, from Lagos to Lima.', writingTip: 'A safe Band 5-6 alternative to "global". Use "globally" for slight variety.', topic: 'Globalisation', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', collocations: ['worldwide demand', 'sold worldwide', 'a worldwide phenomenon'], alternatives: ['global', 'international'], priority: 'high_value' },
    { id: 'glb_v7', type: 'vocabulary', term: 'benefit', pronunciation: '/ˈbenɪfɪt/', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'An advantage gained from something; to gain an advantage.', vietnameseMeaning: 'Lợi ích; hưởng lợi.', example: 'Consumers in wealthy nations have benefited enormously from cheap imported manufacturing.', writingTip: 'As a verb: "benefit from" something. Note the spelling "benefited" (single t in British English).', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['benefit from', 'economic benefits', 'mutual benefit', 'reap the benefits'], antonym: 'drawback', wordFamily: ['beneficial (adj)', 'beneficiary (n)'], priority: 'must_learn' },
    { id: 'glb_v8', type: 'vocabulary', term: 'developing country', pronunciation: '/dɪˈveləpɪŋ ˈkʌntri/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'A country with a relatively low income and a growing industrial base.', vietnameseMeaning: 'Nước đang phát triển.', example: 'Developing countries have gained manufacturing jobs, though often on very thin margins.', writingTip: 'The accepted term in academic writing. Avoid "poor countries" and the outdated "third world".', topic: 'Globalisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['in developing countries', 'developed nations', 'emerging economies'], antonym: 'developed country', priority: 'must_learn' },
    { id: 'glb_v9', type: 'vocabulary', term: 'labour', pronunciation: '/ˈleɪbə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Work, especially physical work; the workers available in a country.', vietnameseMeaning: 'Lao động, nhân công.', example: 'Companies relocate production to countries where labour is abundant and inexpensive.', writingTip: 'Uncountable in this sense: "cheap labour", not "cheap labours". American spelling is "labor".', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cheap labour', 'skilled labour', 'labour costs', 'labour market'], wordFamily: ['labourer (n)', 'laborious (adj)'], priority: 'must_learn' },
    { id: 'glb_v10', type: 'vocabulary', term: 'influence', pronunciation: '/ˈɪnfluəns/', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'The power to affect how something develops or how people behave.', vietnameseMeaning: 'Ảnh hưởng, tác động.', example: 'The influence of American entertainment on youth culture is visible in almost every country.', writingTip: 'Note the preposition: "influence on", not "influence to". "Have an influence on" is standard.', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a strong influence on', 'cultural influence', 'exert influence', 'growing influence'], wordFamily: ['influential (adj)'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'glb_v11', type: 'vocabulary', term: 'multinational', pronunciation: '/ˌmʌltiˈnæʃnəl/', partOfSpeech: 'adjective / noun', cefrLevel: 'B2', definition: 'Operating in several countries; a company that does so.', vietnameseMeaning: 'Đa quốc gia; công ty đa quốc gia.', example: 'Multinational corporations can shift profits between jurisdictions in ways that individual governments struggle to police.', writingTip: 'Also used as a noun on its own: "multinationals dominate the sector".', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['multinational corporations', 'multinational companies', 'large multinationals'], priority: 'must_learn' },
    { id: 'glb_v12', type: 'vocabulary', term: 'outsource', pronunciation: '/ˈaʊtsɔːs/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To pay an outside company, often abroad, to do work previously done internally.', vietnameseMeaning: 'Thuê ngoài, chuyển việc cho bên thứ ba.', example: 'Western firms began to outsource customer service to South Asia in the late 1990s.', writingTip: '"Outsource X to Y". The noun "outsourcing" is more common in essays than the verb.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['outsource production', 'outsource jobs', 'outsource to overseas suppliers'], wordFamily: ['outsourcing (n)'], priority: 'must_learn' },
    { id: 'glb_v13', type: 'vocabulary', term: 'interdependence', pronunciation: '/ˌɪntədɪˈpendəns/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'A situation in which countries or groups rely on each other.', vietnameseMeaning: 'Sự phụ thuộc lẫn nhau.', example: 'Economic interdependence makes armed conflict between major trading partners far more costly.', writingTip: 'An elegant way to describe globalisation’s core mechanism. Pair with "economic" or "growing".', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['economic interdependence', 'growing interdependence', 'mutual interdependence'], wordFamily: ['interdependent (adj)'], priority: 'must_learn' },
    { id: 'glb_v14', type: 'vocabulary', term: 'tariff', pronunciation: '/ˈtærɪf/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A tax placed on goods coming into a country.', vietnameseMeaning: 'Thuế nhập khẩu, thuế quan.', example: 'Tariffs on imported steel protected domestic producers but raised costs for every manufacturer downstream.', writingTip: '"Impose", "raise", "lift" and "remove" are the natural verbs. Countable: "tariffs on steel".', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['impose tariffs', 'lift tariffs', 'high tariffs', 'tariff barriers'], alternatives: ['import duty'], priority: 'high_value' },
    { id: 'glb_v15', type: 'vocabulary', term: 'supply chain', pronunciation: '/səˈplaɪ tʃeɪn/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'The sequence of companies and processes involved in producing and delivering a product.', vietnameseMeaning: 'Chuỗi cung ứng.', example: 'The pandemic exposed how fragile global supply chains had become after decades of cost-cutting.', writingTip: 'A very current, credible term. "Global supply chains" is the standard plural collocation.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['global supply chains', 'disrupt supply chains', 'supply chain disruption'], priority: 'must_learn' },
    { id: 'glb_v16', type: 'vocabulary', term: 'consumerism', pronunciation: '/kənˈsjuːmərɪzəm/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'A social preoccupation with buying and owning goods.', vietnameseMeaning: 'Chủ nghĩa tiêu dùng.', example: 'Global advertising has spread a culture of consumerism to societies that once prized thrift.', writingTip: 'Carries a critical tone. Useful for arguing that globalisation exports values, not only products.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['rampant consumerism', 'a culture of consumerism', 'Western consumerism'], wordFamily: ['consumer (n)', 'consume (v)', 'consumerist (adj)'], priority: 'high_value' },
    { id: 'glb_v17', type: 'vocabulary', term: 'liberalisation', pronunciation: '/ˌlɪbərəlaɪˈzeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The removal of government restrictions on trade or business.', vietnameseMeaning: 'Tự do hoá (thương mại, kinh tế).', example: 'Trade liberalisation in the 1990s transformed Vietnam from a food importer into a leading rice exporter.', writingTip: '"Trade liberalisation" and "economic liberalisation" are the two standard pairings.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['trade liberalisation', 'economic liberalisation', 'market liberalisation'], antonym: 'protectionism', wordFamily: ['liberalise (v)', 'liberal (adj)'], priority: 'high_value' },
    { id: 'glb_v18', type: 'vocabulary', term: 'diaspora', pronunciation: '/daɪˈæspərə/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'A community of people who live outside the country of their origin.', vietnameseMeaning: 'Cộng đồng kiều bào, người xa xứ.', example: 'The Vietnamese diaspora sends home remittances that exceed several categories of foreign investment.', writingTip: 'Usually "the ... diaspora". Excellent for discussing migration, remittances and cultural exchange.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['the diaspora community', 'a large diaspora', 'diaspora networks'], priority: 'optional' },
    { id: 'glb_v19', type: 'vocabulary', term: 'exploit', pronunciation: '/ɪkˈsplɔɪt/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To treat people unfairly in order to profit from their work; to make use of a resource.', vietnameseMeaning: 'Bóc lột; khai thác (tài nguyên).', example: 'Weak labour laws allow some suppliers to exploit workers who have no realistic alternative employment.', writingTip: 'Two distinct senses. With people it is negative; with resources or opportunities it can be neutral.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['exploit workers', 'exploit cheap labour', 'exploit natural resources'], wordFamily: ['exploitation (n)', 'exploitative (adj)'], priority: 'must_learn' },
    { id: 'glb_v20', type: 'vocabulary', term: 'domestic', pronunciation: '/dəˈmestɪk/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Relating to a country’s own internal affairs or market.', vietnameseMeaning: 'Trong nước, nội địa.', example: 'Cheap imports have decimated domestic textile production in several African economies.', writingTip: 'The precise opposite of "foreign" in trade contexts: domestic industry, domestic market, domestic producers.', topic: 'Globalisation', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['domestic market', 'domestic industry', 'domestic producers', 'domestic demand'], antonym: 'foreign', wordFamily: ['domestically (adv)'], priority: 'must_learn' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'glb_v21', type: 'vocabulary', term: 'homogenisation', pronunciation: '/həˌmɒdʒənaɪˈzeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'The process by which different things become uniform and lose their distinctiveness.', vietnameseMeaning: 'Sự đồng nhất hoá, làm mất bản sắc riêng.', example: 'The homogenisation of high streets means a traveller can now cross three continents and see the same shopfronts.', writingTip: 'The key term for the cultural argument against globalisation. "Cultural homogenisation" is the pairing.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cultural homogenisation', 'lead to homogenisation', 'the homogenisation of culture'], antonym: 'diversification', wordFamily: ['homogenise (v)', 'homogeneous (adj)'], priority: 'must_learn' },
    { id: 'glb_v22', type: 'vocabulary', term: 'protectionism', pronunciation: '/prəˈtekʃənɪzəm/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The policy of shielding domestic industries from foreign competition using tariffs and quotas.', vietnameseMeaning: 'Chủ nghĩa bảo hộ (mậu dịch).', example: 'A retreat into protectionism would raise consumer prices without restoring the jobs that automation eliminated.', writingTip: 'The natural counterweight to "free trade" — essential for a balanced globalisation essay.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a rise in protectionism', 'resort to protectionism', 'protectionist policies'], antonym: 'free trade', wordFamily: ['protectionist (adj, n)'], priority: 'must_learn' },
    { id: 'glb_v23', type: 'vocabulary', term: 'sovereignty', pronunciation: '/ˈsɒvrənti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'A country’s authority to govern itself without outside interference.', vietnameseMeaning: 'Chủ quyền quốc gia.', example: 'Critics argue that binding trade agreements erode national sovereignty over environmental standards.', writingTip: 'Common in arguments about international organisations. "National sovereignty" is the usual phrase.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['national sovereignty', 'erode sovereignty', 'surrender sovereignty', 'economic sovereignty'], wordFamily: ['sovereign (adj, n)'], priority: 'high_value' },
    { id: 'glb_v24', type: 'vocabulary', term: 'offshoring', pronunciation: '/ˌɒfˈʃɔːrɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Moving a company’s own operations to another country.', vietnameseMeaning: 'Chuyển hoạt động sản xuất ra nước ngoài.', example: 'Offshoring differs from outsourcing in that the work remains within the company, simply relocated abroad.', writingTip: 'Distinguish carefully from "outsourcing": offshoring moves location, outsourcing changes ownership of the task.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['the offshoring of manufacturing', 'offshoring jobs'], antonym: 'reshoring', wordFamily: ['offshore (v, adj)'], priority: 'optional' },
    { id: 'glb_v25', type: 'vocabulary', term: 'trade deficit', pronunciation: '/treɪd ˈdefɪsɪt/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'The amount by which a country’s imports exceed its exports.', vietnameseMeaning: 'Thâm hụt thương mại.', example: 'A persistent trade deficit is not necessarily harmful if it finances productive investment.', writingTip: 'The opposite is "trade surplus". Both are valuable in Task 1 charts on international trade.', topic: 'Globalisation', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a widening trade deficit', 'run a trade deficit', 'reduce the deficit'], antonym: 'trade surplus', priority: 'high_value' },
    { id: 'glb_v26', type: 'vocabulary', term: 'economic integration', pronunciation: '/ˌiːkəˈnɒmɪk ˌɪntɪˈɡreɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The process by which national economies become linked into a single market.', vietnameseMeaning: 'Hội nhập kinh tế.', example: 'Deeper economic integration within the region has cut the cost of trading between neighbours substantially.', writingTip: 'A precise, formal phrase for what trade blocs do. Pair with "deeper", "regional", "further".', topic: 'Globalisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['regional economic integration', 'deeper integration', 'further integration'], wordFamily: ['integrate (v)', 'integrated (adj)'], priority: 'high_value' },
    { id: 'glb_v27', type: 'vocabulary', term: 'disproportionately', pronunciation: '/ˌdɪsprəˈpɔːʃənətli/', partOfSpeech: 'adverb', cefrLevel: 'C1', definition: 'To an extent that is much greater or smaller than is fair or expected.', vietnameseMeaning: 'Một cách không tương xứng, quá mức so với tỷ lệ hợp lý.', example: 'The gains from open trade have flowed disproportionately to capital rather than to workers.', writingTip: 'A precise way to describe unequal distribution of benefits or harms. Very high value in this topic.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['disproportionately affected', 'disproportionately high', 'benefit disproportionately'], wordFamily: ['disproportionate (adj)'], priority: 'must_learn' },
    { id: 'glb_v28', type: 'vocabulary', term: 'erode', pronunciation: '/ɪˈrəʊd/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To gradually reduce or destroy something.', vietnameseMeaning: 'Bào mòn, làm suy giảm dần.', example: 'The dominance of English online has slowly eroded the position of minority languages.', writingTip: 'Implies gradual, cumulative loss — perfect for cultural and institutional arguments.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['erode traditions', 'erode sovereignty', 'gradually erode', 'erode trust'], alternatives: ['undermine', 'weaken', 'diminish'], wordFamily: ['erosion (n)'], priority: 'must_learn' },
    { id: 'glb_v29', type: 'vocabulary', term: 'proliferate', pronunciation: '/prəˈlɪfəreɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To increase rapidly in number and spread widely.', vietnameseMeaning: 'Lan rộng nhanh chóng, sinh sôi nảy nở.', example: 'International franchises have proliferated across Asian cities over the past two decades.', writingTip: 'A sophisticated alternative to "spread quickly". Intransitive — nothing "proliferates something".', topic: 'Globalisation', bandLevel: '7+', task: 'both', writingSuitability: 'suitable', collocations: ['rapidly proliferate', 'proliferate across'], wordFamily: ['proliferation (n)'], priority: 'optional' },
    { id: 'glb_v30', type: 'vocabulary', term: 'unfettered', pronunciation: '/ʌnˈfetəd/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Not restricted by rules or controls.', vietnameseMeaning: 'Không bị ràng buộc, hoàn toàn tự do không kiểm soát.', example: 'Unfettered capital flows can destabilise small economies within a matter of weeks.', writingTip: 'Almost always before a noun and slightly critical in tone. Use once, for emphasis.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['unfettered markets', 'unfettered access', 'unfettered capital flows'], alternatives: ['unrestricted', 'unregulated'], antonym: 'regulated', priority: 'optional' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'glb_c1', type: 'collocation', term: 'international trade', collocationType: 'Adj + Noun', definition: 'The exchange of goods and services between countries.', vietnameseMeaning: 'Thương mại quốc tế.', example: 'International trade now accounts for well over half of global economic output.', topic: 'Globalisation', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'glb_c2', type: 'collocation', term: 'foreign investment', collocationType: 'Adj + Noun', definition: 'Money put into a country’s businesses by people or firms from abroad.', vietnameseMeaning: 'Đầu tư nước ngoài.', example: 'Foreign investment brought not only capital but also production techniques the country had never used.', alternative: 'overseas investment', topic: 'Globalisation', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'glb_c3', type: 'collocation', term: 'cheap labour', collocationType: 'Adj + Noun', definition: 'Workers who can be employed at low cost.', vietnameseMeaning: 'Nhân công giá rẻ.', example: 'Access to cheap labour was the original reason manufacturers relocated to Southeast Asia.', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: '"Labour" is uncountable here — never "cheap labours".' },
    { id: 'glb_c4', type: 'collocation', term: 'the global economy', collocationType: 'Adj + Noun', definition: 'The worldwide system of production, trade and finance.', vietnameseMeaning: 'Nền kinh tế toàn cầu.', example: 'A recession in one major market now transmits through the global economy within months.', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'glb_c5', type: 'collocation', term: 'cultural differences', collocationType: 'Adj + Noun', definition: 'Variations in the customs and values of different societies.', vietnameseMeaning: 'Sự khác biệt văn hoá.', example: 'Managers posted abroad often underestimate how much cultural differences shape workplace expectations.', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'glb_c6', type: 'collocation', term: 'create job opportunities', collocationType: 'Verb + Noun', definition: 'To bring about new chances for paid employment.', vietnameseMeaning: 'Tạo ra cơ hội việc làm.', example: 'Foreign factories create job opportunities in regions where formal employment was previously scarce.', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'glb_c7', type: 'collocation', term: 'imported goods', collocationType: 'Adj + Noun', definition: 'Products brought into a country from abroad.', vietnameseMeaning: 'Hàng hoá nhập khẩu.', example: 'Imported goods are frequently cheaper than local equivalents because of scale rather than quality.', topic: 'Globalisation', bandLevel: '5-6', task: 'both', priority: 'high_value' },
    { id: 'glb_c8', type: 'collocation', term: 'have an impact on', collocationType: 'Verb + Noun + Prep', definition: 'To affect something noticeably.', vietnameseMeaning: 'Có tác động đến.', example: 'Trade agreements have a far greater impact on rural livelihoods than most voters realise.', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'The preposition is always "on" — never "impact to" or "impact for".' },

    // Advanced (Band 6-7)
    { id: 'glb_c9', type: 'collocation', term: 'multinational corporations', collocationType: 'Adj + Noun', definition: 'Large companies operating across many countries.', vietnameseMeaning: 'Các tập đoàn đa quốc gia.', example: 'Multinational corporations now command revenues larger than the budgets of many national governments.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'glb_c10', type: 'collocation', term: 'break down trade barriers', collocationType: 'Verb + Noun', definition: 'To remove the tariffs and regulations that restrict trade.', vietnameseMeaning: 'Xoá bỏ các rào cản thương mại.', example: 'Regional agreements have broken down trade barriers that stood for most of the twentieth century.', alternative: 'remove trade barriers', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'glb_c11', type: 'collocation', term: 'widen the gap between rich and poor', collocationType: 'Verb + Noun', definition: 'To increase the inequality between wealthy and poor groups.', vietnameseMeaning: 'Nới rộng khoảng cách giàu nghèo.', example: 'Open markets have widened the gap between rich and poor within countries even as they narrowed it between them.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'glb_c12', type: 'collocation', term: 'a global supply chain', collocationType: 'Adj + Noun', definition: 'A production network spread across multiple countries.', vietnameseMeaning: 'Chuỗi cung ứng toàn cầu.', example: 'A single smartphone passes through a global supply chain spanning more than a dozen countries.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'glb_c13', type: 'collocation', term: 'gain a competitive edge', collocationType: 'Verb + Noun', definition: 'To acquire an advantage over rivals.', vietnameseMeaning: 'Giành lợi thế cạnh tranh.', example: 'Countries that invest early in technical education gain a competitive edge that lasts for decades.', alternative: 'gain a competitive advantage', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'glb_c14', type: 'collocation', term: 'cultural exchange', collocationType: 'Adj + Noun', definition: 'The sharing of ideas, customs and art between societies.', vietnameseMeaning: 'Giao lưu văn hoá.', example: 'Cultural exchange has always run in both directions, though rarely in equal volume.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'glb_c15', type: 'collocation', term: 'transcend national borders', collocationType: 'Verb + Noun', definition: 'To extend beyond the boundaries of individual countries.', vietnameseMeaning: 'Vượt qua biên giới quốc gia.', example: 'Environmental problems transcend national borders, which is precisely why they resist national solutions.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'glb_c16', type: 'collocation', term: 'erode cultural identity', collocationType: 'Verb + Noun', definition: 'To gradually weaken a community’s distinctive character.', vietnameseMeaning: 'Làm xói mòn bản sắc văn hoá.', example: 'Whether global media genuinely erodes cultural identity or simply adds another layer to it remains disputed.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'glb_c17', type: 'collocation', term: 'reap the benefits of globalisation', collocationType: 'Verb + Noun', definition: 'To enjoy the advantages that global integration brings.', vietnameseMeaning: 'Gặt hái lợi ích từ toàn cầu hoá.', example: 'Only countries with functioning institutions have been able to reap the benefits of globalisation.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'glb_c18', type: 'collocation', term: 'the free movement of capital', collocationType: 'Noun phrase', definition: 'The ability of money and investment to cross borders without restriction.', vietnameseMeaning: 'Sự lưu chuyển tự do của dòng vốn.', example: 'The free movement of capital rewards countries with stable institutions and punishes those without them.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'glb_c19', type: 'collocation', term: 'be disproportionately affected by', collocationType: 'Verb phrase', definition: 'To suffer a greater share of harm than is fair or expected.', vietnameseMeaning: 'Chịu ảnh hưởng nặng nề hơn mức tương xứng.', example: 'Manufacturing towns have been disproportionately affected by the shift of production overseas.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'glb_c20', type: 'collocation', term: 'resort to protectionist measures', collocationType: 'Verb + Noun', definition: 'To turn to tariffs and restrictions in order to shield domestic industry.', vietnameseMeaning: 'Viện đến các biện pháp bảo hộ.', example: 'Governments under electoral pressure frequently resort to protectionist measures that harm their own consumers.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'glb_p1', type: 'phrasal_verb', term: 'take over', partOfSpeech: 'phrasal verb (separable)', definition: 'To gain control of a company or market.', vietnameseMeaning: 'Thâu tóm, tiếp quản (công ty, thị trường).', example: 'Foreign firms have taken over most of the country’s largest breweries.', formalAlternative: 'acquire', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['take over a company', 'a takeover bid'], academicAlternatives: ['acquire', 'assume control of'] },
    { id: 'glb_p2', type: 'phrasal_verb', term: 'set up', partOfSpeech: 'phrasal verb (separable)', definition: 'To establish a business or organisation.', vietnameseMeaning: 'Thành lập, mở (nhà máy, công ty).', example: 'Manufacturers set up factories wherever wages, regulation and transport costs are most favourable.', formalAlternative: 'establish', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', collocations: ['set up a factory', 'set up operations'], academicAlternatives: ['establish', 'found', 'launch'] },
    { id: 'glb_p3', type: 'phrasal_verb', term: 'depend on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To rely on someone or something for support.', vietnameseMeaning: 'Phụ thuộc vào, dựa vào.', example: 'Several small economies depend almost entirely on a single export commodity.', formalAlternative: 'rely on', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['depend heavily on', 'depend on imports'], academicAlternatives: ['rely on', 'be reliant on', 'be contingent on'] },
    { id: 'glb_p4', type: 'phrasal_verb', term: 'benefit from', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To gain an advantage from something.', vietnameseMeaning: 'Hưởng lợi từ.', example: 'Consumers benefit from lower prices, while displaced workers bear the cost.', formalAlternative: 'gain from', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', academicAlternatives: ['gain from', 'profit from', 'derive benefit from'] },
    { id: 'glb_p5', type: 'phrasal_verb', term: 'catch up with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To reach the same level as someone who is ahead.', vietnameseMeaning: 'Bắt kịp, đuổi kịp.', example: 'Emerging economies have caught up with the West far faster than most forecasters predicted.', formalAlternative: 'reach parity with', topic: 'Globalisation', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['converge with', 'reach parity with', 'match'] },

    // Advanced / less common
    { id: 'glb_p6', type: 'phrasal_verb', term: 'open up', partOfSpeech: 'phrasal verb (separable)', definition: 'To make a market or country accessible to outsiders.', vietnameseMeaning: 'Mở cửa (thị trường, nền kinh tế).', example: 'China opened up its economy gradually, retaining control over which sectors foreigners could enter.', formalAlternative: 'liberalise', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['open up markets', 'open up to foreign investment'], academicAlternatives: ['liberalise', 'deregulate'] },
    { id: 'glb_p7', type: 'phrasal_verb', term: 'break into', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To succeed in entering a market for the first time.', vietnameseMeaning: 'Thâm nhập vào (thị trường mới).', example: 'Local brands struggle to break into markets already dominated by global names.', formalAlternative: 'enter', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['break into a market', 'break into the industry'], academicAlternatives: ['enter', 'penetrate', 'gain a foothold in'] },
    { id: 'glb_p8', type: 'phrasal_verb', term: 'drive down', partOfSpeech: 'phrasal verb (separable)', definition: 'To force prices, wages or costs to fall.', vietnameseMeaning: 'Kéo giảm, đẩy xuống (giá cả, lương).', example: 'Competition from low-wage economies has driven down manufacturing wages across the industrialised world.', formalAlternative: 'reduce', topic: 'Globalisation', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['drive down prices', 'drive down wages', 'drive down costs'], academicAlternatives: ['depress', 'reduce', 'suppress'] },
    { id: 'glb_p9', type: 'phrasal_verb', term: 'wipe out', partOfSpeech: 'phrasal verb (separable)', definition: 'To destroy something completely.', vietnameseMeaning: 'Xoá sổ, huỷ diệt hoàn toàn.', example: 'Cheap imports wiped out an entire generation of small textile workshops.', formalAlternative: 'eliminate', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', usageWarning: 'Emphatic — use only where the destruction really was total.', academicAlternatives: ['eliminate', 'destroy', 'eradicate'] },
    { id: 'glb_p10', type: 'phrasal_verb', term: 'give way to', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To be replaced by something else.', vietnameseMeaning: 'Nhường chỗ cho, bị thay thế bởi.', example: 'Local markets have gradually given way to international supermarket chains.', formalAlternative: 'be replaced by', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'high_value', academicAlternatives: ['be supplanted by', 'be superseded by', 'yield to'] },
  ],

  writingPhrases: [
    { id: 'glb_w1', type: 'writing_phrase', term: 'The debate over globalisation ultimately turns on the question of...', function: 'Introducing an argument', vietnameseMeaning: 'Cuộc tranh luận về toàn cầu hoá cuối cùng xoay quanh câu hỏi...', example: 'The debate over globalisation ultimately turns on the question of who captures the gains it produces.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'glb_w2', type: 'writing_phrase', term: 'Companies relocate production abroad chiefly because...', function: 'Giving a reason', vietnameseMeaning: 'Các công ty chuyển sản xuất ra nước ngoài chủ yếu vì...', example: 'Companies relocate production abroad chiefly because labour costs elsewhere are a fraction of domestic ones.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'glb_w3', type: 'writing_phrase', term: 'This convergence of markets has been driven largely by...', function: 'Explaining a cause', vietnameseMeaning: 'Sự hội tụ của các thị trường này chủ yếu được thúc đẩy bởi...', example: 'This convergence of markets has been driven largely by falling transport costs and near-instant communication.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'glb_w4', type: 'writing_phrase', term: 'The result is that economic shocks now spread...', function: 'Explaining an effect', vietnameseMeaning: 'Kết quả là các cú sốc kinh tế hiện lan truyền...', example: 'The result is that economic shocks now spread across borders in days rather than years.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'glb_w5', type: 'writing_phrase', term: 'The garment industry provides a telling example:', function: 'Giving an example', vietnameseMeaning: 'Ngành may mặc là một ví dụ rất điển hình:', example: 'The garment industry provides a telling example: a shirt may be designed in Europe, sewn in Bangladesh and sold in Japan.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'glb_w6', type: 'writing_phrase', term: 'The most tangible benefit for consumers has been...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi ích rõ rệt nhất đối với người tiêu dùng là...', example: 'The most tangible benefit for consumers has been access to a range of goods at prices previous generations could not have imagined.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'glb_w7', type: 'writing_phrase', term: 'The costs, however, have fallen most heavily on...', function: 'Discussing disadvantages', vietnameseMeaning: 'Tuy nhiên, cái giá phải trả lại đè nặng nhất lên...', example: 'The costs, however, have fallen most heavily on regions whose economies were built around a single industry.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'glb_w8', type: 'writing_phrase', term: 'Instead of retreating from global markets, governments would do better to...', function: 'Suggesting a solution', vietnameseMeaning: 'Thay vì rút khỏi thị trường toàn cầu, các chính phủ nên...', example: 'Instead of retreating from global markets, governments would do better to retrain the workers those markets displace.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'glb_w9', type: 'writing_phrase', term: 'In my view, globalisation is best understood not as a force but as...', function: 'Expressing an opinion', vietnameseMeaning: 'Theo tôi, toàn cầu hoá nên được hiểu không phải như một thế lực mà là...', example: 'In my view, globalisation is best understood not as a force but as a set of political choices that can be made differently.', topic: 'Globalisation', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'glb_w10', type: 'writing_phrase', term: 'While wealthy nations gain access to cheaper goods, developing ones by contrast...', function: 'Comparing ideas', vietnameseMeaning: 'Trong khi các nước giàu tiếp cận hàng hoá rẻ hơn, các nước đang phát triển ngược lại...', example: 'While wealthy nations gain access to cheaper goods, developing ones by contrast gain employment but often on precarious terms.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'glb_m1', type: 'common_mistake', incorrect: 'The globalisation has changed our lives completely.', correct: 'Globalisation has changed our lives completely.', explanation: 'Abstract uncountable nouns such as globalisation, education and technology take no article when used in a general sense. Vietnamese speakers frequently add "the" here.', topic: 'Globalisation', priority: 'must_learn' },
    { id: 'glb_m2', type: 'common_mistake', incorrect: 'Globalisation has a big impact to developing countries.', correct: 'Globalisation has a considerable impact on developing countries.', explanation: 'The fixed preposition is "impact on". "Big" is also spoken register — prefer "considerable", "significant" or "profound".', topic: 'Globalisation', priority: 'must_learn' },
    { id: 'glb_m3', type: 'common_mistake', incorrect: 'Many companies move their factory to countries which have cheap labours.', correct: 'Many companies relocate their factories to countries where labour is cheap.', explanation: 'Three fixes: "labour" is uncountable, "factories" must be plural to match "many companies", and "where" is the natural relative word for a place.', topic: 'Globalisation', priority: 'must_learn' },
    { id: 'glb_m4', type: 'common_mistake', incorrect: 'Developed countries are more richer than developing countries.', correct: 'Developed countries are considerably richer than developing ones.', explanation: 'Never combine "more" with an -er comparative. To intensify a comparison use "far", "considerably" or "significantly" before the comparative.', topic: 'Globalisation', priority: 'high_value' },
    { id: 'glb_m5', type: 'common_mistake', incorrect: 'Globalisation makes people lose their traditional culture.', correct: 'Globalisation risks eroding traditional cultural practices.', explanation: '"Make someone lose" is weak and overstates certainty. "Erode", "undermine" or "dilute" plus a hedging verb such as "risk" or "may" is both more accurate and higher band.', topic: 'Globalisation', priority: 'high_value' },
  ],

  learnFirst: {
    vocabulary: ['glb_v1', 'glb_v11', 'glb_v12', 'glb_v13', 'glb_v15', 'glb_v19', 'glb_v21', 'glb_v22', 'glb_v27', 'glb_v28'],
    collocations: ['glb_c1', 'glb_c9', 'glb_c11', 'glb_c16', 'glb_c19'],
    phrasalVerbs: ['glb_p6', 'glb_p8', 'glb_p3'],
    writingPhrases: ['glb_w1', 'glb_w7', 'glb_w8'],
  },
}
