import type { TopicData } from '../types'

export const GOVERNMENT: TopicData = {
  topic: 'Government',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'gov_v1', type: 'vocabulary', term: 'policy', pronunciation: '/ˈpɒləsi/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A plan of action agreed by a government or organisation.', vietnameseMeaning: 'Chính sách.', example: 'A housing policy that ignores land supply will never reduce prices.', writingTip: 'Countable: "a policy", "several policies". Do not confuse with "politics" (the activity) or "politician".', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['government policy', 'implement a policy', 'foreign policy', 'a policy on'], wordFamily: ['political (adj)', 'politics (n)'], priority: 'must_learn' },
    { id: 'gov_v2', type: 'vocabulary', term: 'implement', pronunciation: '/ˈɪmplɪment/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To put a plan or decision into effect.', vietnameseMeaning: 'Triển khai, thực thi (chính sách, kế hoạch).', example: 'Announcing a policy is easy; implementing it across thousands of institutions is not.', writingTip: 'One of the most useful verbs in Task 2 solution paragraphs. Objects: policies, measures, reforms, schemes.', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['implement a policy', 'implement measures', 'implement reforms', 'fully implement'], alternatives: ['introduce', 'enact', 'put into practice'], wordFamily: ['implementation (n)'], priority: 'must_learn' },
    { id: 'gov_v3', type: 'vocabulary', term: 'authority', pronunciation: '/ɔːˈθɒrəti/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'The power to make decisions; an official organisation with such power.', vietnameseMeaning: 'Quyền lực; cơ quan chức năng.', example: 'Local authorities are responsible for services they no longer have the funding to provide.', writingTip: 'Uncountable when it means power; countable when it means an organisation ("the authorities").', topic: 'Government', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['local authorities', 'exercise authority', 'the relevant authorities'], wordFamily: ['authorise (v)', 'authoritative (adj)'], priority: 'must_learn' },
    { id: 'gov_v4', type: 'vocabulary', term: 'citizen', pronunciation: '/ˈsɪtɪzn/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A legally recognised member of a country.', vietnameseMeaning: 'Công dân.', example: 'Citizens are far more willing to pay tax where they can see what it buys.', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['ordinary citizens', 'senior citizens', 'the rights of citizens'], wordFamily: ['citizenship (n)'], priority: 'high_value' },
    { id: 'gov_v5', type: 'vocabulary', term: 'election', pronunciation: '/ɪˈlekʃn/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A formal process in which people vote to choose representatives.', vietnameseMeaning: 'Cuộc bầu cử.', example: 'Policies that require a decade to bear fruit rarely survive the next election.', writingTip: 'The verb is "hold an election". A person "stands for" or "runs for" election.', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['hold an election', 'a general election', 'win an election'], wordFamily: ['elect (v)', 'elected (adj)', 'electorate (n)'], priority: 'high_value' },
    { id: 'gov_v6', type: 'vocabulary', term: 'regulation', pronunciation: '/ˌreɡjuˈleɪʃn/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'An official rule controlling how something is done.', vietnameseMeaning: 'Quy định, quy chế.', example: 'Safety regulations are almost always written after an avoidable disaster.', writingTip: 'Countable ("regulations"), unlike "legislation" which is uncountable.', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['strict regulations', 'introduce regulations', 'comply with regulations', 'relax regulations'], wordFamily: ['regulate (v)', 'regulatory (adj)', 'regulator (n)'], priority: 'must_learn' },
    { id: 'gov_v7', type: 'vocabulary', term: 'public services', pronunciation: '/ˌpʌblɪk ˈsɜːvɪsɪz/', partOfSpeech: 'noun (plural)', cefrLevel: 'B2', definition: 'Services provided by the state, such as health, education and transport.', vietnameseMeaning: 'Dịch vụ công.', example: 'Public services absorb the consequences of every failure elsewhere in society.', topic: 'Government', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['fund public services', 'cuts to public services', 'essential public services'], priority: 'must_learn' },
    { id: 'gov_v8', type: 'vocabulary', term: 'budget', pronunciation: '/ˈbʌdʒɪt/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A plan of how much money will be available and how it will be spent.', vietnameseMeaning: 'Ngân sách, kế hoạch chi tiêu.', example: 'A defence budget that grows every year inevitably squeezes something else.', topic: 'Government', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a limited budget', 'the national budget', 'cut the budget', 'within budget'], wordFamily: ['budgetary (adj)'], priority: 'high_value' },
    { id: 'gov_v9', type: 'vocabulary', term: 'ban', pronunciation: '/bæn/', partOfSpeech: 'verb / noun', cefrLevel: 'B1', definition: 'To officially forbid something.', vietnameseMeaning: 'Cấm, lệnh cấm.', example: 'Banning advertising had a greater effect on smoking rates than raising the price.', writingTip: 'The verb takes a noun or "-ing": "ban smoking", never "ban to smoke". Also "ban somebody from doing".', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['impose a ban', 'lift a ban', 'a complete ban on', 'ban somebody from'], alternatives: ['prohibit', 'outlaw', 'forbid'], wordFamily: ['banned (adj)'], priority: 'must_learn' },
    { id: 'gov_v10', type: 'vocabulary', term: 'funding', pronunciation: '/ˈfʌndɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Money provided for a particular purpose.', vietnameseMeaning: 'Kinh phí, nguồn tài trợ.', example: 'Funding for preventive programmes is always the first to be cut and the last to be restored.', writingTip: 'Uncountable — "fundings" is always wrong. Use "sources of funding" or "funds" (plural).', topic: 'Government', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['secure funding', 'cut funding', 'public funding', 'adequate funding'], wordFamily: ['fund (v/n)'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'gov_v11', type: 'vocabulary', term: 'legislation', pronunciation: '/ˌledʒɪsˈleɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Laws considered collectively.', vietnameseMeaning: 'Luật pháp, hệ thống văn bản luật.', example: 'Legislation always lags behind the technologies it attempts to control.', writingTip: 'Uncountable — never "legislations". Say "a piece of legislation" for a single law.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['introduce legislation', 'pass legislation', 'stricter legislation', 'environmental legislation'], alternatives: ['laws', 'statutes'], wordFamily: ['legislate (v)', 'legislative (adj)', 'legislature (n)'], priority: 'must_learn' },
    { id: 'gov_v12', type: 'vocabulary', term: 'allocate', pronunciation: '/ˈæləkeɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To assign resources for a particular purpose.', vietnameseMeaning: 'Phân bổ (ngân sách, nguồn lực).', example: 'How a government allocates its budget reveals its priorities more honestly than any speech.', writingTip: 'Pattern: "allocate something to something/somebody". Formal and precise.', topic: 'Government', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['allocate funding', 'allocate resources', 'allocate a budget to'], alternatives: ['assign', 'apportion', 'earmark'], wordFamily: ['allocation (n)'], priority: 'must_learn' },
    { id: 'gov_v13', type: 'vocabulary', term: 'enforce', pronunciation: '/ɪnˈfɔːs/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To make sure a law or rule is obeyed.', vietnameseMeaning: 'Thực thi, cưỡng chế thi hành (luật).', example: 'A law that cannot be enforced does more harm than no law at all.', writingTip: 'Crucial for balanced arguments: passing a law and enforcing it are different problems.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['enforce the law', 'strictly enforce', 'difficult to enforce', 'law enforcement'], wordFamily: ['enforcement (n)', 'enforceable (adj)'], priority: 'must_learn' },
    { id: 'gov_v14', type: 'vocabulary', term: 'accountability', pronunciation: '/əˌkaʊntəˈbɪləti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The obligation to explain and take responsibility for one’s decisions.', vietnameseMeaning: 'Trách nhiệm giải trình.', example: 'Without genuine accountability, transparency amounts to little more than publishing documents nobody reads.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['public accountability', 'a lack of accountability', 'ensure accountability'], wordFamily: ['accountable (adj)'], priority: 'must_learn' },
    { id: 'gov_v15', type: 'vocabulary', term: 'bureaucracy', pronunciation: '/bjʊəˈrɒkrəsi/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'A system of administration with many complicated official rules.', vietnameseMeaning: 'Bộ máy hành chính quan liêu, thủ tục rườm rà.', example: 'Excessive bureaucracy deters exactly the small businesses that regulation is meant to protect.', writingTip: 'Usually negative in tone. The everyday equivalent is "red tape".', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['excessive bureaucracy', 'reduce bureaucracy', 'government bureaucracy'], alternatives: ['red tape', 'administration'], wordFamily: ['bureaucratic (adj)', 'bureaucrat (n)'], priority: 'high_value' },
    { id: 'gov_v16', type: 'vocabulary', term: 'intervene', pronunciation: '/ˌɪntəˈviːn/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To become involved in a situation in order to change it.', vietnameseMeaning: 'Can thiệp vào.', example: 'Markets fail regularly, and the question is not whether the state should intervene but how.', writingTip: 'Pattern: "intervene in". The noun "intervention" is often more useful in essays.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['intervene in the market', 'government intervention', 'directly intervene'], wordFamily: ['intervention (n)', 'interventionist (adj)'], priority: 'must_learn' },
    { id: 'gov_v17', type: 'vocabulary', term: 'mandate', pronunciation: '/ˈmændeɪt/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'The authority given to a government by voters to act on their behalf.', vietnameseMeaning: 'Sự uỷ nhiệm của cử tri, quyền được trao.', example: 'A government elected by a third of voters has a weak mandate for radical reform.', writingTip: 'Also a verb meaning "to make compulsory": "the law mandates helmets".', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a clear mandate', 'a democratic mandate', 'exceed a mandate'], wordFamily: ['mandatory (adj)'], priority: 'high_value' },
    { id: 'gov_v18', type: 'vocabulary', term: 'democratic', pronunciation: '/ˌdeməˈkrætɪk/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Based on the principle that all members have an equal say.', vietnameseMeaning: 'Thuộc về dân chủ, mang tính dân chủ.', example: 'Democratic systems are slow by design, and that slowness is often their greatest protection.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['democratic society', 'democratic process', 'democratic accountability'], antonym: 'authoritarian', wordFamily: ['democracy (n)', 'democratically (adv)'], priority: 'high_value' },
    { id: 'gov_v19', type: 'vocabulary', term: 'corruption', pronunciation: '/kəˈrʌpʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Dishonest use of public power for private gain.', vietnameseMeaning: 'Tham nhũng.', example: 'Corruption is most damaging not when it steals money but when it destroys trust.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['tackle corruption', 'widespread corruption', 'political corruption', 'rooted out corruption'], wordFamily: ['corrupt (adj/v)', 'corrupted (adj)'], priority: 'must_learn' },
    { id: 'gov_v20', type: 'vocabulary', term: 'referendum', pronunciation: '/ˌrefəˈrendəm/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'A direct public vote on a single issue.', vietnameseMeaning: 'Cuộc trưng cầu dân ý.', example: 'A referendum reduces a complex question to a single word, which is both its appeal and its danger.', writingTip: 'Plural: "referendums" (or "referenda"). "Hold a referendum on" is the standard pattern.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['hold a referendum', 'a national referendum', 'the outcome of a referendum'], priority: 'optional' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'gov_v21', type: 'vocabulary', term: 'transparency', pronunciation: '/trænsˈpærənsi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Openness about decisions and how they are made.', vietnameseMeaning: 'Sự minh bạch trong hoạt động của chính quyền.', example: 'Publishing spending data online has improved transparency far more cheaply than any inspectorate.', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['greater transparency', 'ensure transparency', 'a lack of transparency'], antonym: 'secrecy', wordFamily: ['transparent (adj)'], priority: 'must_learn' },
    { id: 'gov_v22', type: 'vocabulary', term: 'sovereignty', pronunciation: '/ˈsɒvrənti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'A country’s right to govern itself without outside interference.', vietnameseMeaning: 'Chủ quyền quốc gia.', example: 'Every international agreement involves surrendering a measure of sovereignty in exchange for influence.', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['national sovereignty', 'surrender sovereignty', 'threaten sovereignty'], wordFamily: ['sovereign (adj/n)'], priority: 'high_value' },
    { id: 'gov_v23', type: 'vocabulary', term: 'curtail', pronunciation: '/kɜːˈteɪl/', partOfSpeech: 'verb', cefrLevel: 'C2', definition: 'To reduce or restrict something, especially a right or freedom.', vietnameseMeaning: 'Cắt giảm, hạn chế (quyền tự do).', example: 'Emergency powers introduced to curtail movement proved remarkably difficult to withdraw.', writingTip: 'Formal and precise. Frequently used with rights, freedoms, spending and activities.', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['curtail freedoms', 'curtail spending', 'severely curtail'], alternatives: ['restrict', 'limit', 'cut back'], antonym: 'extend', wordFamily: ['curtailment (n)'], priority: 'must_learn' },
    { id: 'gov_v24', type: 'vocabulary', term: 'autocratic', pronunciation: '/ˌɔːtəˈkrætɪk/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Ruling with absolute power and without consulting others.', vietnameseMeaning: 'Chuyên quyền, độc đoán.', example: 'Autocratic governments can act quickly, but they have no mechanism for admitting error.', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['an autocratic regime', 'autocratic rule', 'increasingly autocratic'], alternatives: ['authoritarian', 'dictatorial'], antonym: 'democratic', wordFamily: ['autocracy (n)', 'autocrat (n)'], priority: 'high_value' },
    { id: 'gov_v25', type: 'vocabulary', term: 'lobby', pronunciation: '/ˈlɒbi/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To try to influence politicians in favour of a particular cause.', vietnameseMeaning: 'Vận động hành lang, gây ảnh hưởng tới chính giới.', example: 'Industries with the most to lose lobby hardest against the regulations they most need.', writingTip: 'Pattern: "lobby somebody for/against something". The noun "lobbying" is also common.', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['lobby the government', 'lobby against', 'corporate lobbying'], wordFamily: ['lobbyist (n)', 'lobbying (n)'], priority: 'high_value' },
    { id: 'gov_v26', type: 'vocabulary', term: 'consensus', pronunciation: '/kənˈsensəs/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'General agreement among a group.', vietnameseMeaning: 'Sự đồng thuận chung.', example: 'Building a consensus takes longer than issuing an order, but the result survives a change of government.', writingTip: 'Fixed phrases: "reach a consensus", "broad consensus", "consensus on". Avoid "a general consensus of opinion" — it is redundant.', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['reach a consensus', 'broad consensus', 'build consensus', 'consensus on'], alternatives: ['agreement', 'accord'], priority: 'must_learn' },
    { id: 'gov_v27', type: 'vocabulary', term: 'scrutiny', pronunciation: '/ˈskruːtəni/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Careful and critical examination.', vietnameseMeaning: 'Sự giám sát, xem xét kỹ lưỡng.', example: 'Decisions taken during an emergency should face more scrutiny afterwards, not less.', writingTip: 'Common phrases: "come under scrutiny", "public scrutiny", "close scrutiny".', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['public scrutiny', 'come under scrutiny', 'parliamentary scrutiny', 'close scrutiny'], alternatives: ['examination', 'oversight'], wordFamily: ['scrutinise (v)'], priority: 'must_learn' },
    { id: 'gov_v28', type: 'vocabulary', term: 'paternalistic', pronunciation: '/pəˌtɜːnəˈlɪstɪk/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Restricting people’s freedom supposedly for their own good.', vietnameseMeaning: 'Mang tính bao bọc, quyết định thay cho dân "vì lợi ích của họ".', example: 'Critics dismiss sugar taxes as paternalistic, yet accept seatbelt laws without complaint.', writingTip: 'A precise word for the freedom-versus-protection debate that recurs in Task 2.', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['paternalistic policies', 'excessively paternalistic'], wordFamily: ['paternalism (n)'], priority: 'optional' },
    { id: 'gov_v29', type: 'vocabulary', term: 'devolve', pronunciation: '/dɪˈvɒlv/', partOfSpeech: 'verb', cefrLevel: 'C2', definition: 'To transfer power from central to local government.', vietnameseMeaning: 'Phân cấp, chuyển giao quyền lực xuống cấp dưới.', example: 'Devolving transport budgets to city regions has produced faster decisions and fewer white elephants.', writingTip: 'Pattern: "devolve power to". The noun "devolution" is common in political writing.', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['devolve power', 'devolve responsibility to', 'devolved administration'], antonym: 'centralise', wordFamily: ['devolution (n)', 'devolved (adj)'], priority: 'high_value' },
    { id: 'gov_v30', type: 'vocabulary', term: 'legitimacy', pronunciation: '/lɪˈdʒɪtɪməsi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The quality of being accepted as rightful and lawful.', vietnameseMeaning: 'Tính chính danh, sự hợp pháp được thừa nhận.', example: 'A government retains legitimacy only as long as citizens believe the rules apply equally to everyone.', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['democratic legitimacy', 'undermine legitimacy', 'question the legitimacy of'], wordFamily: ['legitimate (adj)', 'legitimise (v)'], priority: 'high_value' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'gov_c1', type: 'collocation', term: 'implement a policy', collocationType: 'Verb + Noun', definition: 'To put an official plan into practice.', vietnameseMeaning: 'Triển khai một chính sách.', example: 'It is far easier to announce a policy than to implement a policy successfully.', alternative: 'put a policy into practice', topic: 'Government', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'gov_c2', type: 'collocation', term: 'pass a law', collocationType: 'Verb + Noun', definition: 'To formally approve new legislation.', vietnameseMeaning: 'Thông qua một đạo luật.', example: 'Parliament passed a law requiring companies to publish their pay ratios.', alternative: 'enact legislation', topic: 'Government', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'You "pass" or "enact" a law — never "make a law" in formal writing.' },
    { id: 'gov_c3', type: 'collocation', term: 'fund public services', collocationType: 'Verb + Noun', definition: 'To provide money for state-run services.', vietnameseMeaning: 'Cấp kinh phí cho dịch vụ công.', example: 'Taxation is the only sustainable way to fund public services at scale.', topic: 'Government', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'gov_c4', type: 'collocation', term: 'hold an election', collocationType: 'Verb + Noun', definition: 'To organise a formal public vote.', vietnameseMeaning: 'Tổ chức một cuộc bầu cử.', example: 'Holding an election is straightforward; holding a credible one is not.', topic: 'Government', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'gov_c5', type: 'collocation', term: 'tackle corruption', collocationType: 'Verb + Noun', definition: 'To take determined action against dishonest use of power.', vietnameseMeaning: 'Đấu tranh chống tham nhũng.', example: 'Countries that tackle corruption first find that investment follows on its own.', alternative: 'combat corruption', topic: 'Government', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'gov_c6', type: 'collocation', term: 'government intervention', collocationType: 'Noun + Noun', definition: 'Action by the state to influence an outcome.', vietnameseMeaning: 'Sự can thiệp của chính phủ.', example: 'Government intervention is justified whenever markets systematically fail the poorest.', topic: 'Government', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'gov_c7', type: 'collocation', term: 'introduce regulations', collocationType: 'Verb + Noun', definition: 'To bring in new official rules.', vietnameseMeaning: 'Ban hành các quy định mới.', example: 'Regulators introduced regulations on advertising to children after years of pressure.', topic: 'Government', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'gov_c8', type: 'collocation', term: 'allocate funding', collocationType: 'Verb + Noun', definition: 'To assign money to a specific purpose.', vietnameseMeaning: 'Phân bổ kinh phí.', example: 'Ministers allocate funding on a three-year cycle, which discourages longer projects.', topic: 'Government', bandLevel: '5-6', task: 'both', priority: 'must_learn' },

    // Advanced (Band 6-7)
    { id: 'gov_c9', type: 'collocation', term: 'enforce the law', collocationType: 'Verb + Noun', definition: 'To ensure legal rules are obeyed.', vietnameseMeaning: 'Thực thi pháp luật.', example: 'Where the police lack resources to enforce the law, penalties become symbolic.', topic: 'Government', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'gov_c10', type: 'collocation', term: 'political stability', collocationType: 'Adj + Noun', definition: 'A condition in which government and institutions are secure and predictable.', vietnameseMeaning: 'Sự ổn định chính trị.', example: 'Political stability attracts long-term investment far more effectively than tax breaks.', topic: 'Government', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'gov_c11', type: 'collocation', term: 'hold politicians accountable', collocationType: 'Verb + Noun + Adj', definition: 'To require elected officials to answer for their decisions.', vietnameseMeaning: 'Buộc các chính trị gia phải chịu trách nhiệm.', example: 'A free press remains the cheapest way to hold politicians accountable between elections.', topic: 'Government', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'gov_c12', type: 'collocation', term: 'cut red tape', collocationType: 'Verb + Noun', definition: 'To remove unnecessary official procedures.', vietnameseMeaning: 'Cắt giảm thủ tục hành chính rườm rà.', example: 'Every government promises to cut red tape and almost every one adds to it.', alternative: 'reduce bureaucracy', topic: 'Government', bandLevel: '6-7', task: 'task2', priority: 'high_value', writingTip: 'A common idiom that is acceptable in Task 2, though "reduce bureaucracy" is more formal.' },
    { id: 'gov_c13', type: 'collocation', term: 'public consultation', collocationType: 'Adj + Noun', definition: 'A formal process of asking citizens for their views before deciding.', vietnameseMeaning: 'Việc lấy ý kiến người dân.', example: 'Meaningful public consultation slows decisions but greatly improves their durability.', topic: 'Government', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'gov_c14', type: 'collocation', term: 'a democratic mandate', collocationType: 'Adj + Noun', definition: 'Authority to govern granted by voters.', vietnameseMeaning: 'Sự uỷ nhiệm dân chủ từ cử tri.', example: 'Radical reform without a democratic mandate rarely outlasts the government that introduced it.', topic: 'Government', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'gov_c15', type: 'collocation', term: 'restrict civil liberties', collocationType: 'Verb + Noun', definition: 'To limit the basic freedoms of citizens.', vietnameseMeaning: 'Hạn chế các quyền tự do dân sự.', example: 'Measures that restrict civil liberties should always carry an expiry date.', topic: 'Government', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },

    // High-impact (Band 7+)
    { id: 'gov_c16', type: 'collocation', term: 'ensure transparency and accountability', collocationType: 'Verb + Noun', definition: 'To guarantee that decisions are open and those who take them answer for them.', vietnameseMeaning: 'Bảo đảm tính minh bạch và trách nhiệm giải trình.', example: 'Independent auditing is the most reliable way to ensure transparency and accountability in public spending.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'gov_c17', type: 'collocation', term: 'curtail individual freedoms', collocationType: 'Verb + Noun', definition: 'To reduce the rights individuals enjoy.', vietnameseMeaning: 'Hạn chế quyền tự do cá nhân.', example: 'Any policy that curtails individual freedoms must demonstrate a clear and proportionate benefit.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'gov_c18', type: 'collocation', term: 'devolve power to local authorities', collocationType: 'Verb + Noun', definition: 'To transfer decision-making from central to regional government.', vietnameseMeaning: 'Phân quyền cho chính quyền địa phương.', example: 'Devolving power to local authorities produces decisions better matched to local conditions.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'gov_c19', type: 'collocation', term: 'come under public scrutiny', collocationType: 'Verb + Prep + Noun', definition: 'To be examined critically by the public and the press.', vietnameseMeaning: 'Chịu sự giám sát của công chúng.', example: 'Contracts awarded without competition should come under public scrutiny as a matter of course.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'gov_c20', type: 'collocation', term: 'undermine democratic legitimacy', collocationType: 'Verb + Noun', definition: 'To weaken public acceptance of a government’s right to rule.', vietnameseMeaning: 'Làm suy yếu tính chính danh dân chủ.', example: 'Persistent unfairness in the electoral system undermines democratic legitimacy over time.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'gov_p1', type: 'phrasal_verb', term: 'bring in', partOfSpeech: 'phrasal verb (separable)', definition: 'To introduce a new law, rule or system.', vietnameseMeaning: 'Ban hành, đưa vào áp dụng (luật mới).', example: 'The government brought in tougher penalties for tax evasion last year.', formalAlternative: 'introduce', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['bring in a law', 'bring in new rules'], academicAlternatives: ['introduce', 'enact', 'institute'] },
    { id: 'gov_p2', type: 'phrasal_verb', term: 'crack down on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To take strong action against something harmful.', vietnameseMeaning: 'Mạnh tay trấn áp, siết chặt xử lý.', example: 'Authorities have cracked down on unlicensed operators after a series of accidents.', formalAlternative: 'take firm action against', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', collocations: ['crack down on crime', 'a crackdown on'], academicAlternatives: ['take firm action against', 'clamp down on', 'suppress'] },
    { id: 'gov_p3', type: 'phrasal_verb', term: 'set out', partOfSpeech: 'phrasal verb (separable)', definition: 'To present or explain something in an organised way.', vietnameseMeaning: 'Trình bày, nêu rõ (kế hoạch, lập luận).', example: 'The report sets out five recommendations, only two of which have been adopted.', formalAlternative: 'outline', topic: 'Government', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', priority: 'high_value', collocations: ['set out proposals', 'set out a plan', 'set out the case for'], academicAlternatives: ['outline', 'present', 'articulate'] },
    { id: 'gov_p4', type: 'phrasal_verb', term: 'call for', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To publicly demand or urge something.', vietnameseMeaning: 'Kêu gọi, yêu cầu công khai.', example: 'Campaigners have called for an independent inquiry into the decision.', formalAlternative: 'demand', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['call for reform', 'call for action', 'call for an inquiry'], academicAlternatives: ['demand', 'urge', 'advocate'] },
    { id: 'gov_p5', type: 'phrasal_verb', term: 'step in', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To become involved in order to help or prevent trouble.', vietnameseMeaning: 'Can thiệp vào để xử lý tình huống.', example: 'When private providers fail, the state is expected to step in whatever the cost.', formalAlternative: 'intervene', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['intervene', 'take over'] },

    // Advanced / less common
    { id: 'gov_p6', type: 'phrasal_verb', term: 'push through', partOfSpeech: 'phrasal verb (separable)', definition: 'To force a law or proposal to be accepted despite opposition.', vietnameseMeaning: 'Thúc đẩy thông qua bất chấp phản đối.', example: 'Legislation pushed through without debate is frequently amended within a year.', formalAlternative: 'force through', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['expedite', 'force through', 'ratify hastily'] },
    { id: 'gov_p7', type: 'phrasal_verb', term: 'water down', partOfSpeech: 'phrasal verb (separable)', definition: 'To make a proposal less strong or effective.', vietnameseMeaning: 'Làm loãng, giảm nhẹ mức độ (đề xuất, quy định).', example: 'The original proposals were watered down after intensive lobbying by the industry.', formalAlternative: 'dilute', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['dilute', 'weaken', 'moderate'] },
    { id: 'gov_p8', type: 'phrasal_verb', term: 'do away with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To abolish or get rid of something.', vietnameseMeaning: 'Bãi bỏ, xoá bỏ hoàn toàn.', example: 'Several countries have done away with cash bail entirely.', formalAlternative: 'abolish', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Informal. "Abolish" or "eliminate" is preferable in a Task 2 essay.', academicAlternatives: ['abolish', 'eliminate', 'repeal'] },
    { id: 'gov_p9', type: 'phrasal_verb', term: 'opt out of', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To choose not to take part in something.', vietnameseMeaning: 'Chọn không tham gia, rút khỏi.', example: 'Allowing wealthy districts to opt out of the funding formula defeats its purpose.', formalAlternative: 'withdraw from', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', usageWarning: 'The opposite is "opt in to". Keep the preposition — "opt out something" is incorrect.', academicAlternatives: ['withdraw from', 'decline to participate in'] },
    { id: 'gov_p10', type: 'phrasal_verb', term: 'roll back', partOfSpeech: 'phrasal verb (separable)', definition: 'To reverse or reduce something that was previously introduced.', vietnameseMeaning: 'Thu hồi, đảo ngược (chính sách đã ban hành).', example: 'Successive administrations have rolled back environmental protections introduced a generation ago.', formalAlternative: 'reverse', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['reverse', 'repeal', 'rescind'] },
  ],

  writingPhrases: [
    { id: 'gov_w1', type: 'writing_phrase', term: 'There is a strong case for state intervention where...', function: 'Introducing an argument', vietnameseMeaning: 'Có cơ sở vững chắc cho sự can thiệp của nhà nước khi...', example: 'There is a strong case for state intervention where the market cannot price a harm accurately.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'gov_w2', type: 'writing_phrase', term: 'Governments favour such measures because they...', function: 'Giving a reason', vietnameseMeaning: 'Các chính phủ ưa chuộng những biện pháp này vì chúng...', example: 'Governments favour such measures because they produce visible results within a single electoral cycle.', topic: 'Government', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'gov_w3', type: 'writing_phrase', term: 'This failure of policy originates in...', function: 'Explaining a cause', vietnameseMeaning: 'Thất bại chính sách này bắt nguồn từ...', example: 'This failure of policy originates in a refusal to fund enforcement alongside legislation.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'gov_w4', type: 'writing_phrase', term: 'The practical consequence for ordinary citizens is that...', function: 'Explaining an effect', vietnameseMeaning: 'Hệ quả thực tế đối với người dân bình thường là...', example: 'The practical consequence for ordinary citizens is that they wait months for a decision that once took days.', topic: 'Government', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'gov_w5', type: 'writing_phrase', term: 'The introduction of the congestion charge in London is instructive here:', function: 'Giving an example', vietnameseMeaning: 'Việc áp dụng phí ùn tắc ở London là một bài học đáng chú ý ở đây:', example: 'The introduction of the congestion charge in London is instructive here: traffic fell immediately and revenue funded public transport.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'gov_w6', type: 'writing_phrase', term: 'The main advantage of regulating this sector is that...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi ích chính của việc quản lý lĩnh vực này là...', example: 'The main advantage of regulating this sector is that it establishes a floor below which no provider can fall.', topic: 'Government', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'gov_w7', type: 'writing_phrase', term: 'The danger of granting such powers is that they are rarely...', function: 'Discussing disadvantages', vietnameseMeaning: 'Nguy cơ của việc trao những quyền lực như vậy là chúng hiếm khi...', example: 'The danger of granting such powers is that they are rarely surrendered once the emergency has passed.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'gov_w8', type: 'writing_phrase', term: 'A more proportionate response would be to...', function: 'Suggesting a solution', vietnameseMeaning: 'Một phản ứng cân xứng hơn sẽ là...', example: 'A more proportionate response would be to require disclosure rather than to prohibit the practice outright.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'gov_w9', type: 'writing_phrase', term: 'I would contend that the state has a duty to...', function: 'Expressing an opinion', vietnameseMeaning: 'Tôi cho rằng nhà nước có nghĩa vụ phải...', example: 'I would contend that the state has a duty to protect those least able to protect themselves.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'gov_w10', type: 'writing_phrase', term: 'Legislation changes behaviour quickly; education changes attitudes, but only...', function: 'Comparing ideas', vietnameseMeaning: 'Luật pháp thay đổi hành vi nhanh chóng; giáo dục thay đổi thái độ, nhưng chỉ...', example: 'Legislation changes behaviour quickly; education changes attitudes, but only over a generation.', topic: 'Government', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'gov_m1', type: 'common_mistake', incorrect: 'The government should to reduce income tax.', correct: 'The government should reduce income tax.', explanation: 'Modal verbs (should, must, can, will) are always followed by the bare infinitive — never by "to".', topic: 'Government', priority: 'must_learn' },
    { id: 'gov_m2', type: 'common_mistake', incorrect: 'Authorities must pay attention on this issue.', correct: 'Authorities must pay attention to this issue.', explanation: 'The fixed phrase is "pay attention to". Vietnamese learners often transfer the preposition "on" from "chú ý vào".', topic: 'Government', priority: 'must_learn' },
    { id: 'gov_m3', type: 'common_mistake', incorrect: 'Stricter legislations are needed to protect workers.', correct: 'Stricter legislation is needed to protect workers.', explanation: '"Legislation" is uncountable and takes a singular verb. If you need a countable noun, use "laws" or "regulations".', topic: 'Government', priority: 'must_learn' },
    { id: 'gov_m4', type: 'common_mistake', incorrect: 'In my country, government spends too little on housing.', correct: 'In my country, the government spends too little on housing.', explanation: '"Government" referring to a specific country’s government always takes "the". Only "in government" as an abstract state omits it.', topic: 'Government', priority: 'must_learn' },
    { id: 'gov_m5', type: 'common_mistake', incorrect: 'The law was introduced in order to reducing accidents.', correct: 'The law was introduced in order to reduce accidents.', explanation: '"In order to" is followed by the bare infinitive. Use "in order that" plus a clause, or "with a view to reducing" if you want the -ing form.', topic: 'Government', priority: 'high_value' },
  ],

  learnFirst: {
    vocabulary: ['gov_v1', 'gov_v2', 'gov_v11', 'gov_v13', 'gov_v14', 'gov_v16', 'gov_v21', 'gov_v23', 'gov_v26', 'gov_v27'],
    collocations: ['gov_c1', 'gov_c6', 'gov_c9', 'gov_c11', 'gov_c16'],
    phrasalVerbs: ['gov_p2', 'gov_p4', 'gov_p3'],
    writingPhrases: ['gov_w1', 'gov_w7', 'gov_w9'],
  },
}
