import type { TopicData } from '../types'

export const HEALTH: TopicData = {
  topic: 'Health',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'hlt_v1', type: 'vocabulary', term: 'obesity', pronunciation: '/əʊˈbiːsəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The condition of being extremely overweight in a way that harms health.', vietnameseMeaning: 'Bệnh béo phì.', example: 'Childhood obesity has tripled in many developed countries since the 1980s.', writingTip: 'Uncountable. The adjective is "obese", which is far stronger than "fat" and more appropriate in writing.', topic: 'Health', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['childhood obesity', 'rising obesity rates', 'tackle obesity', 'the obesity epidemic'], wordFamily: ['obese (adj)'], priority: 'must_learn' },
    { id: 'hlt_v2', type: 'vocabulary', term: 'diet', pronunciation: '/ˈdaɪət/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'The food a person or group usually eats.', vietnameseMeaning: 'Chế độ ăn uống, khẩu phần ăn.', example: 'A diet high in processed food is closely linked to heart disease.', writingTip: 'Note the two meanings: "a balanced diet" (habitual eating) and "go on a diet" (lose weight).', topic: 'Health', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a balanced diet', 'a healthy diet', 'a poor diet', 'dietary habits'], wordFamily: ['dietary (adj)', 'dietician (n)'], priority: 'must_learn' },
    { id: 'hlt_v3', type: 'vocabulary', term: 'disease', pronunciation: '/dɪˈziːz/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'An illness affecting people, animals or plants.', vietnameseMeaning: 'Bệnh tật, căn bệnh.', example: 'Cardiovascular disease remains the leading cause of death worldwide.', writingTip: '"Disease" is usually a named, identifiable condition; "illness" is the broader experience of being unwell.', topic: 'Health', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['infectious disease', 'chronic disease', 'prevent disease', 'spread of disease'], alternatives: ['illness', 'condition', 'ailment'], priority: 'must_learn' },
    { id: 'hlt_v4', type: 'vocabulary', term: 'lifestyle', pronunciation: '/ˈlaɪfstaɪl/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'The way in which a person lives, including habits and daily choices.', vietnameseMeaning: 'Lối sống, phong cách sinh hoạt.', example: 'Most so-called lifestyle diseases could be prevented by modest changes in daily habits.', writingTip: 'The natural verb is "lead": "lead a healthy lifestyle", not "have a healthy lifestyle".', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a healthy lifestyle', 'a sedentary lifestyle', 'lead a lifestyle', 'lifestyle choices'], priority: 'must_learn' },
    { id: 'hlt_v5', type: 'vocabulary', term: 'treatment', pronunciation: '/ˈtriːtmənt/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'Medical care given to a patient for an illness or injury.', vietnameseMeaning: 'Việc điều trị, phương pháp chữa trị.', example: 'Early treatment dramatically improves survival rates for most cancers.', writingTip: 'Uncountable in general use, countable when referring to specific therapies ("new treatments for diabetes").', topic: 'Health', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['medical treatment', 'receive treatment', 'effective treatment', 'access to treatment'], wordFamily: ['treat (v)', 'treatable (adj)'], priority: 'high_value' },
    { id: 'hlt_v6', type: 'vocabulary', term: 'prevent', pronunciation: '/prɪˈvent/', partOfSpeech: 'verb', cefrLevel: 'B1', definition: 'To stop something from happening.', vietnameseMeaning: 'Ngăn ngừa, phòng tránh.', example: 'Vaccination programmes prevent far more deaths than any hospital treatment.', writingTip: 'Pattern: "prevent somebody from doing something". Never "prevent somebody to do".', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['prevent disease', 'prevent illness', 'prevent the spread of'], alternatives: ['avert', 'avoid', 'stop'], wordFamily: ['prevention (n)', 'preventable (adj)', 'preventative (adj)'], priority: 'must_learn' },
    { id: 'hlt_v7', type: 'vocabulary', term: 'healthcare', pronunciation: '/ˈhelθkeə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The organised provision of medical services to a population.', vietnameseMeaning: 'Chăm sóc sức khoẻ, dịch vụ y tế.', example: 'Universal healthcare is expensive, but treating preventable illness late is more expensive still.', writingTip: 'Written as one word in British English. Uncountable — no plural.', topic: 'Health', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['public healthcare', 'access to healthcare', 'the healthcare system', 'free healthcare'], priority: 'must_learn' },
    { id: 'hlt_v8', type: 'vocabulary', term: 'nutrition', pronunciation: '/njuˈtrɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The process of obtaining the food necessary for health and growth.', vietnameseMeaning: 'Dinh dưỡng.', example: 'Poor nutrition in early childhood has consequences that persist into adult life.', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['good nutrition', 'poor nutrition', 'nutritional value', 'nutrition education'], wordFamily: ['nutritious (adj)', 'nutritional (adj)', 'nutrient (n)'], priority: 'high_value' },
    { id: 'hlt_v9', type: 'vocabulary', term: 'mental health', pronunciation: '/ˌmentl ˈhelθ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'A person’s emotional and psychological wellbeing.', vietnameseMeaning: 'Sức khoẻ tâm thần, sức khoẻ tinh thần.', example: 'Mental health services remain chronically underfunded in comparison with physical medicine.', writingTip: 'One of the most examinable health sub-topics. Pair with "stigma", "support", "services".', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['mental health problems', 'mental health services', 'poor mental health'], priority: 'must_learn' },
    { id: 'hlt_v10', type: 'vocabulary', term: 'vaccination', pronunciation: '/ˌvæksɪˈneɪʃn/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'The act of giving someone a substance that protects them against a disease.', vietnameseMeaning: 'Việc tiêm chủng, tiêm vắc-xin.', example: 'Mass vaccination has eliminated diseases that killed millions a century ago.', topic: 'Health', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['mass vaccination', 'vaccination programme', 'vaccination rates'], wordFamily: ['vaccinate (v)', 'vaccine (n)'], priority: 'high_value' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'hlt_v11', type: 'vocabulary', term: 'sedentary', pronunciation: '/ˈsedntri/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Involving a great deal of sitting and very little physical activity.', vietnameseMeaning: 'Ít vận động, ngồi nhiều.', example: 'Office work has made a sedentary lifestyle the norm rather than the exception.', writingTip: 'Almost always used with "lifestyle", "work", "behaviour" or "occupation".', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a sedentary lifestyle', 'sedentary work', 'increasingly sedentary'], antonym: 'active', priority: 'must_learn' },
    { id: 'hlt_v12', type: 'vocabulary', term: 'prevalence', pronunciation: '/ˈprevələns/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'How widespread or common something is within a population.', vietnameseMeaning: 'Mức độ phổ biến, tỷ lệ mắc trong dân số.', example: 'The prevalence of type 2 diabetes has risen in step with average body weight.', writingTip: 'Use "the prevalence of X" as a subject — it produces a much more academic sentence than "many people have X".', topic: 'Health', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['the prevalence of', 'high prevalence', 'growing prevalence'], alternatives: ['incidence', 'frequency'], wordFamily: ['prevalent (adj)'], priority: 'must_learn' },
    { id: 'hlt_v13', type: 'vocabulary', term: 'alleviate', pronunciation: '/əˈliːvieɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To make pain, suffering or a problem less severe.', vietnameseMeaning: 'Làm giảm bớt, xoa dịu (đau đớn, áp lực).', example: 'Regular exercise alleviates the symptoms of mild depression as effectively as medication.', writingTip: 'Use with suffering, symptoms, pressure, stress, poverty — not with numbers or quantities.', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['alleviate symptoms', 'alleviate suffering', 'alleviate pressure', 'alleviate stress'], alternatives: ['relieve', 'ease', 'mitigate'], antonym: 'aggravate', wordFamily: ['alleviation (n)'], priority: 'must_learn' },
    { id: 'hlt_v14', type: 'vocabulary', term: 'chronic', pronunciation: '/ˈkrɒnɪk/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Continuing for a long time and difficult to cure.', vietnameseMeaning: 'Mãn tính, kéo dài dai dẳng.', example: 'Health systems designed for acute illness struggle to manage chronic conditions.', writingTip: 'The opposite is "acute" (severe but short). Also used outside medicine: "chronic underfunding".', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['chronic illness', 'chronic pain', 'chronic condition', 'chronic shortage'], antonym: 'acute', wordFamily: ['chronically (adv)'], priority: 'must_learn' },
    { id: 'hlt_v15', type: 'vocabulary', term: 'epidemic', pronunciation: '/ˌepɪˈdemɪk/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A rapid spread of disease through a population; a rapid rise in any harmful phenomenon.', vietnameseMeaning: 'Dịch bệnh; hiện tượng lan rộng nhanh chóng.', example: 'Public health officials now speak openly of an epidemic of loneliness among the elderly.', writingTip: 'An epidemic is regional; a pandemic is global. The figurative use ("an obesity epidemic") is common and accepted.', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['an obesity epidemic', 'contain an epidemic', 'a global pandemic'], wordFamily: ['epidemiology (n)', 'pandemic (n)'], priority: 'high_value' },
    { id: 'hlt_v16', type: 'vocabulary', term: 'life expectancy', pronunciation: '/ˈlaɪf ɪkˌspektənsi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The average number of years a person is expected to live.', vietnameseMeaning: 'Tuổi thọ trung bình.', example: 'Life expectancy in the poorest districts is almost a decade lower than in the wealthiest.', writingTip: 'Essential for Task 1 data on population. Verbs: rise, fall, exceed, lag behind.', topic: 'Health', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['rising life expectancy', 'average life expectancy', 'life expectancy at birth'], priority: 'must_learn' },
    { id: 'hlt_v17', type: 'vocabulary', term: 'wellbeing', pronunciation: '/ˌwelˈbiːɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The general state of being comfortable, healthy and content.', vietnameseMeaning: 'Sự khoẻ mạnh và hạnh phúc nói chung.', example: 'Access to green space measurably improves the wellbeing of city residents.', writingTip: 'Broader than "health" — it covers emotional and social quality of life as well as physical condition.', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['emotional wellbeing', 'physical wellbeing', 'promote wellbeing', 'a sense of wellbeing'], priority: 'high_value' },
    { id: 'hlt_v18', type: 'vocabulary', term: 'diagnose', pronunciation: '/ˈdaɪəɡnəʊz/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To identify an illness by examining its symptoms.', vietnameseMeaning: 'Chẩn đoán (bệnh).', example: 'Conditions diagnosed at an early stage are usually far cheaper to treat.', writingTip: 'Usually passive: "patients are diagnosed with", "the disease was diagnosed".', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['be diagnosed with', 'early diagnosis', 'accurate diagnosis'], wordFamily: ['diagnosis (n)', 'diagnostic (adj)'], priority: 'high_value' },
    { id: 'hlt_v19', type: 'vocabulary', term: 'preventative', pronunciation: '/prɪˈventətɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Intended to stop something bad from happening.', vietnameseMeaning: 'Mang tính phòng ngừa, dự phòng.', example: 'Every pound spent on preventative medicine saves several pounds in later hospital costs.', writingTip: '"Preventive" and "preventative" are both correct; be consistent within one essay.', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['preventative measures', 'preventative medicine', 'preventative care'], antonym: 'curative', priority: 'must_learn' },
    { id: 'hlt_v20', type: 'vocabulary', term: 'addiction', pronunciation: '/əˈdɪkʃn/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A condition in which someone is unable to stop using or doing something harmful.', vietnameseMeaning: 'Sự nghiện ngập, tình trạng lệ thuộc.', example: 'Treating addiction as a medical problem rather than a crime produces better outcomes.', writingTip: 'Followed by "to": addiction to alcohol, to gambling, to social media.', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['drug addiction', 'addiction to', 'treat addiction', 'overcome addiction'], wordFamily: ['addict (n)', 'addicted (adj)', 'addictive (adj)'], priority: 'high_value' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'hlt_v21', type: 'vocabulary', term: 'susceptible', pronunciation: '/səˈseptəbl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Likely to be affected or harmed by something.', vietnameseMeaning: 'Dễ bị ảnh hưởng, dễ mắc phải.', example: 'Older adults are particularly susceptible to complications from respiratory infections.', writingTip: 'Always "susceptible to". A precise upgrade from "easily gets".', topic: 'Health', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['susceptible to infection', 'particularly susceptible', 'more susceptible to'], alternatives: ['vulnerable to', 'prone to'], antonym: 'resistant', wordFamily: ['susceptibility (n)'], priority: 'must_learn' },
    { id: 'hlt_v22', type: 'vocabulary', term: 'adverse', pronunciation: '/ˈædvɜːs/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Harmful or unfavourable.', vietnameseMeaning: 'Bất lợi, có hại.', example: 'Long working hours have well-documented adverse effects on cardiovascular health.', writingTip: 'Do not confuse with "averse" (unwilling). "Adverse effects" is the standard medical phrase.', topic: 'Health', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['adverse effects', 'adverse consequences', 'adverse conditions', 'adverse reaction'], alternatives: ['harmful', 'detrimental', 'negative'], antonym: 'favourable', wordFamily: ['adversely (adv)', 'adversity (n)'], priority: 'must_learn' },
    { id: 'hlt_v23', type: 'vocabulary', term: 'malnutrition', pronunciation: '/ˌmælnjuˈtrɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Poor health caused by not eating enough, or by an unbalanced diet.', vietnameseMeaning: 'Suy dinh dưỡng.', example: 'Malnutrition takes two forms: too little food in poor regions and too much of the wrong food in rich ones.', topic: 'Health', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['suffer from malnutrition', 'chronic malnutrition', 'child malnutrition'], wordFamily: ['malnourished (adj)'], priority: 'high_value' },
    { id: 'hlt_v24', type: 'vocabulary', term: 'debilitating', pronunciation: '/dɪˈbɪlɪteɪtɪŋ/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Making someone very weak and unable to function normally.', vietnameseMeaning: 'Làm suy nhược, khiến cơ thể yếu đi rõ rệt.', example: 'Chronic fatigue is a debilitating condition that is still widely misunderstood.', writingTip: 'Use before serious illnesses only — it is a strong word and loses force if overused.', topic: 'Health', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['a debilitating illness', 'debilitating pain', 'profoundly debilitating'], alternatives: ['incapacitating', 'crippling'], wordFamily: ['debilitate (v)'], priority: 'optional' },
    { id: 'hlt_v25', type: 'vocabulary', term: 'stigma', pronunciation: '/ˈstɪɡmə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Strong social disapproval attached to a condition or behaviour.', vietnameseMeaning: 'Sự kỳ thị, định kiến xã hội.', example: 'The stigma surrounding mental illness prevents many sufferers from seeking help at all.', writingTip: 'Collocates with "surrounding", "attached to" and the verbs "reduce" and "remove".', topic: 'Health', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['social stigma', 'the stigma surrounding', 'reduce the stigma', 'attach stigma to'], wordFamily: ['stigmatise (v)', 'stigmatised (adj)'], priority: 'must_learn' },
    { id: 'hlt_v26', type: 'vocabulary', term: 'onset', pronunciation: '/ˈɒnset/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The beginning of something, usually unpleasant.', vietnameseMeaning: 'Sự khởi phát, giai đoạn bắt đầu (của bệnh).', example: 'Regular activity can delay the onset of age-related decline by several years.', writingTip: 'Always "the onset of". Very natural with diseases, symptoms and winter.', topic: 'Health', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the onset of disease', 'delay the onset', 'early onset', 'sudden onset'], alternatives: ['beginning', 'start', 'emergence'], priority: 'high_value' },
    { id: 'hlt_v27', type: 'vocabulary', term: 'eradicate', pronunciation: '/ɪˈrædɪkeɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To destroy or get rid of something completely.', vietnameseMeaning: 'Xoá sổ, tiêu diệt hoàn toàn.', example: 'Smallpox remains the only human disease to have been eradicated entirely.', writingTip: 'Implies total elimination — do not use it for problems that can only be reduced.', topic: 'Health', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['eradicate disease', 'eradicate poverty', 'completely eradicate'], alternatives: ['eliminate', 'wipe out', 'stamp out'], wordFamily: ['eradication (n)'], priority: 'high_value' },
    { id: 'hlt_v28', type: 'vocabulary', term: 'sanitation', pronunciation: '/ˌsænɪˈteɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Systems for keeping places clean, especially for removing sewage and waste.', vietnameseMeaning: 'Điều kiện vệ sinh, hệ thống xử lý nước thải.', example: 'Clean water and adequate sanitation have saved more lives than any single medicine.', topic: 'Health', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['poor sanitation', 'adequate sanitation', 'access to sanitation', 'sanitation facilities'], wordFamily: ['sanitary (adj)'], priority: 'high_value' },
    { id: 'hlt_v29', type: 'vocabulary', term: 'longevity', pronunciation: '/lɒnˈdʒevəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Long life, or the length of time something lasts.', vietnameseMeaning: 'Sự trường thọ, tuổi thọ cao.', example: 'Diet, exercise and strong social ties are the three factors most consistently linked to longevity.', writingTip: 'A single elegant noun that replaces "the fact that people live a long time".', topic: 'Health', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['increased longevity', 'contribute to longevity', 'human longevity'], priority: 'high_value' },
    { id: 'hlt_v30', type: 'vocabulary', term: 'burnout', pronunciation: '/ˈbɜːnaʊt/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Extreme physical and emotional exhaustion caused by prolonged stress.', vietnameseMeaning: 'Tình trạng kiệt sức vì căng thẳng kéo dài.', example: 'Burnout among healthcare staff intensified sharply during the pandemic.', writingTip: 'Now recognised as an occupational phenomenon — very useful in work-and-health essays.', topic: 'Health', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['suffer burnout', 'workplace burnout', 'the risk of burnout'], alternatives: ['exhaustion', 'emotional fatigue'], wordFamily: ['burn out (v)', 'burnt out (adj)'], priority: 'high_value' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'hlt_c1', type: 'collocation', term: 'a balanced diet', collocationType: 'Adj + Noun', definition: 'Food intake containing the right proportions of all nutrients.', vietnameseMeaning: 'Chế độ ăn cân bằng, đầy đủ dinh dưỡng.', example: 'A balanced diet costs more than processed food, which is why poverty and poor health travel together.', topic: 'Health', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'Not "an equal diet" or "a fully diet" — "balanced" is the fixed adjective.' },
    { id: 'hlt_c2', type: 'collocation', term: 'lead a healthy lifestyle', collocationType: 'Verb + Noun', definition: 'To live in a way that supports good health.', vietnameseMeaning: 'Sống một lối sống lành mạnh.', example: 'People who lead a healthy lifestyle in their thirties enjoy measurable benefits decades later.', topic: 'Health', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'The verb is "lead", not "have" or "live".' },
    { id: 'hlt_c3', type: 'collocation', term: 'public health', collocationType: 'Adj + Noun', definition: 'The health of a population as a whole, and the systems that protect it.', vietnameseMeaning: 'Sức khoẻ cộng đồng, y tế công cộng.', example: 'Air quality is a public health issue as much as an environmental one.', topic: 'Health', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'hlt_c4', type: 'collocation', term: 'raise public awareness', collocationType: 'Verb + Noun', definition: 'To make more people understand an issue.', vietnameseMeaning: 'Nâng cao nhận thức cộng đồng.', example: 'Campaigns to raise public awareness of stroke symptoms have cut response times significantly.', topic: 'Health', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_c5', type: 'collocation', term: 'medical treatment', collocationType: 'Adj + Noun', definition: 'Care provided by doctors and hospitals.', vietnameseMeaning: 'Điều trị y tế.', example: 'Millions of people delay medical treatment because they cannot afford it.', topic: 'Health', bandLevel: '5-6', task: 'both', priority: 'high_value' },
    { id: 'hlt_c6', type: 'collocation', term: 'prevent disease', collocationType: 'Verb + Noun', definition: 'To stop illness from developing.', vietnameseMeaning: 'Phòng ngừa bệnh tật.', example: 'Investing in clean water does more to prevent disease than building new hospitals.', topic: 'Health', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_c7', type: 'collocation', term: 'the healthcare system', collocationType: 'Noun + Noun', definition: 'The organised network of medical services in a country.', vietnameseMeaning: 'Hệ thống y tế.', example: 'An ageing population will place the healthcare system under unprecedented strain.', topic: 'Health', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'hlt_c8', type: 'collocation', term: 'take regular exercise', collocationType: 'Verb + Noun', definition: 'To be physically active on a consistent basis.', vietnameseMeaning: 'Tập thể dục đều đặn.', example: 'Adults who take regular exercise report better sleep and lower levels of anxiety.', alternative: 'exercise regularly', topic: 'Health', bandLevel: '5-6', task: 'task2', priority: 'high_value', writingTip: 'British English says "take exercise"; "do exercise" is also heard but "take" is more formal.' },

    // Advanced (Band 6-7)
    { id: 'hlt_c9', type: 'collocation', term: 'a sedentary lifestyle', collocationType: 'Adj + Noun', definition: 'A way of living that involves very little movement.', vietnameseMeaning: 'Lối sống ít vận động.', example: 'A sedentary lifestyle is now considered as damaging to health as smoking.', topic: 'Health', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_c10', type: 'collocation', term: 'chronic illness', collocationType: 'Adj + Noun', definition: 'A long-lasting medical condition.', vietnameseMeaning: 'Bệnh mãn tính.', example: 'Managing chronic illness accounts for the majority of health spending in developed nations.', topic: 'Health', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_c11', type: 'collocation', term: 'increase life expectancy', collocationType: 'Verb + Noun', definition: 'To raise the average number of years people live.', vietnameseMeaning: 'Nâng cao tuổi thọ trung bình.', example: 'Better sanitation did more to increase life expectancy than any medical breakthrough.', topic: 'Health', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'hlt_c12', type: 'collocation', term: 'mental health problems', collocationType: 'Adj + Noun', definition: 'Conditions affecting emotional and psychological wellbeing.', vietnameseMeaning: 'Các vấn đề về sức khoẻ tâm thần.', example: 'One in four adults will experience mental health problems in any given year.', topic: 'Health', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_c13', type: 'collocation', term: 'put a strain on health services', collocationType: 'Verb + Noun', definition: 'To place pressure on medical systems beyond what they can comfortably handle.', vietnameseMeaning: 'Gây áp lực lên hệ thống y tế.', example: 'Preventable lifestyle diseases put a strain on health services that are already overstretched.', alternative: 'place pressure on hospitals', topic: 'Health', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'hlt_c14', type: 'collocation', term: 'the prevalence of obesity', collocationType: 'Noun + Prep + Noun', definition: 'How common excessive body weight is within a population.', vietnameseMeaning: 'Tỷ lệ béo phì trong dân số.', example: 'The prevalence of obesity correlates closely with the availability of cheap processed food.', topic: 'Health', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'hlt_c15', type: 'collocation', term: 'access to healthcare', collocationType: 'Noun + Prep + Noun', definition: 'The ability of people to obtain medical services.', vietnameseMeaning: 'Khả năng tiếp cận dịch vụ y tế.', example: 'Unequal access to healthcare explains much of the difference in life expectancy between regions.', topic: 'Health', bandLevel: '6-7', task: 'both', priority: 'must_learn' },

    // High-impact (Band 7+)
    { id: 'hlt_c16', type: 'collocation', term: 'alleviate symptoms', collocationType: 'Verb + Noun', definition: 'To make the effects of an illness less severe.', vietnameseMeaning: 'Làm giảm nhẹ các triệu chứng.', example: 'Mindfulness training has been shown to alleviate symptoms of anxiety in clinical trials.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_c17', type: 'collocation', term: 'preventative measures', collocationType: 'Adj + Noun', definition: 'Actions taken to stop a problem from arising.', vietnameseMeaning: 'Các biện pháp phòng ngừa.', example: 'Preventative measures such as screening cost a fraction of late-stage treatment.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_c18', type: 'collocation', term: 'be susceptible to infection', collocationType: 'Adj + Prep + Noun', definition: 'To be at greater risk of catching a disease.', vietnameseMeaning: 'Dễ bị nhiễm bệnh.', example: 'Malnourished children are far more susceptible to infection than their well-fed peers.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'hlt_c19', type: 'collocation', term: 'eradicate infectious diseases', collocationType: 'Verb + Noun', definition: 'To eliminate contagious illnesses completely.', vietnameseMeaning: 'Xoá sổ hoàn toàn các bệnh truyền nhiễm.', example: 'International cooperation is the only realistic route to eradicating infectious diseases.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'hlt_c20', type: 'collocation', term: 'a nutritional deficiency', collocationType: 'Adj + Noun', definition: 'A harmful lack of a particular nutrient in the diet.', vietnameseMeaning: 'Tình trạng thiếu hụt dinh dưỡng.', example: 'Iron deficiency remains the most widespread nutritional deficiency in the world.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'optional' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'hlt_p1', type: 'phrasal_verb', term: 'come down with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To start suffering from a minor illness.', vietnameseMeaning: 'Bị mắc (một bệnh nhẹ), đổ bệnh.', example: 'Office workers come down with far more colds during winter months.', formalAlternative: 'contract', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Informal and only used for mild illnesses. Write "contract an illness" in a formal essay.', academicAlternatives: ['contract', 'develop', 'be diagnosed with'] },
    { id: 'hlt_p2', type: 'phrasal_verb', term: 'give up', partOfSpeech: 'phrasal verb (separable)', definition: 'To stop doing something, especially a habit.', vietnameseMeaning: 'Từ bỏ, cai (thuốc lá, rượu).', example: 'Financial incentives have persuaded more smokers to give up than warning labels ever did.', formalAlternative: 'quit', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', collocations: ['give up smoking', 'give up alcohol'], academicAlternatives: ['abandon', 'cease', 'quit'] },
    { id: 'hlt_p3', type: 'phrasal_verb', term: 'pass on', partOfSpeech: 'phrasal verb (separable)', definition: 'To transmit a disease or trait to someone else.', vietnameseMeaning: 'Truyền, lây (bệnh) cho người khác.', example: 'Patients can pass on the virus for several days before showing any symptoms.', formalAlternative: 'transmit', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['transmit', 'spread', 'communicate'] },
    { id: 'hlt_p4', type: 'phrasal_verb', term: 'work out', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To exercise, especially in a gym.', vietnameseMeaning: 'Tập luyện thể hình, tập gym.', example: 'People who work out with a friend are considerably more likely to keep going.', formalAlternative: 'exercise', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'optional', usageWarning: 'Informal. Prefer "exercise" or "take regular exercise" in Task 2.', academicAlternatives: ['exercise', 'train'] },
    { id: 'hlt_p5', type: 'phrasal_verb', term: 'get over', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To recover from an illness or difficult experience.', vietnameseMeaning: 'Hồi phục sau bệnh, vượt qua.', example: 'Older patients take considerably longer to get over routine surgery.', formalAlternative: 'recover from', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Conversational. "Recover from" is the academic choice.', academicAlternatives: ['recover from', 'overcome'] },

    // Advanced / less common
    { id: 'hlt_p6', type: 'phrasal_verb', term: 'wear off', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To gradually lose effect.', vietnameseMeaning: 'Hết tác dụng dần (thuốc).', example: 'The protection offered by some vaccines wears off within a year, requiring booster doses.', formalAlternative: 'diminish', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['diminish', 'subside', 'fade'] },
    { id: 'hlt_p7', type: 'phrasal_verb', term: 'build up', partOfSpeech: 'phrasal verb (separable)', definition: 'To increase or accumulate gradually.', vietnameseMeaning: 'Tích tụ dần; xây dựng, tăng cường dần.', example: 'Exposure to a variety of microbes helps children build up natural immunity.', formalAlternative: 'accumulate', topic: 'Health', bandLevel: '6-7', task: 'both', writingSuitability: 'suitable', priority: 'high_value', collocations: ['build up immunity', 'build up resistance', 'build up over time'], academicAlternatives: ['accumulate', 'strengthen', 'develop'] },
    { id: 'hlt_p8', type: 'phrasal_verb', term: 'stem from', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To be caused by or originate in something.', vietnameseMeaning: 'Bắt nguồn từ, xuất phát từ.', example: 'Many adult health problems stem from habits formed in adolescence.', formalAlternative: 'originate in', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', academicAlternatives: ['originate in', 'arise from', 'derive from'] },
    { id: 'hlt_p9', type: 'phrasal_verb', term: 'bring on', partOfSpeech: 'phrasal verb (separable)', definition: 'To cause something unpleasant to begin.', vietnameseMeaning: 'Gây ra, làm khởi phát (cơn bệnh).', example: 'Prolonged stress can bring on physical symptoms that patients rarely connect to their work.', formalAlternative: 'trigger', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['trigger', 'induce', 'precipitate'] },
    { id: 'hlt_p10', type: 'phrasal_verb', term: 'fend off', partOfSpeech: 'phrasal verb (separable)', definition: 'To defend yourself against something harmful.', vietnameseMeaning: 'Chống lại, đẩy lùi (bệnh tật, tấn công).', example: 'A well-nourished body is far better able to fend off infection.', formalAlternative: 'resist', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['resist', 'repel', 'ward off'] },
  ],

  writingPhrases: [
    { id: 'hlt_w1', type: 'writing_phrase', term: 'The case for investing in prevention rather than treatment rests on...', function: 'Introducing an argument', vietnameseMeaning: 'Lập luận ủng hộ đầu tư vào phòng bệnh thay vì chữa bệnh dựa trên...', example: 'The case for investing in prevention rather than treatment rests on a simple economic calculation.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_w2', type: 'writing_phrase', term: 'A significant factor behind rising obesity rates is...', function: 'Giving a reason', vietnameseMeaning: 'Một yếu tố quan trọng đằng sau tỷ lệ béo phì gia tăng là...', example: 'A significant factor behind rising obesity rates is the sheer availability of cheap, calorie-dense food.', topic: 'Health', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_w3', type: 'writing_phrase', term: 'This deterioration in public health can be attributed to...', function: 'Explaining a cause', vietnameseMeaning: 'Sự suy giảm sức khoẻ cộng đồng này có thể được quy cho...', example: 'This deterioration in public health can be attributed to a combination of poor diet and inactivity.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'hlt_w4', type: 'writing_phrase', term: 'The resulting pressure on hospitals is such that...', function: 'Explaining an effect', vietnameseMeaning: 'Áp lực lên bệnh viện do đó lớn đến mức...', example: 'The resulting pressure on hospitals is such that routine operations are postponed for months.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'hlt_w5', type: 'writing_phrase', term: 'The success of anti-smoking legislation illustrates this well:', function: 'Giving an example', vietnameseMeaning: 'Thành công của luật chống thuốc lá minh hoạ rõ điều này:', example: 'The success of anti-smoking legislation illustrates this well: smoking rates halved within two decades.', topic: 'Health', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_w6', type: 'writing_phrase', term: 'The most immediate benefit for patients would be...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi ích tức thời nhất đối với bệnh nhân sẽ là...', example: 'The most immediate benefit for patients would be shorter waiting times for specialist appointments.', topic: 'Health', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'hlt_w7', type: 'writing_phrase', term: 'One drawback of a purely state-funded system is that...', function: 'Discussing disadvantages', vietnameseMeaning: 'Một nhược điểm của hệ thống hoàn toàn do nhà nước chi trả là...', example: 'One drawback of a purely state-funded system is that demand almost always outstrips capacity.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'hlt_w8', type: 'writing_phrase', term: 'A realistic way of addressing this would be to...', function: 'Suggesting a solution', vietnameseMeaning: 'Một cách thực tế để giải quyết điều này là...', example: 'A realistic way of addressing this would be to tax sugary drinks and use the revenue for school meals.', topic: 'Health', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_w9', type: 'writing_phrase', term: 'In my opinion, individuals cannot be held solely responsible for...', function: 'Expressing an opinion', vietnameseMeaning: 'Theo tôi, cá nhân không thể bị quy trách nhiệm hoàn toàn cho...', example: 'In my opinion, individuals cannot be held solely responsible for health outcomes shaped by their environment.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'hlt_w10', type: 'writing_phrase', term: 'Physical illness attracts sympathy, whereas mental illness still attracts...', function: 'Comparing ideas', vietnameseMeaning: 'Bệnh thể chất nhận được sự cảm thông, trong khi bệnh tâm thần vẫn nhận về...', example: 'Physical illness attracts sympathy, whereas mental illness still attracts suspicion in many communities.', topic: 'Health', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'hlt_m1', type: 'common_mistake', incorrect: 'Doctors gave many advices about diet.', correct: 'Doctors gave a great deal of advice about diet.', explanation: '"Advice" is uncountable — no plural and no "many". If you need a countable form, use "pieces of advice" or "recommendations".', topic: 'Health', priority: 'must_learn' },
    { id: 'hlt_m2', type: 'common_mistake', incorrect: 'Many workers today are very stress.', correct: 'Many workers today are highly stressed.', explanation: '"Stress" is the noun; "stressed" is the adjective describing the person. Also prefer "highly" or "extremely" over "very" in formal writing.', topic: 'Health', priority: 'must_learn' },
    { id: 'hlt_m3', type: 'common_mistake', incorrect: 'Fast food makes people become obese.', correct: 'Fast food makes people obese.', explanation: '"Make" is already causative, so "become" is redundant. Alternatively write "Fast food causes obesity".', topic: 'Health', priority: 'high_value' },
    { id: 'hlt_m4', type: 'common_mistake', incorrect: 'Governments should invest more money for healthcare.', correct: 'Governments should invest more money in healthcare.', explanation: 'The verb "invest" takes "in", never "for". The same applies to "spend money on".', topic: 'Health', priority: 'must_learn' },
    { id: 'hlt_m5', type: 'common_mistake', incorrect: 'People are increasingly concerned about their healthy.', correct: 'People are increasingly concerned about their health.', explanation: '"Health" is the noun and "healthy" the adjective. Vietnamese learners frequently swap the two because one word covers both in Vietnamese.', topic: 'Health', priority: 'must_learn' },
  ],

  learnFirst: {
    vocabulary: ['hlt_v1', 'hlt_v9', 'hlt_v11', 'hlt_v12', 'hlt_v13', 'hlt_v14', 'hlt_v19', 'hlt_v21', 'hlt_v22', 'hlt_v25'],
    collocations: ['hlt_c1', 'hlt_c2', 'hlt_c9', 'hlt_c15', 'hlt_c17'],
    phrasalVerbs: ['hlt_p2', 'hlt_p8', 'hlt_p7'],
    writingPhrases: ['hlt_w1', 'hlt_w5', 'hlt_w9'],
  },
}
