import type { TopicData } from '../types'

export const MEDIA: TopicData = {
  topic: 'Media',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'med_v1', type: 'vocabulary', term: 'the media', pronunciation: '/ðə ˈmiːdiə/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'Newspapers, television, radio and online outlets considered collectively.', vietnameseMeaning: 'Giới truyền thông, các phương tiện truyền thông.', example: 'The media shape public opinion long before politicians ever address an issue directly.', writingTip: 'Almost always takes "the". Treated as plural in British academic writing: "the media have reported".', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the mass media', 'media coverage', 'media attention', 'social media'], wordFamily: ['medium (singular n)'], priority: 'must_learn' },
    { id: 'med_v2', type: 'vocabulary', term: 'social media', pronunciation: '/ˈsəʊʃl ˈmiːdiə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Websites and applications that let users create and share content.', vietnameseMeaning: 'Mạng xã hội.', example: 'Social media has replaced the newspaper as the primary source of news for people under thirty.', writingTip: 'Treated as uncountable and usually singular: "social media has", not "social medias".', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['social media platforms', 'on social media', 'social media use'], priority: 'must_learn' },
    { id: 'med_v3', type: 'vocabulary', term: 'audience', pronunciation: '/ˈɔːdiəns/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'The people who watch, read or listen to something.', vietnameseMeaning: 'Khán giả, độc giả, công chúng tiếp nhận.', example: 'Broadcasters chase the largest possible audience, which pushes programming towards the sensational.', writingTip: 'Countable and often collective: "a young audience", "audiences have fragmented".', topic: 'Media', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a wide audience', 'target audience', 'reach an audience', 'audience share'], alternatives: ['viewers', 'readership'], priority: 'must_learn' },
    { id: 'med_v4', type: 'vocabulary', term: 'broadcast', pronunciation: '/ˈbrɔːdkɑːst/', partOfSpeech: 'verb / noun', cefrLevel: 'B2', definition: 'To transmit a programme by television or radio.', vietnameseMeaning: 'Phát sóng, truyền hình, phát thanh.', example: 'State broadcasters are funded by the public but not always accountable to it.', writingTip: 'The past tense is "broadcast", not "broadcasted", in careful British usage.', topic: 'Media', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['broadcast live', 'a news broadcast', 'public broadcaster'], wordFamily: ['broadcaster (n)', 'broadcasting (n)'], priority: 'high_value' },
    { id: 'med_v5', type: 'vocabulary', term: 'headline', pronunciation: '/ˈhedlaɪn/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'The title printed above a news story.', vietnameseMeaning: 'Tiêu đề bài báo, dòng tít.', example: 'Alarming headlines attract clicks even when the article beneath them is far more measured.', writingTip: '"Make headlines" means to become widely reported. A useful idiom in Task 2.', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', collocations: ['make headlines', 'front-page headline', 'misleading headline'], priority: 'high_value' },
    { id: 'med_v6', type: 'vocabulary', term: 'advertise', pronunciation: '/ˈædvətaɪz/', partOfSpeech: 'verb', cefrLevel: 'B1', definition: 'To promote a product or service publicly in order to increase sales.', vietnameseMeaning: 'Quảng cáo.', example: 'Companies advertise most aggressively to the audiences least able to evaluate their claims.', writingTip: 'The noun is "advertising" (the activity) or "an advertisement" (one item). Avoid the informal "advert"/"ad" in essays.', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['advertise products', 'advertising revenue', 'online advertising', 'advertising campaign'], wordFamily: ['advertisement (n)', 'advertiser (n)', 'advertising (n)'], priority: 'must_learn' },
    { id: 'med_v7', type: 'vocabulary', term: 'reliable', pronunciation: '/rɪˈlaɪəbl/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Able to be trusted to be accurate or correct.', vietnameseMeaning: 'Đáng tin cậy, chính xác.', example: 'Readers now need real skill to distinguish reliable reporting from material designed purely to provoke.', writingTip: 'Use for sources and information. "Credible" is the higher-band equivalent.', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a reliable source', 'reliable information', 'highly reliable'], antonym: 'unreliable', wordFamily: ['rely (v)', 'reliability (n)'], priority: 'must_learn' },
    { id: 'med_v8', type: 'vocabulary', term: 'coverage', pronunciation: '/ˈkʌvərɪdʒ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The reporting of an event or subject by the media.', vietnameseMeaning: 'Sự đưa tin, mức độ đưa tin về một sự kiện.', example: 'Coverage of natural disasters fades within days, long before the recovery has begun.', writingTip: 'Uncountable: "extensive coverage", never "coverages".', topic: 'Media', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['media coverage', 'extensive coverage', 'news coverage', 'biased coverage'], wordFamily: ['cover (v)'], priority: 'must_learn' },
    { id: 'med_v9', type: 'vocabulary', term: 'influence', pronunciation: '/ˈɪnfluəns/', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'The power to affect what people think or do.', vietnameseMeaning: 'Ảnh hưởng, sức tác động.', example: 'The influence of online recommendation systems on what people read is far greater than most users realise.', writingTip: 'Always "influence on", never "influence to". "Exert influence over" is the formal variant.', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a powerful influence on', 'exert influence', 'undue influence', 'media influence'], wordFamily: ['influential (adj)'], priority: 'must_learn' },
    { id: 'med_v10', type: 'vocabulary', term: 'entertainment', pronunciation: '/ˌentəˈteɪnmənt/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Films, shows and other activities that amuse people.', vietnameseMeaning: 'Giải trí.', example: 'The boundary between news and entertainment has blurred to the point where the two are hard to separate.', writingTip: 'Uncountable. "Entertainment value" is a useful phrase when criticising sensational reporting.', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['entertainment industry', 'popular entertainment', 'entertainment value'], wordFamily: ['entertain (v)', 'entertaining (adj)'], priority: 'high_value' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'med_v11', type: 'vocabulary', term: 'misinformation', pronunciation: '/ˌmɪsɪnfəˈmeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'False information that is spread, whether or not the intention is to deceive.', vietnameseMeaning: 'Thông tin sai lệch.', example: 'Misinformation about vaccines spreads faster than corrections ever can.', writingTip: 'Distinguish from "disinformation", which is deliberately false. Both are far better than "fake news" in an essay.', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['spread misinformation', 'combat misinformation', 'online misinformation'], alternatives: ['disinformation', 'false information'], priority: 'must_learn' },
    { id: 'med_v12', type: 'vocabulary', term: 'bias', pronunciation: '/ˈbaɪəs/', partOfSpeech: 'noun (uncountable) / verb', cefrLevel: 'B2', definition: 'An unfair preference for or against a person, group or idea.', vietnameseMeaning: 'Thiên vị, thiên kiến.', example: 'Political bias is often expressed less through outright falsehood than through the choice of what to report.', writingTip: 'Usually uncountable: "media bias", "evidence of bias". The adjective is "biased" (never "bias").', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['political bias', 'media bias', 'show bias towards', 'unconscious bias'], antonym: 'impartiality', wordFamily: ['biased (adj)', 'unbiased (adj)'], priority: 'must_learn' },
    { id: 'med_v13', type: 'vocabulary', term: 'censorship', pronunciation: '/ˈsensəʃɪp/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The suppression of information or opinion by an authority.', vietnameseMeaning: 'Sự kiểm duyệt.', example: 'Governments defend censorship as a shield against harm, while critics see it as protection for those in power.', writingTip: 'Uncountable. "Impose", "relax" and "lift" censorship are the natural verbs.', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['impose censorship', 'state censorship', 'internet censorship', 'relax censorship'], wordFamily: ['censor (v, n)', 'censored (adj)'], priority: 'must_learn' },
    { id: 'med_v14', type: 'vocabulary', term: 'credibility', pronunciation: '/ˌkredəˈbɪləti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The quality of being believable and worthy of trust.', vietnameseMeaning: 'Độ tin cậy, uy tín.', example: 'A single fabricated story can destroy the credibility a publication spent decades building.', writingTip: '"Undermine / damage / restore credibility" are the standard verb pairings.', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['undermine credibility', 'lose credibility', 'restore credibility', 'lack credibility'], wordFamily: ['credible (adj)', 'incredible (adj)'], priority: 'must_learn' },
    { id: 'med_v15', type: 'vocabulary', term: 'journalism', pronunciation: '/ˈdʒɜːnəlɪzəm/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The activity of collecting and reporting news.', vietnameseMeaning: 'Nghề báo, hoạt động báo chí.', example: 'Investigative journalism is expensive, slow and precisely what advertising-funded models cannot sustain.', writingTip: 'Uncountable. "Investigative journalism" and "quality journalism" are the key collocations.', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['investigative journalism', 'quality journalism', 'citizen journalism'], wordFamily: ['journalist (n)', 'journalistic (adj)'], priority: 'must_learn' },
    { id: 'med_v16', type: 'vocabulary', term: 'sensationalism', pronunciation: '/senˈseɪʃnəlɪzəm/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The presentation of stories in a shocking way to attract attention.', vietnameseMeaning: 'Lối đưa tin giật gân, câu khách.', example: 'Sensationalism sells papers, but it leaves readers with a distorted picture of how dangerous the world actually is.', writingTip: 'The adjective "sensationalist" is equally useful: "sensationalist reporting".', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['media sensationalism', 'resort to sensationalism', 'sensationalist reporting'], wordFamily: ['sensational (adj)', 'sensationalise (v)'], priority: 'high_value' },
    { id: 'med_v17', type: 'vocabulary', term: 'regulation', pronunciation: '/ˌreɡjuˈleɪʃn/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'Official rules controlling how something operates.', vietnameseMeaning: 'Quy định, sự quản lý bằng luật lệ.', example: 'Effective regulation of online platforms has to distinguish between hosting content and promoting it.', writingTip: 'Uncountable for the concept, countable for individual rules ("new regulations").', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['stricter regulation', 'government regulation', 'self-regulation', 'media regulation'], wordFamily: ['regulate (v)', 'regulator (n)', 'regulatory (adj)'], priority: 'must_learn' },
    { id: 'med_v18', type: 'vocabulary', term: 'algorithm', pronunciation: '/ˈælɡərɪðəm/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A set of rules a computer follows, here to decide what content a user sees.', vietnameseMeaning: 'Thuật toán (quyết định nội dung hiển thị).', example: 'Recommendation algorithms reward content that provokes a reaction, not content that informs.', writingTip: 'Essential for any modern media essay. Note the silent "h" in the pronunciation.', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['recommendation algorithm', 'algorithms determine', 'algorithmic bias'], wordFamily: ['algorithmic (adj)'], priority: 'must_learn' },
    { id: 'med_v19', type: 'vocabulary', term: 'circulation', pronunciation: '/ˌsɜːkjəˈleɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The number of copies of a newspaper or magazine sold.', vietnameseMeaning: 'Số lượng phát hành (báo chí).', example: 'Print circulation has fallen by roughly two-thirds since the turn of the century.', writingTip: 'Excellent for Task 1 charts on newspaper sales: "circulation declined steadily".', topic: 'Media', bandLevel: '6-7', task: 'task1', writingSuitability: 'highly_suitable', collocations: ['declining circulation', 'circulation figures', 'boost circulation'], wordFamily: ['circulate (v)'], priority: 'high_value' },
    { id: 'med_v20', type: 'vocabulary', term: 'digitalisation', pronunciation: '/ˌdɪdʒɪtəlaɪˈzeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The shift of activities and services into digital form.', vietnameseMeaning: 'Quá trình số hoá.', example: 'The digitalisation of news destroyed the advertising model that had funded reporting for a century.', writingTip: 'A formal alternative to "the move online". "Digitisation" refers more narrowly to converting files.', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['the digitalisation of media', 'rapid digitalisation'], wordFamily: ['digital (adj)', 'digitalise (v)'], priority: 'optional' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'med_v21', type: 'vocabulary', term: 'echo chamber', pronunciation: '/ˈekəʊ ˌtʃeɪmbə/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'An environment where people encounter only opinions that match their own.', vietnameseMeaning: 'Buồng vọng âm — môi trường chỉ tiếp xúc quan điểm tương đồng.', example: 'Personalised feeds create echo chambers in which opposing arguments simply never appear.', writingTip: 'A precise, current metaphor. "Filter bubble" is a close synonym worth knowing as well.', topic: 'Media', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['create echo chambers', 'trapped in an echo chamber'], alternatives: ['filter bubble'], priority: 'must_learn' },
    { id: 'med_v22', type: 'vocabulary', term: 'propaganda', pronunciation: '/ˌprɒpəˈɡændə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Information, often biased or misleading, spread to promote a political cause.', vietnameseMeaning: 'Tuyên truyền có định hướng, thông tin tuyên truyền.', example: 'What distinguishes propaganda from persuasion is the deliberate concealment of who is speaking and why.', writingTip: 'Uncountable and strongly negative in English — use it deliberately, not as a neutral synonym for publicity.', topic: 'Media', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['state propaganda', 'spread propaganda', 'a propaganda campaign'], priority: 'high_value' },
    { id: 'med_v23', type: 'vocabulary', term: 'clickbait', pronunciation: '/ˈklɪkbeɪt/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Online content designed purely to attract clicks rather than to inform.', vietnameseMeaning: 'Nội dung câu view, tiêu đề giật tít câu khách.', example: 'Clickbait headlines exploit curiosity in a way that traditional editorial standards would never have permitted.', writingTip: 'Informal in origin but now standard in academic discussion of media. Safe in Task 2.', topic: 'Media', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['clickbait headlines', 'resort to clickbait'], priority: 'high_value' },
    { id: 'med_v24', type: 'vocabulary', term: 'transparency', pronunciation: '/trænsˈpærənsi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Openness about how decisions are made and who is responsible.', vietnameseMeaning: 'Tính minh bạch.', example: 'Greater transparency about who funds a publication would allow readers to weigh its reporting appropriately.', writingTip: 'A key concept in solution paragraphs. "Demand / ensure / lack transparency" are all natural.', topic: 'Media', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['greater transparency', 'lack of transparency', 'ensure transparency'], antonym: 'secrecy', wordFamily: ['transparent (adj)'], priority: 'must_learn' },
    { id: 'med_v25', type: 'vocabulary', term: 'scrutiny', pronunciation: '/ˈskruːtəni/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Careful and critical examination.', vietnameseMeaning: 'Sự giám sát, xem xét kỹ lưỡng.', example: 'A free press subjects those in power to the scrutiny that elections alone cannot provide.', writingTip: '"Come under scrutiny" and "public scrutiny" are the standard phrases. Uncountable.', topic: 'Media', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['public scrutiny', 'come under scrutiny', 'close scrutiny', 'escape scrutiny'], wordFamily: ['scrutinise (v)'], priority: 'must_learn' },
    { id: 'med_v26', type: 'vocabulary', term: 'polarise', pronunciation: '/ˈpəʊləraɪz/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To divide people into two sharply opposed groups.', vietnameseMeaning: 'Phân cực, chia rẽ thành hai phe đối lập.', example: 'Coverage that frames every issue as a contest between two camps polarises debate rather than clarifying it.', writingTip: 'The noun "polarisation" is equally common: "growing political polarisation".', topic: 'Media', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['polarise opinion', 'deeply polarised', 'political polarisation'], wordFamily: ['polarisation (n)', 'polarised (adj)'], priority: 'high_value' },
    { id: 'med_v27', type: 'vocabulary', term: 'mainstream media', pronunciation: '/ˈmeɪnstriːm ˈmiːdiə/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'The large, established news organisations reaching the widest audiences.', vietnameseMeaning: 'Truyền thông chính thống, các cơ quan báo chí lớn.', example: 'Distrust of the mainstream media has driven many readers towards sources with no editorial standards at all.', writingTip: 'A neutral descriptive term in academic writing, though it is used pejoratively in political debate.', topic: 'Media', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['distrust of the mainstream media', 'mainstream outlets'], priority: 'high_value' },
    { id: 'med_v28', type: 'vocabulary', term: 'accountability', pronunciation: '/əˌkaʊntəˈbɪləti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The obligation to explain and take responsibility for one’s actions.', vietnameseMeaning: 'Trách nhiệm giải trình.', example: 'Platforms have acquired the reach of publishers without accepting any of their accountability.', writingTip: 'Central to arguments about regulating technology companies. "Hold X to account" is a strong variant.', topic: 'Media', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['public accountability', 'a lack of accountability', 'demand accountability'], wordFamily: ['accountable (adj)'], priority: 'must_learn' },
    { id: 'med_v29', type: 'vocabulary', term: 'distort', pronunciation: '/dɪˈstɔːt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To change something so that it gives a false impression.', vietnameseMeaning: 'Bóp méo, làm sai lệch.', example: 'Selecting only the most dramatic incidents distorts public understanding of how common crime actually is.', writingTip: 'More precise than "change" when the result is a misleading picture. The noun is "distortion".', topic: 'Media', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['distort the facts', 'distort public perception', 'a distorted picture'], wordFamily: ['distortion (n)', 'distorted (adj)'], priority: 'must_learn' },
    { id: 'med_v30', type: 'vocabulary', term: 'discerning', pronunciation: '/dɪˈsɜːnɪŋ/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Able to judge quality and make careful distinctions.', vietnameseMeaning: 'Sáng suốt, biết phân biệt, tinh tường.', example: 'Media literacy education aims to produce discerning readers rather than merely sceptical ones.', writingTip: 'A refined alternative to "careful" or "critical" when describing audiences.', topic: 'Media', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['a discerning audience', 'discerning readers', 'discerning consumers'], wordFamily: ['discern (v)', 'discernment (n)'], priority: 'optional' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'med_c1', type: 'collocation', term: 'media coverage', collocationType: 'Noun + Noun', definition: 'The reporting given to a subject by news organisations.', vietnameseMeaning: 'Sự đưa tin của truyền thông.', example: 'Media coverage of the election focused almost entirely on personalities rather than policies.', topic: 'Media', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'med_c2', type: 'collocation', term: 'social media platform', collocationType: 'Noun + Noun', definition: 'A website or app where users share content with each other.', vietnameseMeaning: 'Nền tảng mạng xã hội.', example: 'Social media platforms now function as the main distributor of news without accepting responsibility for it.', topic: 'Media', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'med_c3', type: 'collocation', term: 'a reliable source', collocationType: 'Adj + Noun', definition: 'A place or person whose information can be trusted.', vietnameseMeaning: 'Nguồn tin đáng tin cậy.', example: 'Students should be taught to check whether a claim originates from a reliable source before sharing it.', alternative: 'a credible source', topic: 'Media', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'med_c4', type: 'collocation', term: 'shape public opinion', collocationType: 'Verb + Noun', definition: 'To influence what the general population believes.', vietnameseMeaning: 'Định hình dư luận công chúng.', example: 'Newspapers shape public opinion less through argument than through the stories they choose to run.', topic: 'Media', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'med_c5', type: 'collocation', term: 'freedom of the press', collocationType: 'Noun phrase', definition: 'The right of journalists to report without government control.', vietnameseMeaning: 'Tự do báo chí.', example: 'Freedom of the press is meaningless without legal protection for the journalists who exercise it.', alternative: 'press freedom', topic: 'Media', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'med_c6', type: 'collocation', term: 'spread rapidly', collocationType: 'Verb + Adverb', definition: 'To reach many people in a very short time.', vietnameseMeaning: 'Lan truyền nhanh chóng.', example: 'False claims spread rapidly because outrage travels further than correction.', topic: 'Media', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'med_c7', type: 'collocation', term: 'watch television', collocationType: 'Verb + Noun', definition: 'To view television programmes.', vietnameseMeaning: 'Xem truyền hình.', example: 'Adults over sixty still watch television for several hours a day, while teenagers barely watch it at all.', topic: 'Media', bandLevel: '5-6', task: 'both', priority: 'high_value', writingTip: 'No article: "watch television", not "watch the television", when you mean the medium in general.' },
    { id: 'med_c8', type: 'collocation', term: 'raise awareness of', collocationType: 'Verb + Noun', definition: 'To make more people conscious of an issue.', vietnameseMeaning: 'Nâng cao nhận thức về.', example: 'Documentaries can raise awareness of issues that never survive a two-minute news bulletin.', topic: 'Media', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },

    // Advanced (Band 6-7)
    { id: 'med_c9', type: 'collocation', term: 'spread misinformation', collocationType: 'Verb + Noun', definition: 'To circulate false or inaccurate information.', vietnameseMeaning: 'Phát tán thông tin sai lệch.', example: 'Anonymous accounts spread misinformation faster than moderators can remove it.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'med_c10', type: 'collocation', term: 'biased reporting', collocationType: 'Adj + Noun', definition: 'News coverage that unfairly favours one side.', vietnameseMeaning: 'Đưa tin thiên vị.', example: 'Biased reporting is rarely a matter of invention; it is usually a matter of emphasis and omission.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'med_c11', type: 'collocation', term: 'impose censorship', collocationType: 'Verb + Noun', definition: 'To officially restrict what may be published or broadcast.', vietnameseMeaning: 'Áp đặt kiểm duyệt.', example: 'Governments that impose censorship in the name of stability often find dissent simply moves elsewhere.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'med_c12', type: 'collocation', term: 'undermine public trust', collocationType: 'Verb + Noun', definition: 'To gradually weaken people’s confidence in an institution.', vietnameseMeaning: 'Làm suy giảm niềm tin của công chúng.', example: 'Repeated corrections and retractions undermine public trust even when they demonstrate honesty.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'med_c13', type: 'collocation', term: 'verify information', collocationType: 'Verb + Noun', definition: 'To check that information is true before accepting it.', vietnameseMeaning: 'Kiểm chứng thông tin.', example: 'Readers now have to verify information themselves, a task once performed by editors.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'med_c14', type: 'collocation', term: 'media literacy', collocationType: 'Noun + Noun', definition: 'The ability to analyse and evaluate media messages critically.', vietnameseMeaning: 'Năng lực đọc hiểu và đánh giá truyền thông.', example: 'Teaching media literacy in schools is a far more durable defence than removing individual posts.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'med_c15', type: 'collocation', term: 'advertising revenue', collocationType: 'Noun + Noun', definition: 'Income earned from selling advertising space.', vietnameseMeaning: 'Doanh thu quảng cáo.', example: 'As advertising revenue migrated to search engines, hundreds of local newspapers closed.', topic: 'Media', bandLevel: '6-7', task: 'both', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'med_c16', type: 'collocation', term: 'hold those in power to account', collocationType: 'Verb phrase', definition: 'To make powerful people explain and answer for their actions.', vietnameseMeaning: 'Buộc những người nắm quyền phải giải trình.', example: 'The essential function of a free press is to hold those in power to account between elections.', topic: 'Media', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'med_c17', type: 'collocation', term: 'distort public perception', collocationType: 'Verb + Noun', definition: 'To give people a misleading impression of reality.', vietnameseMeaning: 'Bóp méo nhận thức của công chúng.', example: 'Constant coverage of violent crime distorts public perception of risk in overwhelmingly safe neighbourhoods.', topic: 'Media', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'med_c18', type: 'collocation', term: 'reinforce existing prejudices', collocationType: 'Verb + Noun', definition: 'To strengthen unfair opinions people already hold.', vietnameseMeaning: 'Củng cố những định kiến sẵn có.', example: 'Feeds tailored to a user’s history tend to reinforce existing prejudices rather than challenge them.', topic: 'Media', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'med_c19', type: 'collocation', term: 'strike a balance between freedom and regulation', collocationType: 'Verb + Noun', definition: 'To find a workable compromise between open expression and legal control.', vietnameseMeaning: 'Cân bằng giữa tự do ngôn luận và quản lý.', example: 'Any workable policy must strike a balance between freedom and regulation, since either extreme causes real harm.', topic: 'Media', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'med_c20', type: 'collocation', term: 'sensationalise a story', collocationType: 'Verb + Noun', definition: 'To present a news item in a deliberately shocking way.', vietnameseMeaning: 'Giật gân hoá một câu chuyện.', example: 'Outlets competing for attention sensationalise stories that a specialist would report in a single paragraph.', topic: 'Media', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'med_p1', type: 'phrasal_verb', term: 'find out', partOfSpeech: 'phrasal verb (separable)', definition: 'To discover information.', vietnameseMeaning: 'Tìm hiểu, phát hiện ra thông tin.', example: 'Most people now find out about breaking events through their phones rather than a bulletin.', formalAlternative: 'discover', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['discover', 'learn', 'ascertain'] },
    { id: 'med_p2', type: 'phrasal_verb', term: 'log on', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To connect to a website or online service.', vietnameseMeaning: 'Đăng nhập, truy cập trực tuyến.', example: 'Users who log on several times an hour are exposed to a continuous stream of unverified claims.', formalAlternative: 'access', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['access', 'connect to'] },
    { id: 'med_p3', type: 'phrasal_verb', term: 'point out', partOfSpeech: 'phrasal verb (separable)', definition: 'To draw attention to a fact.', vietnameseMeaning: 'Chỉ ra, nêu bật một sự thật.', example: 'Critics point out that platforms profit precisely from the content they claim to be unable to control.', formalAlternative: 'note', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', academicAlternatives: ['note', 'observe', 'highlight', 'contend'] },
    { id: 'med_p4', type: 'phrasal_verb', term: 'make up', partOfSpeech: 'phrasal verb (separable)', definition: 'To invent something that is not true.', vietnameseMeaning: 'Bịa đặt, dựng chuyện.', example: 'A handful of sites make up stories entirely, knowing that outrage generates advertising income.', formalAlternative: 'fabricate', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Informal, and it also means "to constitute". "Fabricate" removes both problems.', academicAlternatives: ['fabricate', 'invent', 'concoct'] },
    { id: 'med_p5', type: 'phrasal_verb', term: 'keep up with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To stay informed about something as it develops.', vietnameseMeaning: 'Theo dõi, cập nhật kịp thời.', example: 'It has become almost impossible to keep up with the volume of information published each day.', formalAlternative: 'stay informed about', topic: 'Media', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['stay abreast of', 'monitor', 'follow'] },

    // Advanced / less common
    { id: 'med_p6', type: 'phrasal_verb', term: 'crack down on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To take strong action against something.', vietnameseMeaning: 'Mạnh tay xử lý, siết chặt quản lý.', example: 'Regulators have begun to crack down on undisclosed paid promotion by online personalities.', formalAlternative: 'take firm action against', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', collocations: ['crack down on abuse', 'crack down on false advertising'], academicAlternatives: ['take firm action against', 'clamp down on', 'suppress'] },
    { id: 'med_p7', type: 'phrasal_verb', term: 'water down', partOfSpeech: 'phrasal verb (separable)', definition: 'To make a proposal or rule weaker and less effective.', vietnameseMeaning: 'Làm loãng, làm suy yếu (quy định, đề xuất).', example: 'Lobbying watered down the original proposals until almost nothing enforceable remained.', formalAlternative: 'dilute', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['dilute', 'weaken', 'soften'] },
    { id: 'med_p8', type: 'phrasal_verb', term: 'bring to light', partOfSpeech: 'phrasal verb', definition: 'To reveal something that was previously hidden.', vietnameseMeaning: 'Đưa ra ánh sáng, phơi bày sự thật.', example: 'Investigative reporting brought to light a pattern of abuse that internal reviews had missed for years.', formalAlternative: 'reveal', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', academicAlternatives: ['reveal', 'expose', 'uncover'] },
    { id: 'med_p9', type: 'phrasal_verb', term: 'play down', partOfSpeech: 'phrasal verb (separable)', definition: 'To make something seem less important than it is.', vietnameseMeaning: 'Giảm nhẹ, làm nhẹ đi tầm quan trọng.', example: 'Outlets owned by interested parties tend to play down stories that damage their proprietors.', formalAlternative: 'downplay', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['downplay', 'minimise', 'understate'] },
    { id: 'med_p10', type: 'phrasal_verb', term: 'blow out of proportion', partOfSpeech: 'phrasal verb', definition: 'To make something seem far more serious than it really is.', vietnameseMeaning: 'Thổi phồng quá mức.', example: 'Isolated incidents are routinely blown out of proportion until they appear to be national crises.', formalAlternative: 'exaggerate', topic: 'Media', bandLevel: '6-7', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Idiomatic and slightly conversational. "Exaggerate" or "overstate" is safer in a formal essay.', academicAlternatives: ['exaggerate', 'overstate', 'magnify'] },
  ],

  writingPhrases: [
    { id: 'med_w1', type: 'writing_phrase', term: 'At the heart of the debate about media freedom lies the question of...', function: 'Introducing an argument', vietnameseMeaning: 'Cốt lõi của cuộc tranh luận về tự do báo chí là câu hỏi...', example: 'At the heart of the debate about media freedom lies the question of who decides what counts as harmful.', topic: 'Media', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'med_w2', type: 'writing_phrase', term: 'False stories travel so quickly because...', function: 'Giving a reason', vietnameseMeaning: 'Tin giả lan truyền nhanh đến vậy là vì...', example: 'False stories travel so quickly because they are written to provoke emotion, which no accurate account can match.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'med_w3', type: 'writing_phrase', term: 'This decline in trust can be traced back to...', function: 'Explaining a cause', vietnameseMeaning: 'Sự suy giảm niềm tin này có thể truy nguyên từ...', example: 'This decline in trust can be traced back to the moment news outlets began competing with entertainment for the same attention.', topic: 'Media', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'med_w4', type: 'writing_phrase', term: 'One consequence of round-the-clock coverage is that...', function: 'Explaining an effect', vietnameseMeaning: 'Một hệ quả của việc đưa tin liên tục suốt ngày đêm là...', example: 'One consequence of round-the-clock coverage is that speed is now rewarded far more than accuracy.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'med_w5', type: 'writing_phrase', term: 'The reporting of health scares offers a clear example:', function: 'Giving an example', vietnameseMeaning: 'Việc đưa tin về các mối lo sức khoẻ là một ví dụ rõ ràng:', example: 'The reporting of health scares offers a clear example: a preliminary study becomes a headline about a cure.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'med_w6', type: 'writing_phrase', term: 'The undoubted advantage of open digital platforms is that...', function: 'Discussing advantages', vietnameseMeaning: 'Ưu điểm không thể phủ nhận của các nền tảng số mở là...', example: 'The undoubted advantage of open digital platforms is that they allow voices excluded by traditional editors to be heard.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'med_w7', type: 'writing_phrase', term: 'The corresponding danger is that...', function: 'Discussing disadvantages', vietnameseMeaning: 'Nguy cơ tương ứng đi kèm là...', example: 'The corresponding danger is that a rumour and a verified report now reach the reader in exactly the same format.', topic: 'Media', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'med_w8', type: 'writing_phrase', term: 'Rather than censoring content, a more effective response would be to...', function: 'Suggesting a solution', vietnameseMeaning: 'Thay vì kiểm duyệt nội dung, một giải pháp hiệu quả hơn là...', example: 'Rather than censoring content, a more effective response would be to teach young people how claims are manufactured.', topic: 'Media', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'med_w9', type: 'writing_phrase', term: 'I am convinced that the responsibility rests as much with readers as with...', function: 'Expressing an opinion', vietnameseMeaning: 'Tôi tin rằng trách nhiệm thuộc về người đọc không kém gì...', example: 'I am convinced that the responsibility rests as much with readers as with the platforms that serve them content.', topic: 'Media', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'med_w10', type: 'writing_phrase', term: 'Traditional newspapers were slow but accountable, whereas online sources are...', function: 'Comparing ideas', vietnameseMeaning: 'Báo giấy truyền thống chậm nhưng có trách nhiệm giải trình, trong khi các nguồn trực tuyến lại...', example: 'Traditional newspapers were slow but accountable, whereas online sources are instantaneous and frequently anonymous.', topic: 'Media', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'med_m1', type: 'common_mistake', incorrect: 'Nowadays, medias have a strong influence to young people.', correct: 'The media have a strong influence on young people.', explanation: 'Two errors: "media" is already plural (the singular is "medium") so "medias" does not exist, and the fixed preposition is "influence on", not "influence to".', topic: 'Media', priority: 'must_learn' },
    { id: 'med_m2', type: 'common_mistake', incorrect: 'Many informations on the internet are not true.', correct: 'A great deal of the information on the internet is inaccurate.', explanation: '"Information" is uncountable: no plural -s, no "many", and it takes a singular verb. Use "much", "a great deal of" or "a large amount of".', topic: 'Media', priority: 'must_learn' },
    { id: 'med_m3', type: 'common_mistake', incorrect: 'The news are reported by many channels every day.', correct: 'The news is reported by many channels every day.', explanation: '"News" looks plural but is an uncountable singular noun: "the news is", "a piece of news". This trips up almost every learner at least once.', topic: 'Media', priority: 'must_learn' },
    { id: 'med_m4', type: 'common_mistake', incorrect: 'Social media make people become addicted easily.', correct: 'Social media can make people addicted, or: Social media encourages addictive behaviour.', explanation: 'Two issues: "social media" takes a singular verb, and "make someone become" is redundant — "make someone + adjective" is enough. Adding "can" also avoids an unsupportable absolute claim.', topic: 'Media', priority: 'high_value' },
    { id: 'med_m5', type: 'common_mistake', incorrect: 'Journalists should tell the truth and not fake the news.', correct: 'Journalists should report accurately rather than fabricate stories.', explanation: '"Fake" as a verb and "the news" as an object are informal here. Academic writing prefers "report accurately", "verify claims" and "fabricate stories".', topic: 'Media', priority: 'high_value' },
  ],

  learnFirst: {
    vocabulary: ['med_v11', 'med_v12', 'med_v13', 'med_v14', 'med_v15', 'med_v18', 'med_v21', 'med_v24', 'med_v28', 'med_v29'],
    collocations: ['med_c4', 'med_c9', 'med_c14', 'med_c16', 'med_c19'],
    phrasalVerbs: ['med_p3', 'med_p8', 'med_p6'],
    writingPhrases: ['med_w1', 'med_w4', 'med_w8'],
  },
}
