import type { TopicData } from '../types'

export const SCIENCE: TopicData = {
  topic: 'Science',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'sci_v1', type: 'vocabulary', term: 'research', pronunciation: '/rɪˈsɜːtʃ/', partOfSpeech: 'noun (uncountable) / verb', cefrLevel: 'B1', definition: 'Careful study carried out to discover new facts.', vietnameseMeaning: 'Nghiên cứu.', example: 'Research into rare diseases attracts little funding because the potential market is small.', writingTip: 'Uncountable — never "researches". Say "a great deal of research" or "studies".', topic: 'Science', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['carry out research', 'medical research', 'research findings', 'research into'], wordFamily: ['researcher (n)'], priority: 'must_learn' },
    { id: 'sci_v2', type: 'vocabulary', term: 'discovery', pronunciation: '/dɪˈskʌvəri/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'The finding of something that was previously unknown.', vietnameseMeaning: 'Khám phá, phát hiện.', example: 'The discovery of antibiotics extended average life expectancy more than any other single advance.', writingTip: 'Countable: "a major discovery", "scientific discoveries". Do not confuse with "invention".', topic: 'Science', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a major discovery', 'scientific discovery', 'make a discovery'], wordFamily: ['discover (v)'], priority: 'must_learn' },
    { id: 'sci_v3', type: 'vocabulary', term: 'experiment', pronunciation: '/ɪkˈsperɪmənt/', partOfSpeech: 'noun (countable) / verb', cefrLevel: 'B1', definition: 'A controlled test carried out to establish whether an idea is correct.', vietnameseMeaning: 'Thí nghiệm, thực nghiệm.', example: 'An experiment that cannot be repeated by other laboratories tells us very little.', writingTip: '"Conduct" or "carry out" an experiment — never "do an experiment" in formal writing.', topic: 'Science', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['conduct an experiment', 'controlled experiment', 'experiment on animals'], wordFamily: ['experimental (adj)', 'experimentation (n)'], priority: 'must_learn' },
    { id: 'sci_v4', type: 'vocabulary', term: 'evidence', pronunciation: '/ˈevɪdəns/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Facts or information that support a conclusion.', vietnameseMeaning: 'Bằng chứng, chứng cứ.', example: 'There is now overwhelming evidence linking air pollution to childhood asthma.', writingTip: 'Uncountable — "evidence is", never "evidences" or "an evidence". Use "a piece of evidence".', topic: 'Science', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['strong evidence', 'scientific evidence', 'evidence suggests', 'lack of evidence'], wordFamily: ['evident (adj)', 'evidently (adv)'], priority: 'must_learn' },
    { id: 'sci_v5', type: 'vocabulary', term: 'develop', pronunciation: '/dɪˈveləp/', partOfSpeech: 'verb', cefrLevel: 'B1', definition: 'To create or improve something gradually over time.', vietnameseMeaning: 'Phát triển, tạo ra dần dần.', example: 'Vaccines that once took a decade to develop were produced within a year.', writingTip: 'Very versatile. The noun "development" works equally well in both writing tasks.', topic: 'Science', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['develop a vaccine', 'develop new technology', 'rapid development'], wordFamily: ['development (n)', 'developer (n)'], priority: 'must_learn' },
    { id: 'sci_v6', type: 'vocabulary', term: 'funding', pronunciation: '/ˈfʌndɪŋ/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Money provided to support a particular activity.', vietnameseMeaning: 'Nguồn tài trợ, kinh phí.', example: 'Basic research depends almost entirely on public funding, since its commercial value is unpredictable.', writingTip: 'Uncountable. "Secure", "cut" and "allocate" funding are the natural verbs.', topic: 'Science', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['research funding', 'secure funding', 'government funding', 'cut funding'], wordFamily: ['fund (v, n)'], priority: 'must_learn' },
    { id: 'sci_v7', type: 'vocabulary', term: 'laboratory', pronunciation: '/ləˈbɒrətri/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'A room or building equipped for scientific work.', vietnameseMeaning: 'Phòng thí nghiệm.', example: 'Results obtained in a laboratory frequently fail to hold up under real-world conditions.', writingTip: 'Use the full form in academic writing rather than the informal "lab".', topic: 'Science', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['laboratory conditions', 'in a laboratory', 'laboratory experiments'], priority: 'high_value' },
    { id: 'sci_v8', type: 'vocabulary', term: 'theory', pronunciation: '/ˈθɪəri/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A well-tested explanation of how something works.', vietnameseMeaning: 'Học thuyết, lý thuyết khoa học.', example: 'In science a theory is not a guess but an explanation that has survived repeated attempts to disprove it.', writingTip: 'Explaining this distinction is itself a strong Band 7+ point in essays about scientific literacy.', topic: 'Science', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['scientific theory', 'propose a theory', 'test a theory'], wordFamily: ['theoretical (adj)', 'theorise (v)'], priority: 'high_value' },
    { id: 'sci_v9', type: 'vocabulary', term: 'benefit', pronunciation: '/ˈbenɪfɪt/', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'An advantage gained from something.', vietnameseMeaning: 'Lợi ích; hưởng lợi.', example: 'The benefits of genetic screening must be weighed against the anxiety it can cause.', writingTip: '"Benefit from" as a verb. "Weigh the benefits against the risks" is a strong essay phrase.', topic: 'Science', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['benefit from', 'potential benefits', 'weigh the benefits against'], antonym: 'risk', wordFamily: ['beneficial (adj)'], priority: 'must_learn' },
    { id: 'sci_v10', type: 'vocabulary', term: 'treatment', pronunciation: '/ˈtriːtmənt/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'Medical care given to cure an illness or injury.', vietnameseMeaning: 'Phương pháp điều trị.', example: 'New treatments frequently reach wealthy markets years before they become available elsewhere.', writingTip: 'Countable for specific therapies, uncountable for care in general: "receive treatment".', topic: 'Science', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['effective treatment', 'receive treatment', 'a new treatment for'], wordFamily: ['treat (v)', 'treatable (adj)'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'sci_v11', type: 'vocabulary', term: 'breakthrough', pronunciation: '/ˈbreɪkθruː/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'An important discovery that suddenly makes progress possible.', vietnameseMeaning: 'Bước đột phá, phát hiện mang tính bước ngoặt.', example: 'Genuine breakthroughs are rare; most progress comes from thousands of small, unremarkable refinements.', writingTip: '"A major breakthrough", "a scientific breakthrough". Avoid overusing it for routine findings.', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a major breakthrough', 'medical breakthrough', 'achieve a breakthrough'], priority: 'must_learn' },
    { id: 'sci_v12', type: 'vocabulary', term: 'hypothesis', pronunciation: '/haɪˈpɒθəsɪs/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'A proposed explanation that can be tested by experiment.', vietnameseMeaning: 'Giả thuyết khoa học.', example: 'A hypothesis that cannot in principle be proved wrong is of no scientific use whatsoever.', writingTip: 'The plural is "hypotheses" (/haɪˈpɒθəsiːz/). "Test a hypothesis" is the standard verb.', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['test a hypothesis', 'formulate a hypothesis', 'support the hypothesis'], wordFamily: ['hypothesise (v)', 'hypothetical (adj)'], priority: 'high_value' },
    { id: 'sci_v13', type: 'vocabulary', term: 'innovation', pronunciation: '/ˌɪnəˈveɪʃn/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A new method, idea or product; the process of creating these.', vietnameseMeaning: 'Sự đổi mới, sáng tạo mới.', example: 'Innovation flourishes where researchers are permitted to fail without losing their funding.', writingTip: 'Uncountable for the process, countable for specific inventions ("recent innovations").', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['technological innovation', 'drive innovation', 'stifle innovation'], wordFamily: ['innovate (v)', 'innovative (adj)'], priority: 'must_learn' },
    { id: 'sci_v14', type: 'vocabulary', term: 'clinical trial', pronunciation: '/ˈklɪnɪkl ˈtraɪəl/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A carefully controlled test of a medical treatment on human volunteers.', vietnameseMeaning: 'Thử nghiệm lâm sàng.', example: 'Clinical trials that exclude older patients produce medicines whose effects on them are simply unknown.', writingTip: 'A concrete, credible term that grounds an argument about medical ethics or drug approval.', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['conduct a clinical trial', 'clinical trial results', 'phase three trials'], priority: 'high_value' },
    { id: 'sci_v15', type: 'vocabulary', term: 'ethics', pronunciation: '/ˈeθɪks/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'Moral principles governing what is acceptable behaviour.', vietnameseMeaning: 'Đạo đức, các nguyên tắc đạo đức nghề nghiệp.', example: 'The ethics of editing human embryos are being debated long after the technique became possible.', writingTip: 'Plural in form. The adjective "ethical" is more common in essays: "ethical concerns".', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['medical ethics', 'research ethics', 'ethical concerns', 'ethical guidelines'], wordFamily: ['ethical (adj)', 'unethical (adj)'], priority: 'must_learn' },
    { id: 'sci_v16', type: 'vocabulary', term: 'biotechnology', pronunciation: '/ˌbaɪəʊtekˈnɒlədʒi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The use of living organisms or their components to make products.', vietnameseMeaning: 'Công nghệ sinh học.', example: 'Biotechnology has produced crops that resist drought, though their long-term effects remain contested.', writingTip: 'Uncountable. Often shortened to "biotech" in speech, but write it out in an essay.', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['advances in biotechnology', 'the biotechnology industry'], priority: 'high_value' },
    { id: 'sci_v17', type: 'vocabulary', term: 'genome', pronunciation: '/ˈdʒiːnəʊm/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'The complete set of genetic material in an organism.', vietnameseMeaning: 'Bộ gen, hệ gen của sinh vật.', example: 'Sequencing the human genome cost billions; it can now be done for the price of a laptop.', writingTip: 'Useful for concrete examples about how fast scientific capability changes.', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['the human genome', 'sequence a genome', 'genome editing'], wordFamily: ['genetic (adj)', 'gene (n)'], priority: 'optional' },
    { id: 'sci_v18', type: 'vocabulary', term: 'peer review', pronunciation: '/ˌpɪə rɪˈvjuː/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The evaluation of research by other experts before publication.', vietnameseMeaning: 'Quá trình bình duyệt của giới chuyên môn.', example: 'Peer review is an imperfect filter, but it is considerably better than publishing with no filter at all.', writingTip: 'A precise term that shows real understanding of how science works. Also used as a verb.', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['undergo peer review', 'peer-reviewed journal', 'the peer review process'], priority: 'must_learn' },
    { id: 'sci_v19', type: 'vocabulary', term: 'sceptical', pronunciation: '/ˈskeptɪkl/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Doubtful about whether a claim is true.', vietnameseMeaning: 'Hoài nghi, còn nghi ngờ.', example: 'Scientists are trained to remain sceptical of results that confirm exactly what they hoped to find.', writingTip: 'American spelling is "skeptical". "Sceptical of/about" — both prepositions are correct.', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['remain sceptical', 'deeply sceptical', 'sceptical of claims'], wordFamily: ['scepticism (n)', 'sceptic (n)'], priority: 'high_value' },
    { id: 'sci_v20', type: 'vocabulary', term: 'application', pronunciation: '/ˌæplɪˈkeɪʃn/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A practical use to which a discovery can be put.', vietnameseMeaning: 'Ứng dụng thực tiễn.', example: 'Research undertaken with no application in mind has produced some of the most useful technologies we have.', writingTip: '"Practical applications" is the key collocation in science essays.', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['practical applications', 'potential applications', 'find an application'], wordFamily: ['apply (v)', 'applied (adj)'], priority: 'must_learn' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'sci_v21', type: 'vocabulary', term: 'empirical', pronunciation: '/ɪmˈpɪrɪkl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Based on observation and measurement rather than theory alone.', vietnameseMeaning: 'Dựa trên thực nghiệm, quan sát thực tế.', example: 'Policy should rest on empirical evidence rather than on assumptions that happen to be politically convenient.', writingTip: '"Empirical evidence", "empirical research", "empirical data" — a hallmark of academic register.', topic: 'Science', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['empirical evidence', 'empirical research', 'empirical data'], antonym: 'theoretical', wordFamily: ['empirically (adv)'], priority: 'must_learn' },
    { id: 'sci_v22', type: 'vocabulary', term: 'replication', pronunciation: '/ˌreplɪˈkeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The repeating of a study by other researchers to check its results.', vietnameseMeaning: 'Sự lặp lại nghiên cứu để kiểm chứng kết quả.', example: 'A significant proportion of published psychology findings have failed replication by independent teams.', writingTip: 'The "replication crisis" is a genuine, current example that impresses in essays on scientific reliability.', topic: 'Science', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['fail replication', 'the replication crisis', 'independent replication'], wordFamily: ['replicate (v)', 'replicable (adj)'], priority: 'high_value' },
    { id: 'sci_v23', type: 'vocabulary', term: 'longitudinal study', pronunciation: '/ˌlɒŋɡɪˈtjuːdɪnl ˈstʌdi/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'Research that follows the same subjects over many years.', vietnameseMeaning: 'Nghiên cứu theo dõi dài hạn.', example: 'Only a longitudinal study can distinguish a genuine long-term effect from a temporary correlation.', writingTip: 'Excellent for arguing that some questions cannot be answered quickly or cheaply.', topic: 'Science', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a longitudinal study of', 'longitudinal data'], priority: 'high_value' },
    { id: 'sci_v24', type: 'vocabulary', term: 'paradigm', pronunciation: '/ˈpærədaɪm/', partOfSpeech: 'noun (countable)', cefrLevel: 'C2', definition: 'The framework of assumptions within which research is conducted.', vietnameseMeaning: 'Hệ hình, khung tư duy chủ đạo trong một lĩnh vực.', example: 'A genuine paradigm shift occurs perhaps once a century in any given field.', writingTip: '"Paradigm shift" is the standard phrase. Use it only for genuinely fundamental change.', topic: 'Science', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['a paradigm shift', 'the dominant paradigm', 'challenge the paradigm'], priority: 'optional' },
    { id: 'sci_v25', type: 'vocabulary', term: 'interdisciplinary', pronunciation: '/ˌɪntədɪsəˈplɪnəri/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Involving two or more academic fields working together.', vietnameseMeaning: 'Liên ngành, kết hợp nhiều lĩnh vực.', example: 'The most productive laboratories are interdisciplinary, pairing biologists with engineers and statisticians.', writingTip: 'A strong argument for how research should be funded and organised.', topic: 'Science', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['interdisciplinary research', 'an interdisciplinary approach', 'interdisciplinary collaboration'], priority: 'high_value' },
    { id: 'sci_v26', type: 'vocabulary', term: 'evidence-based', pronunciation: '/ˈevɪdəns beɪst/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Founded on systematically gathered evidence rather than opinion or tradition.', vietnameseMeaning: 'Dựa trên bằng chứng khoa học.', example: 'Evidence-based medicine replaced a great deal of practice that had continued purely out of habit.', writingTip: 'Always hyphenated before a noun. Extremely useful in solution paragraphs across many topics.', topic: 'Science', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['evidence-based policy', 'evidence-based medicine', 'an evidence-based approach'], priority: 'must_learn' },
    { id: 'sci_v27', type: 'vocabulary', term: 'rigorous', pronunciation: '/ˈrɪɡərəs/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Extremely thorough and careful in method.', vietnameseMeaning: 'Nghiêm ngặt, chặt chẽ về phương pháp.', example: 'Rigorous testing is precisely what distinguishes a medicine from a remedy.', writingTip: '"Rigorous testing / analysis / standards" — a precise upgrade on "careful" or "strict".', topic: 'Science', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['rigorous testing', 'rigorous standards', 'scientifically rigorous'], wordFamily: ['rigour (n)', 'rigorously (adv)'], priority: 'must_learn' },
    { id: 'sci_v28', type: 'vocabulary', term: 'unprecedented', pronunciation: '/ʌnˈpresɪdentɪd/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Never having happened before.', vietnameseMeaning: 'Chưa từng có tiền lệ.', example: 'The speed of vaccine development in 2020 was genuinely unprecedented in medical history.', writingTip: 'A strong word — reserve it for things that really are without precedent, or it loses force.', topic: 'Science', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['at an unprecedented rate', 'unprecedented growth', 'largely unprecedented'], priority: 'high_value' },
    { id: 'sci_v29', type: 'vocabulary', term: 'harness', pronunciation: '/ˈhɑːnɪs/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To control and make productive use of a force or resource.', vietnameseMeaning: 'Khai thác, tận dụng có kiểm soát.', example: 'Learning to harness artificial intelligence for diagnosis may prove more valuable than any single drug.', writingTip: '"Harness the power of" and "harness technology" are natural. A sophisticated verb of use.', topic: 'Science', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['harness technology', 'harness the power of', 'harness energy'], alternatives: ['exploit', 'utilise', 'channel'], priority: 'high_value' },
    { id: 'sci_v30', type: 'vocabulary', term: 'inconclusive', pronunciation: '/ˌɪnkənˈkluːsɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Not leading to a definite result or conclusion.', vietnameseMeaning: 'Chưa đưa ra kết luận rõ ràng.', example: 'The findings remain inconclusive, which is a reason for further study rather than for dismissing the concern.', writingTip: 'A precise hedging word. Using it correctly demonstrates genuine academic caution.', topic: 'Science', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the evidence is inconclusive', 'inconclusive results', 'remain inconclusive'], antonym: 'conclusive', priority: 'must_learn' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'sci_c1', type: 'collocation', term: 'carry out research', collocationType: 'Verb + Noun', definition: 'To perform a systematic investigation.', vietnameseMeaning: 'Tiến hành nghiên cứu.', example: 'Universities carry out research that no company would fund because the payoff is decades away.', alternative: 'conduct research', topic: 'Science', bandLevel: '5-6', task: 'both', priority: 'must_learn', writingTip: 'Never "do a research" — "research" is uncountable and takes "carry out" or "conduct".' },
    { id: 'sci_c2', type: 'collocation', term: 'scientific evidence', collocationType: 'Adj + Noun', definition: 'Facts gathered through systematic investigation.', vietnameseMeaning: 'Bằng chứng khoa học.', example: 'Scientific evidence for the link between smoking and cancer accumulated for years before policy changed.', topic: 'Science', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'sci_c3', type: 'collocation', term: 'medical research', collocationType: 'Adj + Noun', definition: 'Investigation aimed at improving health and treating disease.', vietnameseMeaning: 'Nghiên cứu y học.', example: 'Medical research has extended life expectancy far more than any improvement in individual behaviour.', topic: 'Science', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'sci_c4', type: 'collocation', term: 'conduct an experiment', collocationType: 'Verb + Noun', definition: 'To perform a controlled scientific test.', vietnameseMeaning: 'Thực hiện một thí nghiệm.', example: 'Before any drug reaches patients, researchers conduct experiments on cells and then on animals.', topic: 'Science', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'sci_c5', type: 'collocation', term: 'scientific progress', collocationType: 'Adj + Noun', definition: 'Advancement in scientific knowledge and capability.', vietnameseMeaning: 'Tiến bộ khoa học.', example: 'Scientific progress is rarely as sudden as popular accounts suggest.', topic: 'Science', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'sci_c6', type: 'collocation', term: 'find a cure for', collocationType: 'Verb + Noun', definition: 'To discover a way of eliminating a disease.', vietnameseMeaning: 'Tìm ra phương pháp chữa khỏi bệnh.', example: 'Enormous sums have been spent trying to find a cure for conditions that turn out to be many diseases at once.', topic: 'Science', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'sci_c7', type: 'collocation', term: 'test a theory', collocationType: 'Verb + Noun', definition: 'To check whether an explanation holds up against observation.', vietnameseMeaning: 'Kiểm chứng một lý thuyết.', example: 'Researchers test a theory by trying to break it, not by looking for cases that fit.', topic: 'Science', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'sci_c8', type: 'collocation', term: 'government funding', collocationType: 'Noun + Noun', definition: 'Public money allocated to support an activity.', vietnameseMeaning: 'Kinh phí từ ngân sách nhà nước.', example: 'Government funding for basic science is easy to cut and extremely slow to rebuild.', topic: 'Science', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },

    // Advanced (Band 6-7)
    { id: 'sci_c9', type: 'collocation', term: 'a major breakthrough', collocationType: 'Adj + Noun', definition: 'An important discovery that transforms what is possible.', vietnameseMeaning: 'Một bước đột phá quan trọng.', example: 'A major breakthrough in battery chemistry would do more for emissions than a decade of exhortation.', topic: 'Science', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'sci_c10', type: 'collocation', term: 'raise ethical concerns', collocationType: 'Verb + Noun', definition: 'To prompt moral questions that need to be addressed.', vietnameseMeaning: 'Làm dấy lên những quan ngại về đạo đức.', example: 'Editing the genes of unborn children raises ethical concerns that no technical advance can resolve.', topic: 'Science', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'sci_c11', type: 'collocation', term: 'allocate funding to research', collocationType: 'Verb + Noun', definition: 'To assign money for the purpose of investigation.', vietnameseMeaning: 'Phân bổ kinh phí cho nghiên cứu.', example: 'Governments allocate funding to research whose benefits will arrive long after the current administration has gone.', topic: 'Science', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'sci_c12', type: 'collocation', term: 'publish findings', collocationType: 'Verb + Noun', definition: 'To make research results publicly available.', vietnameseMeaning: 'Công bố kết quả nghiên cứu.', example: 'Researchers who publish findings that fail to support their hypothesis are still rare, and that is a problem.', topic: 'Science', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'sci_c13', type: 'collocation', term: 'draw a conclusion', collocationType: 'Verb + Noun', definition: 'To reach a judgement based on the available information.', vietnameseMeaning: 'Rút ra kết luận.', example: 'It is too early to draw a firm conclusion from a single small study.', topic: 'Science', bandLevel: '6-7', task: 'both', priority: 'must_learn' },
    { id: 'sci_c14', type: 'collocation', term: 'undergo peer review', collocationType: 'Verb + Noun', definition: 'To be examined by other experts before publication.', vietnameseMeaning: 'Trải qua quá trình bình duyệt.', example: 'Claims that have not undergone peer review deserve considerably more caution than those that have.', topic: 'Science', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'sci_c15', type: 'collocation', term: 'push the boundaries of knowledge', collocationType: 'Verb + Noun', definition: 'To extend what is known beyond its current limits.', vietnameseMeaning: 'Mở rộng ranh giới tri thức.', example: 'Curiosity-driven work pushes the boundaries of knowledge in directions no funding committee would have chosen.', topic: 'Science', bandLevel: '6-7', task: 'task2', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'sci_c16', type: 'collocation', term: 'empirical evidence', collocationType: 'Adj + Noun', definition: 'Evidence obtained through observation or experiment.', vietnameseMeaning: 'Bằng chứng thực nghiệm.', example: 'The empirical evidence supports a modest effect, not the transformation the headlines described.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'sci_c17', type: 'collocation', term: 'weigh the risks against the benefits', collocationType: 'Verb phrase', definition: 'To compare potential harms with potential advantages before deciding.', vietnameseMeaning: 'Cân nhắc giữa rủi ro và lợi ích.', example: 'Regulators must weigh the risks against the benefits with imperfect information and no option to wait indefinitely.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'sci_c18', type: 'collocation', term: 'establish a causal link', collocationType: 'Verb + Noun', definition: 'To demonstrate that one thing actually causes another.', vietnameseMeaning: 'Xác lập mối quan hệ nhân quả.', example: 'Establishing a causal link requires far more than showing that two trends move together.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'must_learn', writingTip: 'Excellent for the classic "correlation is not causation" point.' },
    { id: 'sci_c19', type: 'collocation', term: 'adhere to rigorous standards', collocationType: 'Verb + Noun', definition: 'To follow demanding rules of method and conduct.', vietnameseMeaning: 'Tuân thủ các tiêu chuẩn nghiêm ngặt.', example: 'Laboratories that adhere to rigorous standards produce fewer results, and considerably more reliable ones.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'sci_c20', type: 'collocation', term: 'the pace of scientific advancement', collocationType: 'Noun phrase', definition: 'The speed at which scientific knowledge is developing.', vietnameseMeaning: 'Tốc độ tiến bộ của khoa học.', example: 'The pace of scientific advancement has outstripped the ability of regulators to keep up.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'sci_p1', type: 'phrasal_verb', term: 'carry out', partOfSpeech: 'phrasal verb (separable)', definition: 'To perform a task or investigation.', vietnameseMeaning: 'Tiến hành, thực hiện (nghiên cứu, thí nghiệm).', example: 'The team carried out a series of trials across four countries simultaneously.', formalAlternative: 'conduct', topic: 'Science', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['carry out research', 'carry out tests', 'carry out an experiment'], academicAlternatives: ['conduct', 'perform', 'undertake'] },
    { id: 'sci_p2', type: 'phrasal_verb', term: 'find out', partOfSpeech: 'phrasal verb (separable)', definition: 'To discover a fact through investigation.', vietnameseMeaning: 'Tìm ra, phát hiện.', example: 'Researchers set out to find out why the treatment worked in one population but not another.', formalAlternative: 'determine', topic: 'Science', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['determine', 'establish', 'ascertain'] },
    { id: 'sci_p3', type: 'phrasal_verb', term: 'come up with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To produce an idea or solution.', vietnameseMeaning: 'Nghĩ ra, đưa ra (ý tưởng, giải pháp).', example: 'Small teams frequently come up with ideas that large, well-funded laboratories overlook.', formalAlternative: 'devise', topic: 'Science', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Conversational. "Devise", "develop" or "propose" is preferable in a formal essay.', academicAlternatives: ['devise', 'formulate', 'propose'] },
    { id: 'sci_p4', type: 'phrasal_verb', term: 'test out', partOfSpeech: 'phrasal verb (separable)', definition: 'To try something in order to see whether it works.', vietnameseMeaning: 'Thử nghiệm để kiểm tra hiệu quả.', example: 'New diagnostic tools are tested out in a handful of hospitals before any national rollout.', formalAlternative: 'trial', topic: 'Science', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['trial', 'evaluate', 'assess'] },
    { id: 'sci_p5', type: 'phrasal_verb', term: 'rule out', partOfSpeech: 'phrasal verb (separable)', definition: 'To eliminate a possibility from consideration.', vietnameseMeaning: 'Loại trừ (một khả năng).', example: 'The study ruled out diet as an explanation, which narrowed the search considerably.', formalAlternative: 'exclude', topic: 'Science', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['rule out a possibility', 'cannot be ruled out'], academicAlternatives: ['exclude', 'eliminate', 'discount'] },

    // Advanced / less common
    { id: 'sci_p6', type: 'phrasal_verb', term: 'build on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To use existing work as a foundation for further development.', vietnameseMeaning: 'Kế thừa và phát triển từ nền tảng có sẵn.', example: 'Every significant advance builds on decades of unglamorous work by people whose names are forgotten.', formalAlternative: 'extend', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['build on earlier findings', 'build on previous research'], academicAlternatives: ['extend', 'expand upon', 'develop from'] },
    { id: 'sci_p7', type: 'phrasal_verb', term: 'account for', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To explain the reason for something; to make up a proportion.', vietnameseMeaning: 'Lý giải nguyên nhân; chiếm một tỷ lệ.', example: 'Genetics accounts for only part of the variation; environment explains a great deal of the rest.', formalAlternative: 'explain', topic: 'Science', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['account for the difference', 'account for 40%'], academicAlternatives: ['explain', 'constitute', 'represent'] },
    { id: 'sci_p8', type: 'phrasal_verb', term: 'stem from', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To originate from a particular cause.', vietnameseMeaning: 'Bắt nguồn từ, có nguyên nhân từ.', example: 'Much public distrust of science stems from the way uncertainty is reported as disagreement.', formalAlternative: 'originate from', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', academicAlternatives: ['originate from', 'arise from', 'derive from'] },
    { id: 'sci_p9', type: 'phrasal_verb', term: 'shed light on', partOfSpeech: 'phrasal verb', definition: 'To help explain something that was previously unclear.', vietnameseMeaning: 'Làm sáng tỏ, giúp hiểu rõ hơn.', example: 'Brain imaging has shed light on processes that were entirely inaccessible a generation ago.', formalAlternative: 'clarify', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'high_value', academicAlternatives: ['clarify', 'illuminate', 'elucidate'] },
    { id: 'sci_p10', type: 'phrasal_verb', term: 'follow up', partOfSpeech: 'phrasal verb (separable)', definition: 'To investigate something further after an initial finding.', vietnameseMeaning: 'Theo dõi tiếp, nghiên cứu bổ sung.', example: 'The initial result was promising, but nobody followed it up for another fifteen years.', formalAlternative: 'pursue further', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['follow-up study', 'follow up on findings'], academicAlternatives: ['pursue further', 'investigate further'] },
  ],

  writingPhrases: [
    { id: 'sci_w1', type: 'writing_phrase', term: 'The case for funding basic research rests on the observation that...', function: 'Introducing an argument', vietnameseMeaning: 'Lập luận ủng hộ tài trợ nghiên cứu cơ bản dựa trên nhận định rằng...', example: 'The case for funding basic research rests on the observation that its most valuable results were never the ones anyone predicted.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'sci_w2', type: 'writing_phrase', term: 'Progress in this field has been slow largely because...', function: 'Giving a reason', vietnameseMeaning: 'Tiến bộ trong lĩnh vực này diễn ra chậm chủ yếu vì...', example: 'Progress in this field has been slow largely because the trials required take decades to produce usable results.', topic: 'Science', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'sci_w3', type: 'writing_phrase', term: 'The evidence suggests that this effect is driven primarily by...', function: 'Explaining a cause', vietnameseMeaning: 'Bằng chứng cho thấy hiệu ứng này chủ yếu do... gây ra.', example: 'The evidence suggests that this effect is driven primarily by exposure in early childhood rather than in adulthood.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'sci_w4', type: 'writing_phrase', term: 'The practical consequence of this discovery is that...', function: 'Explaining an effect', vietnameseMeaning: 'Hệ quả thực tiễn của khám phá này là...', example: 'The practical consequence of this discovery is that a condition once considered untreatable can now be managed at home.', topic: 'Science', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'sci_w5', type: 'writing_phrase', term: 'The development of penicillin is instructive here:', function: 'Giving an example', vietnameseMeaning: 'Câu chuyện phát triển penicillin rất đáng suy ngẫm ở đây:', example: 'The development of penicillin is instructive here: an accidental observation took more than a decade to become a usable medicine.', topic: 'Science', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'sci_w6', type: 'writing_phrase', term: 'The most obvious benefit of this line of research is...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi ích rõ ràng nhất của hướng nghiên cứu này là...', example: 'The most obvious benefit of this line of research is the prospect of diagnosing disease years before symptoms appear.', topic: 'Science', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'sci_w7', type: 'writing_phrase', term: 'The ethical objection to this technology is that...', function: 'Discussing disadvantages', vietnameseMeaning: 'Phản biện về mặt đạo đức đối với công nghệ này là...', example: 'The ethical objection to this technology is that those affected most by it are precisely those least able to consent.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'sci_w8', type: 'writing_phrase', term: 'A sensible safeguard would be to require that...', function: 'Suggesting a solution', vietnameseMeaning: 'Một biện pháp bảo vệ hợp lý sẽ là yêu cầu rằng...', example: 'A sensible safeguard would be to require that any publicly funded research be published in full, including negative results.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'sci_w9', type: 'writing_phrase', term: 'In my judgement, the greater risk lies not in the technology itself but in...', function: 'Expressing an opinion', vietnameseMeaning: 'Theo đánh giá của tôi, rủi ro lớn hơn không nằm ở bản thân công nghệ mà ở...', example: 'In my judgement, the greater risk lies not in the technology itself but in deploying it before we understand who it fails.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'sci_w10', type: 'writing_phrase', term: 'Applied research delivers immediate returns, whereas fundamental research...', function: 'Comparing ideas', vietnameseMeaning: 'Nghiên cứu ứng dụng mang lại kết quả tức thì, trong khi nghiên cứu cơ bản...', example: 'Applied research delivers immediate returns, whereas fundamental research produces the knowledge that applied work later depends on.', topic: 'Science', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'sci_m1', type: 'common_mistake', incorrect: 'Scientists have done many researches about this problem.', correct: 'Scientists have carried out a great deal of research into this problem.', explanation: '"Research" is uncountable: no plural and no "many". The verb is "carry out" or "conduct", and the preposition is "research into" or "research on".', topic: 'Science', priority: 'must_learn' },
    { id: 'sci_m2', type: 'common_mistake', incorrect: 'There are many evidences that support this theory.', correct: 'There is considerable evidence to support this theory.', explanation: '"Evidence" is uncountable and takes a singular verb. Quantify it with "considerable", "little" or "a body of".', topic: 'Science', priority: 'must_learn' },
    { id: 'sci_m3', type: 'common_mistake', incorrect: 'Science and technology develops very fast nowadays.', correct: 'Science and technology are developing rapidly.', explanation: 'Two subjects joined by "and" take a plural verb. "Fast" is also informal in this position — use "rapidly" or "at speed".', topic: 'Science', priority: 'high_value' },
    { id: 'sci_m4', type: 'common_mistake', incorrect: 'The research proved that stress causes heart disease.', correct: 'The study found a strong association between stress and heart disease.', explanation: 'Science rarely "proves" anything outright, and a single study never does. Use hedged verbs — "suggests", "indicates", "found an association" — which examiners reward as academic caution.', topic: 'Science', priority: 'must_learn' },
    { id: 'sci_m5', type: 'common_mistake', incorrect: 'Scientists made a new medicine to cure the disease.', correct: 'Researchers developed a new drug to treat the disease.', explanation: '"Make" is too general for scientific work — use "develop". Note also that "treat" is usually accurate where "cure" overstates: most drugs manage a condition rather than eliminate it.', topic: 'Science', priority: 'high_value' },
  ],

  learnFirst: {
    vocabulary: ['sci_v4', 'sci_v11', 'sci_v13', 'sci_v15', 'sci_v18', 'sci_v21', 'sci_v26', 'sci_v27', 'sci_v30', 'sci_v6'],
    collocations: ['sci_c1', 'sci_c10', 'sci_c16', 'sci_c17', 'sci_c18'],
    phrasalVerbs: ['sci_p1', 'sci_p5', 'sci_p6'],
    writingPhrases: ['sci_w1', 'sci_w7', 'sci_w8'],
  },
}
