import type { TopicData } from '../types'

export const SOCIETY: TopicData = {
  topic: 'Society',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'soc_v1', type: 'vocabulary', term: 'community', pronunciation: '/kəˈmjuːnəti/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A group of people living in the same place or sharing something in common.', vietnameseMeaning: 'Cộng đồng.', example: 'Libraries survive because they serve a community, not because they lend books efficiently.', writingTip: 'Very productive: local community, the business community, a sense of community.', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['local community', 'a sense of community', 'community spirit', 'serve the community'], wordFamily: ['communal (adj)'], priority: 'must_learn' },
    { id: 'soc_v2', type: 'vocabulary', term: 'tradition', pronunciation: '/trəˈdɪʃn/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A belief or custom passed down within a group over time.', vietnameseMeaning: 'Truyền thống, phong tục lâu đời.', example: 'Traditions survive not because they are useful but because they give people a shared identity.', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a long-standing tradition', 'preserve traditions', 'break with tradition'], wordFamily: ['traditional (adj)', 'traditionally (adv)'], priority: 'high_value' },
    { id: 'soc_v3', type: 'vocabulary', term: 'generation', pronunciation: '/ˌdʒenəˈreɪʃn/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'All the people born at roughly the same time.', vietnameseMeaning: 'Thế hệ.', example: 'This is the first generation in a century likely to be poorer than its parents.', writingTip: 'Useful phrases: the younger generation, future generations, a generation gap.', topic: 'Society', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['the younger generation', 'future generations', 'the generation gap'], wordFamily: ['generational (adj)'], priority: 'must_learn' },
    { id: 'soc_v4', type: 'vocabulary', term: 'equality', pronunciation: '/iˈkwɒləti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The state of everyone having the same rights and opportunities.', vietnameseMeaning: 'Sự bình đẳng.', example: 'Legal equality means little without the resources to exercise the rights it grants.', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['gender equality', 'promote equality', 'equality of opportunity'], antonym: 'inequality', wordFamily: ['equal (adj)', 'equally (adv)'], priority: 'must_learn' },
    { id: 'soc_v5', type: 'vocabulary', term: 'volunteer', pronunciation: '/ˌvɒlənˈtɪə/', partOfSpeech: 'noun / verb', cefrLevel: 'B1', definition: 'A person who works without pay; to offer to do so.', vietnameseMeaning: 'Tình nguyện viên; làm tình nguyện.', example: 'Volunteers deliver services that governments quietly rely on but never budget for.', writingTip: 'Note the stress on the final syllable. The adjective is "voluntary".', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['voluntary work', 'volunteer for', 'a team of volunteers'], wordFamily: ['voluntary (adj)', 'voluntarily (adv)'], priority: 'high_value' },
    { id: 'soc_v6', type: 'vocabulary', term: 'population', pronunciation: '/ˌpɒpjuˈleɪʃn/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'All the people living in a particular area.', vietnameseMeaning: 'Dân số.', example: 'A shrinking population creates problems that no amount of economic growth can solve.', writingTip: 'Essential in Task 1. Verbs: grow, shrink, decline, double.', topic: 'Society', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['an ageing population', 'population growth', 'the urban population', 'population density'], wordFamily: ['populate (v)', 'populous (adj)'], priority: 'must_learn' },
    { id: 'soc_v7', type: 'vocabulary', term: 'attitude', pronunciation: '/ˈætɪtjuːd/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A settled way of thinking or feeling about something.', vietnameseMeaning: 'Thái độ, quan niệm.', example: 'Attitudes towards mental illness have changed more in twenty years than in the previous century.', writingTip: 'The preposition is "towards" (or "to"), never "with": "attitudes towards work".', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['attitudes towards', 'change attitudes', 'a positive attitude', 'shifting attitudes'], priority: 'must_learn' },
    { id: 'soc_v8', type: 'vocabulary', term: 'behaviour', pronunciation: '/bɪˈheɪvjə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'The way in which a person or group acts.', vietnameseMeaning: 'Hành vi, cách cư xử.', example: 'Changing behaviour is far harder than changing opinions, as every public campaign discovers.', writingTip: 'Uncountable in this sense. Note the British spelling with "-our"; American English uses "behavior".', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['antisocial behaviour', 'change behaviour', 'behaviour patterns'], wordFamily: ['behave (v)', 'behavioural (adj)'], priority: 'high_value' },
    { id: 'soc_v9', type: 'vocabulary', term: 'responsibility', pronunciation: '/rɪˌspɒnsəˈbɪləti/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A duty to deal with something or care for someone.', vietnameseMeaning: 'Trách nhiệm.', example: 'Responsibility for social care is shared between so many bodies that nobody is truly accountable.', writingTip: 'Patterns: "take responsibility for", "have a responsibility to do something".', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['take responsibility for', 'shared responsibility', 'a moral responsibility'], wordFamily: ['responsible (adj)', 'responsibly (adv)'], priority: 'must_learn' },
    { id: 'soc_v10', type: 'vocabulary', term: 'discrimination', pronunciation: '/dɪˌskrɪmɪˈneɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Unfair treatment of people because of who they are.', vietnameseMeaning: 'Sự phân biệt đối xử.', example: 'Discrimination is rarely announced; it usually appears as a series of small refusals.', writingTip: 'The preposition is "against": "discrimination against older workers".', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['racial discrimination', 'discrimination against', 'combat discrimination', 'age discrimination'], wordFamily: ['discriminate (v)', 'discriminatory (adj)'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'soc_v11', type: 'vocabulary', term: 'inequality', pronunciation: '/ˌɪnɪˈkwɒləti/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'An unfair difference in wealth, status or opportunity.', vietnameseMeaning: 'Sự bất bình đẳng.', example: 'Inequality becomes politically dangerous when people stop believing the rules are fair.', writingTip: 'Verbs: reduce, address, tackle, widen. Avoid "solve inequality" — it cannot be solved outright.', topic: 'Society', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['income inequality', 'address inequality', 'widening inequality', 'social inequality'], antonym: 'equality', priority: 'must_learn' },
    { id: 'soc_v12', type: 'vocabulary', term: 'norm', pronunciation: '/nɔːm/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'A standard of behaviour that is typical or expected in a group.', vietnameseMeaning: 'Chuẩn mực, quy tắc ứng xử chung.', example: 'Social norms restrain behaviour far more effectively than laws ever could.', writingTip: 'Also useful as "the norm": "Remote work has become the norm in several industries."', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['social norms', 'cultural norms', 'become the norm', 'challenge norms'], wordFamily: ['normal (adj)', 'normative (adj)'], priority: 'must_learn' },
    { id: 'soc_v13', type: 'vocabulary', term: 'integrate', pronunciation: '/ˈɪntɪɡreɪt/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To become, or help someone become, a full part of a group.', vietnameseMeaning: 'Hoà nhập, hoà nhập vào cộng đồng.', example: 'Newcomers integrate fastest where language classes are free and work is legally available.', writingTip: 'Pattern: "integrate into society". "Integration" is the key noun in immigration essays.', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['integrate into society', 'fully integrated', 'social integration'], antonym: 'segregate', wordFamily: ['integration (n)', 'integrated (adj)'], priority: 'must_learn' },
    { id: 'soc_v14', type: 'vocabulary', term: 'isolation', pronunciation: '/ˌaɪsəˈleɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The state of being alone and separated from others.', vietnameseMeaning: 'Sự cô lập, tình trạng bị tách biệt.', example: 'Social isolation among the elderly carries a health risk comparable to heavy smoking.', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['social isolation', 'suffer isolation', 'a sense of isolation'], wordFamily: ['isolate (v)', 'isolated (adj)'], priority: 'high_value' },
    { id: 'soc_v15', type: 'vocabulary', term: 'demographic', pronunciation: '/ˌdeməˈɡræfɪk/', partOfSpeech: 'adjective / noun', cefrLevel: 'C1', definition: 'Relating to the structure of a population; a particular population group.', vietnameseMeaning: 'Thuộc về nhân khẩu học; nhóm dân cư.', example: 'Demographic change will reshape public spending more profoundly than any political decision.', writingTip: 'The plural noun "demographics" means the statistics themselves. Very useful in Task 1.', topic: 'Society', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['demographic change', 'demographic shift', 'a key demographic'], wordFamily: ['demography (n)'], priority: 'high_value' },
    { id: 'soc_v16', type: 'vocabulary', term: 'welfare', pronunciation: '/ˈwelfeə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The health and wellbeing of people; state support for those in need.', vietnameseMeaning: 'Phúc lợi xã hội; sự chăm lo đời sống.', example: 'A generous welfare system is affordable only where most people are working and paying tax.', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the welfare state', 'welfare benefits', 'social welfare', 'child welfare'], priority: 'high_value' },
    { id: 'soc_v17', type: 'vocabulary', term: 'prejudice', pronunciation: '/ˈpredʒudɪs/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'An unreasonable opinion formed without knowledge or experience.', vietnameseMeaning: 'Định kiến, thành kiến.', example: 'Prejudice weakens fastest where people of different backgrounds work together as equals.', writingTip: 'Prejudice is the attitude; discrimination is the resulting behaviour. Distinguish them clearly.', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['racial prejudice', 'overcome prejudice', 'deep-seated prejudice'], alternatives: ['bias', 'bigotry'], wordFamily: ['prejudiced (adj)'], priority: 'high_value' },
    { id: 'soc_v18', type: 'vocabulary', term: 'diversity', pronunciation: '/daɪˈvɜːsəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The presence of people of many different kinds within a group.', vietnameseMeaning: 'Sự đa dạng (về văn hoá, sắc tộc).', example: 'Diversity enriches a society only when institutions are prepared to adapt to it.', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cultural diversity', 'ethnic diversity', 'celebrate diversity', 'greater diversity'], wordFamily: ['diverse (adj)', 'diversify (v)'], priority: 'must_learn' },
    { id: 'soc_v19', type: 'vocabulary', term: 'mobility', pronunciation: '/məʊˈbɪləti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The ability to move between social classes or geographic places.', vietnameseMeaning: 'Sự dịch chuyển (địa lý hoặc giai tầng xã hội).', example: 'Social mobility has fallen in most wealthy countries even as average incomes have risen.', writingTip: '"Social mobility" is one of the highest-value phrases in Society essays.', topic: 'Society', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['social mobility', 'upward mobility', 'limited mobility'], wordFamily: ['mobile (adj)'], priority: 'must_learn' },
    { id: 'soc_v20', type: 'vocabulary', term: 'ageing population', pronunciation: '/ˈeɪdʒɪŋ ˌpɒpjuˈleɪʃn/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A population in which the average age is rising.', vietnameseMeaning: 'Dân số già hoá.', example: 'An ageing population is a triumph of public health and a problem for public finance.', writingTip: 'Note the British spelling "ageing"; American English writes "aging".', topic: 'Society', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a rapidly ageing population', 'cope with an ageing population'], priority: 'must_learn' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'soc_v21', type: 'vocabulary', term: 'cohesion', pronunciation: '/kəʊˈhiːʒn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The state of a group being united and working well together.', vietnameseMeaning: 'Sự gắn kết, tính cố kết cộng đồng.', example: 'Social cohesion depends less on shared origins than on shared institutions.', writingTip: '"Social cohesion" is the standard collocation and an instant Band 7+ signal.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['social cohesion', 'maintain cohesion', 'undermine cohesion'], alternatives: ['unity', 'solidarity'], wordFamily: ['cohesive (adj)'], priority: 'must_learn' },
    { id: 'soc_v22', type: 'vocabulary', term: 'marginalise', pronunciation: '/ˈmɑːdʒɪnəlaɪz/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To push a group to the edges of society and treat them as unimportant.', vietnameseMeaning: 'Đẩy ra ngoài lề xã hội, gạt bỏ.', example: 'Digital-only public services marginalise precisely the people who need them most.', writingTip: 'Most often passive: "are marginalised", "marginalised groups".', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['marginalised groups', 'marginalised communities', 'increasingly marginalised'], alternatives: ['exclude', 'sideline', 'alienate'], wordFamily: ['marginalisation (n)', 'marginal (adj)'], priority: 'must_learn' },
    { id: 'soc_v23', type: 'vocabulary', term: 'erode', pronunciation: '/ɪˈrəʊd/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To gradually destroy or weaken something.', vietnameseMeaning: 'Bào mòn, làm suy yếu dần.', example: 'Constant relocation for work erodes the community ties that make neighbourhoods safe.', writingTip: 'Excellent for slow, invisible damage: erode trust, values, confidence, rights.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['erode trust', 'erode traditional values', 'gradually erode'], alternatives: ['undermine', 'weaken', 'wear away'], wordFamily: ['erosion (n)'], priority: 'must_learn' },
    { id: 'soc_v24', type: 'vocabulary', term: 'altruism', pronunciation: '/ˈæltruɪzəm/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'Concern for the welfare of others without expecting anything in return.', vietnameseMeaning: 'Lòng vị tha, tinh thần vì người khác.', example: 'Blood donation systems that rely on altruism collect safer blood than those that pay donors.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['pure altruism', 'an act of altruism'], antonym: 'selfishness', wordFamily: ['altruistic (adj)'], priority: 'optional' },
    { id: 'soc_v25', type: 'vocabulary', term: 'entrenched', pronunciation: '/ɪnˈtrentʃt/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'So firmly established that it is very difficult to change.', vietnameseMeaning: 'Ăn sâu, cố hữu, khó thay đổi.', example: 'Entrenched attitudes towards gender roles change slowly even where the law has moved quickly.', writingTip: 'Use before attitudes, inequality, poverty, interests. Signals that easy solutions will fail.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['deeply entrenched', 'entrenched attitudes', 'entrenched inequality'], alternatives: ['ingrained', 'deep-seated'], wordFamily: ['entrench (v)'], priority: 'must_learn' },
    { id: 'soc_v26', type: 'vocabulary', term: 'philanthropy', pronunciation: '/fɪˈlænθrəpi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'The practice of giving money to good causes.', vietnameseMeaning: 'Hoạt động từ thiện của người giàu.', example: 'Philanthropy can fund experiments that governments would never risk, but it cannot replace taxation.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['private philanthropy', 'rely on philanthropy'], wordFamily: ['philanthropic (adj)', 'philanthropist (n)'], priority: 'optional' },
    { id: 'soc_v27', type: 'vocabulary', term: 'disenfranchised', pronunciation: '/ˌdɪsɪnˈfræntʃaɪzd/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Deprived of rights, especially the right to vote or to influence decisions.', vietnameseMeaning: 'Bị tước quyền, không có tiếng nói.', example: 'Communities that feel disenfranchised eventually stop participating altogether.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['feel disenfranchised', 'disenfranchised voters'], alternatives: ['excluded', 'powerless'], wordFamily: ['disenfranchise (v)'], priority: 'optional' },
    { id: 'soc_v28', type: 'vocabulary', term: 'conform', pronunciation: '/kənˈfɔːm/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To behave according to the expectations of a group.', vietnameseMeaning: 'Tuân theo, làm theo khuôn mẫu chung.', example: 'Adolescents conform to peer expectations far more readily than to parental instruction.', writingTip: 'Pattern: "conform to" a standard or expectation, never "conform with" in this sense.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['conform to norms', 'pressure to conform', 'refuse to conform'], wordFamily: ['conformity (n)', 'conformist (n/adj)'], priority: 'high_value' },
    { id: 'soc_v29', type: 'vocabulary', term: 'stratification', pronunciation: '/ˌstrætɪfɪˈkeɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'The division of society into distinct layers of status or wealth.', vietnameseMeaning: 'Sự phân tầng xã hội.', example: 'Housing costs have produced a stratification by geography as rigid as any by class.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['social stratification', 'increasing stratification'], wordFamily: ['stratified (adj)'], priority: 'optional' },
    { id: 'soc_v30', type: 'vocabulary', term: 'solidarity', pronunciation: '/ˌsɒlɪˈdærəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Mutual support within a group facing a shared situation.', vietnameseMeaning: 'Tình đoàn kết, sự tương trợ.', example: 'Solidarity is easiest to sustain in societies where people expect to need help themselves one day.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a sense of solidarity', 'show solidarity with', 'social solidarity'], alternatives: ['unity', 'mutual support'], priority: 'high_value' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'soc_c1', type: 'collocation', term: 'social problems', collocationType: 'Adj + Noun', definition: 'Difficulties affecting many people in a society.', vietnameseMeaning: 'Các vấn đề xã hội.', example: 'Most social problems have several causes and no single remedy.', topic: 'Society', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'Use the adjective "social", not the noun "society", before a noun.' },
    { id: 'soc_c2', type: 'collocation', term: 'the older generation', collocationType: 'Adj + Noun', definition: 'People who were born considerably earlier than those now young.', vietnameseMeaning: 'Thế hệ lớn tuổi.', example: 'The older generation is often blamed for changes it had little power to prevent.', topic: 'Society', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'soc_c3', type: 'collocation', term: 'a sense of community', collocationType: 'Noun + Prep + Noun', definition: 'A feeling of belonging among people who live or work together.', vietnameseMeaning: 'Tinh thần cộng đồng, cảm giác thuộc về.', example: 'Frequent moves for work make a sense of community almost impossible to build.', topic: 'Society', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'soc_c4', type: 'collocation', term: 'equal opportunities', collocationType: 'Adj + Noun', definition: 'The same chances in life for everyone regardless of background.', vietnameseMeaning: 'Cơ hội bình đẳng cho mọi người.', example: 'Providing equal opportunities requires unequal spending, since some children start much further back.', topic: 'Society', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'soc_c5', type: 'collocation', term: 'traditional values', collocationType: 'Adj + Noun', definition: 'Long-established beliefs about how people should live.', vietnameseMeaning: 'Các giá trị truyền thống.', example: 'Traditional values are frequently invoked most loudly at the point where they are disappearing.', topic: 'Society', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'soc_c6', type: 'collocation', term: 'an ageing population', collocationType: 'Adj + Noun', definition: 'A population whose average age is increasing.', vietnameseMeaning: 'Dân số đang già hoá.', example: 'An ageing population means a shrinking number of workers supporting a growing number of pensioners.', topic: 'Society', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'soc_c7', type: 'collocation', term: 'do voluntary work', collocationType: 'Verb + Noun', definition: 'To help others without being paid.', vietnameseMeaning: 'Làm công việc tình nguyện.', example: 'Students who do voluntary work develop skills that no classroom can teach.', alternative: 'volunteer', topic: 'Society', bandLevel: '5-6', task: 'task2', priority: 'high_value', writingTip: 'The verb is "do" voluntary work, not "make".' },
    { id: 'soc_c8', type: 'collocation', term: 'the gap between rich and poor', collocationType: 'Noun + Prep + Noun', definition: 'The difference in wealth between the wealthiest and poorest.', vietnameseMeaning: 'Khoảng cách giàu nghèo.', example: 'The gap between rich and poor is now visible in life expectancy as well as in income.', topic: 'Society', bandLevel: '5-6', task: 'both', priority: 'must_learn' },

    // Advanced (Band 6-7)
    { id: 'soc_c9', type: 'collocation', term: 'social mobility', collocationType: 'Adj + Noun', definition: 'The ability of people to move to a higher social or economic position.', vietnameseMeaning: 'Sự dịch chuyển giai tầng xã hội.', example: 'Social mobility depends far more on where a child is born than on how hard they work.', topic: 'Society', bandLevel: '6-7', task: 'both', priority: 'must_learn' },
    { id: 'soc_c10', type: 'collocation', term: 'social norms', collocationType: 'Adj + Noun', definition: 'Unwritten rules governing acceptable behaviour.', vietnameseMeaning: 'Chuẩn mực xã hội.', example: 'Social norms change more quickly than laws and often force the law to follow.', topic: 'Society', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'soc_c11', type: 'collocation', term: 'racial discrimination', collocationType: 'Adj + Noun', definition: 'Unfair treatment based on a person’s ethnic background.', vietnameseMeaning: 'Phân biệt chủng tộc.', example: 'Racial discrimination in hiring persists even where identical applications are compared.', topic: 'Society', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'soc_c12', type: 'collocation', term: 'the welfare state', collocationType: 'Noun + Noun', definition: 'A system in which the government provides support for citizens in need.', vietnameseMeaning: 'Nhà nước phúc lợi.', example: 'The welfare state was designed for a working life that no longer resembles most people’s.', topic: 'Society', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'soc_c13', type: 'collocation', term: 'integrate into society', collocationType: 'Verb + Prep + Noun', definition: 'To become a full participating member of a community.', vietnameseMeaning: 'Hoà nhập vào xã hội.', example: 'Refugees integrate into society fastest when they are permitted to work immediately.', topic: 'Society', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'soc_c14', type: 'collocation', term: 'social isolation', collocationType: 'Adj + Noun', definition: 'A lack of contact with other people.', vietnameseMeaning: 'Sự cô lập xã hội.', example: 'Social isolation is now treated as a public health issue rather than a private misfortune.', topic: 'Society', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'soc_c15', type: 'collocation', term: 'demographic change', collocationType: 'Adj + Noun', definition: 'A shift in the age, size or composition of a population.', vietnameseMeaning: 'Sự thay đổi cơ cấu dân số.', example: 'Demographic change is the most predictable challenge governments face and the least prepared for.', topic: 'Society', bandLevel: '6-7', task: 'both', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'soc_c16', type: 'collocation', term: 'maintain social cohesion', collocationType: 'Verb + Noun', definition: 'To keep a society united and functioning together.', vietnameseMeaning: 'Duy trì sự gắn kết xã hội.', example: 'Shared public spaces do more to maintain social cohesion than any official campaign.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'soc_c17', type: 'collocation', term: 'marginalised communities', collocationType: 'Adj + Noun', definition: 'Groups pushed to the edges of social and economic life.', vietnameseMeaning: 'Các cộng đồng bị đẩy ra ngoài lề.', example: 'Policies designed without input from marginalised communities tend to fail them again.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'soc_c18', type: 'collocation', term: 'erode traditional values', collocationType: 'Verb + Noun', definition: 'To gradually weaken long-established beliefs and customs.', vietnameseMeaning: 'Làm mai một các giá trị truyền thống.', example: 'Critics argue that global media erodes traditional values, though young people rarely see it that way.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'soc_c19', type: 'collocation', term: 'deeply entrenched attitudes', collocationType: 'Adv + Adj + Noun', definition: 'Firmly fixed opinions that resist change.', vietnameseMeaning: 'Những thái độ đã ăn sâu, khó thay đổi.', example: 'Legislation cannot by itself dislodge deeply entrenched attitudes.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'soc_c20', type: 'collocation', term: 'foster a sense of solidarity', collocationType: 'Verb + Noun', definition: 'To encourage mutual support within a group.', vietnameseMeaning: 'Nuôi dưỡng tinh thần đoàn kết.', example: 'National service schemes are defended on the grounds that they foster a sense of solidarity across classes.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'soc_p1', type: 'phrasal_verb', term: 'grow up', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To develop from a child into an adult.', vietnameseMeaning: 'Lớn lên, trưởng thành.', example: 'Children who grow up in overcrowded housing perform worse at school for reasons unrelated to ability.', formalAlternative: 'be raised', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['be raised', 'mature', 'come of age'] },
    { id: 'soc_p2', type: 'phrasal_verb', term: 'fit in', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To be accepted by and feel comfortable within a group.', vietnameseMeaning: 'Hoà nhập với nhóm, được chấp nhận.', example: 'The pressure to fit in explains a great deal of adolescent behaviour.', formalAlternative: 'assimilate', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['assimilate', 'integrate', 'conform'] },
    { id: 'soc_p3', type: 'phrasal_verb', term: 'look after', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To take care of someone or something.', vietnameseMeaning: 'Chăm sóc, trông nom.', example: 'Millions of unpaid carers look after relatives whom the state would otherwise support.', formalAlternative: 'care for', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['care for', 'attend to', 'support'] },
    { id: 'soc_p4', type: 'phrasal_verb', term: 'take part in', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To participate in an activity.', vietnameseMeaning: 'Tham gia vào (hoạt động).', example: 'People who take part in community activities report far lower levels of loneliness.', formalAlternative: 'participate in', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['participate in', 'engage in', 'be involved in'] },
    { id: 'soc_p5', type: 'phrasal_verb', term: 'look down on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To consider someone inferior.', vietnameseMeaning: 'Coi thường, khinh thường.', example: 'Societies that look down on manual work eventually find themselves short of people willing to do it.', formalAlternative: 'disdain', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['disdain', 'regard as inferior', 'denigrate'] },

    // Advanced / less common
    { id: 'soc_p6', type: 'phrasal_verb', term: 'break down', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To fail or collapse, especially of a system or relationship.', vietnameseMeaning: 'Đổ vỡ, sụp đổ (hệ thống, quan hệ).', example: 'When trust between citizens and institutions breaks down, no amount of enforcement compensates.', formalAlternative: 'collapse', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', usageWarning: 'Has several senses, including "analyse in detail" — make the meaning clear from context.', academicAlternatives: ['collapse', 'disintegrate', 'fail'] },
    { id: 'soc_p7', type: 'phrasal_verb', term: 'pass down', partOfSpeech: 'phrasal verb (separable)', definition: 'To give knowledge or customs to a younger generation.', vietnameseMeaning: 'Truyền lại cho thế hệ sau.', example: 'Skills passed down within families disappear within a generation once the industry closes.', formalAlternative: 'transmit', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['pass down traditions', 'passed down through generations'], academicAlternatives: ['transmit', 'hand down', 'bequeath'] },
    { id: 'soc_p8', type: 'phrasal_verb', term: 'shut out', partOfSpeech: 'phrasal verb (separable)', definition: 'To prevent someone from taking part or entering.', vietnameseMeaning: 'Loại trừ, ngăn không cho tham gia.', example: 'Unpaid internships shut out anyone who cannot afford to work for nothing.', formalAlternative: 'exclude', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['exclude', 'bar', 'debar'] },
    { id: 'soc_p9', type: 'phrasal_verb', term: 'give back', partOfSpeech: 'phrasal verb (separable)', definition: 'To do something helpful for a community that has helped you.', vietnameseMeaning: 'Đền đáp, cống hiến lại cho cộng đồng.', example: 'Successful graduates who give back to their old schools raise the ambitions of pupils behind them.', formalAlternative: 'contribute to', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['contribute to', 'reciprocate'] },
    { id: 'soc_p10', type: 'phrasal_verb', term: 'reach out to', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To make an effort to communicate with or help a group.', vietnameseMeaning: 'Chủ động tiếp cận, hướng tới (một nhóm người).', example: 'Services that reach out to isolated residents cost less than the emergencies they prevent.', formalAlternative: 'make contact with', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['engage with', 'make contact with', 'approach'] },
  ],

  writingPhrases: [
    { id: 'soc_w1', type: 'writing_phrase', term: 'A society is fairly judged by how it treats...', function: 'Introducing an argument', vietnameseMeaning: 'Một xã hội được đánh giá công bằng qua cách nó đối xử với...', example: 'A society is fairly judged by how it treats those who can offer it nothing in return.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'soc_w2', type: 'writing_phrase', term: 'Community ties have weakened partly because...', function: 'Giving a reason', vietnameseMeaning: 'Các mối liên kết cộng đồng suy yếu một phần vì...', example: 'Community ties have weakened partly because people now change address far more often than their grandparents did.', topic: 'Society', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'soc_w3', type: 'writing_phrase', term: 'The origins of this inequality lie in...', function: 'Explaining a cause', vietnameseMeaning: 'Nguồn gốc của sự bất bình đẳng này nằm ở...', example: 'The origins of this inequality lie in differences of opportunity established long before school begins.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'soc_w4', type: 'writing_phrase', term: 'The social cost of this exclusion is considerable:', function: 'Explaining an effect', vietnameseMeaning: 'Cái giá xã hội của sự loại trừ này là rất lớn:', example: 'The social cost of this exclusion is considerable: whole neighbourhoods lose the habit of participation.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'soc_w5', type: 'writing_phrase', term: 'Community-run libraries are a good case in point:', function: 'Giving an example', vietnameseMeaning: 'Các thư viện do cộng đồng vận hành là một ví dụ điển hình:', example: 'Community-run libraries are a good case in point: they survive because residents value them, not because they are profitable.', topic: 'Society', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'soc_w6', type: 'writing_phrase', term: 'A more diverse society benefits from...', function: 'Discussing advantages', vietnameseMeaning: 'Một xã hội đa dạng hơn được hưởng lợi từ...', example: 'A more diverse society benefits from a wider range of perspectives when solving unfamiliar problems.', topic: 'Society', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'soc_w7', type: 'writing_phrase', term: 'The difficulty with this argument is that it overlooks...', function: 'Discussing disadvantages', vietnameseMeaning: 'Khó khăn của lập luận này là nó bỏ qua...', example: 'The difficulty with this argument is that it overlooks the households for whom moving is not an option.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'soc_w8', type: 'writing_phrase', term: 'One practical step towards greater inclusion would be to...', function: 'Suggesting a solution', vietnameseMeaning: 'Một bước đi thiết thực hướng tới sự hoà nhập tốt hơn là...', example: 'One practical step towards greater inclusion would be to fund community spaces that are genuinely free to use.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'soc_w9', type: 'writing_phrase', term: 'It seems to me that responsibility here is shared between...', function: 'Expressing an opinion', vietnameseMeaning: 'Với tôi, trách nhiệm ở đây được chia sẻ giữa...', example: 'It seems to me that responsibility here is shared between the state, employers and individuals themselves.', topic: 'Society', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'soc_w10', type: 'writing_phrase', term: 'Older generations valued stability above all; younger people, by contrast, appear to value...', function: 'Comparing ideas', vietnameseMeaning: 'Các thế hệ trước coi trọng sự ổn định trên hết; ngược lại, người trẻ dường như coi trọng...', example: 'Older generations valued stability above all; younger people, by contrast, appear to value flexibility and self-expression.', topic: 'Society', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'soc_m1', type: 'common_mistake', incorrect: 'In the modern society, people are increasingly busy.', correct: 'In modern society, people are increasingly busy.', explanation: '"Society" in this general sense takes no article. Only use "the society" when you mean one specific society already identified.', topic: 'Society', priority: 'must_learn' },
    { id: 'soc_m2', type: 'common_mistake', incorrect: 'There are many peoples living in poverty.', correct: 'There are many people living in poverty.', explanation: '"People" is already plural. "Peoples" only means distinct ethnic or national groups: "the indigenous peoples of the region".', topic: 'Society', priority: 'must_learn' },
    { id: 'soc_m3', type: 'common_mistake', incorrect: 'Elderly people should be respect by the young.', correct: 'Elderly people should be respected by the young.', explanation: 'A passive construction needs the past participle after "be": should be respected, must be treated, can be seen.', topic: 'Society', priority: 'must_learn' },
    { id: 'soc_m4', type: 'common_mistake', incorrect: 'Society is consist of many different groups.', correct: 'Society consists of many different groups.', explanation: '"Consist" is never used in the passive and never with "be". Either "consists of" or "is composed of".', topic: 'Society', priority: 'high_value' },
    { id: 'soc_m5', type: 'common_mistake', incorrect: 'Discriminate against women is still common in some workplaces.', correct: 'Discrimination against women is still common in some workplaces.', explanation: 'A subject must be a noun, not a verb. "Discriminate" is the verb; "discrimination" is the noun you need here.', topic: 'Society', priority: 'must_learn' },
  ],

  learnFirst: {
    vocabulary: ['soc_v10', 'soc_v11', 'soc_v12', 'soc_v13', 'soc_v18', 'soc_v19', 'soc_v21', 'soc_v22', 'soc_v23', 'soc_v25'],
    collocations: ['soc_c1', 'soc_c8', 'soc_c9', 'soc_c13', 'soc_c16'],
    phrasalVerbs: ['soc_p3', 'soc_p4', 'soc_p7'],
    writingPhrases: ['soc_w1', 'soc_w7', 'soc_w9'],
  },
}
