import type { TopicData } from '../types'

export const TECHNOLOGY: TopicData = {
  topic: 'Technology',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'tch_v1', type: 'vocabulary', term: 'innovation', pronunciation: '/ˌɪnəˈveɪʃn/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'A new idea, method or product; the process of creating these.', vietnameseMeaning: 'Sự đổi mới, phát kiến mới.', example: 'Technological innovation has historically created more jobs than it has destroyed.', writingTip: 'Uncountable when it means the process, countable for a specific new invention.', topic: 'Technology', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['technological innovation', 'drive innovation', 'stifle innovation', 'a culture of innovation'], wordFamily: ['innovate (v)', 'innovative (adj)', 'innovator (n)'], priority: 'must_learn' },
    { id: 'tch_v2', type: 'vocabulary', term: 'device', pronunciation: '/dɪˈvaɪs/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A piece of equipment designed for a particular purpose.', vietnameseMeaning: 'Thiết bị, máy móc.', example: 'The average household now owns more connected devices than there are people living in it.', writingTip: 'Useful as a general term when you want to avoid repeating "phone", "tablet" and "laptop".', topic: 'Technology', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['electronic device', 'mobile device', 'a connected device'], alternatives: ['gadget', 'appliance'], priority: 'high_value' },
    { id: 'tch_v3', type: 'vocabulary', term: 'access', pronunciation: '/ˈækses/', partOfSpeech: 'noun (uncountable) / verb', cefrLevel: 'B1', definition: 'The opportunity or right to use or obtain something.', vietnameseMeaning: 'Sự tiếp cận, quyền truy cập.', example: 'Universal access to broadband is now as important to opportunity as access to roads once was.', writingTip: 'The noun takes "to": "access to information". The verb takes no preposition: "access information".', topic: 'Technology', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['access to information', 'gain access to', 'unlimited access', 'restrict access'], wordFamily: ['accessible (adj)', 'accessibility (n)'], priority: 'must_learn' },
    { id: 'tch_v4', type: 'vocabulary', term: 'digital', pronunciation: '/ˈdɪdʒɪtl/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Involving computers and electronic information.', vietnameseMeaning: 'Thuộc về kỹ thuật số.', example: 'Digital records are cheaper to store but far easier to lose in a single failure.', topic: 'Technology', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['digital technology', 'digital skills', 'digital age', 'go digital'], antonym: 'analogue', wordFamily: ['digitise (v)', 'digitally (adv)', 'digitisation (n)'], priority: 'must_learn' },
    { id: 'tch_v5', type: 'vocabulary', term: 'software', pronunciation: '/ˈsɒftweə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'The programs used to operate a computer.', vietnameseMeaning: 'Phần mềm máy tính.', example: 'Educational software is only as good as the teaching that surrounds it.', writingTip: 'Uncountable — never "softwares". Say "a piece of software" or "software packages".', topic: 'Technology', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['software development', 'install software', 'a piece of software'], antonym: 'hardware', priority: 'high_value' },
    { id: 'tch_v6', type: 'vocabulary', term: 'convenient', pronunciation: '/kənˈviːniənt/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Easy to use and saving time or effort.', vietnameseMeaning: 'Tiện lợi, thuận tiện.', example: 'Online banking is undeniably convenient, but it has left older customers behind.', writingTip: 'The noun is "convenience". Avoid "convenient for me to do" — prefer "it is convenient to".', topic: 'Technology', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['highly convenient', 'convenient access', 'for the sake of convenience'], antonym: 'inconvenient', wordFamily: ['convenience (n)', 'conveniently (adv)'], priority: 'high_value' },
    { id: 'tch_v7', type: 'vocabulary', term: 'efficient', pronunciation: '/ɪˈfɪʃnt/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Working well without wasting time, money or energy.', vietnameseMeaning: 'Hiệu quả, không lãng phí nguồn lực.', example: 'Automated sorting has made postal services dramatically more efficient.', writingTip: '"Efficient" means without waste; "effective" means it achieves the goal. They are not interchangeable.', topic: 'Technology', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['highly efficient', 'energy efficient', 'improve efficiency'], antonym: 'inefficient', wordFamily: ['efficiency (n)', 'efficiently (adv)'], priority: 'must_learn' },
    { id: 'tch_v8', type: 'vocabulary', term: 'replace', pronunciation: '/rɪˈpleɪs/', partOfSpeech: 'verb', cefrLevel: 'B1', definition: 'To take the place of something or someone.', vietnameseMeaning: 'Thay thế.', example: 'Machines will replace routine work long before they replace jobs requiring judgement.', writingTip: 'Pattern: "replace A with B". Do not write "replace A by B" in this sense.', topic: 'Technology', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['replace workers', 'replace human labour', 'gradually replace'], alternatives: ['supersede', 'substitute'], wordFamily: ['replacement (n)'], priority: 'must_learn' },
    { id: 'tch_v9', type: 'vocabulary', term: 'privacy', pronunciation: '/ˈprɪvəsi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The state of being free from being observed or having personal information exposed.', vietnameseMeaning: 'Sự riêng tư, quyền riêng tư.', example: 'Users routinely trade away their privacy for services they could not otherwise afford.', writingTip: 'Central to almost every technology essay. Pair with "invade", "protect", "erode".', topic: 'Technology', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['invasion of privacy', 'protect privacy', 'privacy concerns', 'the right to privacy'], wordFamily: ['private (adj)'], priority: 'must_learn' },
    { id: 'tch_v10', type: 'vocabulary', term: 'online', pronunciation: '/ˌɒnˈlaɪn/', partOfSpeech: 'adjective / adverb', cefrLevel: 'B1', definition: 'Connected to or available through the internet.', vietnameseMeaning: 'Trực tuyến, trên mạng.', example: 'Online learning widens access, yet it demands a level of self-discipline many students lack.', writingTip: 'One word, no hyphen. Works as both adjective ("online course") and adverb ("shop online").', topic: 'Technology', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['online learning', 'online shopping', 'online community', 'go online'], antonym: 'offline', priority: 'high_value' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'tch_v11', type: 'vocabulary', term: 'automate', pronunciation: '/ˈɔːtəmeɪt/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To make a process operate by machine rather than by people.', vietnameseMeaning: 'Tự động hoá bằng máy móc.', example: 'Tasks that follow clear rules are the first to be automated in any industry.', writingTip: 'The noun "automation" is often more useful in essays: "the pace of automation".', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['automate a process', 'fully automated', 'increasingly automated'], wordFamily: ['automation (n)', 'automated (adj)'], priority: 'must_learn' },
    { id: 'tch_v12', type: 'vocabulary', term: 'revolutionise', pronunciation: '/ˌrevəˈluːʃənaɪz/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To change something completely and for the better.', vietnameseMeaning: 'Cách mạng hoá, thay đổi hoàn toàn.', example: 'Mobile payments have revolutionised commerce in countries that never had widespread banking.', writingTip: 'Powerful but overused by candidates. Save it for genuinely fundamental change.', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['revolutionise the way', 'revolutionise an industry', 'completely revolutionise'], alternatives: ['transform', 'reshape', 'overhaul'], wordFamily: ['revolution (n)', 'revolutionary (adj)'], priority: 'high_value' },
    { id: 'tch_v13', type: 'vocabulary', term: 'cybersecurity', pronunciation: '/ˌsaɪbəsɪˈkjʊərəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Protection of computer systems and data against attack.', vietnameseMeaning: 'An ninh mạng.', example: 'Cybersecurity has become a matter of national defence rather than merely a technical concern.', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cybersecurity threat', 'invest in cybersecurity', 'cybersecurity measures'], priority: 'high_value' },
    { id: 'tch_v14', type: 'vocabulary', term: 'artificial intelligence', pronunciation: '/ˌɑːtɪfɪʃl ɪnˈtelɪdʒəns/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Computer systems able to perform tasks that normally require human thought.', vietnameseMeaning: 'Trí tuệ nhân tạo.', example: 'Artificial intelligence can process medical images faster than any radiologist, but it cannot reassure a patient.', writingTip: 'Write it in full at first mention, then use "AI". Uncountable, so no article in general statements.', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the rise of artificial intelligence', 'AI-driven', 'develop artificial intelligence'], priority: 'must_learn' },
    { id: 'tch_v15', type: 'vocabulary', term: 'surveillance', pronunciation: '/səˈveɪləns/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Close observation of people, often by cameras or data monitoring.', vietnameseMeaning: 'Sự giám sát, theo dõi.', example: 'Constant surveillance may reduce street crime, but it also changes how freely citizens behave.', writingTip: 'Note the pronunciation — the middle syllable is stressed. Common with "mass", "state", "under".', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['mass surveillance', 'under surveillance', 'surveillance cameras', 'state surveillance'], alternatives: ['monitoring', 'observation'], priority: 'must_learn' },
    { id: 'tch_v16', type: 'vocabulary', term: 'streamline', pronunciation: '/ˈstriːmlaɪn/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To make a process simpler and more efficient.', vietnameseMeaning: 'Tinh gọn, đơn giản hoá quy trình.', example: 'Digital identity systems streamline everything from tax returns to hospital admissions.', writingTip: 'Perfect for arguing that technology reduces bureaucracy — much sharper than "make easier".', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['streamline a process', 'streamline operations', 'streamline procedures'], alternatives: ['simplify', 'rationalise', 'optimise'], priority: 'high_value' },
    { id: 'tch_v17', type: 'vocabulary', term: 'obsolete', pronunciation: '/ˈɒbsəliːt/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'No longer used because something newer has replaced it.', vietnameseMeaning: 'Lỗi thời, không còn được dùng nữa.', example: 'Skills that were valuable a decade ago have already become obsolete in several industries.', writingTip: 'Common patterns: "become obsolete", "render something obsolete".', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['become obsolete', 'render obsolete', 'technologically obsolete'], alternatives: ['outdated', 'outmoded', 'defunct'], wordFamily: ['obsolescence (n)'], priority: 'must_learn' },
    { id: 'tch_v18', type: 'vocabulary', term: 'connectivity', pronunciation: '/ˌkɒnekˈtɪvəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The ability to connect to networks or to other people.', vietnameseMeaning: 'Khả năng kết nối (mạng).', example: 'Poor connectivity in rural areas is now a barrier to employment as much as to entertainment.', topic: 'Technology', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['internet connectivity', 'improve connectivity', 'global connectivity'], wordFamily: ['connect (v)', 'connected (adj)'], priority: 'high_value' },
    { id: 'tch_v19', type: 'vocabulary', term: 'algorithm', pronunciation: '/ˈælɡərɪðəm/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'A set of rules a computer follows to solve a problem or make a decision.', vietnameseMeaning: 'Thuật toán.', example: 'Recommendation algorithms show users more of what they already believe, narrowing debate.', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a recommendation algorithm', 'algorithmic bias', 'design an algorithm'], wordFamily: ['algorithmic (adj)'], priority: 'high_value' },
    { id: 'tch_v20', type: 'vocabulary', term: 'dependence', pronunciation: '/dɪˈpendəns/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The state of needing something in order to function.', vietnameseMeaning: 'Sự phụ thuộc, lệ thuộc.', example: 'Our dependence on digital systems becomes visible only when they fail.', writingTip: 'Always "dependence on". "Reliance on" is a good synonym for variety.', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['dependence on technology', 'growing dependence', 'reduce dependence'], alternatives: ['reliance', 'dependency'], wordFamily: ['depend (v)', 'dependent (adj)'], priority: 'must_learn' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'tch_v21', type: 'vocabulary', term: 'ubiquitous', pronunciation: '/juːˈbɪkwɪtəs/', partOfSpeech: 'adjective', cefrLevel: 'C2', definition: 'Present or found everywhere.', vietnameseMeaning: 'Có mặt khắp nơi, phổ biến rộng khắp.', example: 'Smartphones have become so ubiquitous that their absence, not their presence, now attracts attention.', writingTip: 'A single striking word — use it once in an essay, never twice.', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['become ubiquitous', 'now ubiquitous', 'ubiquitous technology'], alternatives: ['omnipresent', 'pervasive', 'universal'], antonym: 'rare', wordFamily: ['ubiquity (n)'], priority: 'high_value' },
    { id: 'tch_v22', type: 'vocabulary', term: 'disruptive', pronunciation: '/dɪsˈrʌptɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Causing radical change to an existing industry or way of doing things.', vietnameseMeaning: 'Mang tính đột phá, phá vỡ trật tự cũ.', example: 'Ride-hailing apps proved disruptive not because they were sophisticated but because they ignored existing rules.', writingTip: 'In business contexts this is neutral or positive; in social contexts it is negative. Make the sense clear.', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['disruptive technology', 'disruptive innovation', 'prove disruptive'], wordFamily: ['disrupt (v)', 'disruption (n)'], priority: 'high_value' },
    { id: 'tch_v23', type: 'vocabulary', term: 'redundant', pronunciation: '/rɪˈdʌndənt/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'No longer needed, especially of a worker whose job has disappeared.', vietnameseMeaning: 'Dư thừa, bị cho thôi việc do không còn cần thiết.', example: 'Automation has made thousands of clerical workers redundant across the banking sector.', writingTip: 'The fixed phrase is "make somebody redundant". The noun is "redundancy".', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['make workers redundant', 'be made redundant', 'redundancy payments'], alternatives: ['surplus', 'unnecessary'], wordFamily: ['redundancy (n)'], priority: 'high_value' },
    { id: 'tch_v24', type: 'vocabulary', term: 'proliferation', pronunciation: '/prəˌlɪfəˈreɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'A rapid increase in the number of something.', vietnameseMeaning: 'Sự gia tăng nhanh chóng về số lượng.', example: 'The proliferation of connected devices has multiplied the number of ways a home can be attacked.', writingTip: 'Always "the proliferation of". Usually implies the increase is troubling.', topic: 'Technology', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['the proliferation of', 'rapid proliferation', 'unchecked proliferation'], alternatives: ['spread', 'multiplication'], wordFamily: ['proliferate (v)'], priority: 'high_value' },
    { id: 'tch_v25', type: 'vocabulary', term: 'transformative', pronunciation: '/trænsˈfɔːmətɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Causing a major and lasting change.', vietnameseMeaning: 'Có tính chuyển đổi sâu sắc, làm thay đổi căn bản.', example: 'For patients in remote regions, remote diagnosis has been genuinely transformative.', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a transformative effect', 'transformative potential', 'genuinely transformative'], wordFamily: ['transform (v)', 'transformation (n)'], priority: 'high_value' },
    { id: 'tch_v26', type: 'vocabulary', term: 'anonymity', pronunciation: '/ˌænəˈnɪməti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The condition of not being identified by name.', vietnameseMeaning: 'Tính ẩn danh, sự giấu tên.', example: 'The anonymity of online forums encourages both honest confession and outright abuse.', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['online anonymity', 'the cloak of anonymity', 'preserve anonymity'], wordFamily: ['anonymous (adj)', 'anonymously (adv)'], priority: 'high_value' },
    { id: 'tch_v27', type: 'vocabulary', term: 'encroach', pronunciation: '/ɪnˈkrəʊtʃ/', partOfSpeech: 'verb', cefrLevel: 'C2', definition: 'To gradually intrude on someone’s rights, time or space.', vietnameseMeaning: 'Lấn chiếm, xâm phạm dần dần.', example: 'Workplace monitoring software increasingly encroaches on the private lives of employees.', writingTip: 'Always "encroach on/upon". Suggests a slow, unwelcome advance rather than a single violation.', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['encroach on privacy', 'encroach on freedom', 'gradually encroach'], alternatives: ['intrude on', 'infringe'], wordFamily: ['encroachment (n)'], priority: 'high_value' },
    { id: 'tch_v28', type: 'vocabulary', term: 'augment', pronunciation: '/ɔːɡˈment/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To increase or improve something by adding to it.', vietnameseMeaning: 'Bổ sung, tăng cường thêm.', example: 'The most promising systems augment human judgement rather than attempting to replace it.', writingTip: 'Excellent for the nuanced argument that technology should support, not supplant, people.', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['augment human ability', 'augment income', 'augmented reality'], alternatives: ['supplement', 'enhance', 'bolster'], antonym: 'diminish', wordFamily: ['augmentation (n)'], priority: 'high_value' },
    { id: 'tch_v29', type: 'vocabulary', term: 'digital divide', pronunciation: '/ˌdɪdʒɪtl dɪˈvaɪd/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'The gap between those with good access to technology and those without.', vietnameseMeaning: 'Khoảng cách số giữa người có và không có điều kiện tiếp cận công nghệ.', example: 'Moving public services online widens the digital divide unless connectivity is guaranteed first.', writingTip: 'Verbs: bridge, close, widen, deepen. A ready-made Band 7+ noun phrase.', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['bridge the digital divide', 'widen the digital divide'], priority: 'must_learn' },
    { id: 'tch_v30', type: 'vocabulary', term: 'seamless', pronunciation: '/ˈsiːmləs/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Happening smoothly with no obvious joins or interruptions.', vietnameseMeaning: 'Liền mạch, trơn tru không gián đoạn.', example: 'Users now expect a seamless transition between their phone, laptop and television.', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a seamless experience', 'seamless integration', 'seamless transition'], alternatives: ['smooth', 'uninterrupted'], wordFamily: ['seamlessly (adv)'], priority: 'optional' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'tch_c1', type: 'collocation', term: 'social media platforms', collocationType: 'Noun + Noun', definition: 'Websites and apps that let people share content and interact.', vietnameseMeaning: 'Các nền tảng mạng xã hội.', example: 'Social media platforms now shape political opinion more powerfully than newspapers do.', topic: 'Technology', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: '"Social media" takes a singular or plural verb; "social medias" is always wrong.' },
    { id: 'tch_c2', type: 'collocation', term: 'access to information', collocationType: 'Noun + Prep + Noun', definition: 'The ability to obtain knowledge and data.', vietnameseMeaning: 'Khả năng tiếp cận thông tin.', example: 'Free access to information has done more for self-education than any government scheme.', topic: 'Technology', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'tch_c3', type: 'collocation', term: 'technological advances', collocationType: 'Adj + Noun', definition: 'Improvements and new developments in technology.', vietnameseMeaning: 'Những tiến bộ công nghệ.', example: 'Technological advances have shortened the working week far less than early economists predicted.', alternative: 'technological progress', topic: 'Technology', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'tch_c4', type: 'collocation', term: 'online shopping', collocationType: 'Adj + Noun', definition: 'Buying goods over the internet.', vietnameseMeaning: 'Mua sắm trực tuyến.', example: 'The growth of online shopping has emptied high streets in towns across the country.', topic: 'Technology', bandLevel: '5-6', task: 'both', priority: 'high_value' },
    { id: 'tch_c5', type: 'collocation', term: 'improve efficiency', collocationType: 'Verb + Noun', definition: 'To make a process waste less time or fewer resources.', vietnameseMeaning: 'Nâng cao hiệu suất.', example: 'Digital scheduling has improved efficiency in hospitals without any additional staff.', topic: 'Technology', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'tch_c6', type: 'collocation', term: 'browse the internet', collocationType: 'Verb + Noun', definition: 'To look at pages on the web without a fixed purpose.', vietnameseMeaning: 'Lướt web, duyệt internet.', example: 'Teenagers browse the internet for several hours a day on average.', alternative: 'surf the web', topic: 'Technology', bandLevel: '5-6', task: 'task2', priority: 'optional', writingTip: '"The internet" always takes "the" in formal writing.' },
    { id: 'tch_c7', type: 'collocation', term: 'personal information', collocationType: 'Adj + Noun', definition: 'Data that identifies or describes an individual.', vietnameseMeaning: 'Thông tin cá nhân.', example: 'Users hand over personal information without reading a single line of the agreement.', alternative: 'personal data', topic: 'Technology', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'tch_c8', type: 'collocation', term: 'screen time', collocationType: 'Noun + Noun', definition: 'Time spent looking at a phone, computer or television.', vietnameseMeaning: 'Thời gian sử dụng màn hình.', example: 'Excessive screen time in early childhood is associated with delayed language development.', topic: 'Technology', bandLevel: '5-6', task: 'both', priority: 'high_value' },

    // Advanced (Band 6-7)
    { id: 'tch_c9', type: 'collocation', term: 'rapid technological advancement', collocationType: 'Adj + Noun', definition: 'Fast development of new technology.', vietnameseMeaning: 'Sự phát triển công nghệ nhanh chóng.', example: 'Rapid technological advancement has outpaced the laws intended to regulate it.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'tch_c10', type: 'collocation', term: 'a digital footprint', collocationType: 'Adj + Noun', definition: 'The trail of data a person leaves behind online.', vietnameseMeaning: 'Dấu vết số mà người dùng để lại trên mạng.', example: 'Employers routinely examine the digital footprint of applicants before interviewing them.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'tch_c11', type: 'collocation', term: 'protect personal data', collocationType: 'Verb + Noun', definition: 'To keep private information secure from misuse.', vietnameseMeaning: 'Bảo vệ dữ liệu cá nhân.', example: 'Legislation to protect personal data has proved difficult to enforce across borders.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'tch_c12', type: 'collocation', term: 'the rise of artificial intelligence', collocationType: 'Noun + Prep + Noun', definition: 'The growing importance and capability of AI systems.', vietnameseMeaning: 'Sự trỗi dậy của trí tuệ nhân tạo.', example: 'The rise of artificial intelligence has reopened old questions about the value of human work.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'tch_c13', type: 'collocation', term: 'keep pace with technological change', collocationType: 'Verb + Noun', definition: 'To develop as quickly as technology does.', vietnameseMeaning: 'Theo kịp tốc độ thay đổi của công nghệ.', example: 'Training systems must keep pace with technological change or workers will be left stranded.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'tch_c14', type: 'collocation', term: 'automate routine tasks', collocationType: 'Verb + Noun', definition: 'To have machines carry out repetitive work.', vietnameseMeaning: 'Tự động hoá các công việc lặp đi lặp lại.', example: 'Software that automates routine tasks frees professionals for work requiring judgement.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'tch_c15', type: 'collocation', term: 'a data breach', collocationType: 'Noun + Noun', definition: 'An incident in which private information is stolen or exposed.', vietnameseMeaning: 'Vụ rò rỉ, xâm phạm dữ liệu.', example: 'A single data breach can expose the records of millions of customers at once.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'tch_c16', type: 'collocation', term: 'bridge the digital divide', collocationType: 'Verb + Noun', definition: 'To reduce inequality in access to technology.', vietnameseMeaning: 'Thu hẹp khoảng cách số.', example: 'Subsidised broadband is the cheapest way to bridge the digital divide in rural regions.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'tch_c17', type: 'collocation', term: 'encroach on privacy', collocationType: 'Verb + Prep + Noun', definition: 'To gradually reduce someone’s private space or rights.', vietnameseMeaning: 'Xâm phạm quyền riêng tư.', example: 'Facial recognition in public spaces encroaches on privacy in ways citizens never consented to.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'tch_c18', type: 'collocation', term: 'render jobs obsolete', collocationType: 'Verb + Noun + Adj', definition: 'To make particular occupations unnecessary.', vietnameseMeaning: 'Khiến nhiều công việc trở nên lỗi thời.', example: 'Automation will render some jobs obsolete while creating others that do not yet have names.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'tch_c19', type: 'collocation', term: 'the proliferation of misinformation', collocationType: 'Noun + Prep + Noun', definition: 'The rapid spread of false or misleading content.', vietnameseMeaning: 'Sự lan tràn của thông tin sai lệch.', example: 'The proliferation of misinformation online has made verification a basic civic skill.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'tch_c20', type: 'collocation', term: 'harness the potential of technology', collocationType: 'Verb + Noun', definition: 'To make full and controlled use of what technology can offer.', vietnameseMeaning: 'Khai thác tiềm năng của công nghệ.', example: 'Schools that harness the potential of technology use it to individualise teaching, not to replace teachers.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'tch_p1', type: 'phrasal_verb', term: 'log in / log on', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To enter a username and password to access a system.', vietnameseMeaning: 'Đăng nhập vào hệ thống.', example: 'Requiring citizens to log in through a single national identity system raises obvious risks.', formalAlternative: 'sign in', topic: 'Technology', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['sign in', 'authenticate'] },
    { id: 'tch_p2', type: 'phrasal_verb', term: 'back up', partOfSpeech: 'phrasal verb (separable)', definition: 'To make a spare copy of computer data.', vietnameseMeaning: 'Sao lưu dữ liệu.', example: 'Organisations that fail to back up their records regularly rarely survive a serious attack.', formalAlternative: 'create a backup of', topic: 'Technology', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['duplicate', 'archive'] },
    { id: 'tch_p3', type: 'phrasal_verb', term: 'switch off', partOfSpeech: 'phrasal verb (separable)', definition: 'To turn a device off; also, to stop paying attention.', vietnameseMeaning: 'Tắt thiết bị; ngừng tập trung, thư giãn.', example: 'Employees who cannot switch off from work messages report far higher levels of exhaustion.', formalAlternative: 'disconnect', topic: 'Technology', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['disconnect', 'deactivate'] },
    { id: 'tch_p4', type: 'phrasal_verb', term: 'keep up with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To manage to stay level with something that is moving fast.', vietnameseMeaning: 'Theo kịp, bắt kịp.', example: 'Older employees often struggle to keep up with the software their companies adopt.', formalAlternative: 'keep pace with', topic: 'Technology', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', academicAlternatives: ['keep pace with', 'match', 'stay abreast of'] },
    { id: 'tch_p5', type: 'phrasal_verb', term: 'set up', partOfSpeech: 'phrasal verb (separable)', definition: 'To establish or install something so that it is ready to use.', vietnameseMeaning: 'Thiết lập, cài đặt, thành lập.', example: 'Anyone can set up an online business with almost no starting capital.', formalAlternative: 'establish', topic: 'Technology', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['establish', 'install', 'configure'] },

    // Advanced / less common
    { id: 'tch_p6', type: 'phrasal_verb', term: 'roll out', partOfSpeech: 'phrasal verb (separable)', definition: 'To introduce a product or service across a wide area.', vietnameseMeaning: 'Triển khai trên diện rộng.', example: 'The government plans to roll out high-speed broadband to every village by 2030.', formalAlternative: 'implement nationally', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['roll out a scheme', 'roll out nationwide'], academicAlternatives: ['implement', 'introduce', 'deploy'] },
    { id: 'tch_p7', type: 'phrasal_verb', term: 'phase in', partOfSpeech: 'phrasal verb (separable)', definition: 'To introduce something gradually over a planned period.', vietnameseMeaning: 'Đưa vào áp dụng dần theo lộ trình.', example: 'New privacy rules will be phased in over three years to give firms time to adapt.', formalAlternative: 'introduce gradually', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'high_value', academicAlternatives: ['introduce incrementally', 'stage'] },
    { id: 'tch_p8', type: 'phrasal_verb', term: 'shut down', partOfSpeech: 'phrasal verb (separable)', definition: 'To stop a system, service or business from operating.', vietnameseMeaning: 'Đóng cửa, ngừng hoạt động (hệ thống).', example: 'Authoritarian governments increasingly shut down the internet during periods of unrest.', formalAlternative: 'suspend', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['suspend', 'terminate', 'close'] },
    { id: 'tch_p9', type: 'phrasal_verb', term: 'hack into', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To gain unauthorised access to a computer system.', vietnameseMeaning: 'Xâm nhập trái phép vào hệ thống máy tính.', example: 'Criminals who hack into hospital systems now target patient records rather than money.', formalAlternative: 'gain unauthorised access to', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['breach', 'infiltrate', 'compromise'] },
    { id: 'tch_p10', type: 'phrasal_verb', term: 'bring about', partOfSpeech: 'phrasal verb (separable)', definition: 'To cause something to happen.', vietnameseMeaning: 'Mang lại, dẫn tới (sự thay đổi).', example: 'Few inventions have brought about as much social change as the mobile phone.', formalAlternative: 'give rise to', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['bring about change', 'bring about a transformation'], academicAlternatives: ['give rise to', 'generate', 'precipitate'] },
  ],

  writingPhrases: [
    { id: 'tch_w1', type: 'writing_phrase', term: 'The central question is not whether technology is powerful, but whether...', function: 'Introducing an argument', vietnameseMeaning: 'Câu hỏi trọng tâm không phải công nghệ có mạnh hay không, mà là liệu...', example: 'The central question is not whether technology is powerful, but whether we retain any control over how it is used.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'tch_w2', type: 'writing_phrase', term: 'This is largely because digital services are designed to...', function: 'Giving a reason', vietnameseMeaning: 'Điều này chủ yếu là vì các dịch vụ số được thiết kế để...', example: 'This is largely because digital services are designed to maximise the time users spend on them.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'tch_w3', type: 'writing_phrase', term: 'The root of the problem lies in the way data is...', function: 'Explaining a cause', vietnameseMeaning: 'Gốc rễ của vấn đề nằm ở cách dữ liệu được...', example: 'The root of the problem lies in the way data is collected long before anyone considers how it will be used.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'tch_w4', type: 'writing_phrase', term: 'One consequence of this shift is that workers are now expected to...', function: 'Explaining an effect', vietnameseMeaning: 'Một hệ quả của sự thay đổi này là người lao động giờ đây phải...', example: 'One consequence of this shift is that workers are now expected to remain contactable outside working hours.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'tch_w5', type: 'writing_phrase', term: 'The spread of mobile banking in East Africa demonstrates this:', function: 'Giving an example', vietnameseMeaning: 'Sự lan rộng của ngân hàng di động ở Đông Phi cho thấy điều này:', example: 'The spread of mobile banking in East Africa demonstrates this: millions gained financial services without ever entering a bank.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'tch_w6', type: 'writing_phrase', term: 'The greatest advantage of this technology is its capacity to...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi thế lớn nhất của công nghệ này là khả năng...', example: 'The greatest advantage of this technology is its capacity to deliver expert diagnosis where no specialist exists.', topic: 'Technology', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'tch_w7', type: 'writing_phrase', term: 'The most troubling drawback, however, is the loss of...', function: 'Discussing disadvantages', vietnameseMeaning: 'Tuy nhiên, nhược điểm đáng lo ngại nhất là sự mất đi của...', example: 'The most troubling drawback, however, is the loss of any meaningful control over personal information.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'tch_w8', type: 'writing_phrase', term: 'Regulators could respond by requiring companies to...', function: 'Suggesting a solution', vietnameseMeaning: 'Cơ quan quản lý có thể ứng phó bằng cách yêu cầu các công ty...', example: 'Regulators could respond by requiring companies to explain, in plain language, exactly what data they collect.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'tch_w9', type: 'writing_phrase', term: 'To my mind, the benefits of automation outweigh its costs only if...', function: 'Expressing an opinion', vietnameseMeaning: 'Theo tôi, lợi ích của tự động hoá chỉ lớn hơn cái giá phải trả nếu...', example: 'To my mind, the benefits of automation outweigh its costs only if displaced workers are genuinely retrained.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'tch_w10', type: 'writing_phrase', term: 'Earlier inventions displaced physical labour; today’s systems increasingly displace...', function: 'Comparing ideas', vietnameseMeaning: 'Các phát minh trước đây thay thế lao động chân tay; các hệ thống ngày nay ngày càng thay thế...', example: 'Earlier inventions displaced physical labour; today’s systems increasingly displace the work of trained professionals.', topic: 'Technology', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'tch_m1', type: 'common_mistake', incorrect: 'The internet provides many informations.', correct: 'The internet provides a vast amount of information.', explanation: '"Information" is uncountable in English even though Vietnamese treats it as countable. Use "a piece of information" or "a great deal of information".', topic: 'Technology', priority: 'must_learn' },
    { id: 'tch_m2', type: 'common_mistake', incorrect: 'Most students use internet to do research.', correct: 'Most students use the internet to do research.', explanation: '"The internet" always takes the definite article in formal writing, as do "the web" and "the media".', topic: 'Technology', priority: 'must_learn' },
    { id: 'tch_m3', type: 'common_mistake', incorrect: 'Technology have changed our lives completely.', correct: 'Technology has changed our lives completely.', explanation: '"Technology" is uncountable and takes a singular verb. The same applies to "equipment", "research" and "software".', topic: 'Technology', priority: 'must_learn' },
    { id: 'tch_m4', type: 'common_mistake', incorrect: 'Young people are too depend on their phones.', correct: 'Young people are too dependent on their phones.', explanation: 'After "be" you need the adjective "dependent", not the verb "depend". Alternatively: "Young people depend too heavily on their phones."', topic: 'Technology', priority: 'must_learn' },
    { id: 'tch_m5', type: 'common_mistake', incorrect: 'Schools should buy more softwares for students.', correct: 'Schools should buy more software for students.', explanation: '"Software" is uncountable, like "hardware" and "equipment". To count them use "software packages" or "applications".', topic: 'Technology', priority: 'high_value' },
  ],

  learnFirst: {
    vocabulary: ['tch_v1', 'tch_v9', 'tch_v11', 'tch_v14', 'tch_v15', 'tch_v17', 'tch_v20', 'tch_v22', 'tch_v27', 'tch_v29'],
    collocations: ['tch_c3', 'tch_c9', 'tch_c11', 'tch_c16', 'tch_c20'],
    phrasalVerbs: ['tch_p10', 'tch_p4', 'tch_p6'],
    writingPhrases: ['tch_w1', 'tch_w7', 'tch_w9'],
  },
}
