import type { TopicData } from '../types'

export const TRANSPORT: TopicData = {
  topic: 'Transport',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'trn_v1', type: 'vocabulary', term: 'traffic congestion', pronunciation: '/ˈtræfɪk kənˈdʒestʃən/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'A situation in which roads are so full of vehicles that traffic moves very slowly.', vietnameseMeaning: 'Tình trạng tắc nghẽn giao thông.', example: 'Traffic congestion costs the average commuter more than a hundred hours a year.', writingTip: 'Uncountable — never "congestions". "Ease / relieve / reduce congestion" are the natural verbs.', topic: 'Transport', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['ease traffic congestion', 'severe congestion', 'reduce congestion', 'congestion charge'], alternatives: ['traffic jams', 'gridlock'], wordFamily: ['congested (adj)', 'congest (v)'], priority: 'must_learn' },
    { id: 'trn_v2', type: 'vocabulary', term: 'commute', pronunciation: '/kəˈmjuːt/', partOfSpeech: 'verb / noun', cefrLevel: 'B1', definition: 'To travel regularly between home and work; the journey itself.', vietnameseMeaning: 'Đi lại hằng ngày giữa nhà và nơi làm việc.', example: 'Millions of people commute into the capital each morning, placing enormous strain on the rail network.', writingTip: 'As a noun it is countable: "a long commute", "daily commutes". "Commuter" is the person.', topic: 'Transport', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['daily commute', 'commute to work', 'long commute', 'commute by train'], wordFamily: ['commuter (n)', 'commuting (n)'], priority: 'must_learn' },
    { id: 'trn_v3', type: 'vocabulary', term: 'public transport', pronunciation: '/ˌpʌblɪk ˈtrænspɔːt/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'Buses, trains and other shared vehicles available to everyone for a fare.', vietnameseMeaning: 'Giao thông công cộng.', example: 'Affordable public transport is the single most effective way of reducing private car use.', writingTip: 'British English uses "public transport"; American English "public transportation". Both accepted, but stay consistent.', topic: 'Transport', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['use public transport', 'invest in public transport', 'reliable public transport', 'public transport network'], antonym: 'private vehicles', priority: 'must_learn' },
    { id: 'trn_v4', type: 'vocabulary', term: 'pedestrian', pronunciation: '/pəˈdestriən/', partOfSpeech: 'noun / adjective', cefrLevel: 'B1', definition: 'A person walking rather than travelling in a vehicle.', vietnameseMeaning: 'Người đi bộ.', example: 'Widening pavements and narrowing roads makes city centres far safer for pedestrians.', writingTip: 'As an adjective it means "for walking": pedestrian zone, pedestrian crossing, pedestrian-friendly.', topic: 'Transport', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['pedestrian crossing', 'pedestrian zone', 'pedestrian safety', 'pedestrian-friendly streets'], wordFamily: ['pedestrianise (v)', 'pedestrianised (adj)'], priority: 'must_learn' },
    { id: 'trn_v5', type: 'vocabulary', term: 'fuel', pronunciation: '/ˈfjuːəl/', partOfSpeech: 'noun (uncountable) / verb', cefrLevel: 'B1', definition: 'A substance such as petrol or diesel burned to produce power.', vietnameseMeaning: 'Nhiên liệu.', example: 'Rising fuel prices have persuaded many households to switch to public transport.', writingTip: 'Uncountable as a substance. As a verb it also means "to make something increase": "fuel demand".', topic: 'Transport', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['fuel consumption', 'fuel efficiency', 'fuel prices', 'fossil fuel'], wordFamily: ['refuel (v)', 'fuel-efficient (adj)'], priority: 'high_value' },
    { id: 'trn_v6', type: 'vocabulary', term: 'vehicle', pronunciation: '/ˈviːəkl/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'A machine such as a car, bus or lorry used for transporting people or goods.', vietnameseMeaning: 'Phương tiện giao thông, xe cộ.', example: 'The number of privately owned vehicles in the city has doubled within a decade.', writingTip: 'More formal and more general than "car" — useful when your point covers cars, buses and lorries alike.', topic: 'Transport', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['private vehicles', 'motor vehicles', 'electric vehicles', 'vehicle ownership'], alternatives: ['automobile'], priority: 'must_learn' },
    { id: 'trn_v7', type: 'vocabulary', term: 'accessible', pronunciation: '/əkˈsesəbl/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Easy to reach, enter or use, including by people with disabilities.', vietnameseMeaning: 'Dễ tiếp cận, thuận tiện cho việc sử dụng.', example: 'Rural communities complain that hospitals are simply not accessible without a car.', writingTip: 'Follow with "to" for people ("accessible to the elderly") and use "make X accessible" for solutions.', topic: 'Transport', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['easily accessible', 'accessible to everyone', 'make transport accessible', 'wheelchair accessible'], antonym: 'inaccessible', wordFamily: ['access (n, v)', 'accessibility (n)'], priority: 'must_learn' },
    { id: 'trn_v8', type: 'vocabulary', term: 'fare', pronunciation: '/feə/', partOfSpeech: 'noun (countable)', cefrLevel: 'B1', definition: 'The money a passenger pays to travel on public transport.', vietnameseMeaning: 'Tiền vé, giá vé đi lại.', example: 'Cutting bus fares for students would encourage far more young people to leave their cars at home.', writingTip: 'Do not confuse with "fee" (paid for a service or membership) or "fair" (just, reasonable).', topic: 'Transport', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['train fares', 'raise fares', 'reduce fares', 'flat fare'], priority: 'high_value' },
    { id: 'trn_v9', type: 'vocabulary', term: 'convenient', pronunciation: '/kənˈviːniənt/', partOfSpeech: 'adjective', cefrLevel: 'B1', definition: 'Useful, easy or quick to do; suiting your needs.', vietnameseMeaning: 'Tiện lợi, thuận tiện.', example: 'Private cars remain more convenient than buses for journeys that involve carrying children or shopping.', writingTip: 'A Band 5-6 word — perfectly correct, but pair it with a precise reason so the sentence still earns marks.', topic: 'Transport', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', collocations: ['far more convenient', 'convenient alternative', 'convenient access'], antonym: 'inconvenient', wordFamily: ['convenience (n)', 'conveniently (adv)'], priority: 'high_value' },
    { id: 'trn_v10', type: 'vocabulary', term: 'rush hour', pronunciation: '/ˈrʌʃ aʊə/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'The period each morning and evening when traffic is heaviest.', vietnameseMeaning: 'Giờ cao điểm.', example: 'During the evening rush hour, average speeds on the ring road fall below fifteen kilometres per hour.', writingTip: 'Usually singular with "the". "Peak hours" is the more formal alternative in academic writing.', topic: 'Transport', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', collocations: ['during rush hour', 'morning rush hour', 'rush-hour traffic'], alternatives: ['peak hours', 'peak time'], priority: 'high_value' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'trn_v11', type: 'vocabulary', term: 'infrastructure', pronunciation: '/ˈɪnfrəstrʌktʃə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The basic physical systems a country needs to function, such as roads, railways and bridges.', vietnameseMeaning: 'Cơ sở hạ tầng.', example: 'Decades of underinvestment have left the country with transport infrastructure unfit for its population.', writingTip: 'Uncountable: "infrastructure is", never "infrastructures are". A high-frequency word in both tasks.', topic: 'Transport', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['transport infrastructure', 'invest in infrastructure', 'ageing infrastructure', 'infrastructure projects'], priority: 'must_learn' },
    { id: 'trn_v12', type: 'vocabulary', term: 'emissions', pronunciation: '/ɪˈmɪʃnz/', partOfSpeech: 'noun (plural)', cefrLevel: 'B2', definition: 'Gases or other substances released into the air, especially by vehicles and factories.', vietnameseMeaning: 'Khí thải, lượng phát thải.', example: 'Road transport is responsible for roughly a fifth of national carbon emissions.', writingTip: 'Normally plural in this sense. "Emission" singular refers to the act of releasing.', topic: 'Transport', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['carbon emissions', 'vehicle emissions', 'cut emissions', 'emission standards'], wordFamily: ['emit (v)', 'emitter (n)'], priority: 'must_learn' },
    { id: 'trn_v13', type: 'vocabulary', term: 'subsidise', pronunciation: '/ˈsʌbsɪdaɪz/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To pay part of the cost of something so that it is cheaper for the public.', vietnameseMeaning: 'Trợ giá, tài trợ một phần chi phí.', example: 'Governments that heavily subsidise rail travel consistently record lower levels of car dependency.', writingTip: 'American spelling is "subsidize". The noun "subsidy" is countable: "fuel subsidies".', topic: 'Transport', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['subsidise public transport', 'heavily subsidised', 'subsidise fares'], wordFamily: ['subsidy (n)', 'subsidised (adj)'], priority: 'must_learn' },
    { id: 'trn_v14', type: 'vocabulary', term: 'transit', pronunciation: '/ˈtrænzɪt/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The system of transporting people or goods from one place to another.', vietnameseMeaning: 'Hệ thống vận chuyển, quá cảnh.', example: 'Cities that built mass transit systems early have been far better placed to absorb population growth.', writingTip: '"Mass transit" and "transit system" are the natural collocations. "In transit" means "being transported".', topic: 'Transport', bandLevel: '6-7', task: 'both', writingSuitability: 'suitable', collocations: ['mass transit', 'transit system', 'rapid transit', 'in transit'], priority: 'high_value' },
    { id: 'trn_v15', type: 'vocabulary', term: 'freight', pronunciation: '/freɪt/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'Goods transported in bulk by lorry, train, ship or aircraft.', vietnameseMeaning: 'Hàng hoá vận chuyển, vận tải hàng hoá.', example: 'Shifting freight from roads to railways would substantially reduce both congestion and emissions.', writingTip: 'Uncountable. "Freight transport" and "rail freight" are standard; avoid "freights".', topic: 'Transport', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['rail freight', 'freight transport', 'move freight', 'freight costs'], alternatives: ['cargo', 'goods'], priority: 'high_value' },
    { id: 'trn_v16', type: 'vocabulary', term: 'fatality', pronunciation: '/fəˈtæləti/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A death caused by an accident, disaster or violence.', vietnameseMeaning: 'Ca tử vong (do tai nạn).', example: 'Lowering urban speed limits to thirty kilometres per hour has cut pedestrian fatalities dramatically.', writingTip: 'More formal than "deaths" and standard in road-safety writing. "Road fatalities" is the key phrase.', topic: 'Transport', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['road fatalities', 'reduce fatalities', 'fatality rate', 'traffic fatalities'], wordFamily: ['fatal (adj)', 'fatally (adv)'], priority: 'high_value' },
    { id: 'trn_v17', type: 'vocabulary', term: 'carpool', pronunciation: '/ˈkɑːpuːl/', partOfSpeech: 'verb / noun', cefrLevel: 'B2', definition: 'To share a car journey with others who are travelling the same way.', vietnameseMeaning: 'Đi chung xe, chia sẻ chuyến xe.', example: 'Employers can encourage staff to carpool by reserving the best parking spaces for shared vehicles.', writingTip: 'Also written "car-share" in British English. A concrete, credible solution to propose in Task 2.', topic: 'Transport', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['carpool scheme', 'encourage carpooling', 'carpool lane'], alternatives: ['car-share', 'ride-share'], wordFamily: ['carpooling (n)'], priority: 'high_value' },
    { id: 'trn_v18', type: 'vocabulary', term: 'ridership', pronunciation: '/ˈraɪdəʃɪp/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The number of people who use a public transport service.', vietnameseMeaning: 'Lượng hành khách sử dụng phương tiện công cộng.', example: 'Ridership on the metro recovered slowly after the pandemic, remaining below pre-2020 levels.', writingTip: 'Very useful in Task 1 when a chart shows passenger numbers over time. "Ridership rose/fell by".', topic: 'Transport', bandLevel: '6-7', task: 'task1', writingSuitability: 'highly_suitable', collocations: ['increase ridership', 'declining ridership', 'ridership levels', 'boost ridership'], alternatives: ['passenger numbers'], priority: 'high_value' },
    { id: 'trn_v19', type: 'vocabulary', term: 'bottleneck', pronunciation: '/ˈbɒtlnek/', partOfSpeech: 'noun (countable)', cefrLevel: 'B2', definition: 'A narrow point where traffic or progress slows down and builds up.', vietnameseMeaning: 'Điểm nghẽn, nút thắt cổ chai.', example: 'A single bridge acts as a bottleneck for all traffic entering the old quarter.', writingTip: 'Works literally for roads and figuratively for any process that slows things down. Useful for variety.', topic: 'Transport', bandLevel: '6-7', task: 'both', writingSuitability: 'suitable', collocations: ['a major bottleneck', 'create a bottleneck', 'ease the bottleneck'], priority: 'optional' },
    { id: 'trn_v20', type: 'vocabulary', term: 'sustainable', pronunciation: '/səˈsteɪnəbl/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Able to continue over a long period without damaging the environment.', vietnameseMeaning: 'Bền vững, có thể duy trì lâu dài.', example: 'Cycling and walking are the only genuinely sustainable modes of transport for short urban journeys.', writingTip: 'Extremely high frequency. "Sustainable transport / mobility / development" are all natural.', topic: 'Transport', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['sustainable transport', 'sustainable mobility', 'environmentally sustainable'], antonym: 'unsustainable', wordFamily: ['sustain (v)', 'sustainability (n)'], priority: 'must_learn' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'trn_v21', type: 'vocabulary', term: 'gridlock', pronunciation: '/ˈɡrɪdlɒk/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'A situation in which traffic cannot move at all because every road is blocked.', vietnameseMeaning: 'Tình trạng kẹt xe hoàn toàn, tê liệt giao thông.', example: 'Without urgent investment in alternatives, the city centre faces permanent gridlock within a decade.', writingTip: 'Stronger than "congestion" — reserve it for complete standstill, or your meaning is overstated.', topic: 'Transport', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['total gridlock', 'urban gridlock', 'bring the city to gridlock'], alternatives: ['standstill'], wordFamily: ['gridlocked (adj)'], priority: 'high_value' },
    { id: 'trn_v22', type: 'vocabulary', term: 'car dependency', pronunciation: '/kɑː dɪˈpendənsi/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'A situation in which people have no realistic alternative to driving.', vietnameseMeaning: 'Sự phụ thuộc vào xe hơi cá nhân.', example: 'Suburban planning that separates housing from shops and schools entrenches car dependency for generations.', writingTip: 'A precise, sophisticated way to name the underlying problem rather than just describing traffic.', topic: 'Transport', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['reduce car dependency', 'entrench car dependency', 'high levels of car dependency'], wordFamily: ['car-dependent (adj)'], priority: 'must_learn' },
    { id: 'trn_v23', type: 'vocabulary', term: 'modal shift', pronunciation: '/ˈməʊdl ʃɪft/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'A change in the type of transport people choose, for example from cars to trains.', vietnameseMeaning: 'Sự chuyển dịch phương thức đi lại.', example: 'Congestion charging in London produced a measurable modal shift towards buses and cycling.', writingTip: 'A genuine technical term from transport policy. Using it correctly signals real topic knowledge.', topic: 'Transport', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['achieve a modal shift', 'encourage a modal shift', 'a modal shift towards'], priority: 'high_value' },
    { id: 'trn_v24', type: 'vocabulary', term: 'autonomous vehicle', pronunciation: '/ɔːˈtɒnəməs ˈviːəkl/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'A vehicle capable of driving itself without a human driver.', vietnameseMeaning: 'Xe tự hành, xe tự lái.', example: 'Autonomous vehicles may reduce accidents caused by human error, but they raise difficult questions about liability.', writingTip: 'More formal than "self-driving car" and better suited to academic writing.', topic: 'Transport', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['fully autonomous vehicles', 'autonomous driving', 'deploy autonomous vehicles'], alternatives: ['self-driving car', 'driverless car'], wordFamily: ['autonomy (n)', 'autonomously (adv)'], priority: 'high_value' },
    { id: 'trn_v25', type: 'vocabulary', term: 'decongest', pronunciation: '/ˌdiːkənˈdʒest/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To relieve overcrowding on roads or in an area.', vietnameseMeaning: 'Giảm tải, làm giảm ùn tắc.', example: 'Relocating the wholesale market to the outskirts did a great deal to decongest the historic centre.', writingTip: 'A precise single verb where weaker candidates write "make less crowded". Use sparingly.', topic: 'Transport', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['decongest the city centre', 'decongest major routes'], wordFamily: ['decongestion (n)'], priority: 'optional' },
    { id: 'trn_v26', type: 'vocabulary', term: 'connectivity', pronunciation: '/ˌkɒnekˈtɪvəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The degree to which places are linked by transport or communication networks.', vietnameseMeaning: 'Mức độ kết nối giữa các khu vực.', example: 'Improved rail connectivity has allowed smaller towns to share in the prosperity of nearby cities.', writingTip: 'Excellent for arguing that transport drives economic opportunity, not merely convenience.', topic: 'Transport', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['improve connectivity', 'poor connectivity', 'transport connectivity', 'regional connectivity'], wordFamily: ['connect (v)', 'connected (adj)'], priority: 'high_value' },
    { id: 'trn_v27', type: 'vocabulary', term: 'viable', pronunciation: '/ˈvaɪəbl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Capable of working successfully in practice.', vietnameseMeaning: 'Khả thi, có thể thực hiện được.', example: 'Cycling only becomes a viable alternative once separated lanes make it feel safe.', writingTip: '"A viable alternative / option / solution" is a hallmark Band 7+ phrase in solution paragraphs.', topic: 'Transport', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a viable alternative', 'economically viable', 'commercially viable', 'viable option'], antonym: 'unviable', wordFamily: ['viability (n)'], priority: 'must_learn' },
    { id: 'trn_v28', type: 'vocabulary', term: 'deter', pronunciation: '/dɪˈtɜː/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To discourage someone from doing something by making it difficult or unattractive.', vietnameseMeaning: 'Ngăn cản, làm nản lòng.', example: 'High parking charges deter motorists far more effectively than public awareness campaigns.', writingTip: 'Follow with "from + -ing": "deter people from driving". Never "deter people to drive".', topic: 'Transport', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['deter drivers', 'deter people from driving', 'act as a deterrent'], antonym: 'encourage', wordFamily: ['deterrent (n)', 'deterrence (n)'], priority: 'high_value' },
    { id: 'trn_v29', type: 'vocabulary', term: 'thoroughfare', pronunciation: '/ˈθʌrəfeə/', partOfSpeech: 'noun (countable)', cefrLevel: 'C1', definition: 'A main road that traffic passes along through a town.', vietnameseMeaning: 'Trục đường chính, đường lớn xuyên qua thành phố.', example: 'Closing the main thoroughfare to private cars on Sundays has proved unexpectedly popular.', writingTip: 'A precise noun for a main road. Useful for lexical variety, but "main road" is never wrong.', topic: 'Transport', bandLevel: '7+', task: 'both', writingSuitability: 'suitable', collocations: ['a busy thoroughfare', 'main thoroughfare', 'public thoroughfare'], alternatives: ['main road', 'arterial road'], priority: 'optional' },
    { id: 'trn_v30', type: 'vocabulary', term: 'incentivise', pronunciation: '/ɪnˈsentɪvaɪz/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To motivate people to act by offering them a reward or advantage.', vietnameseMeaning: 'Tạo động lực, khuyến khích bằng lợi ích.', example: 'Rather than banning older vehicles outright, governments could incentivise their replacement through scrappage schemes.', writingTip: 'Stronger than "encourage" because it implies a concrete reward. Excellent in solution paragraphs.', topic: 'Transport', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['incentivise cycling', 'financially incentivise', 'incentivise a switch to'], alternatives: ['encourage', 'reward'], wordFamily: ['incentive (n)'], priority: 'must_learn' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'trn_c1', type: 'collocation', term: 'ease traffic congestion', collocationType: 'Verb + Noun', definition: 'To make traffic flow more freely and reduce delays.', vietnameseMeaning: 'Giảm bớt tình trạng tắc nghẽn giao thông.', example: 'A network of dedicated bus lanes would do more to ease traffic congestion than building additional roads.', alternative: 'relieve congestion', topic: 'Transport', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'Use "ease" or "relieve" rather than "solve" — congestion is managed, not eliminated.' },
    { id: 'trn_c2', type: 'collocation', term: 'public transport system', collocationType: 'Adj + Noun', definition: 'The organised network of buses, trains and trams serving an area.', vietnameseMeaning: 'Hệ thống giao thông công cộng.', example: 'Tokyo demonstrates that a punctual, affordable public transport system can make car ownership almost unnecessary.', topic: 'Transport', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'trn_c3', type: 'collocation', term: 'road accident', collocationType: 'Noun + Noun', definition: 'A crash involving vehicles on a road.', vietnameseMeaning: 'Tai nạn giao thông đường bộ.', example: 'Road accidents remain the leading cause of death among Vietnamese men under thirty.', alternative: 'traffic accident', topic: 'Transport', bandLevel: '5-6', task: 'both', priority: 'must_learn' },
    { id: 'trn_c4', type: 'collocation', term: 'get stuck in traffic', collocationType: 'Verb + Prep + Noun', definition: 'To be unable to move because of heavy traffic.', vietnameseMeaning: 'Bị kẹt xe, mắc kẹt trong dòng xe cộ.', example: 'Commuters who get stuck in traffic for two hours a day lose the equivalent of a month each year.', topic: 'Transport', bandLevel: '5-6', task: 'task2', priority: 'high_value', writingTip: 'Slightly conversational but widely accepted. "Be delayed by congestion" is the formal version.' },
    { id: 'trn_c5', type: 'collocation', term: 'traffic volume', collocationType: 'Noun + Noun', definition: 'The number of vehicles using a road over a given period.', vietnameseMeaning: 'Lưu lượng giao thông.', example: 'Traffic volume on the motorway rose steadily throughout the period shown.', topic: 'Transport', bandLevel: '5-6', task: 'task1', priority: 'must_learn', writingTip: 'Very useful in Task 1 line graphs about roads. Pair with rise/fall verbs and adverbs.' },
    { id: 'trn_c6', type: 'collocation', term: 'speed limit', collocationType: 'Noun + Noun', definition: 'The maximum legal speed allowed on a particular road.', vietnameseMeaning: 'Giới hạn tốc độ.', example: 'Enforcing existing speed limits is cheaper and quicker than redesigning junctions.', topic: 'Transport', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'trn_c7', type: 'collocation', term: 'reduce car use', collocationType: 'Verb + Noun', definition: 'To lower the number of journeys made by private car.', vietnameseMeaning: 'Giảm việc sử dụng xe cá nhân.', example: 'Any serious plan to improve urban air quality must reduce car use rather than simply making cars cleaner.', topic: 'Transport', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'trn_c8', type: 'collocation', term: 'improve road safety', collocationType: 'Verb + Noun', definition: 'To make roads less dangerous for all users.', vietnameseMeaning: 'Cải thiện an toàn giao thông.', example: 'Compulsory helmet laws have improved road safety considerably in countries where motorcycles dominate.', topic: 'Transport', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },

    // Advanced (Band 6-7)
    { id: 'trn_c9', type: 'collocation', term: 'invest in transport infrastructure', collocationType: 'Verb + Noun', definition: 'To spend substantial public money on roads, railways and transport networks.', vietnameseMeaning: 'Đầu tư vào hạ tầng giao thông.', example: 'Countries that invest in transport infrastructure early tend to attract manufacturing investment later.', topic: 'Transport', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'trn_c10', type: 'collocation', term: 'cut carbon emissions', collocationType: 'Verb + Noun', definition: 'To reduce the amount of carbon dioxide released.', vietnameseMeaning: 'Cắt giảm lượng khí thải carbon.', example: 'Electrifying the bus fleet would cut carbon emissions across the metropolitan area by an estimated eight per cent.', alternative: 'reduce carbon emissions', topic: 'Transport', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'trn_c11', type: 'collocation', term: 'congestion charge', collocationType: 'Noun + Noun', definition: 'A fee drivers must pay to enter a busy city area.', vietnameseMeaning: 'Phí chống ùn tắc khi vào trung tâm thành phố.', example: 'Stockholm introduced a congestion charge on a trial basis, and public support grew once the benefits became visible.', topic: 'Transport', bandLevel: '6-7', task: 'task2', priority: 'high_value', writingTip: 'A concrete, real-world policy example — far more persuasive than saying "the government should do something".' },
    { id: 'trn_c12', type: 'collocation', term: 'ease the burden on the road network', collocationType: 'Verb + Noun', definition: 'To reduce the pressure placed on roads by heavy use.', vietnameseMeaning: 'Giảm gánh nặng cho mạng lưới đường bộ.', example: 'Moving heavy goods onto rail would ease the burden on the road network and extend the life of motorways.', topic: 'Transport', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'trn_c13', type: 'collocation', term: 'dedicated cycle lane', collocationType: 'Adj + Noun', definition: 'A part of the road reserved exclusively for bicycles.', vietnameseMeaning: 'Làn đường dành riêng cho xe đạp.', example: 'Cities only see mass cycling once dedicated cycle lanes are physically separated from motor traffic.', alternative: 'segregated cycle lane', topic: 'Transport', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'trn_c14', type: 'collocation', term: 'peak-hour demand', collocationType: 'Adj + Noun', definition: 'The level of travel required during the busiest parts of the day.', vietnameseMeaning: 'Nhu cầu đi lại vào giờ cao điểm.', example: 'Staggered working hours would spread peak-hour demand across a longer window.', topic: 'Transport', bandLevel: '6-7', task: 'both', priority: 'high_value' },
    { id: 'trn_c15', type: 'collocation', term: 'account for a large proportion of journeys', collocationType: 'Verb + Noun', definition: 'To make up a substantial share of all trips made.', vietnameseMeaning: 'Chiếm một tỷ lệ lớn trong tổng số chuyến đi.', example: 'Trips of under three kilometres account for a large proportion of journeys made by car.', topic: 'Transport', bandLevel: '6-7', task: 'task1', priority: 'must_learn', writingTip: 'A model Task 1 pattern for pie charts on transport modes.' },

    // High-impact (Band 7+)
    { id: 'trn_c16', type: 'collocation', term: 'alleviate chronic congestion', collocationType: 'Verb + Adj + Noun', definition: 'To reduce traffic problems that have persisted for a long time.', vietnameseMeaning: 'Giảm nhẹ tình trạng ùn tắc kéo dài.', example: 'No single measure will alleviate chronic congestion; only a combination of pricing, investment and planning can.', topic: 'Transport', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'trn_c17', type: 'collocation', term: 'a viable alternative to private cars', collocationType: 'Adj + Noun', definition: 'A realistic option that people would genuinely choose instead of driving.', vietnameseMeaning: 'Một lựa chọn khả thi thay thế cho xe cá nhân.', example: 'Until buses run every few minutes, they will not be a viable alternative to private cars for most families.', topic: 'Transport', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'trn_c18', type: 'collocation', term: 'place enormous strain on', collocationType: 'Verb + Noun', definition: 'To create severe pressure on a system or resource.', vietnameseMeaning: 'Gây áp lực rất lớn lên (hệ thống, nguồn lực).', example: 'Rapid population growth has placed enormous strain on a rail network designed half a century ago.', topic: 'Transport', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'trn_c19', type: 'collocation', term: 'discourage private car ownership', collocationType: 'Verb + Noun', definition: 'To make owning a car less attractive through policy.', vietnameseMeaning: 'Hạn chế việc sở hữu xe hơi cá nhân.', example: 'Singapore discourages private car ownership through a quota system that makes licences extremely expensive.', topic: 'Transport', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'trn_c20', type: 'collocation', term: 'an integrated transport network', collocationType: 'Adj + Noun', definition: 'A system in which different modes of transport connect smoothly with one another.', vietnameseMeaning: 'Mạng lưới giao thông liên thông, tích hợp.', example: 'An integrated transport network in which one ticket covers bus, metro and rail removes much of the friction of not driving.', topic: 'Transport', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'trn_p1', type: 'phrasal_verb', term: 'get around', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To travel from place to place within an area.', vietnameseMeaning: 'Đi lại, di chuyển trong một khu vực.', example: 'Elderly residents find it increasingly difficult to get around once local bus routes are withdrawn.', formalAlternative: 'travel', topic: 'Transport', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['get around the city', 'get around easily'], academicAlternatives: ['travel', 'move about', 'navigate'] },
    { id: 'trn_p2', type: 'phrasal_verb', term: 'set off', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To begin a journey.', vietnameseMeaning: 'Khởi hành, bắt đầu chuyến đi.', example: 'Many commuters now set off an hour earlier simply to avoid the worst of the congestion.', formalAlternative: 'depart', topic: 'Transport', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['depart', 'begin a journey'] },
    { id: 'trn_p3', type: 'phrasal_verb', term: 'pick up', partOfSpeech: 'phrasal verb (separable)', definition: 'To collect someone in a vehicle.', vietnameseMeaning: 'Đón (ai đó bằng xe).', example: 'The school run, in which parents drive to pick up their children, is a major source of morning congestion.', formalAlternative: 'collect', topic: 'Transport', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', collocations: ['pick up passengers', 'pick up children'], academicAlternatives: ['collect', 'transport'] },
    { id: 'trn_p4', type: 'phrasal_verb', term: 'hold up', partOfSpeech: 'phrasal verb (separable)', definition: 'To delay someone or something.', vietnameseMeaning: 'Làm chậm trễ, gây trì hoãn.', example: 'Roadworks on the main bridge held up traffic for several hours each morning.', formalAlternative: 'delay', topic: 'Transport', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', usageWarning: 'Also means "to rob" — context makes the meaning clear, but "delay" avoids all ambiguity.', academicAlternatives: ['delay', 'obstruct', 'impede'] },
    { id: 'trn_p5', type: 'phrasal_verb', term: 'run out of', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To use up the whole supply of something.', vietnameseMeaning: 'Hết, cạn kiệt (nhiên liệu, nguồn lực).', example: 'Drivers of electric cars still worry about running out of charge on long journeys.', formalAlternative: 'exhaust supplies of', topic: 'Transport', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['exhaust', 'deplete'] },

    // Advanced / less common
    { id: 'trn_p6', type: 'phrasal_verb', term: 'phase in', partOfSpeech: 'phrasal verb (separable)', definition: 'To introduce something gradually over a planned period.', vietnameseMeaning: 'Áp dụng dần dần theo lộ trình.', example: 'A low-emission zone should be phased in over several years so that households can plan for it.', formalAlternative: 'introduce gradually', topic: 'Transport', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['phase in restrictions', 'be phased in gradually'], academicAlternatives: ['introduce incrementally', 'implement in stages'] },
    { id: 'trn_p7', type: 'phrasal_verb', term: 'switch to', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To change from using one thing to using another.', vietnameseMeaning: 'Chuyển sang sử dụng (phương tiện khác).', example: 'Commuters will only switch to public transport when it becomes faster than driving, not merely cheaper.', formalAlternative: 'change to', topic: 'Transport', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['switch to rail', 'switch to electric vehicles'], academicAlternatives: ['transition to', 'adopt', 'convert to'] },
    { id: 'trn_p8', type: 'phrasal_verb', term: 'build up', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To increase gradually until it becomes heavy or intense.', vietnameseMeaning: 'Dồn ứ, tích tụ dần (dòng xe).', example: 'Traffic builds up quickly at the tunnel entrance whenever a single lane is closed.', formalAlternative: 'accumulate', topic: 'Transport', bandLevel: '6-7', task: 'both', writingSuitability: 'suitable', priority: 'high_value', collocations: ['traffic builds up', 'pressure builds up'], academicAlternatives: ['accumulate', 'intensify'] },
    { id: 'trn_p9', type: 'phrasal_verb', term: 'cater for', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To provide what a particular group of people needs.', vietnameseMeaning: 'Đáp ứng nhu cầu của (một nhóm đối tượng).', example: 'Transport planning has historically catered for motorists while treating cyclists as an afterthought.', formalAlternative: 'accommodate', topic: 'Transport', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', priority: 'high_value', collocations: ['cater for the needs of', 'cater for commuters'], academicAlternatives: ['accommodate', 'serve', 'provide for'] },
    { id: 'trn_p10', type: 'phrasal_verb', term: 'do away with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To get rid of something completely.', vietnameseMeaning: 'Xoá bỏ, loại bỏ hoàn toàn.', example: 'Some campaigners argue that city centres should do away with private cars altogether.', formalAlternative: 'abolish', topic: 'Transport', bandLevel: '6-7', task: 'task2', writingSuitability: 'use_with_caution', priority: 'optional', usageWarning: 'Informal. In an essay, "abolish", "eliminate" or "ban" reads considerably better.', academicAlternatives: ['abolish', 'eliminate', 'remove'] },
  ],

  writingPhrases: [
    { id: 'trn_w1', type: 'writing_phrase', term: 'The strongest case for prioritising public transport rests on...', function: 'Introducing an argument', vietnameseMeaning: 'Lập luận mạnh nhất ủng hộ việc ưu tiên giao thông công cộng dựa trên...', example: 'The strongest case for prioritising public transport rests on the simple fact that roads cannot be widened indefinitely.', topic: 'Transport', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'trn_w2', type: 'writing_phrase', term: 'The root of the congestion problem lies in...', function: 'Giving a reason', vietnameseMeaning: 'Gốc rễ của vấn đề ùn tắc nằm ở...', example: 'The root of the congestion problem lies in decades of planning that placed homes and workplaces far apart.', topic: 'Transport', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'trn_w3', type: 'writing_phrase', term: 'This surge in vehicle numbers can be attributed to...', function: 'Explaining a cause', vietnameseMeaning: 'Sự gia tăng đột biến về số lượng xe có thể được lý giải bởi...', example: 'This surge in vehicle numbers can be attributed to rising incomes combined with cheap consumer credit.', topic: 'Transport', bandLevel: '6-7', task: 'both', priority: 'must_learn' },
    { id: 'trn_w4', type: 'writing_phrase', term: 'The knock-on effect on air quality is considerable, since...', function: 'Explaining an effect', vietnameseMeaning: 'Tác động dây chuyền lên chất lượng không khí là rất lớn, bởi vì...', example: 'The knock-on effect on air quality is considerable, since idling engines emit far more pollution per kilometre than moving ones.', topic: 'Transport', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'trn_w5', type: 'writing_phrase', term: 'Amsterdam is a case in point:', function: 'Giving an example', vietnameseMeaning: 'Amsterdam là một ví dụ điển hình:', example: 'Amsterdam is a case in point: sustained investment in cycling infrastructure has made bicycles the default choice for short trips.', topic: 'Transport', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'trn_w6', type: 'writing_phrase', term: 'The chief advantage of a well-connected rail network is that...', function: 'Discussing advantages', vietnameseMeaning: 'Ưu điểm chính của mạng lưới đường sắt kết nối tốt là...', example: 'The chief advantage of a well-connected rail network is that it moves large numbers of people using a fraction of the land roads require.', topic: 'Transport', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'trn_w7', type: 'writing_phrase', term: 'The main drawback of restricting car access is the impact on...', function: 'Discussing disadvantages', vietnameseMeaning: 'Nhược điểm chính của việc hạn chế xe cá nhân là ảnh hưởng đến...', example: 'The main drawback of restricting car access is the impact on small traders, who depend on customers arriving by vehicle.', topic: 'Transport', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'trn_w8', type: 'writing_phrase', term: 'A more realistic approach would be to make alternatives attractive rather than to...', function: 'Suggesting a solution', vietnameseMeaning: 'Một cách tiếp cận thực tế hơn là làm cho các lựa chọn thay thế hấp dẫn thay vì...', example: 'A more realistic approach would be to make alternatives attractive rather than to punish drivers who currently have no other option.', topic: 'Transport', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'trn_w9', type: 'writing_phrase', term: 'I would argue that investment in transport should be judged by...', function: 'Expressing an opinion', vietnameseMeaning: 'Tôi cho rằng đầu tư giao thông nên được đánh giá dựa trên...', example: 'I would argue that investment in transport should be judged by how many people it moves, not by how many kilometres of road it produces.', topic: 'Transport', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'trn_w10', type: 'writing_phrase', term: 'Building new roads relieves congestion only briefly, whereas improving public transport...', function: 'Comparing ideas', vietnameseMeaning: 'Xây thêm đường chỉ giảm ùn tắc trong thời gian ngắn, trong khi cải thiện giao thông công cộng...', example: 'Building new roads relieves congestion only briefly, whereas improving public transport changes travel habits permanently.', topic: 'Transport', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'trn_m1', type: 'common_mistake', incorrect: 'I go to work by the bus every day.', correct: 'I travel to work by bus every day.', explanation: 'With "by + means of transport" there is no article: by bus, by car, by train, by plane. Say "on the bus" only when you mean physically inside a specific bus.', topic: 'Transport', priority: 'must_learn' },
    { id: 'trn_m2', type: 'common_mistake', incorrect: 'There are many traffics in Hanoi in the morning.', correct: 'There is heavy traffic in Hanoi in the morning.', explanation: '"Traffic" is uncountable — no plural and no "many". Use "heavy traffic", "a great deal of traffic" or "high traffic volumes".', topic: 'Transport', priority: 'must_learn' },
    { id: 'trn_m3', type: 'common_mistake', incorrect: 'The government should build more roads to solve traffic jam.', correct: 'The government should expand the metro network to ease traffic congestion.', explanation: 'Two problems: "traffic jam" is countable and needs an article or plural ("traffic jams"), and congestion is eased or reduced rather than "solved". "Congestion" is also the more academic choice.', topic: 'Transport', priority: 'must_learn' },
    { id: 'trn_m4', type: 'common_mistake', incorrect: 'High parking fees can deter people to drive into the city.', correct: 'High parking fees can deter people from driving into the city.', explanation: '"Deter" is followed by "from + -ing", never by "to + verb". The same pattern applies to "discourage" and "prevent".', topic: 'Transport', priority: 'high_value' },
    { id: 'trn_m5', type: 'common_mistake', incorrect: 'Vehicles emit a lot of smokes that pollute the air.', correct: 'Vehicles emit large quantities of exhaust fumes that pollute the air.', explanation: '"Smoke" is uncountable and refers to fire; what vehicles release is "exhaust fumes" or "emissions". "A lot of" is also too informal for an academic essay.', topic: 'Transport', priority: 'high_value' },
  ],

  learnFirst: {
    vocabulary: ['trn_v1', 'trn_v2', 'trn_v3', 'trn_v11', 'trn_v12', 'trn_v13', 'trn_v20', 'trn_v22', 'trn_v27', 'trn_v30'],
    collocations: ['trn_c1', 'trn_c7', 'trn_c9', 'trn_c17', 'trn_c20'],
    phrasalVerbs: ['trn_p7', 'trn_p6', 'trn_p9'],
    writingPhrases: ['trn_w1', 'trn_w3', 'trn_w8'],
  },
}
