import type { TopicData } from '../types'

export const WORK: TopicData = {
  topic: 'Work & Employment',

  vocabulary: [
    // ── Band 5-6 ──────────────────────────────────────────────────────────
    { id: 'wrk_v1', type: 'vocabulary', term: 'employee', pronunciation: '/ɪmˈplɔɪiː/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A person who is paid to work for an organisation.', vietnameseMeaning: 'Nhân viên, người làm công ăn lương.', example: 'Employees who feel trusted by their managers are consistently more productive.', writingTip: 'Distinguish carefully from "employer" (the company or person who pays). Candidates often confuse the two.', topic: 'Work & Employment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['full-time employee', 'motivate employees', 'employee satisfaction'], antonym: 'employer', wordFamily: ['employ (v)', 'employment (n)', 'employer (n)'], priority: 'must_learn' },
    { id: 'wrk_v2', type: 'vocabulary', term: 'salary', pronunciation: '/ˈsæləri/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A fixed regular payment, usually monthly, for professional work.', vietnameseMeaning: 'Lương (thường tính theo tháng, cho công việc văn phòng).', example: 'A high salary does not compensate for work that feels meaningless.', writingTip: 'A "salary" is monthly and fixed; a "wage" is usually hourly or weekly. Task 1 charts often use "average wages".', topic: 'Work & Employment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a competitive salary', 'earn a salary', 'salary increase', 'starting salary'], alternatives: ['pay', 'wage', 'remuneration'], priority: 'high_value' },
    { id: 'wrk_v3', type: 'vocabulary', term: 'career', pronunciation: '/kəˈrɪə/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'The series of jobs a person has over their working life.', vietnameseMeaning: 'Sự nghiệp, con đường nghề nghiệp.', example: 'Few people now expect to spend an entire career with a single employer.', writingTip: 'Do not confuse with "carrier". Common patterns: pursue a career, a career in medicine, career prospects.', topic: 'Work & Employment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['pursue a career', 'career prospects', 'a career change', 'career path'], priority: 'must_learn' },
    { id: 'wrk_v4', type: 'vocabulary', term: 'workforce', pronunciation: '/ˈwɜːkfɔːs/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'All the people who work in a country, industry or company.', vietnameseMeaning: 'Lực lượng lao động.', example: 'Women now make up almost half of the global workforce.', writingTip: 'A useful collective noun that avoids repeating "workers". Takes a singular verb in British English.', topic: 'Work & Employment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['a skilled workforce', 'enter the workforce', 'the ageing workforce'], alternatives: ['labour force', 'staff'], priority: 'must_learn' },
    { id: 'wrk_v5', type: 'vocabulary', term: 'promotion', pronunciation: '/prəˈməʊʃn/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A move to a more senior position at work.', vietnameseMeaning: 'Sự thăng chức, thăng tiến.', example: 'Employees who are denied promotion for several years almost always look elsewhere.', writingTip: 'The verb is "be promoted", not "be promotioned". Also means advertising in a business context.', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['gain promotion', 'promotion prospects', 'be considered for promotion'], wordFamily: ['promote (v)', 'promoted (adj)'], priority: 'high_value' },
    { id: 'wrk_v6', type: 'vocabulary', term: 'qualification', pronunciation: '/ˌkwɒlɪfɪˈkeɪʃn/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'An official record showing you have completed a course or passed an exam.', vietnameseMeaning: 'Bằng cấp, chứng chỉ chuyên môn.', example: 'Employers increasingly value demonstrated ability over formal qualifications.', writingTip: 'Countable, unlike "experience". You "gain" or "obtain" a qualification.', topic: 'Work & Employment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['formal qualifications', 'gain a qualification', 'professional qualification'], wordFamily: ['qualify (v)', 'qualified (adj)'], priority: 'high_value' },
    { id: 'wrk_v7', type: 'vocabulary', term: 'unemployment', pronunciation: '/ˌʌnɪmˈplɔɪmənt/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B1', definition: 'The situation of not having a job when you want one.', vietnameseMeaning: 'Tình trạng thất nghiệp.', example: 'Youth unemployment rose sharply in the years following the financial crisis.', writingTip: 'Essential for Task 1 line graphs. Say "the unemployment rate", not "the unemployment percentage".', topic: 'Work & Employment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['unemployment rate', 'youth unemployment', 'rising unemployment', 'long-term unemployment'], antonym: 'employment', wordFamily: ['unemployed (adj)'], priority: 'must_learn' },
    { id: 'wrk_v8', type: 'vocabulary', term: 'colleague', pronunciation: '/ˈkɒliːɡ/', partOfSpeech: 'noun', cefrLevel: 'B1', definition: 'A person you work with.', vietnameseMeaning: 'Đồng nghiệp.', example: 'Supportive colleagues matter more to job satisfaction than any bonus scheme.', writingTip: 'More formal than "workmate". The final "-gue" is silent after the "l".', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['senior colleague', 'work alongside colleagues', 'supportive colleagues'], alternatives: ['co-worker', 'associate'], priority: 'optional' },
    { id: 'wrk_v9', type: 'vocabulary', term: 'recruit', pronunciation: '/rɪˈkruːt/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To find and hire new people to work in an organisation.', vietnameseMeaning: 'Tuyển dụng nhân sự.', example: 'Hospitals in rural areas struggle to recruit specialists at any salary.', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['recruit staff', 'recruit graduates', 'recruitment process'], alternatives: ['hire', 'take on', 'appoint'], wordFamily: ['recruitment (n)', 'recruiter (n)'], priority: 'high_value' },
    { id: 'wrk_v10', type: 'vocabulary', term: 'productivity', pronunciation: '/ˌprɒdʌkˈtɪvəti/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The amount of useful output produced for each hour or worker.', vietnameseMeaning: 'Năng suất lao động.', example: 'Countries with the longest working hours frequently record the lowest productivity.', writingTip: 'A key economic term. Verbs: boost, raise, improve, undermine.', topic: 'Work & Employment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['boost productivity', 'improve productivity', 'productivity growth', 'low productivity'], wordFamily: ['productive (adj)', 'produce (v)'], priority: 'must_learn' },

    // ── Band 6-7 ──────────────────────────────────────────────────────────
    { id: 'wrk_v11', type: 'vocabulary', term: 'enhance', pronunciation: '/ɪnˈhɑːns/', partOfSpeech: 'verb', cefrLevel: 'B2', definition: 'To improve the quality or value of something.', vietnameseMeaning: 'Nâng cao, cải thiện chất lượng.', example: 'Ongoing training enhances both employee capability and company loyalty.', writingTip: 'A safe, formal upgrade from "improve" that fits almost any Task 2 topic.', topic: 'Work & Employment', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['enhance productivity', 'enhance skills', 'enhance reputation', 'greatly enhance'], alternatives: ['improve', 'strengthen', 'boost'], antonym: 'diminish', wordFamily: ['enhancement (n)', 'enhanced (adj)'], priority: 'must_learn' },
    { id: 'wrk_v12', type: 'vocabulary', term: 'flexible', pronunciation: '/ˈfleksəbl/', partOfSpeech: 'adjective', cefrLevel: 'B2', definition: 'Able to change or be changed to suit new conditions.', vietnameseMeaning: 'Linh hoạt, có thể điều chỉnh.', example: 'Flexible hours allow parents to remain in work who would otherwise have to leave it.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['flexible working', 'flexible hours', 'highly flexible'], antonym: 'rigid', wordFamily: ['flexibility (n)', 'flexibly (adv)'], priority: 'must_learn' },
    { id: 'wrk_v13', type: 'vocabulary', term: 'workload', pronunciation: '/ˈwɜːkləʊd/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'The amount of work a person is required to do.', vietnameseMeaning: 'Khối lượng công việc.', example: 'An unmanageable workload is the single most common reason teachers leave the profession.', writingTip: 'Adjectives that fit naturally: heavy, excessive, unmanageable, reasonable.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['a heavy workload', 'reduce the workload', 'an excessive workload'], priority: 'high_value' },
    { id: 'wrk_v14', type: 'vocabulary', term: 'incentive', pronunciation: '/ɪnˈsentɪv/', partOfSpeech: 'noun', cefrLevel: 'B2', definition: 'Something that encourages a person to act in a particular way.', vietnameseMeaning: 'Động lực, khuyến khích (thường bằng lợi ích vật chất).', example: 'Tax incentives are a cheaper way of changing corporate behaviour than legal penalties.', writingTip: 'Very useful in solution paragraphs. Patterns: "provide/offer an incentive to do something".', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['financial incentive', 'provide incentives', 'a strong incentive', 'tax incentives'], alternatives: ['motivation', 'inducement'], antonym: 'deterrent', wordFamily: ['incentivise (v)'], priority: 'must_learn' },
    { id: 'wrk_v15', type: 'vocabulary', term: 'turnover', pronunciation: '/ˈtɜːnəʊvə/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The rate at which employees leave and are replaced; also, total sales revenue.', vietnameseMeaning: 'Tỷ lệ nhân viên nghỉ việc; hoặc doanh thu.', example: 'High staff turnover is expensive, since every departure means months of lost expertise.', writingTip: 'Two distinct meanings — "staff turnover" (people) and "annual turnover" (money). Signal which you mean.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['high staff turnover', 'reduce turnover', 'annual turnover'], priority: 'high_value' },
    { id: 'wrk_v16', type: 'vocabulary', term: 'morale', pronunciation: '/məˈrɑːl/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'The level of confidence and enthusiasm within a group.', vietnameseMeaning: 'Tinh thần làm việc, nhuệ khí của tập thể.', example: 'Recognition costs nothing and raises morale more reliably than a modest pay rise.', writingTip: 'Do not confuse with "moral" (ethical) or "morals" (principles). Verbs: boost, raise, damage, undermine.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['boost morale', 'low morale', 'damage morale', 'staff morale'], priority: 'high_value' },
    { id: 'wrk_v17', type: 'vocabulary', term: 'delegate', pronunciation: '/ˈdelɪɡeɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To give responsibility for a task to someone else.', vietnameseMeaning: 'Uỷ quyền, giao việc cho cấp dưới.', example: 'Managers who cannot delegate become bottlenecks in their own organisations.', writingTip: 'Verb /ˈdelɪɡeɪt/ and noun /ˈdelɪɡət/ differ in the final vowel.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['delegate tasks', 'delegate responsibility', 'delegate authority'], wordFamily: ['delegation (n)'], priority: 'high_value' },
    { id: 'wrk_v18', type: 'vocabulary', term: 'expertise', pronunciation: '/ˌekspɜːˈtiːz/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Deep skill or knowledge in a particular field.', vietnameseMeaning: 'Chuyên môn sâu, trình độ chuyên gia.', example: 'Technical expertise is easy to hire; institutional memory is not.', writingTip: 'Uncountable — never "expertises". Stress falls on the last syllable.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['technical expertise', 'draw on expertise', 'considerable expertise'], wordFamily: ['expert (n/adj)'], priority: 'high_value' },
    { id: 'wrk_v19', type: 'vocabulary', term: 'outsource', pronunciation: '/ˈaʊtsɔːs/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To pay an outside company to do work previously done internally.', vietnameseMeaning: 'Thuê ngoài, giao việc cho đơn vị bên ngoài.', example: 'Firms that outsource customer service to cut costs often lose the loyalty they had built.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['outsource production', 'outsource jobs overseas', 'outsourced labour'], wordFamily: ['outsourcing (n)'], priority: 'high_value' },
    { id: 'wrk_v20', type: 'vocabulary', term: 'job satisfaction', pronunciation: '/ˈdʒɒb ˌsætɪsˈfækʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'B2', definition: 'The sense of fulfilment a person gets from their work.', vietnameseMeaning: 'Sự hài lòng với công việc.', example: 'Beyond a modest income, job satisfaction depends far more on autonomy than on pay.', writingTip: 'A ready-made noun phrase that lets you avoid the vague "people are happy at work".', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['high job satisfaction', 'derive job satisfaction from', 'levels of job satisfaction'], priority: 'must_learn' },

    // ── Band 7+ ───────────────────────────────────────────────────────────
    { id: 'wrk_v21', type: 'vocabulary', term: 'remuneration', pronunciation: '/rɪˌmjuːnəˈreɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'Payment for work or services.', vietnameseMeaning: 'Thù lao, khoản chi trả cho công việc.', example: 'Executive remuneration has risen far faster than average earnings for three decades.', writingTip: 'Formal and slightly bureaucratic. Effective once in an essay about pay; avoid repeating it.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['executive remuneration', 'adequate remuneration', 'a remuneration package'], alternatives: ['pay', 'compensation'], wordFamily: ['remunerate (v)'], priority: 'optional' },
    { id: 'wrk_v22', type: 'vocabulary', term: 'precarious', pronunciation: '/prɪˈkeəriəs/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Insecure and likely to change for the worse at any moment.', vietnameseMeaning: 'Bấp bênh, không ổn định.', example: 'Zero-hours contracts leave workers in a precarious position from one week to the next.', writingTip: '"Precarious employment" and "precarious work" are established terms in labour economics.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['precarious employment', 'a precarious position', 'increasingly precarious'], alternatives: ['insecure', 'unstable'], antonym: 'secure', wordFamily: ['precariously (adv)', 'precarity (n)'], priority: 'must_learn' },
    { id: 'wrk_v23', type: 'vocabulary', term: 'incentivise', pronunciation: '/ɪnˈsentɪvaɪz/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To motivate someone by offering a reward.', vietnameseMeaning: 'Tạo động lực bằng lợi ích, khuyến khích bằng phần thưởng.', example: 'Governments could incentivise firms to train older workers rather than replace them.', writingTip: 'Pattern: "incentivise somebody to do something". Sharper than "encourage" when money is involved.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['incentivise employers', 'incentivise investment', 'financially incentivise'], alternatives: ['encourage', 'motivate'], wordFamily: ['incentive (n)'], priority: 'must_learn' },
    { id: 'wrk_v24', type: 'vocabulary', term: 'attrition', pronunciation: '/əˈtrɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C2', definition: 'A gradual reduction in staff numbers as people leave and are not replaced.', vietnameseMeaning: 'Sự giảm dần nhân sự do nghỉ việc tự nhiên.', example: 'The company reduced its headcount through natural attrition rather than compulsory redundancies.', writingTip: 'A precise term worth one use in an essay on restructuring or downsizing.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['natural attrition', 'a high rate of attrition', 'reduce staff through attrition'], priority: 'optional' },
    { id: 'wrk_v25', type: 'vocabulary', term: 'entrepreneurial', pronunciation: '/ˌɒntrəprəˈnɜːriəl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Showing the willingness to take business risks in order to make a profit.', vietnameseMeaning: 'Có tinh thần khởi nghiệp, dám nghĩ dám làm.', example: 'Schools rarely reward the entrepreneurial instincts that build successful businesses.', writingTip: 'The noun "entrepreneur" is spelled with "-eur" and pronounced with final stress.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['entrepreneurial spirit', 'entrepreneurial skills', 'an entrepreneurial culture'], wordFamily: ['entrepreneur (n)', 'entrepreneurship (n)'], priority: 'high_value' },
    { id: 'wrk_v26', type: 'vocabulary', term: 'equitable', pronunciation: '/ˈekwɪtəbl/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Fair and reasonable in the way people are treated.', vietnameseMeaning: 'Công bằng, hợp lý đối với mọi người.', example: 'A more equitable distribution of parental leave would help close the gender pay gap.', writingTip: '"Equitable" means fair, while "equal" means identical — a distinction that impresses examiners.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['equitable distribution', 'equitable treatment', 'more equitable'], alternatives: ['fair', 'just'], antonym: 'inequitable', wordFamily: ['equity (n)', 'equitably (adv)'], priority: 'high_value' },
    { id: 'wrk_v27', type: 'vocabulary', term: 'stagnate', pronunciation: '/stæɡˈneɪt/', partOfSpeech: 'verb', cefrLevel: 'C1', definition: 'To stop developing or improving.', vietnameseMeaning: 'Trì trệ, dậm chân tại chỗ.', example: 'Real wages have stagnated even as company profits have risen steadily.', writingTip: 'Excellent for Task 1 as well: a line that neither rises nor falls "stagnated" or "remained stagnant".', topic: 'Work & Employment', bandLevel: '7+', task: 'both', writingSuitability: 'highly_suitable', collocations: ['wages stagnate', 'growth stagnates', 'remain stagnant'], alternatives: ['plateau', 'stall'], wordFamily: ['stagnation (n)', 'stagnant (adj)'], priority: 'must_learn' },
    { id: 'wrk_v28', type: 'vocabulary', term: 'counterproductive', pronunciation: '/ˌkaʊntəprəˈdʌktɪv/', partOfSpeech: 'adjective', cefrLevel: 'C1', definition: 'Having the opposite effect to the one intended.', vietnameseMeaning: 'Phản tác dụng, gây hiệu quả ngược.', example: 'Monitoring employees minute by minute is counterproductive, since it destroys the trust it depends on.', writingTip: 'Extremely useful for rebutting an opposing argument in a discussion essay.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['prove counterproductive', 'ultimately counterproductive'], alternatives: ['self-defeating'], priority: 'must_learn' },
    { id: 'wrk_v29', type: 'vocabulary', term: 'gig economy', pronunciation: '/ˈɡɪɡ ɪˌkɒnəmi/', partOfSpeech: 'noun', cefrLevel: 'C1', definition: 'A labour market based on short-term contracts and freelance work.', vietnameseMeaning: 'Nền kinh tế việc làm tự do, làm theo hợp đồng ngắn hạn.', example: 'The gig economy offers genuine flexibility, but almost none of the protections of formal employment.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the rise of the gig economy', 'gig economy workers'], priority: 'high_value' },
    { id: 'wrk_v30', type: 'vocabulary', term: 'exploitation', pronunciation: '/ˌeksplɔɪˈteɪʃn/', partOfSpeech: 'noun (uncountable)', cefrLevel: 'C1', definition: 'Unfair treatment of people in order to profit from their work.', vietnameseMeaning: 'Sự bóc lột sức lao động.', example: 'Without enforceable minimum standards, outsourcing simply relocates exploitation rather than ending it.', writingTip: 'Also used neutrally of resources ("the exploitation of oil reserves"). Context decides the tone.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['labour exploitation', 'protect workers from exploitation', 'economic exploitation'], wordFamily: ['exploit (v)', 'exploitative (adj)'], priority: 'high_value' },
  ],

  collocations: [
    // Essential (Band 5-6)
    { id: 'wrk_c1', type: 'collocation', term: 'apply for a job', collocationType: 'Verb + Prep + Noun', definition: 'To formally request to be considered for a position.', vietnameseMeaning: 'Nộp đơn xin việc.', example: 'Graduates now apply for dozens of jobs before receiving a single interview.', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'You apply FOR a job but apply TO a company.' },
    { id: 'wrk_c2', type: 'collocation', term: 'full-time employment', collocationType: 'Adj + Noun', definition: 'Work of a standard number of hours per week.', vietnameseMeaning: 'Việc làm toàn thời gian.', example: 'Full-time employment no longer guarantees a standard of living it once did.', alternative: 'permanent employment', topic: 'Work & Employment', bandLevel: '5-6', task: 'both', priority: 'high_value' },
    { id: 'wrk_c3', type: 'collocation', term: 'job satisfaction', collocationType: 'Noun + Noun', definition: 'The pleasure and fulfilment gained from one’s work.', vietnameseMeaning: 'Sự hài lòng trong công việc.', example: 'Nurses report high job satisfaction despite low pay and long shifts.', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', priority: 'must_learn' },
    { id: 'wrk_c4', type: 'collocation', term: 'work long hours', collocationType: 'Verb + Noun', definition: 'To spend an excessive amount of time working.', vietnameseMeaning: 'Làm việc nhiều giờ, làm việc quá sức.', example: 'Employees who work long hours are not necessarily producing more.', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: 'Not "work many hours" — "long hours" is the fixed collocation.' },
    { id: 'wrk_c5', type: 'collocation', term: 'earn a living', collocationType: 'Verb + Noun', definition: 'To make enough money to support yourself.', vietnameseMeaning: 'Kiếm sống, mưu sinh.', example: 'Artists rarely earn a living from their work alone.', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'wrk_c6', type: 'collocation', term: 'a permanent contract', collocationType: 'Adj + Noun', definition: 'An employment agreement with no fixed end date.', vietnameseMeaning: 'Hợp đồng lao động không xác định thời hạn.', example: 'Younger workers wait years longer for a permanent contract than their parents did.', alternative: 'an open-ended contract', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', priority: 'high_value' },
    { id: 'wrk_c7', type: 'collocation', term: 'gain experience', collocationType: 'Verb + Noun', definition: 'To develop practical knowledge by doing something.', vietnameseMeaning: 'Tích luỹ kinh nghiệm.', example: 'Internships allow students to gain experience that no lecture can provide.', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', priority: 'must_learn', writingTip: '"Experience" is uncountable here — never "gain many experiences".' },
    { id: 'wrk_c8', type: 'collocation', term: 'career prospects', collocationType: 'Noun + Noun', definition: 'The chances of advancing in your working life.', vietnameseMeaning: 'Triển vọng nghề nghiệp.', example: 'A degree improves career prospects, though less dramatically than it once did.', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', priority: 'high_value' },

    // Advanced (Band 6-7)
    { id: 'wrk_c9', type: 'collocation', term: 'work-life balance', collocationType: 'Noun + Noun', definition: 'A healthy division between time spent working and time spent living.', vietnameseMeaning: 'Cân bằng giữa công việc và cuộc sống.', example: 'A four-day week has improved work-life balance without reducing output in several trials.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', priority: 'must_learn', writingTip: 'Hyphenated, and normally used with "achieve", "maintain" or "improve".' },
    { id: 'wrk_c10', type: 'collocation', term: 'a competitive salary', collocationType: 'Adj + Noun', definition: 'Pay at least as good as that offered by rival employers.', vietnameseMeaning: 'Mức lương cạnh tranh.', example: 'A competitive salary attracts applicants, but only good management keeps them.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'wrk_c11', type: 'collocation', term: 'high staff turnover', collocationType: 'Adj + Noun', definition: 'A situation in which employees leave and are replaced frequently.', vietnameseMeaning: 'Tỷ lệ nhân viên nghỉ việc cao.', example: 'High staff turnover in the care sector is a symptom of poor pay rather than poor recruitment.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'wrk_c12', type: 'collocation', term: 'boost productivity', collocationType: 'Verb + Noun', definition: 'To increase the output produced per worker or per hour.', vietnameseMeaning: 'Thúc đẩy năng suất lao động.', example: 'Adequate rest boosts productivity more reliably than extending the working day.', topic: 'Work & Employment', bandLevel: '6-7', task: 'both', priority: 'must_learn' },
    { id: 'wrk_c13', type: 'collocation', term: 'job security', collocationType: 'Noun + Noun', definition: 'Confidence that your employment will continue.', vietnameseMeaning: 'Sự ổn định, an toàn trong công việc.', example: 'Many workers would trade a higher salary for greater job security.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'wrk_c14', type: 'collocation', term: 'flexible working arrangements', collocationType: 'Adj + Noun', definition: 'Employment terms allowing choice over hours or location.', vietnameseMeaning: 'Chế độ làm việc linh hoạt.', example: 'Flexible working arrangements have kept many experienced staff in jobs they would otherwise have left.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'wrk_c15', type: 'collocation', term: 'professional development', collocationType: 'Adj + Noun', definition: 'Ongoing training that improves an employee’s skills.', vietnameseMeaning: 'Phát triển chuyên môn nghề nghiệp.', example: 'Firms that cut professional development first are usually the first to lose their best people.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', priority: 'high_value' },

    // High-impact (Band 7+)
    { id: 'wrk_c16', type: 'collocation', term: 'precarious employment', collocationType: 'Adj + Noun', definition: 'Work that is insecure, badly paid and easily withdrawn.', vietnameseMeaning: 'Việc làm bấp bênh, thiếu ổn định.', example: 'Precarious employment makes long-term planning impossible for millions of households.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'wrk_c17', type: 'collocation', term: 'wage stagnation', collocationType: 'Noun + Noun', definition: 'A prolonged period in which pay fails to rise in real terms.', vietnameseMeaning: 'Tình trạng lương trì trệ không tăng.', example: 'Wage stagnation explains much of the political discontent in wealthy democracies.', topic: 'Work & Employment', bandLevel: '7+', task: 'both', priority: 'high_value' },
    { id: 'wrk_c18', type: 'collocation', term: 'close the gender pay gap', collocationType: 'Verb + Noun', definition: 'To eliminate the difference between average male and female earnings.', vietnameseMeaning: 'Thu hẹp khoảng cách lương giữa nam và nữ.', example: 'Transparent pay scales have done more to close the gender pay gap than voluntary targets.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'wrk_c19', type: 'collocation', term: 'attract and retain talent', collocationType: 'Verb + Noun', definition: 'To draw in skilled people and keep them in the organisation.', vietnameseMeaning: 'Thu hút và giữ chân nhân tài.', example: 'Organisations that cannot attract and retain talent inevitably lose ground to those that can.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'wrk_c20', type: 'collocation', term: 'exploit cheap labour', collocationType: 'Verb + Noun', definition: 'To profit unfairly from workers who are paid very little.', vietnameseMeaning: 'Bóc lột lao động giá rẻ.', example: 'Global supply chains too often exploit cheap labour in countries with weak protections.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  phrasalVerbs: [
    // Common
    { id: 'wrk_p1', type: 'phrasal_verb', term: 'take on', partOfSpeech: 'phrasal verb (separable)', definition: 'To employ someone; to accept a responsibility.', vietnameseMeaning: 'Tuyển thêm người; nhận thêm trách nhiệm.', example: 'Small firms are reluctant to take on new staff when regulation is uncertain.', formalAlternative: 'recruit', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', collocations: ['take on staff', 'take on responsibility'], academicAlternatives: ['recruit', 'employ', 'assume'] },
    { id: 'wrk_p2', type: 'phrasal_verb', term: 'lay off', partOfSpeech: 'phrasal verb (separable)', definition: 'To dismiss workers because there is not enough work.', vietnameseMeaning: 'Cho thôi việc, sa thải vì thiếu việc.', example: 'Manufacturers laid off thousands of workers when demand collapsed.', formalAlternative: 'make redundant', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', usageWarning: 'Not the same as "fire" or "dismiss", which imply the worker did something wrong.', academicAlternatives: ['make redundant', 'dismiss', 'downsize'] },
    { id: 'wrk_p3', type: 'phrasal_verb', term: 'carry out', partOfSpeech: 'phrasal verb (separable)', definition: 'To perform a task, study or instruction.', vietnameseMeaning: 'Thực hiện, tiến hành (nhiệm vụ, nghiên cứu).', example: 'Employers should carry out regular reviews of workload as well as performance.', formalAlternative: 'conduct', topic: 'Work & Employment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', priority: 'must_learn', collocations: ['carry out research', 'carry out a survey', 'carry out duties'], academicAlternatives: ['conduct', 'perform', 'undertake'] },
    { id: 'wrk_p4', type: 'phrasal_verb', term: 'take over', partOfSpeech: 'phrasal verb (separable)', definition: 'To assume control of something from someone else.', vietnameseMeaning: 'Tiếp quản, đảm nhận thay.', example: 'Machines have already taken over the most repetitive parts of assembly work.', formalAlternative: 'assume control of', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', academicAlternatives: ['assume control of', 'supersede', 'acquire'] },
    { id: 'wrk_p5', type: 'phrasal_verb', term: 'step down', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To leave an important position voluntarily.', vietnameseMeaning: 'Từ chức, rút khỏi vị trí lãnh đạo.', example: 'Executives who step down after a scandal frequently reappear elsewhere within a year.', formalAlternative: 'resign', topic: 'Work & Employment', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['resign', 'relinquish a post'] },

    // Advanced / less common
    { id: 'wrk_p6', type: 'phrasal_verb', term: 'burn out', partOfSpeech: 'phrasal verb (intransitive)', definition: 'To become exhausted through prolonged overwork.', vietnameseMeaning: 'Kiệt sức vì làm việc quá tải.', example: 'Junior doctors burn out at a rate no health system can afford.', formalAlternative: 'suffer exhaustion', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'must_learn', collocations: ['burn out quickly', 'burnt out staff'], academicAlternatives: ['become exhausted', 'suffer burnout'] },
    { id: 'wrk_p7', type: 'phrasal_verb', term: 'cut back on', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To reduce spending or activity.', vietnameseMeaning: 'Cắt giảm (chi tiêu, hoạt động).', example: 'Firms that cut back on training during downturns take years to recover the lost skills.', formalAlternative: 'reduce', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Slightly informal. "Reduce", "curtail" or "scale back" are safer in Task 2.', academicAlternatives: ['reduce', 'curtail', 'scale back'] },
    { id: 'wrk_p8', type: 'phrasal_verb', term: 'take up', partOfSpeech: 'phrasal verb (separable)', definition: 'To start a job, activity or hobby.', vietnameseMeaning: 'Bắt đầu nhận (một công việc, hoạt động).', example: 'Retirees who take up part-time work report better health than those who stop entirely.', formalAlternative: 'commence', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'high_value', usageWarning: 'Also means "occupy space or time" — make the sense clear from context.', academicAlternatives: ['commence', 'undertake', 'assume'] },
    { id: 'wrk_p9', type: 'phrasal_verb', term: 'come up with', partOfSpeech: 'phrasal verb (inseparable)', definition: 'To think of an idea or solution.', vietnameseMeaning: 'Nghĩ ra, đưa ra (ý tưởng, giải pháp).', example: 'Teams with diverse backgrounds come up with a wider range of solutions.', formalAlternative: 'devise', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'use_with_caution', priority: 'high_value', usageWarning: 'Conversational. In formal writing prefer "devise", "propose" or "formulate".', academicAlternatives: ['devise', 'propose', 'formulate', 'generate'] },
    { id: 'wrk_p10', type: 'phrasal_verb', term: 'hand over', partOfSpeech: 'phrasal verb (separable)', definition: 'To give responsibility or control to someone else.', vietnameseMeaning: 'Bàn giao, chuyển giao trách nhiệm.', example: 'Long-serving managers rarely hand over authority as smoothly as organisations assume.', formalAlternative: 'transfer', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', priority: 'optional', academicAlternatives: ['transfer', 'delegate', 'relinquish'] },
  ],

  writingPhrases: [
    { id: 'wrk_w1', type: 'writing_phrase', term: 'The argument for shorter working hours rests on the observation that...', function: 'Introducing an argument', vietnameseMeaning: 'Lập luận ủng hộ giảm giờ làm dựa trên nhận định rằng...', example: 'The argument for shorter working hours rests on the observation that output and hours are only loosely connected.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'wrk_w2', type: 'writing_phrase', term: 'Employees leave for one overriding reason:', function: 'Giving a reason', vietnameseMeaning: 'Nhân viên nghỉ việc vì một lý do bao trùm:', example: 'Employees leave for one overriding reason: they no longer believe their effort will be recognised.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'wrk_w3', type: 'writing_phrase', term: 'This shortage of skilled workers arises from...', function: 'Explaining a cause', vietnameseMeaning: 'Tình trạng thiếu lao động có tay nghề này bắt nguồn từ...', example: 'This shortage of skilled workers arises from decades of underinvestment in vocational training.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'wrk_w4', type: 'writing_phrase', term: 'The effect on staff morale is immediate and measurable:', function: 'Explaining an effect', vietnameseMeaning: 'Tác động lên tinh thần nhân viên là tức thì và có thể đo lường được:', example: 'The effect on staff morale is immediate and measurable: absence rates rise within a single quarter.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'high_value' },
    { id: 'wrk_w5', type: 'writing_phrase', term: 'Iceland’s four-day week trial is a good illustration:', function: 'Giving an example', vietnameseMeaning: 'Thử nghiệm tuần làm việc bốn ngày của Iceland là một minh hoạ tốt:', example: 'Iceland’s four-day week trial is a good illustration: output held steady while reported stress fell.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', priority: 'must_learn' },
    { id: 'wrk_w6', type: 'writing_phrase', term: 'The principal benefit for employers would be...', function: 'Discussing advantages', vietnameseMeaning: 'Lợi ích chính đối với người sử dụng lao động sẽ là...', example: 'The principal benefit for employers would be a sharp reduction in the cost of replacing staff.', topic: 'Work & Employment', bandLevel: '6-7', task: 'task2', priority: 'high_value' },
    { id: 'wrk_w7', type: 'writing_phrase', term: 'The obvious risk of such flexibility is that it can slide into...', function: 'Discussing disadvantages', vietnameseMeaning: 'Rủi ro rõ ràng của sự linh hoạt này là nó có thể trượt thành...', example: 'The obvious risk of such flexibility is that it can slide into insecurity for the worker.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'wrk_w8', type: 'writing_phrase', term: 'Employers could mitigate this by...', function: 'Suggesting a solution', vietnameseMeaning: 'Người sử dụng lao động có thể giảm thiểu điều này bằng cách...', example: 'Employers could mitigate this by guaranteeing a minimum number of paid hours each month.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'wrk_w9', type: 'writing_phrase', term: 'I am firmly of the view that job security matters more than...', function: 'Expressing an opinion', vietnameseMeaning: 'Tôi tin chắc rằng sự ổn định công việc quan trọng hơn...', example: 'I am firmly of the view that job security matters more than marginal increases in pay.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'must_learn' },
    { id: 'wrk_w10', type: 'writing_phrase', term: 'Where previous generations valued stability, younger workers tend to prioritise...', function: 'Comparing ideas', vietnameseMeaning: 'Trong khi các thế hệ trước coi trọng sự ổn định, người lao động trẻ có xu hướng ưu tiên...', example: 'Where previous generations valued stability, younger workers tend to prioritise autonomy and purpose.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', priority: 'high_value' },
  ],

  commonMistakes: [
    { id: 'wrk_m1', type: 'common_mistake', incorrect: 'It is difficult to find a work in this city.', correct: 'It is difficult to find work in this city.', explanation: '"Work" is uncountable and takes no article; "job" is countable. Either "find work" or "find a job" — never "a work".', topic: 'Work & Employment', priority: 'must_learn' },
    { id: 'wrk_m2', type: 'common_mistake', incorrect: 'The company has more than 500 staffs.', correct: 'The company has more than 500 members of staff.', explanation: '"Staff" is a collective noun with no plural -s. Use "staff", "members of staff" or "employees".', topic: 'Work & Employment', priority: 'must_learn' },
    { id: 'wrk_m3', type: 'common_mistake', incorrect: 'Companies should pay a higher salary for their employees.', correct: 'Companies should pay their employees a higher salary.', explanation: 'The verb "pay" takes the person directly, or "to + person". "Pay a salary for someone" means paying on their behalf.', topic: 'Work & Employment', priority: 'high_value' },
    { id: 'wrk_m4', type: 'common_mistake', incorrect: 'Young applicants often lack of working experiences.', correct: 'Young applicants often lack work experience.', explanation: 'Two errors: the verb "lack" takes no "of" (only the noun phrase "a lack of" does), and "experience" is uncountable in this sense.', topic: 'Work & Employment', priority: 'must_learn' },
    { id: 'wrk_m5', type: 'common_mistake', incorrect: 'He lost his job because of lazy.', correct: 'He lost his job because he was lazy.', explanation: '"Because of" must be followed by a noun ("because of his laziness"); "because" is followed by a full clause.', topic: 'Work & Employment', priority: 'must_learn' },
  ],

  learnFirst: {
    vocabulary: ['wrk_v7', 'wrk_v10', 'wrk_v11', 'wrk_v14', 'wrk_v20', 'wrk_v22', 'wrk_v23', 'wrk_v27', 'wrk_v28', 'wrk_v12'],
    collocations: ['wrk_c3', 'wrk_c9', 'wrk_c12', 'wrk_c13', 'wrk_c19'],
    phrasalVerbs: ['wrk_p1', 'wrk_p2', 'wrk_p3'],
    writingPhrases: ['wrk_w1', 'wrk_w7', 'wrk_w9'],
  },
}
