import { VocabularyItem } from './types'

export const VOCABULARY_DATA: VocabularyItem[] = [
  // ─── VOCABULARY (30 items) ───────────────────────────────────────────────

  // Environment
  { id: 'v1', type: 'vocabulary', term: 'mitigate', pronunciation: '/ˈmɪtɪɡeɪt/', partOfSpeech: 'verb', definition: 'To reduce the harmful effects of something.', vietnameseMeaning: 'Giảm thiểu, làm giảm tác động tiêu cực.', example: 'Governments should introduce stricter regulations to mitigate the effects of air pollution.', writingTip: 'Often used with "impact", "effects", "consequences", "risks". More precise than simply saying "reduce".', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['mitigate the impact', 'mitigate the effects', 'mitigate the consequences', 'mitigate the risks'], alternatives: ['reduce', 'alleviate', 'minimise', 'lessen'] },

  { id: 'v2', type: 'vocabulary', term: 'exacerbate', pronunciation: '/ɪɡˈzæsəbeɪt/', partOfSpeech: 'verb', definition: 'To make a problem or situation worse.', vietnameseMeaning: 'Làm trầm trọng thêm, làm tệ hơn.', example: 'Rapid industrialisation has exacerbated environmental degradation in many developing nations.', writingTip: 'A powerful alternative to "worsen" or "make worse". Use when discussing negative trends.', topic: 'Environment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['exacerbate the problem', 'exacerbate inequality', 'exacerbate the situation'], alternatives: ['worsen', 'aggravate', 'intensify', 'compound'] },

  { id: 'v3', type: 'vocabulary', term: 'deplete', pronunciation: '/dɪˈpliːt/', partOfSpeech: 'verb', definition: 'To reduce something significantly, especially a natural resource.', vietnameseMeaning: 'Làm cạn kiệt, tiêu hao đáng kể.', example: 'Continued deforestation has depleted the natural habitats of countless species.', writingTip: 'Commonly used with "resources", "reserves", "stocks". Implies a serious or irreversible reduction.', topic: 'Environment', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['deplete natural resources', 'deplete the ozone layer', 'deplete fish stocks'], alternatives: ['exhaust', 'use up', 'reduce'] },

  { id: 'v4', type: 'vocabulary', term: 'sustainable', pronunciation: '/səˈsteɪnəbl/', partOfSpeech: 'adjective', definition: 'Able to be maintained without depleting natural resources or causing long-term harm.', vietnameseMeaning: 'Bền vững, có thể duy trì lâu dài.', example: 'Governments must invest in sustainable energy sources to reduce dependence on fossil fuels.', writingTip: 'Very high-frequency in IELTS. Use "sustainable development", "sustainable practices", "sustainable solutions".', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['sustainable development', 'sustainable energy', 'sustainable practices', 'sustainable solution'] },

  // Education
  { id: 'v5', type: 'vocabulary', term: 'facilitate', pronunciation: '/fəˈsɪlɪteɪt/', partOfSpeech: 'verb', definition: 'To make a process or action easier or more likely to happen.', vietnameseMeaning: 'Tạo điều kiện thuận lợi, hỗ trợ, xúc tiến.', example: 'Technology can facilitate collaboration between students in different parts of the world.', writingTip: 'More formal than "help" or "make easier". Suitable for Task 2 arguments.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['facilitate learning', 'facilitate communication', 'facilitate access'], alternatives: ['enable', 'support', 'promote', 'encourage'] },

  { id: 'v6', type: 'vocabulary', term: 'equip', pronunciation: '/ɪˈkwɪp/', partOfSpeech: 'verb', definition: 'To provide someone with the necessary skills, knowledge, or tools.', vietnameseMeaning: 'Trang bị, cung cấp kỹ năng hoặc kiến thức cần thiết.', example: 'Universities should equip graduates with practical skills as well as theoretical knowledge.', writingTip: 'Common in education topics. "equip students with" is a very natural collocation.', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['equip students with skills', 'equip people with knowledge', 'equip the workforce'] },

  { id: 'v7', type: 'vocabulary', term: 'cultivate', pronunciation: '/ˈkʌltɪveɪt/', partOfSpeech: 'verb', definition: 'To develop or improve a skill, quality, or relationship through deliberate effort.', vietnameseMeaning: 'Vun đắp, phát triển, trau dồi (kỹ năng, phẩm chất).', example: 'Schools should cultivate critical thinking skills rather than relying solely on rote memorisation.', writingTip: 'Commonly used with "skills", "habits", "relationships", "attitudes". More formal than "develop".', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['cultivate skills', 'cultivate critical thinking', 'cultivate a culture of'], alternatives: ['develop', 'foster', 'nurture', 'promote'] },

  // Health
  { id: 'v8', type: 'vocabulary', term: 'alleviate', pronunciation: '/əˈliːvieɪt/', partOfSpeech: 'verb', definition: 'To make a problem, pain, or difficulty less severe.', vietnameseMeaning: 'Giảm bớt, làm nhẹ đi (đau đớn, khó khăn).', example: 'Regular physical activity can alleviate symptoms of depression and anxiety.', writingTip: 'A strong alternative to "reduce" when discussing pain, stress, or social problems. Slightly more formal.', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['alleviate poverty', 'alleviate stress', 'alleviate symptoms', 'alleviate pressure'], alternatives: ['reduce', 'ease', 'relieve', 'lessen'] },

  { id: 'v9', type: 'vocabulary', term: 'prevalence', pronunciation: '/ˈprevələns/', partOfSpeech: 'noun', definition: 'The fact of something being widespread or common in a particular area or group.', vietnameseMeaning: 'Sự phổ biến, tỷ lệ mắc phải (của một hiện tượng hay bệnh).', example: 'The prevalence of obesity among young people has risen sharply over the past two decades.', writingTip: 'Use "the prevalence of" to discuss how common a health issue or social problem is. Very natural in academic writing.', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['the prevalence of obesity', 'growing prevalence', 'high prevalence'] },

  { id: 'v10', type: 'vocabulary', term: 'sedentary', pronunciation: '/ˈsedənteri/', partOfSpeech: 'adjective', definition: 'Involving little physical activity; tending to sit or stay inactive.', vietnameseMeaning: 'Lười vận động, ngồi nhiều, ít vận động thể chất.', example: 'A sedentary lifestyle is one of the leading causes of obesity and cardiovascular disease.', writingTip: '"Sedentary lifestyle" is a very high-frequency IELTS collocation. Use it when discussing modern health problems.', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['sedentary lifestyle', 'sedentary behaviour', 'increasingly sedentary'] },

  // Technology
  { id: 'v11', type: 'vocabulary', term: 'revolutionise', pronunciation: '/ˌrevəˈluːʃənaɪz/', partOfSpeech: 'verb', definition: 'To change something completely and fundamentally.', vietnameseMeaning: 'Cách mạng hoá, thay đổi hoàn toàn.', example: 'The internet has revolutionised the way people access information and communicate with others.', writingTip: 'Use when discussing significant technological changes. Avoid overusing — reserve it for truly transformative changes.', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['revolutionise communication', 'revolutionise the way', 'revolutionise industry'], alternatives: ['transform', 'reshape', 'fundamentally change'] },

  { id: 'v12', type: 'vocabulary', term: 'ubiquitous', pronunciation: '/juːˈbɪkwɪtəs/', partOfSpeech: 'adjective', definition: 'Present, appearing, or found everywhere.', vietnameseMeaning: 'Có mặt khắp nơi, phổ biến rộng rãi.', example: 'Smartphones have become ubiquitous in modern society, changing almost every aspect of daily life.', writingTip: 'A sophisticated alternative to "everywhere" or "very common". Use sparingly for maximum effect.', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'suitable', collocations: ['become ubiquitous', 'ubiquitous technology', 'ubiquitous in modern life'], alternatives: ['widespread', 'universal', 'pervasive'] },

  { id: 'v13', type: 'vocabulary', term: 'automate', pronunciation: '/ˈɔːtəmeɪt/', partOfSpeech: 'verb', definition: 'To use technology or machines to perform tasks with minimal human involvement.', vietnameseMeaning: 'Tự động hoá (sử dụng máy móc thay thế con người).', example: 'Many manufacturing jobs have been automated, raising concerns about unemployment.', writingTip: 'Crucial for discussing AI and the future of work. "Automation" (noun) is also very common.', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['automate processes', 'automate tasks', 'increasingly automated'] },

  // Economy
  { id: 'v14', type: 'vocabulary', term: 'fluctuate', pronunciation: '/ˈflʌktʃueɪt/', partOfSpeech: 'verb', definition: 'To change irregularly and unpredictably between higher and lower levels.', vietnameseMeaning: 'Dao động, lên xuống thất thường.', example: 'The unemployment rate fluctuated between 5% and 8% during the decade.', writingTip: 'Essential for Task 1 when describing graphs and charts. "Fluctuated" shows irregular movement — do not use it for consistent rises or falls.', topic: 'Economy', bandLevel: '6-7', task: 'task1', writingSuitability: 'highly_suitable', collocations: ['fluctuate significantly', 'fluctuate between', 'prices fluctuate'] },

  { id: 'v15', type: 'vocabulary', term: 'disparity', pronunciation: '/dɪˈspærɪti/', partOfSpeech: 'noun', definition: 'A great difference or inequality, especially between groups.', vietnameseMeaning: 'Sự chênh lệch, bất bình đẳng lớn giữa các nhóm.', example: 'There is a growing disparity in income between the wealthiest and poorest members of society.', writingTip: 'More precise than "difference" or "gap" when emphasising inequality. Often used with "income", "wealth", "educational".', topic: 'Economy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['income disparity', 'wealth disparity', 'growing disparity', 'address the disparity'], alternatives: ['inequality', 'gap', 'imbalance'] },

  { id: 'v16', type: 'vocabulary', term: 'stimulate', pronunciation: '/ˈstɪmjuleɪt/', partOfSpeech: 'verb', definition: 'To encourage activity, growth, or development.', vietnameseMeaning: 'Kích thích, thúc đẩy sự tăng trưởng.', example: 'Lower interest rates are designed to stimulate economic growth by encouraging borrowing and investment.', writingTip: 'Common in economic and government topics. "Stimulate the economy" is a key collocation.', topic: 'Economy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['stimulate economic growth', 'stimulate the economy', 'stimulate investment'], alternatives: ['boost', 'encourage', 'drive', 'promote'] },

  // Work & Employment
  { id: 'v17', type: 'vocabulary', term: 'enhance', pronunciation: '/ɪnˈhɑːns/', partOfSpeech: 'verb', definition: 'To improve the quality, value, or effectiveness of something.', vietnameseMeaning: 'Nâng cao, cải thiện, tăng cường.', example: 'Professional development programmes can significantly enhance employee productivity and job satisfaction.', writingTip: 'More formal than "improve". Common in work, education, and technology topics.', topic: 'Work & Employment', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['enhance productivity', 'enhance skills', 'enhance the quality of', 'enhance performance'], alternatives: ['improve', 'boost', 'strengthen', 'develop'] },

  { id: 'v18', type: 'vocabulary', term: 'incentivise', pronunciation: '/ɪnˈsentɪvaɪz/', partOfSpeech: 'verb', definition: 'To motivate someone to do something by offering a reward or benefit.', vietnameseMeaning: 'Khuyến khích, tạo động lực bằng phần thưởng hoặc lợi ích.', example: 'Governments should incentivise businesses to adopt environmentally friendly practices.', writingTip: 'A precise and formal alternative to "encourage" when there is a material reward involved.', topic: 'Work & Employment', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['incentivise businesses', 'incentivise employees', 'financial incentives'], alternatives: ['encourage', 'motivate', 'reward'] },

  // Government
  { id: 'v19', type: 'vocabulary', term: 'implement', pronunciation: '/ˈɪmplɪment/', partOfSpeech: 'verb', definition: 'To put a plan, policy, or decision into effect.', vietnameseMeaning: 'Thực hiện, triển khai, áp dụng (chính sách, kế hoạch).', example: 'The government should implement stricter measures to combat rising crime rates.', writingTip: '"Implement policies/measures/regulations" is a very high-frequency IELTS Task 2 collocation. Learn to use it naturally.', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['implement policies', 'implement measures', 'implement regulations', 'implement a strategy'] },

  { id: 'v20', type: 'vocabulary', term: 'legislation', pronunciation: '/ˌledʒɪˈsleɪʃn/', partOfSpeech: 'noun', definition: 'Laws or a set of laws passed by a government.', vietnameseMeaning: 'Luật pháp, pháp chế, hệ thống luật được ban hành.', example: 'Stricter legislation is needed to protect workers from exploitation in the gig economy.', writingTip: 'Uncountable noun — do NOT say "legislations". Use "legislation" or "pieces of legislation".', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['introduce legislation', 'stricter legislation', 'environmental legislation', 'pass legislation'] },

  { id: 'v21', type: 'vocabulary', term: 'allocate', pronunciation: '/ˈæləkeɪt/', partOfSpeech: 'verb', definition: 'To distribute resources or funds for a specific purpose.', vietnameseMeaning: 'Phân bổ, phân phối (nguồn lực, ngân sách) cho mục đích cụ thể.', example: 'Governments must allocate sufficient funding to public healthcare systems.', writingTip: 'More formal than "give" or "spend on". Use in government and economy topics.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['allocate resources', 'allocate funding', 'allocate a budget'], alternatives: ['distribute', 'assign', 'devote', 'channel'] },

  // Society
  { id: 'v22', type: 'vocabulary', term: 'cohesion', pronunciation: '/kəʊˈhiːʒn/', partOfSpeech: 'noun', definition: 'The quality of being united and working together effectively.', vietnameseMeaning: 'Sự gắn kết, tính đoàn kết, sự thống nhất trong xã hội.', example: 'Immigration can both enrich and challenge social cohesion, depending on how it is managed.', writingTip: '"Social cohesion" is the key collocation. Often discussed in the context of immigration, multiculturalism, and community.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['social cohesion', 'maintain cohesion', 'promote social cohesion', 'sense of cohesion'] },

  { id: 'v23', type: 'vocabulary', term: 'inequality', pronunciation: '/ˌɪnɪˈkwɒlɪti/', partOfSpeech: 'noun', definition: 'An unfair situation in which some groups have more power, money, or opportunities than others.', vietnameseMeaning: 'Bất bình đẳng, sự chênh lệch không công bằng giữa các nhóm.', example: 'Addressing income inequality should be a central goal of any progressive government.', writingTip: 'One of the most common words in IELTS Task 2. Use "address/reduce/tackle inequality" — not "solve inequality".', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['income inequality', 'social inequality', 'address inequality', 'widen inequality', 'reduce inequality'] },

  { id: 'v24', type: 'vocabulary', term: 'marginalise', pronunciation: '/ˈmɑːdʒɪnəlaɪz/', partOfSpeech: 'verb', definition: 'To treat a person or group as unimportant or to exclude them from mainstream society.', vietnameseMeaning: 'Gạt ra ngoài lề, đẩy sang bên lề xã hội.', example: 'Elderly people risk being marginalised in societies that place excessive value on youth and productivity.', writingTip: 'A precise and powerful word for discussing social exclusion. Often used in passive form: "are marginalised".', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['marginalised groups', 'marginalised communities', 'feel marginalised'], alternatives: ['exclude', 'alienate', 'sideline'] },

  // Family
  { id: 'v25', type: 'vocabulary', term: 'nurture', pronunciation: '/ˈnɜːtʃə/', partOfSpeech: 'verb', definition: 'To care for and encourage the development of someone or something.', vietnameseMeaning: 'Nuôi dưỡng, vun đắp, chăm sóc để phát triển.', example: "Parents play a vital role in nurturing children's emotional intelligence from an early age.", writingTip: 'Often used in family and education topics. Conveys both care and active development — not just passive protection.', topic: 'Family', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['nurture children', 'nurture talent', 'nurture relationships', 'nature vs nurture'], alternatives: ['raise', 'develop', 'foster', 'support'] },

  // Cities
  { id: 'v26', type: 'vocabulary', term: 'infrastructure', pronunciation: '/ˈɪnfrəstrʌktʃə/', partOfSpeech: 'noun', definition: 'The basic physical and organisational systems that a country or city needs to function, such as roads, water supply, and power.', vietnameseMeaning: 'Cơ sở hạ tầng (đường xá, điện, nước, hệ thống giao thông).', example: 'Rapid urban growth has put enormous pressure on existing infrastructure in major cities.', writingTip: 'Uncountable noun. Very high frequency in Task 1 and Task 2 on cities and urbanisation topics.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['public infrastructure', 'transport infrastructure', 'invest in infrastructure', 'urban infrastructure'] },

  { id: 'v27', type: 'vocabulary', term: 'urbanisation', pronunciation: '/ˌɜːbənaɪˈzeɪʃn/', partOfSpeech: 'noun', definition: 'The process by which more people come to live in cities rather than rural areas.', vietnameseMeaning: 'Đô thị hoá, quá trình dân số di chuyển về thành thị.', example: 'Rapid urbanisation in developing countries has created significant challenges related to housing and sanitation.', writingTip: 'Crucial for cities-related Task 2 essays. Use "rapid urbanisation" as a natural collocation.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['rapid urbanisation', 'rate of urbanisation', 'challenges of urbanisation'] },

  // Globalisation
  { id: 'v28', type: 'vocabulary', term: 'interconnected', pronunciation: '/ˌɪntəkəˈnektɪd/', partOfSpeech: 'adjective', definition: 'Linked to each other so that each has an effect on the others.', vietnameseMeaning: 'Liên kết với nhau, phụ thuộc lẫn nhau.', example: 'In an increasingly interconnected world, economic crises in one country can have global consequences.', writingTip: 'Excellent for globalisation and technology topics. "An increasingly interconnected world" is a natural academic phrase.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['increasingly interconnected', 'interconnected world', 'deeply interconnected'] },

  // Task 1 focused
  { id: 'v29', type: 'vocabulary', term: 'account for', pronunciation: '/əˈkaʊnt fɔː/', partOfSpeech: 'verb phrase', definition: 'To make up a particular proportion of something; to explain.', vietnameseMeaning: 'Chiếm (một tỷ lệ), giải thích, là nguyên nhân của.', example: 'Public transport accounted for approximately 35% of all daily commutes in the city.', writingTip: 'Essential for Task 1 when describing proportions or percentages. "X accounted for Y%" is very natural.', topic: 'Transport', bandLevel: '5-6', task: 'task1', writingSuitability: 'highly_suitable', collocations: ['account for 30%', 'account for the majority', 'account for the difference'] },

  { id: 'v30', type: 'vocabulary', term: 'deteriorate', pronunciation: '/dɪˈtɪəriəreɪt/', partOfSpeech: 'verb', definition: 'To become progressively worse over time.', vietnameseMeaning: 'Xuống cấp, suy giảm dần dần theo thời gian.', example: 'Air quality in the capital has continued to deteriorate despite recent government interventions.', writingTip: 'Use for negative trends — environment, health, social problems. Do not confuse with "decrease" (quantitative).', topic: 'Environment', bandLevel: '6-7', task: 'both', writingSuitability: 'highly_suitable', collocations: ['deteriorate rapidly', 'continue to deteriorate', 'deteriorating conditions'], alternatives: ['worsen', 'decline', 'degrade'] },

  // ─── COLLOCATIONS (30 items) ─────────────────────────────────────────────

  { id: 'c1', type: 'collocation', term: 'pose a threat', collocationType: 'Verb + Noun', definition: 'To create a danger or risk to something or someone.', vietnameseMeaning: 'Gây ra mối đe doạ, tạo ra nguy hiểm.', example: 'Rising sea levels pose a serious threat to coastal communities around the world.', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['pose a serious threat', 'pose a significant threat', 'pose a growing threat'] },

  { id: 'c2', type: 'collocation', term: 'tackle climate change', collocationType: 'Verb + Noun', definition: 'To deal with or take action against the problem of climate change.', vietnameseMeaning: 'Đối phó với, giải quyết vấn đề biến đổi khí hậu.', example: 'International cooperation is essential to effectively tackle climate change.', writingTip: '"Tackle" is a strong, natural verb. Avoid "solve the problem of climate change" — climate change cannot be fully "solved".', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['tackle the problem', 'tackle the issue', 'tackle poverty'] },

  { id: 'c3', type: 'collocation', term: 'reduce carbon emissions', collocationType: 'Verb + Noun', definition: 'To lower the amount of carbon dioxide released into the atmosphere.', vietnameseMeaning: 'Giảm lượng khí thải carbon, giảm phát thải CO2.', example: 'Many countries have committed to reducing carbon emissions by 2050.', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['carbon emissions', 'greenhouse gas emissions', 'reduce emissions significantly'] },

  { id: 'c4', type: 'collocation', term: 'raise awareness', collocationType: 'Verb + Noun', definition: "To increase people's knowledge and understanding of an issue.", vietnameseMeaning: 'Nâng cao nhận thức, tăng cường hiểu biết về một vấn đề.', example: 'Campaigns designed to raise awareness of mental health issues have become increasingly common.', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['raise public awareness', 'raise awareness of', 'raise awareness among'] },

  { id: 'c5', type: 'collocation', term: 'play a crucial role', collocationType: 'Verb + Noun', definition: 'To be extremely important in a situation or process.', vietnameseMeaning: 'Đóng vai trò then chốt, quan trọng không thể thiếu.', example: 'Education plays a crucial role in reducing poverty and promoting social mobility.', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['play a crucial role in', 'play a vital role', 'play a significant role', 'play a key role'] },

  { id: 'c6', type: 'collocation', term: 'bridge the gap', collocationType: 'Verb + Noun', definition: 'To reduce the difference between two groups or things.', vietnameseMeaning: 'Thu hẹp khoảng cách, rút ngắn sự chênh lệch.', example: 'Digital education platforms can help bridge the gap between wealthy and disadvantaged students.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['bridge the gap between', 'bridge the educational gap', 'bridge the digital divide'] },

  { id: 'c7', type: 'collocation', term: 'drive economic growth', collocationType: 'Verb + Noun', definition: "To cause or stimulate an increase in a country's economic output.", vietnameseMeaning: 'Thúc đẩy tăng trưởng kinh tế.', example: 'Foreign investment has long been considered a key factor in driving economic growth in developing nations.', topic: 'Economy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['drive growth', 'drive innovation', 'drive change'] },

  { id: 'c8', type: 'collocation', term: 'impose stricter regulations', collocationType: 'Verb + Noun', definition: 'To introduce and enforce more demanding rules or laws.', vietnameseMeaning: 'Áp đặt, ban hành các quy định nghiêm ngặt hơn.', example: 'The government has been under pressure to impose stricter regulations on the food industry.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['impose regulations', 'impose restrictions', 'impose a ban', 'impose penalties'] },

  { id: 'c9', type: 'collocation', term: 'address the root cause', collocationType: 'Verb + Noun', definition: 'To deal with the fundamental source of a problem rather than its symptoms.', vietnameseMeaning: 'Giải quyết nguyên nhân gốc rễ của vấn đề.', example: 'Any effective crime prevention strategy must address the root causes of criminal behaviour.', topic: 'Crime & Law', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['root cause', 'underlying cause', 'address the issue', 'address the problem'] },

  { id: 'c10', type: 'collocation', term: 'maintain social cohesion', collocationType: 'Verb + Noun', definition: 'To preserve unity and a sense of belonging within a society.', vietnameseMeaning: 'Duy trì sự gắn kết xã hội, giữ vững tính đoàn kết cộng đồng.', example: 'Strong public institutions are essential to maintaining social cohesion in diverse societies.', topic: 'Society', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable' },

  { id: 'c11', type: 'collocation', term: 'exert pressure on', collocationType: 'Verb + Preposition', definition: 'To apply force or influence to make someone do something.', vietnameseMeaning: 'Gây áp lực lên, tạo sức ép đối với.', example: 'Consumer groups continue to exert pressure on corporations to adopt sustainable practices.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['exert pressure on governments', 'exert pressure on companies', 'come under pressure'] },

  { id: 'c12', type: 'collocation', term: 'reach a consensus', collocationType: 'Verb + Noun', definition: 'To achieve general agreement among a group of people.', vietnameseMeaning: 'Đạt được sự đồng thuận, thống nhất ý kiến chung.', example: 'International leaders have struggled to reach a consensus on effective climate policy.', topic: 'Government', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['reach a consensus on', 'international consensus', 'broad consensus', 'build consensus'] },

  { id: 'c13', type: 'collocation', term: 'have a profound effect', collocationType: 'Verb + Adjective + Noun', definition: 'To have a deep and far-reaching impact on something.', vietnameseMeaning: 'Có tác động sâu sắc và lâu dài.', example: 'The COVID-19 pandemic has had a profound effect on working patterns across the globe.', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['profound effect', 'profound impact', 'profound influence', 'significant effect', 'devastating effect'] },

  { id: 'c14', type: 'collocation', term: 'keep pace with', collocationType: 'Verb + Noun', definition: 'To develop or progress at the same speed as something else.', vietnameseMeaning: 'Theo kịp, bắt kịp tốc độ phát triển của thứ gì đó.', example: 'Education systems must evolve to keep pace with rapid technological advancement.', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['keep pace with change', 'keep pace with demand', 'keep pace with development'] },

  { id: 'c15', type: 'collocation', term: 'critical thinking skills', collocationType: 'Adjective + Noun', definition: 'The ability to think analytically and make reasoned judgements.', vietnameseMeaning: 'Kỹ năng tư duy phản biện, phân tích và đánh giá vấn đề.', example: 'Universities should prioritise the development of critical thinking skills over the memorisation of facts.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['develop critical thinking', 'analytical skills', 'problem-solving skills'] },

  { id: 'c16', type: 'collocation', term: 'make a significant contribution', collocationType: 'Verb + Noun', definition: 'To make an important and meaningful difference to something.', vietnameseMeaning: 'Đóng góp đáng kể, có những cống hiến quan trọng.', example: 'Volunteers make a significant contribution to the provision of social services in many communities.', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['make a contribution to', 'make a positive contribution', 'significant contribution to society'] },

  { id: 'c17', type: 'collocation', term: 'lead a sedentary lifestyle', collocationType: 'Verb + Noun', definition: 'To live in a way that involves very little physical activity.', vietnameseMeaning: 'Sống với lối sống ít vận động, ngồi nhiều.', example: 'Many office workers lead a sedentary lifestyle, which increases their risk of developing chronic diseases.', topic: 'Health', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['sedentary lifestyle', 'active lifestyle', 'unhealthy lifestyle'] },

  { id: 'c18', type: 'collocation', term: 'take measures to', collocationType: 'Verb + Noun', definition: 'To take steps or actions to achieve a particular goal.', vietnameseMeaning: 'Thực hiện các biện pháp để, tiến hành các bước nhằm.', example: 'Authorities must take effective measures to reduce the number of road traffic accidents.', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['take measures to reduce', 'take steps to', 'take action to', 'implement measures'] },

  { id: 'c19', type: 'collocation', term: 'generate revenue', collocationType: 'Verb + Noun', definition: 'To produce income or profit, especially for a government or business.', vietnameseMeaning: 'Tạo ra doanh thu, thu nhập, lợi nhuận.', example: 'Tourism is a vital industry that generates significant revenue for many small economies.', topic: 'Economy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['generate revenue', 'generate income', 'generate profit', 'generate employment'] },

  { id: 'c20', type: 'collocation', term: 'narrow the gap', collocationType: 'Verb + Noun', definition: 'To reduce the difference between two groups, levels, or amounts.', vietnameseMeaning: 'Thu hẹp khoảng cách, giảm sự chênh lệch.', example: 'Policy reforms have helped to narrow the gap between the richest and poorest households.', topic: 'Economy', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['narrow the gap between', 'widen the gap', 'bridge the gap', 'close the gap'] },

  { id: 'c21', type: 'collocation', term: 'provide equal opportunities', collocationType: 'Verb + Noun', definition: 'To ensure that all people have the same access to resources and possibilities.', vietnameseMeaning: 'Tạo cơ hội bình đẳng, đảm bảo mọi người đều có quyền tiếp cận như nhau.', example: 'The government has a responsibility to provide equal opportunities in education for all children, regardless of background.', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['equal opportunities', 'equal access', 'level playing field'] },

  { id: 'c22', type: 'collocation', term: 'bear the financial burden', collocationType: 'Verb + Noun', definition: 'To be responsible for a significant financial cost or weight.', vietnameseMeaning: 'Gánh chịu gánh nặng tài chính, chịu chi phí lớn.', example: 'Young people today are increasingly expected to bear the financial burden of higher education themselves.', topic: 'Economy', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['bear the burden', 'financial burden', 'economic burden', 'shift the burden'] },

  { id: 'c23', type: 'collocation', term: 'rising rates of', collocationType: 'Adjective + Noun', definition: 'Increasing levels or amounts of something, often a problem.', vietnameseMeaning: 'Tỷ lệ ngày càng tăng của, mức độ gia tăng của.', example: 'Many developed countries are grappling with rising rates of obesity and related health conditions.', topic: 'Health', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['rising rates of obesity', 'rising crime rates', 'rising unemployment rates', 'increasing rates of'] },

  { id: 'c24', type: 'collocation', term: 'pose ethical challenges', collocationType: 'Verb + Noun', definition: 'To create moral dilemmas or questions that are difficult to resolve.', vietnameseMeaning: 'Đặt ra những thách thức về mặt đạo đức, tạo ra các tình huống khó xử về đạo lý.', example: 'The development of artificial intelligence poses serious ethical challenges that society must address.', topic: 'Technology', bandLevel: '7+', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['ethical challenges', 'ethical concerns', 'ethical implications', 'moral dilemma'] },

  { id: 'c25', type: 'collocation', term: 'acquire knowledge', collocationType: 'Verb + Noun', definition: 'To gain or develop knowledge or skills through study or experience.', vietnameseMeaning: 'Thu nhận kiến thức, tiếp thu tri thức qua học tập hoặc kinh nghiệm.', example: 'Students should be encouraged to acquire knowledge independently rather than relying entirely on teachers.', topic: 'Education', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['acquire knowledge', 'acquire skills', 'acquire experience'] },

  { id: 'c26', type: 'collocation', term: 'rapid technological advances', collocationType: 'Adjective + Noun', definition: 'Fast and significant developments or improvements in technology.', vietnameseMeaning: 'Những tiến bộ công nghệ nhanh chóng và đáng kể.', example: 'Rapid technological advances have transformed the global economy over the past three decades.', topic: 'Technology', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['technological advances', 'technological progress', 'technological development', 'technological innovation'] },

  { id: 'c27', type: 'collocation', term: 'invest in infrastructure', collocationType: 'Verb + Noun', definition: 'To spend money on developing physical or organisational systems.', vietnameseMeaning: 'Đầu tư vào cơ sở hạ tầng.', example: 'Cities need to invest in public transport infrastructure to reduce traffic congestion.', topic: 'Cities & Urbanisation', bandLevel: '5-6', task: 'both', writingSuitability: 'highly_suitable', collocations: ['invest in infrastructure', 'invest in education', 'invest in public services'] },

  { id: 'c28', type: 'collocation', term: 'show a steady increase', collocationType: 'Verb + Noun', definition: 'To display a gradual and consistent rise over time.', vietnameseMeaning: 'Cho thấy sự tăng trưởng đều đặn, ổn định.', example: 'The graph shows a steady increase in the number of people using renewable energy sources between 2000 and 2020.', topic: 'Energy', bandLevel: '5-6', task: 'task1', writingSuitability: 'highly_suitable', collocations: ['steady increase', 'gradual increase', 'significant increase', 'dramatic rise', 'sharp decline'] },

  { id: 'c29', type: 'collocation', term: 'reach a peak', collocationType: 'Verb + Noun', definition: 'To reach the highest point or level at a particular time.', vietnameseMeaning: 'Đạt đỉnh cao nhất, lên đến mức cao nhất.', example: 'Sales reached a peak in December before declining significantly in the following months.', topic: 'Economy', bandLevel: '5-6', task: 'task1', writingSuitability: 'highly_suitable', collocations: ['reach a peak', 'reach a high of', 'peak at', 'hit a high of', 'decline from a peak of'] },

  { id: 'c30', type: 'collocation', term: 'protect the environment', collocationType: 'Verb + Noun', definition: 'To take action to preserve and safeguard the natural world.', vietnameseMeaning: 'Bảo vệ môi trường thiên nhiên, gìn giữ hệ sinh thái.', example: 'Both governments and individuals have a responsibility to protect the environment for future generations.', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['protect the environment', 'protect natural habitats', 'environmental protection', 'conserve resources'] },

  // ─── PHRASAL VERBS (20 items) ────────────────────────────────────────────

  { id: 'p1', type: 'phrasal_verb', term: 'bring about', partOfSpeech: 'phrasal verb', definition: 'To cause something to happen or exist.', vietnameseMeaning: 'Gây ra, dẫn đến, tạo nên sự thay đổi.', example: 'Technological innovation has brought about significant changes in the global labour market.', writingTip: 'Suitable for IELTS Writing. More formal than "make happen". "Give rise to" and "lead to" are slightly more academic.', topic: 'Society', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['bring about change', 'bring about improvements', 'bring about a transformation'], academicAlternatives: ['cause', 'lead to', 'result in', 'give rise to'] },

  { id: 'p2', type: 'phrasal_verb', term: 'cut down on', partOfSpeech: 'phrasal verb', definition: 'To reduce the amount or frequency of something.', vietnameseMeaning: 'Cắt giảm, giảm thiểu lượng hoặc tần suất.', example: 'Individuals should cut down on their use of single-use plastics to protect the environment.', writingTip: 'Slightly informal. In Task 2 essays, "reduce" or "minimise" is often preferable. Acceptable in less formal contexts.', topic: 'Environment', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', academicAlternatives: ['reduce', 'minimise', 'decrease', 'limit'] },

  { id: 'p3', type: 'phrasal_verb', term: 'carry out', partOfSpeech: 'phrasal verb', definition: 'To do or perform a task, activity, or plan.', vietnameseMeaning: 'Thực hiện, tiến hành, triển khai (nhiệm vụ, kế hoạch).', example: 'Governments should carry out thorough research before implementing new education policies.', writingTip: '"Conduct" is slightly more formal than "carry out" in academic contexts, but both are acceptable.', topic: 'Government', bandLevel: '5-6', task: 'both', writingSuitability: 'suitable', collocations: ['carry out research', 'carry out a study', 'carry out an investigation', 'carry out plans'], academicAlternatives: ['conduct', 'perform', 'implement', 'execute'] },

  { id: 'p4', type: 'phrasal_verb', term: 'give rise to', partOfSpeech: 'phrasal verb', definition: 'To cause something to develop or come into existence.', vietnameseMeaning: 'Dẫn đến, tạo ra, là nguyên nhân của.', example: 'Rapid urbanisation has given rise to a range of social and environmental challenges.', writingTip: 'One of the most academic phrasal verbs. Fully appropriate for formal IELTS writing.', topic: 'Cities & Urbanisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['give rise to concerns', 'give rise to problems', 'give rise to opportunities'] },

  { id: 'p5', type: 'phrasal_verb', term: 'account for', partOfSpeech: 'phrasal verb', definition: 'To make up a proportion of something; to explain the reason for.', vietnameseMeaning: 'Chiếm (một tỷ lệ nhất định); giải thích nguyên nhân.', example: 'Renewable energy sources now account for nearly 30% of electricity production in the country.', writingTip: 'Essential for Task 1. Fully academic and appropriate. "X accounted for Y%" is a key Task 1 sentence pattern.', topic: 'Energy', bandLevel: '5-6', task: 'task1', writingSuitability: 'highly_suitable', collocations: ['account for a large proportion', 'account for the majority', 'account for the difference'] },

  { id: 'p6', type: 'phrasal_verb', term: 'stem from', partOfSpeech: 'phrasal verb', definition: 'To originate from or be caused by something.', vietnameseMeaning: 'Bắt nguồn từ, xuất phát từ, có nguyên nhân từ.', example: 'Many social problems stem from a lack of access to quality education in early childhood.', writingTip: 'Formal and academic. Fully appropriate for IELTS Task 2.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['stem from poverty', 'stem from inequality', 'largely stem from'], academicAlternatives: ['originate from', 'arise from', 'result from'] },

  { id: 'p7', type: 'phrasal_verb', term: 'take into account', partOfSpeech: 'phrasal verb', definition: 'To consider a particular factor when making a decision or forming a judgement.', vietnameseMeaning: 'Tính đến, xem xét, cân nhắc (một yếu tố nào đó).', example: 'Policymakers must take into account the long-term environmental consequences of their decisions.', writingTip: 'Fully academic and natural in formal writing. "Consider" is also appropriate.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['take into account the impact', 'take into account various factors'], academicAlternatives: ['consider', 'factor in', 'account for'] },

  { id: 'p8', type: 'phrasal_verb', term: 'call for', partOfSpeech: 'phrasal verb', definition: 'To publicly demand or require something.', vietnameseMeaning: 'Kêu gọi, đòi hỏi, yêu cầu một cách công khai.', example: 'Environmental groups are calling for a complete ban on single-use plastics.', writingTip: 'Acceptable in formal writing, especially when referring to what organisations or governments are doing.', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['call for action', 'call for reform', 'call for stricter measures'], academicAlternatives: ['demand', 'advocate for', 'urge'] },

  { id: 'p9', type: 'phrasal_verb', term: 'point out', partOfSpeech: 'phrasal verb', definition: 'To draw attention to a fact or problem.', vietnameseMeaning: 'Chỉ ra, lưu ý, nhấn mạnh một vấn đề hoặc sự kiện.', example: 'Critics have pointed out that the new policy may disproportionately affect low-income households.', writingTip: 'Acceptable in academic writing. "Highlight" or "note" can be used as alternatives.', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', academicAlternatives: ['highlight', 'note', 'argue', 'observe'] },

  { id: 'p10', type: 'phrasal_verb', term: 'phase out', partOfSpeech: 'phrasal verb', definition: 'To gradually stop using or producing something over a period of time.', vietnameseMeaning: 'Loại bỏ dần dần, từng bước xoá bỏ theo thời gian.', example: 'Several European governments have pledged to phase out petrol and diesel vehicles by 2035.', writingTip: 'Appropriate for formal writing when discussing policy changes over time.', topic: 'Environment', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', academicAlternatives: ['gradually eliminate', 'discontinue', 'withdraw'] },

  { id: 'p11', type: 'phrasal_verb', term: 'draw on', partOfSpeech: 'phrasal verb', definition: 'To use something as a source of information, knowledge, or experience.', vietnameseMeaning: 'Dựa vào, khai thác, sử dụng (kiến thức, kinh nghiệm) như một nguồn lực.', example: 'Effective teachers draw on a wide range of pedagogical approaches to meet the needs of different learners.', writingTip: 'Appropriate in formal and academic contexts. "Utilise" or "draw upon" are equally suitable.', topic: 'Education', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['draw on experience', 'draw on research', 'draw on knowledge'], academicAlternatives: ['utilise', 'employ', 'rely on'] },

  { id: 'p12', type: 'phrasal_verb', term: 'result in', partOfSpeech: 'phrasal verb', definition: 'To cause something to happen as a consequence.', vietnameseMeaning: 'Dẫn đến, gây ra (một hậu quả hoặc kết quả).', example: 'A lack of investment in education can result in long-term economic decline.', writingTip: 'Fully academic. One of the most important cause-and-effect phrases in academic writing.', topic: 'Economy', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['result in significant changes', 'result in job losses', 'ultimately result in'] },

  { id: 'p13', type: 'phrasal_verb', term: 'deal with', partOfSpeech: 'phrasal verb', definition: 'To take action in order to handle a problem or situation.', vietnameseMeaning: 'Xử lý, giải quyết, đối phó với vấn đề hoặc tình huống.', example: 'Governments must find more effective ways to deal with the growing problem of urban homelessness.', writingTip: 'Acceptable in formal writing. "Address" is often a slightly more sophisticated alternative.', topic: 'Society', bandLevel: '5-6', task: 'task2', writingSuitability: 'suitable', academicAlternatives: ['address', 'tackle', 'handle', 'manage'] },

  { id: 'p14', type: 'phrasal_verb', term: 'build on', partOfSpeech: 'phrasal verb', definition: 'To use something as a basis for further development.', vietnameseMeaning: 'Xây dựng dựa trên, phát triển thêm từ nền tảng hiện có.', example: 'Future research should build on these findings to develop more effective treatment options.', writingTip: 'Appropriate in formal and academic contexts.', topic: 'Science', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', academicAlternatives: ['expand on', 'develop from', 'extend'] },

  { id: 'p15', type: 'phrasal_verb', term: 'set out', partOfSpeech: 'phrasal verb', definition: 'To explain or describe something in a clear and organised way; to begin a journey or task.', vietnameseMeaning: 'Trình bày, giải thích rõ ràng; bắt đầu thực hiện (kế hoạch).', example: 'The report sets out a series of recommendations for improving urban air quality.', writingTip: '"Set out" is appropriate and natural in formal writing.', topic: 'Government', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', collocations: ['set out plans', 'set out to achieve', 'set out the argument'], academicAlternatives: ['outline', 'present', 'describe'] },

  { id: 'p16', type: 'phrasal_verb', term: 'make up', partOfSpeech: 'phrasal verb', definition: 'To constitute or form a particular proportion of something.', vietnameseMeaning: 'Cấu thành, chiếm (một phần tỷ lệ) trong tổng thể.', example: 'Women make up approximately 48% of the total workforce in the country.', writingTip: 'Appropriate for Task 1. "Account for" and "constitute" are slightly more formal alternatives.', topic: 'Work & Employment', bandLevel: '5-6', task: 'task1', writingSuitability: 'suitable', academicAlternatives: ['constitute', 'account for', 'comprise', 'represent'] },

  { id: 'p17', type: 'phrasal_verb', term: 'focus on', partOfSpeech: 'phrasal verb', definition: 'To concentrate attention or effort on a particular thing.', vietnameseMeaning: 'Tập trung vào, chú trọng đến.', example: 'Policymakers should focus on long-term solutions rather than short-term measures.', writingTip: 'Completely natural and academic. One of the most versatile phrases in IELTS Writing.', topic: 'Government', bandLevel: '5-6', task: 'task2', writingSuitability: 'highly_suitable', collocations: ['focus on the issue', 'focus on improving', 'shift focus to'] },

  { id: 'p18', type: 'phrasal_verb', term: 'look into', partOfSpeech: 'phrasal verb', definition: 'To investigate or examine something more carefully.', vietnameseMeaning: 'Điều tra, xem xét kỹ lưỡng, tìm hiểu sâu hơn.', example: 'Researchers need to look into the long-term health effects of prolonged screen use.', writingTip: 'Slightly informal. In academic writing, "investigate" or "examine" is usually preferable.', topic: 'Health', bandLevel: '5-6', task: 'task2', writingSuitability: 'use_with_caution', academicAlternatives: ['investigate', 'examine', 'explore', 'study'] },

  { id: 'p19', type: 'phrasal_verb', term: 'catch up with', partOfSpeech: 'phrasal verb', definition: 'To reach the same level or standard as someone or something else.', vietnameseMeaning: 'Bắt kịp, theo kịp trình độ hoặc tiến bộ của người khác.', example: 'Developing countries are working hard to catch up with wealthier nations in terms of technology and infrastructure.', writingTip: 'Acceptable in formal writing, particularly when discussing economic or technological development.', topic: 'Globalisation', bandLevel: '6-7', task: 'task2', writingSuitability: 'suitable', academicAlternatives: ['match', 'reach the level of', 'keep pace with'] },

  { id: 'p20', type: 'phrasal_verb', term: 'break down', partOfSpeech: 'phrasal verb', definition: 'To separate into smaller parts for analysis; to fail to function.', vietnameseMeaning: 'Phân tích chi tiết, chia nhỏ để xem xét; hoặc bị hỏng, sụp đổ.', example: 'The chart breaks down household energy consumption by source and year.', writingTip: 'In Task 1, "break down" is natural when describing how data is categorised. "Categorise" is a more formal alternative.', topic: 'Energy', bandLevel: '5-6', task: 'task1', writingSuitability: 'suitable', academicAlternatives: ['analyse', 'separate', 'categorise', 'divide'] },
]
